export const NS = 'http://opcfoundation.org/UA/DI/';

export class BrowseNames {
   static readonly Abort: string = 'Abort'
   static readonly ActualMode: string = 'ActualMode'
   static readonly AssetId: string = 'AssetId'
   static readonly BaseLifetimeIndicationType: string = 'BaseLifetimeIndicationType'
   static readonly BlockType: string = 'BlockType'
   static readonly BreakLock: string = 'BreakLock'
   static readonly CachedLoadingType: string = 'CachedLoadingType'
   static readonly ChangeLogReference: string = 'ChangeLogReference'
   static readonly CheckFunctionAlarmType: string = 'CheckFunctionAlarmType'
   static readonly ComponentName: string = 'ComponentName'
   static readonly ComponentType: string = 'ComponentType'
   static readonly ConfigurableObjectType: string = 'ConfigurableObjectType'
   static readonly Confirm: string = 'Confirm'
   static readonly Confirmation: string = 'Confirmation'
   static readonly ConfirmationStateMachineType: string = 'ConfirmationStateMachineType'
   static readonly ConfirmationTimeout: string = 'ConfirmationTimeout'
   static readonly ConnectionPointType: string = 'ConnectionPointType'
   static readonly ConnectsTo: string = 'ConnectsTo'
   static readonly ConnectsToParent: string = 'ConnectsToParent'
   static readonly CPIdentifier_Placeholder: string = '<CPIdentifier>'
   static readonly CurrentVersion: string = 'CurrentVersion'
   static readonly DeviceClass: string = 'DeviceClass'
   static readonly DeviceFeatures: string = 'DeviceFeatures'
   static readonly DeviceHealth: string = 'DeviceHealth'
   static readonly DeviceHealthAlarms: string = 'DeviceHealthAlarms'
   static readonly DeviceHealthDiagnosticAlarmType: string = 'DeviceHealthDiagnosticAlarmType'
   static readonly DeviceHealthEnumeration: string = 'DeviceHealthEnumeration'
   static readonly DeviceManual: string = 'DeviceManual'
   static readonly DeviceRevision: string = 'DeviceRevision'
   static readonly DeviceSet: string = 'DeviceSet'
   static readonly DeviceTopology: string = 'DeviceTopology'
   static readonly DeviceType: string = 'DeviceType'
   static readonly DeviceTypeImage: string = 'DeviceTypeImage'
   static readonly DiameterIndicationType: string = 'DiameterIndicationType'
   static readonly DirectLoadingType: string = 'DirectLoadingType'
   static readonly Documentation: string = 'Documentation'
   static readonly DocumentationFiles: string = 'DocumentationFiles'
   static readonly DocumentFileId_Placeholder: string = '<DocumentFileId>'
   static readonly DocumentIdentifier_Placeholder: string = '<DocumentIdentifier>'
   static readonly Error: string = 'Error'
   static readonly ErrorMessage: string = 'ErrorMessage'
   static readonly ErrorToIdle: string = 'ErrorToIdle'
   static readonly ExitLock: string = 'ExitLock'
   static readonly FailureAlarmType: string = 'FailureAlarmType'
   static readonly FallbackVersion: string = 'FallbackVersion'
   static readonly FetchResultDataType: string = 'FetchResultDataType'
   static readonly FetchTransferResultData: string = 'FetchTransferResultData'
   static readonly FileSystemLoadingType: string = 'FileSystemLoadingType'
   static readonly FileTransfer: string = 'FileTransfer'
   static readonly FunctionalGroupType: string = 'FunctionalGroupType'
   static readonly GetUpdateBehavior: string = 'GetUpdateBehavior'
   static readonly GroupIdentifier_Placeholder: string = '<GroupIdentifier>'
   static readonly HardwareRevision: string = 'HardwareRevision'
   static readonly Hash: string = 'Hash'
   static readonly Identification: string = 'Identification'
   static readonly IDeviceHealthType: string = 'IDeviceHealthType'
   static readonly Idle: string = 'Idle'
   static readonly IdleToInstalling: string = 'IdleToInstalling'
   static readonly IdleToPreparing: string = 'IdleToPreparing'
   static readonly ImageIdentifier_Placeholder: string = '<ImageIdentifier>'
   static readonly ImageSet: string = 'ImageSet'
   static readonly Indication: string = 'Indication'
   static readonly InitLock: string = 'InitLock'
   static readonly Installation: string = 'Installation'
   static readonly InstallationDelay: string = 'InstallationDelay'
   static readonly InstallationStateMachineType: string = 'InstallationStateMachineType'
   static readonly InstallFiles: string = 'InstallFiles'
   static readonly Installing: string = 'Installing'
   static readonly InstallingToError: string = 'InstallingToError'
   static readonly InstallingToIdle: string = 'InstallingToIdle'
   static readonly InstallSoftwarePackage: string = 'InstallSoftwarePackage'
   static readonly IOperationCounterType: string = 'IOperationCounterType'
   static readonly IsOnline: string = 'IsOnline'
   static readonly ISupportInfoType: string = 'ISupportInfoType'
   static readonly ITagNameplateType: string = 'ITagNameplateType'
   static readonly IVendorNameplateType: string = 'IVendorNameplateType'
   static readonly LengthIndicationType: string = 'LengthIndicationType'
   static readonly LifetimeVariableType: string = 'LifetimeVariableType'
   static readonly LimitValue: string = 'LimitValue'
   static readonly Loading: string = 'Loading'
   static readonly Lock: string = 'Lock'
   static readonly Locked: string = 'Locked'
   static readonly LockingClient: string = 'LockingClient'
   static readonly LockingServicesType: string = 'LockingServicesType'
   static readonly LockingUser: string = 'LockingUser'
   static readonly MaintenanceRequiredAlarmType: string = 'MaintenanceRequiredAlarmType'
   static readonly Manufacturer: string = 'Manufacturer'
   static readonly ManufacturerUri: string = 'ManufacturerUri'
   static readonly MethodSet: string = 'MethodSet'
   static readonly Model: string = 'Model'
   static readonly NetworkAddress: string = 'NetworkAddress'
   static readonly NetworkIdentifier_Placeholder: string = '<NetworkIdentifier>'
   static readonly NetworkSet: string = 'NetworkSet'
   static readonly NetworkType: string = 'NetworkType'
   static readonly NormalMode: string = 'NormalMode'
   static readonly NotWaitingForConfirm: string = 'NotWaitingForConfirm'
   static readonly NotWaitingForConfirmToWaitingForConfirm: string = 'NotWaitingForConfirmToWaitingForConfirm'
   static readonly NotWaitingForPowerCycle: string = 'NotWaitingForPowerCycle'
   static readonly NotWaitingForPowerCycleToWaitingForPowerCycle: string = 'NotWaitingForPowerCycleToWaitingForPowerCycle'
   static readonly NumberOfPartsIndicationType: string = 'NumberOfPartsIndicationType'
   static readonly NumberOfUsagesIndicationType: string = 'NumberOfUsagesIndicationType'
   static readonly ObjectIdentifier_Placeholder: string = '<ObjectIdentifier>'
   static readonly OffSpecAlarmType: string = 'OffSpecAlarmType'
   static readonly OnlineAccess: string = 'OnlineAccess'
   static readonly OperationCycleCounter: string = 'OperationCycleCounter'
   static readonly OperationDuration: string = 'OperationDuration'
   static readonly PackageLoadingType: string = 'PackageLoadingType'
   static readonly ParameterIdentifier_Placeholder: string = '<ParameterIdentifier>'
   static readonly ParameterResultDataType: string = 'ParameterResultDataType'
   static readonly Parameters: string = 'Parameters'
   static readonly ParameterSet: string = 'ParameterSet'
   static readonly PatchIdentifiers: string = 'PatchIdentifiers'
   static readonly PendingVersion: string = 'PendingVersion'
   static readonly PercentComplete: string = 'PercentComplete'
   static readonly PermittedMode: string = 'PermittedMode'
   static readonly PowerCycle: string = 'PowerCycle'
   static readonly PowerCycleStateMachineType: string = 'PowerCycleStateMachineType'
   static readonly PowerOnDuration: string = 'PowerOnDuration'
   static readonly Prepare: string = 'Prepare'
   static readonly PreparedForUpdate: string = 'PreparedForUpdate'
   static readonly PreparedForUpdateToResuming: string = 'PreparedForUpdateToResuming'
   static readonly PrepareForUpdate: string = 'PrepareForUpdate'
   static readonly PrepareForUpdateStateMachineType: string = 'PrepareForUpdateStateMachineType'
   static readonly Preparing: string = 'Preparing'
   static readonly PreparingToIdle: string = 'PreparingToIdle'
   static readonly PreparingToPreparedForUpdate: string = 'PreparingToPreparedForUpdate'
   static readonly ProductCode: string = 'ProductCode'
   static readonly ProductInstanceUri: string = 'ProductInstanceUri'
   static readonly ProfileIdentifier_Placeholder: string = '<ProfileIdentifier>'
   static readonly ProtocolSupport: string = 'ProtocolSupport'
   static readonly ProtocolSupportIdentifier_Placeholder: string = '<ProtocolSupportIdentifier>'
   static readonly ProtocolType: string = 'ProtocolType'
   static readonly ReleaseDate: string = 'ReleaseDate'
   static readonly RemainingLockTime: string = 'RemainingLockTime'
   static readonly RenewLock: string = 'RenewLock'
   static readonly Resume: string = 'Resume'
   static readonly Resuming: string = 'Resuming'
   static readonly ResumingToIdle: string = 'ResumingToIdle'
   static readonly RevisionCounter: string = 'RevisionCounter'
   static readonly SerialNumber: string = 'SerialNumber'
   static readonly SoftwareLoadingType: string = 'SoftwareLoadingType'
   static readonly SoftwareReleaseDate: string = 'SoftwareReleaseDate'
   static readonly SoftwareRevision: string = 'SoftwareRevision'
   static readonly SoftwareType: string = 'SoftwareType'
   static readonly SoftwareUpdate: string = 'SoftwareUpdate'
   static readonly SoftwareUpdateType: string = 'SoftwareUpdateType'
   static readonly SoftwareVersionFileType: string = 'SoftwareVersionFileType'
   static readonly SoftwareVersionType: string = 'SoftwareVersionType'
   static readonly StartValue: string = 'StartValue'
   static readonly SubstanceVolumeIndicationType: string = 'SubstanceVolumeIndicationType'
   static readonly SupportedTypes: string = 'SupportedTypes'
   static readonly TargetMode: string = 'TargetMode'
   static readonly TimeIndicationType: string = 'TimeIndicationType'
   static readonly TopologyElementType: string = 'TopologyElementType'
   static readonly TransferFromDevice: string = 'TransferFromDevice'
   static readonly TransferResultDataDataType: string = 'TransferResultDataDataType'
   static readonly TransferResultErrorDataType: string = 'TransferResultErrorDataType'
   static readonly TransferServicesType: string = 'TransferServicesType'
   static readonly TransferToDevice: string = 'TransferToDevice'
   static readonly UIElement: string = 'UIElement'
   static readonly UIElementType: string = 'UIElementType'
   static readonly UpdateBehavior: string = 'UpdateBehavior'
   static readonly UpdateKey: string = 'UpdateKey'
   static readonly UpdateStatus: string = 'UpdateStatus'
   static readonly ValidateFiles: string = 'ValidateFiles'
   static readonly VendorErrorCode: string = 'VendorErrorCode'
   static readonly WaitingForConfirm: string = 'WaitingForConfirm'
   static readonly WaitingForConfirmToNotWaitingForConfirm: string = 'WaitingForConfirmToNotWaitingForConfirm'
   static readonly WaitingForPowerCycle: string = 'WaitingForPowerCycle'
   static readonly WaitingForPowerCycleToNotWaitingForPowerCycle: string = 'WaitingForPowerCycleToNotWaitingForPowerCycle'
   static readonly WarningValues: string = 'WarningValues'
   static readonly WriteBlockSize: string = 'WriteBlockSize'
   static readonly WriteTimeout: string = 'WriteTimeout'
}

export class DataTypeIds {
    static readonly DeviceHealthEnumeration: string = 'nsu=' + NS + ';i=6244'
    static readonly FetchResultDataType: string = 'nsu=' + NS + ';i=6522'
    static readonly TransferResultErrorDataType: string = 'nsu=' + NS + ';i=15888'
    static readonly TransferResultDataDataType: string = 'nsu=' + NS + ';i=15889'
    static readonly ParameterResultDataType: string = 'nsu=' + NS + ';i=6525'
    static readonly SoftwareVersionFileType: string = 'nsu=' + NS + ';i=331'
    static readonly UpdateBehavior: string = 'nsu=' + NS + ';i=333'
}

export class MethodIds {
    static readonly TopologyElementType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly TopologyElementType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly TopologyElementType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly TopologyElementType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open: string = 'nsu=' + NS + ';i=36'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Close: string = 'nsu=' + NS + ';i=39'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read: string = 'nsu=' + NS + ';i=63'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Write: string = 'nsu=' + NS + ';i=66'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition: string = 'nsu=' + NS + ';i=68'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_SetPosition: string = 'nsu=' + NS + ';i=71'
    static readonly ComponentType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly ComponentType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly ComponentType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly ComponentType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly DeviceType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly DeviceType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly DeviceType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly DeviceType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly SoftwareType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly SoftwareType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly SoftwareType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly SoftwareType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly BlockType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly BlockType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly BlockType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly BlockType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly NetworkType_Lock_InitLock: string = 'nsu=' + NS + ';i=6299'
    static readonly NetworkType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6302'
    static readonly NetworkType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6304'
    static readonly NetworkType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6306'
    static readonly ConnectionPointType_Lock_InitLock: string = 'nsu=' + NS + ';i=6166'
    static readonly ConnectionPointType_Lock_RenewLock: string = 'nsu=' + NS + ';i=6169'
    static readonly ConnectionPointType_Lock_ExitLock: string = 'nsu=' + NS + ';i=6171'
    static readonly ConnectionPointType_Lock_BreakLock: string = 'nsu=' + NS + ';i=6173'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock: string = 'nsu=' + NS + ';i=6299'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RenewLock: string = 'nsu=' + NS + ';i=6302'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_ExitLock: string = 'nsu=' + NS + ';i=6304'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_BreakLock: string = 'nsu=' + NS + ';i=6306'
    static readonly TransferServicesType_TransferToDevice: string = 'nsu=' + NS + ';i=6527'
    static readonly TransferServicesType_TransferFromDevice: string = 'nsu=' + NS + ';i=6529'
    static readonly TransferServicesType_FetchTransferResultData: string = 'nsu=' + NS + ';i=6531'
    static readonly LockingServicesType_InitLock: string = 'nsu=' + NS + ';i=6393'
    static readonly LockingServicesType_RenewLock: string = 'nsu=' + NS + ';i=6396'
    static readonly LockingServicesType_ExitLock: string = 'nsu=' + NS + ';i=6398'
    static readonly LockingServicesType_BreakLock: string = 'nsu=' + NS + ';i=6400'
    static readonly SoftwareUpdateType_PrepareForUpdate_Prepare: string = 'nsu=' + NS + ';i=19'
    static readonly SoftwareUpdateType_PrepareForUpdate_Abort: string = 'nsu=' + NS + ';i=20'
    static readonly SoftwareUpdateType_Installation_Resume: string = 'nsu=' + NS + ';i=61'
    static readonly SoftwareUpdateType_Confirmation_Confirm: string = 'nsu=' + NS + ';i=112'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForRead: string = 'nsu=' + NS + ';i=124'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForWrite: string = 'nsu=' + NS + ';i=127'
    static readonly SoftwareUpdateType_Parameters_CloseAndCommit: string = 'nsu=' + NS + ';i=130'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForRead: string = 'nsu=' + NS + ';i=142'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForWrite: string = 'nsu=' + NS + ';i=145'
    static readonly PackageLoadingType_FileTransfer_CloseAndCommit: string = 'nsu=' + NS + ';i=148'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForRead: string = 'nsu=' + NS + ';i=142'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForWrite: string = 'nsu=' + NS + ';i=145'
    static readonly DirectLoadingType_FileTransfer_CloseAndCommit: string = 'nsu=' + NS + ';i=148'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForRead: string = 'nsu=' + NS + ';i=142'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForWrite: string = 'nsu=' + NS + ';i=145'
    static readonly CachedLoadingType_FileTransfer_CloseAndCommit: string = 'nsu=' + NS + ';i=148'
    static readonly CachedLoadingType_GetUpdateBehavior: string = 'nsu=' + NS + ';i=189'
    static readonly FileSystemLoadingType_FileSystem_CreateDirectory: string = 'nsu=' + NS + ';i=195'
    static readonly FileSystemLoadingType_FileSystem_CreateFile: string = 'nsu=' + NS + ';i=198'
    static readonly FileSystemLoadingType_FileSystem_DeleteFileSystemObject: string = 'nsu=' + NS + ';i=201'
    static readonly FileSystemLoadingType_FileSystem_MoveOrCopy: string = 'nsu=' + NS + ';i=203'
    static readonly FileSystemLoadingType_GetUpdateBehavior: string = 'nsu=' + NS + ';i=206'
    static readonly FileSystemLoadingType_ValidateFiles: string = 'nsu=' + NS + ';i=209'
    static readonly PrepareForUpdateStateMachineType_Prepare: string = 'nsu=' + NS + ';i=228'
    static readonly PrepareForUpdateStateMachineType_Abort: string = 'nsu=' + NS + ';i=229'
    static readonly PrepareForUpdateStateMachineType_Resume: string = 'nsu=' + NS + ';i=230'
    static readonly InstallationStateMachineType_InstallSoftwarePackage: string = 'nsu=' + NS + ';i=265'
    static readonly InstallationStateMachineType_InstallFiles: string = 'nsu=' + NS + ';i=268'
    static readonly InstallationStateMachineType_Resume: string = 'nsu=' + NS + ';i=270'
    static readonly ConfirmationStateMachineType_Confirm: string = 'nsu=' + NS + ';i=321'
}

export class ObjectIds {
    static readonly DeviceSet: string = 'nsu=' + NS + ';i=5001'
    static readonly DeviceFeatures: string = 'nsu=' + NS + ';i=15034'
    static readonly NetworkSet: string = 'nsu=' + NS + ';i=6078'
    static readonly DeviceTopology: string = 'nsu=' + NS + ';i=6094'
    static readonly TopologyElementType_ParameterSet: string = 'nsu=' + NS + ';i=5002'
    static readonly TopologyElementType_MethodSet: string = 'nsu=' + NS + ';i=5003'
    static readonly TopologyElementType_GroupIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6567'
    static readonly TopologyElementType_Identification: string = 'nsu=' + NS + ';i=6014'
    static readonly TopologyElementType_Lock: string = 'nsu=' + NS + ';i=6161'
    static readonly IDeviceHealthType_DeviceHealthAlarms: string = 'nsu=' + NS + ';i=15053'
    static readonly ISupportInfoType_DeviceTypeImage: string = 'nsu=' + NS + ';i=15055'
    static readonly ISupportInfoType_Documentation: string = 'nsu=' + NS + ';i=15057'
    static readonly ISupportInfoType_DocumentationFiles: string = 'nsu=' + NS + ';i=27'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder: string = 'nsu=' + NS + ';i=28'
    static readonly ISupportInfoType_ProtocolSupport: string = 'nsu=' + NS + ';i=15059'
    static readonly ISupportInfoType_ImageSet: string = 'nsu=' + NS + ';i=15061'
    static readonly DeviceType_CPIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6571'
    static readonly DeviceType_CPIdentifier_Placeholder_NetworkAddress: string = 'nsu=' + NS + ';i=6592'
    static readonly DeviceType_DeviceHealthAlarms: string = 'nsu=' + NS + ';i=15105'
    static readonly DeviceType_DeviceTypeImage: string = 'nsu=' + NS + ';i=6209'
    static readonly DeviceType_Documentation: string = 'nsu=' + NS + ';i=6211'
    static readonly DeviceType_ProtocolSupport: string = 'nsu=' + NS + ';i=6213'
    static readonly DeviceType_ImageSet: string = 'nsu=' + NS + ';i=6215'
    static readonly ConfigurableObjectType_SupportedTypes: string = 'nsu=' + NS + ';i=5004'
    static readonly ConfigurableObjectType_ObjectIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6026'
    static readonly FunctionalGroupType_GroupIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6027'
    static readonly NetworkType_ProfileIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6596'
    static readonly NetworkType_CPIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6248'
    static readonly NetworkType_CPIdentifier_Placeholder_NetworkAddress: string = 'nsu=' + NS + ';i=6292'
    static readonly NetworkType_Lock: string = 'nsu=' + NS + ';i=6294'
    static readonly ConnectionPointType_NetworkAddress: string = 'nsu=' + NS + ';i=6354'
    static readonly ConnectionPointType_ProfileIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6499'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6599'
    static readonly SoftwareUpdateType_Loading: string = 'nsu=' + NS + ';i=2'
    static readonly SoftwareUpdateType_PrepareForUpdate: string = 'nsu=' + NS + ';i=4'
    static readonly SoftwareUpdateType_Installation: string = 'nsu=' + NS + ';i=40'
    static readonly SoftwareUpdateType_PowerCycle: string = 'nsu=' + NS + ';i=76'
    static readonly SoftwareUpdateType_Confirmation: string = 'nsu=' + NS + ';i=98'
    static readonly SoftwareUpdateType_Parameters: string = 'nsu=' + NS + ';i=122'
    static readonly PackageLoadingType_CurrentVersion: string = 'nsu=' + NS + ';i=139'
    static readonly PackageLoadingType_FileTransfer: string = 'nsu=' + NS + ';i=140'
    static readonly CachedLoadingType_PendingVersion: string = 'nsu=' + NS + ';i=187'
    static readonly CachedLoadingType_FallbackVersion: string = 'nsu=' + NS + ';i=188'
    static readonly FileSystemLoadingType_FileSystem: string = 'nsu=' + NS + ';i=194'
    static readonly PrepareForUpdateStateMachineType_Idle: string = 'nsu=' + NS + ';i=231'
    static readonly PrepareForUpdateStateMachineType_Preparing: string = 'nsu=' + NS + ';i=233'
    static readonly PrepareForUpdateStateMachineType_PreparedForUpdate: string = 'nsu=' + NS + ';i=235'
    static readonly PrepareForUpdateStateMachineType_Resuming: string = 'nsu=' + NS + ';i=237'
    static readonly PrepareForUpdateStateMachineType_IdleToPreparing: string = 'nsu=' + NS + ';i=239'
    static readonly PrepareForUpdateStateMachineType_PreparingToIdle: string = 'nsu=' + NS + ';i=241'
    static readonly PrepareForUpdateStateMachineType_PreparingToPreparedForUpdate: string = 'nsu=' + NS + ';i=243'
    static readonly PrepareForUpdateStateMachineType_PreparedForUpdateToResuming: string = 'nsu=' + NS + ';i=245'
    static readonly PrepareForUpdateStateMachineType_ResumingToIdle: string = 'nsu=' + NS + ';i=247'
    static readonly InstallationStateMachineType_Idle: string = 'nsu=' + NS + ';i=271'
    static readonly InstallationStateMachineType_Installing: string = 'nsu=' + NS + ';i=273'
    static readonly InstallationStateMachineType_Error: string = 'nsu=' + NS + ';i=275'
    static readonly InstallationStateMachineType_IdleToInstalling: string = 'nsu=' + NS + ';i=277'
    static readonly InstallationStateMachineType_InstallingToIdle: string = 'nsu=' + NS + ';i=279'
    static readonly InstallationStateMachineType_InstallingToError: string = 'nsu=' + NS + ';i=281'
    static readonly InstallationStateMachineType_ErrorToIdle: string = 'nsu=' + NS + ';i=283'
    static readonly PowerCycleStateMachineType_NotWaitingForPowerCycle: string = 'nsu=' + NS + ';i=299'
    static readonly PowerCycleStateMachineType_WaitingForPowerCycle: string = 'nsu=' + NS + ';i=301'
    static readonly PowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle: string = 'nsu=' + NS + ';i=303'
    static readonly PowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle: string = 'nsu=' + NS + ';i=305'
    static readonly ConfirmationStateMachineType_NotWaitingForConfirm: string = 'nsu=' + NS + ';i=323'
    static readonly ConfirmationStateMachineType_WaitingForConfirm: string = 'nsu=' + NS + ';i=325'
    static readonly ConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm: string = 'nsu=' + NS + ';i=327'
    static readonly ConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm: string = 'nsu=' + NS + ';i=329'
    static readonly FetchResultDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=6551'
    static readonly TransferResultErrorDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=15891'
    static readonly TransferResultDataDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=15892'
    static readonly ParameterResultDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=6554'
    static readonly FetchResultDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=6535'
    static readonly TransferResultErrorDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=15900'
    static readonly TransferResultDataDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=15901'
    static readonly ParameterResultDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=6538'
    static readonly FetchResultDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=15909'
    static readonly TransferResultErrorDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=15910'
    static readonly TransferResultDataDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=15911'
    static readonly ParameterResultDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=15912'
}

export class ObjectTypeIds {
    static readonly TopologyElementType: string = 'nsu=' + NS + ';i=1001'
    static readonly IVendorNameplateType: string = 'nsu=' + NS + ';i=15035'
    static readonly ITagNameplateType: string = 'nsu=' + NS + ';i=15048'
    static readonly IDeviceHealthType: string = 'nsu=' + NS + ';i=15051'
    static readonly ISupportInfoType: string = 'nsu=' + NS + ';i=15054'
    static readonly ComponentType: string = 'nsu=' + NS + ';i=15063'
    static readonly DeviceType: string = 'nsu=' + NS + ';i=1002'
    static readonly SoftwareType: string = 'nsu=' + NS + ';i=15106'
    static readonly BlockType: string = 'nsu=' + NS + ';i=1003'
    static readonly DeviceHealthDiagnosticAlarmType: string = 'nsu=' + NS + ';i=15143'
    static readonly FailureAlarmType: string = 'nsu=' + NS + ';i=15292'
    static readonly CheckFunctionAlarmType: string = 'nsu=' + NS + ';i=15441'
    static readonly OffSpecAlarmType: string = 'nsu=' + NS + ';i=15590'
    static readonly MaintenanceRequiredAlarmType: string = 'nsu=' + NS + ';i=15739'
    static readonly ConfigurableObjectType: string = 'nsu=' + NS + ';i=1004'
    static readonly BaseLifetimeIndicationType: string = 'nsu=' + NS + ';i=473'
    static readonly TimeIndicationType: string = 'nsu=' + NS + ';i=474'
    static readonly NumberOfPartsIndicationType: string = 'nsu=' + NS + ';i=475'
    static readonly NumberOfUsagesIndicationType: string = 'nsu=' + NS + ';i=476'
    static readonly LengthIndicationType: string = 'nsu=' + NS + ';i=477'
    static readonly DiameterIndicationType: string = 'nsu=' + NS + ';i=478'
    static readonly SubstanceVolumeIndicationType: string = 'nsu=' + NS + ';i=479'
    static readonly FunctionalGroupType: string = 'nsu=' + NS + ';i=1005'
    static readonly ProtocolType: string = 'nsu=' + NS + ';i=1006'
    static readonly IOperationCounterType: string = 'nsu=' + NS + ';i=480'
    static readonly NetworkType: string = 'nsu=' + NS + ';i=6247'
    static readonly ConnectionPointType: string = 'nsu=' + NS + ';i=6308'
    static readonly TransferServicesType: string = 'nsu=' + NS + ';i=6526'
    static readonly LockingServicesType: string = 'nsu=' + NS + ';i=6388'
    static readonly SoftwareUpdateType: string = 'nsu=' + NS + ';i=1'
    static readonly SoftwareLoadingType: string = 'nsu=' + NS + ';i=135'
    static readonly PackageLoadingType: string = 'nsu=' + NS + ';i=137'
    static readonly DirectLoadingType: string = 'nsu=' + NS + ';i=153'
    static readonly CachedLoadingType: string = 'nsu=' + NS + ';i=171'
    static readonly FileSystemLoadingType: string = 'nsu=' + NS + ';i=192'
    static readonly SoftwareVersionType: string = 'nsu=' + NS + ';i=212'
    static readonly PrepareForUpdateStateMachineType: string = 'nsu=' + NS + ';i=213'
    static readonly InstallationStateMachineType: string = 'nsu=' + NS + ';i=249'
    static readonly PowerCycleStateMachineType: string = 'nsu=' + NS + ';i=285'
    static readonly ConfirmationStateMachineType: string = 'nsu=' + NS + ';i=307'
}

export class ReferenceTypeIds {
    static readonly ConnectsTo: string = 'nsu=' + NS + ';i=6030'
    static readonly ConnectsToParent: string = 'nsu=' + NS + ';i=6467'
    static readonly IsOnline: string = 'nsu=' + NS + ';i=6031'
}

export class VariableIds {
    static readonly TopologyElementType_ParameterSet_ParameterIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6017'
    static readonly TopologyElementType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly TopologyElementType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly TopologyElementType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly TopologyElementType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly TopologyElementType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly TopologyElementType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly TopologyElementType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly TopologyElementType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly TopologyElementType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly IVendorNameplateType_Manufacturer: string = 'nsu=' + NS + ';i=15036'
    static readonly IVendorNameplateType_ManufacturerUri: string = 'nsu=' + NS + ';i=15037'
    static readonly IVendorNameplateType_Model: string = 'nsu=' + NS + ';i=15038'
    static readonly IVendorNameplateType_HardwareRevision: string = 'nsu=' + NS + ';i=15039'
    static readonly IVendorNameplateType_SoftwareRevision: string = 'nsu=' + NS + ';i=15040'
    static readonly IVendorNameplateType_DeviceRevision: string = 'nsu=' + NS + ';i=15041'
    static readonly IVendorNameplateType_ProductCode: string = 'nsu=' + NS + ';i=15042'
    static readonly IVendorNameplateType_DeviceManual: string = 'nsu=' + NS + ';i=15043'
    static readonly IVendorNameplateType_DeviceClass: string = 'nsu=' + NS + ';i=15044'
    static readonly IVendorNameplateType_SerialNumber: string = 'nsu=' + NS + ';i=15045'
    static readonly IVendorNameplateType_ProductInstanceUri: string = 'nsu=' + NS + ';i=15046'
    static readonly IVendorNameplateType_RevisionCounter: string = 'nsu=' + NS + ';i=15047'
    static readonly IVendorNameplateType_SoftwareReleaseDate: string = 'nsu=' + NS + ';i=23'
    static readonly IVendorNameplateType_PatchIdentifiers: string = 'nsu=' + NS + ';i=24'
    static readonly ITagNameplateType_AssetId: string = 'nsu=' + NS + ';i=15049'
    static readonly ITagNameplateType_ComponentName: string = 'nsu=' + NS + ';i=15050'
    static readonly IDeviceHealthType_DeviceHealth: string = 'nsu=' + NS + ';i=15052'
    static readonly ISupportInfoType_DeviceTypeImage_ImageIdentifier_Placeholder: string = 'nsu=' + NS + ';i=15056'
    static readonly ISupportInfoType_Documentation_DocumentIdentifier_Placeholder: string = 'nsu=' + NS + ';i=15058'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Size: string = 'nsu=' + NS + ';i=29'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Writable: string = 'nsu=' + NS + ';i=30'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_UserWritable: string = 'nsu=' + NS + ';i=31'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_OpenCount: string = 'nsu=' + NS + ';i=32'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open_InputArguments: string = 'nsu=' + NS + ';i=37'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open_OutputArguments: string = 'nsu=' + NS + ';i=38'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Close_InputArguments: string = 'nsu=' + NS + ';i=62'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read_InputArguments: string = 'nsu=' + NS + ';i=64'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read_OutputArguments: string = 'nsu=' + NS + ';i=65'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Write_InputArguments: string = 'nsu=' + NS + ';i=67'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition_InputArguments: string = 'nsu=' + NS + ';i=69'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition_OutputArguments: string = 'nsu=' + NS + ';i=70'
    static readonly ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_SetPosition_InputArguments: string = 'nsu=' + NS + ';i=72'
    static readonly ISupportInfoType_ProtocolSupport_ProtocolSupportIdentifier_Placeholder: string = 'nsu=' + NS + ';i=15060'
    static readonly ISupportInfoType_ImageSet_ImageIdentifier_Placeholder: string = 'nsu=' + NS + ';i=15062'
    static readonly ComponentType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly ComponentType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly ComponentType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly ComponentType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly ComponentType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly ComponentType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly ComponentType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly ComponentType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly ComponentType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly ComponentType_Manufacturer: string = 'nsu=' + NS + ';i=15086'
    static readonly ComponentType_ManufacturerUri: string = 'nsu=' + NS + ';i=15087'
    static readonly ComponentType_Model: string = 'nsu=' + NS + ';i=15088'
    static readonly ComponentType_HardwareRevision: string = 'nsu=' + NS + ';i=15089'
    static readonly ComponentType_SoftwareRevision: string = 'nsu=' + NS + ';i=15090'
    static readonly ComponentType_DeviceRevision: string = 'nsu=' + NS + ';i=15091'
    static readonly ComponentType_ProductCode: string = 'nsu=' + NS + ';i=15092'
    static readonly ComponentType_DeviceManual: string = 'nsu=' + NS + ';i=15093'
    static readonly ComponentType_DeviceClass: string = 'nsu=' + NS + ';i=15094'
    static readonly ComponentType_SerialNumber: string = 'nsu=' + NS + ';i=15095'
    static readonly ComponentType_ProductInstanceUri: string = 'nsu=' + NS + ';i=15096'
    static readonly ComponentType_RevisionCounter: string = 'nsu=' + NS + ';i=15097'
    static readonly ComponentType_AssetId: string = 'nsu=' + NS + ';i=15098'
    static readonly ComponentType_ComponentName: string = 'nsu=' + NS + ';i=15099'
    static readonly DeviceType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly DeviceType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly DeviceType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly DeviceType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly DeviceType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly DeviceType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly DeviceType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly DeviceType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly DeviceType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly DeviceType_Manufacturer: string = 'nsu=' + NS + ';i=6003'
    static readonly DeviceType_ManufacturerUri: string = 'nsu=' + NS + ';i=15100'
    static readonly DeviceType_Model: string = 'nsu=' + NS + ';i=6004'
    static readonly DeviceType_HardwareRevision: string = 'nsu=' + NS + ';i=6008'
    static readonly DeviceType_SoftwareRevision: string = 'nsu=' + NS + ';i=6007'
    static readonly DeviceType_DeviceRevision: string = 'nsu=' + NS + ';i=6006'
    static readonly DeviceType_ProductCode: string = 'nsu=' + NS + ';i=15101'
    static readonly DeviceType_DeviceManual: string = 'nsu=' + NS + ';i=6005'
    static readonly DeviceType_DeviceClass: string = 'nsu=' + NS + ';i=6470'
    static readonly DeviceType_SerialNumber: string = 'nsu=' + NS + ';i=6001'
    static readonly DeviceType_ProductInstanceUri: string = 'nsu=' + NS + ';i=15102'
    static readonly DeviceType_RevisionCounter: string = 'nsu=' + NS + ';i=6002'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly DeviceType_CPIdentifier_Placeholder_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly DeviceType_DeviceHealth: string = 'nsu=' + NS + ';i=6208'
    static readonly DeviceType_DeviceTypeImage_ImageIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6210'
    static readonly DeviceType_Documentation_DocumentIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6212'
    static readonly DeviceType_ProtocolSupport_ProtocolSupportIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6214'
    static readonly DeviceType_ImageSet_ImageIdentifier_Placeholder: string = 'nsu=' + NS + ';i=6216'
    static readonly SoftwareType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly SoftwareType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly SoftwareType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly SoftwareType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly SoftwareType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly SoftwareType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly SoftwareType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly SoftwareType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly SoftwareType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly SoftwareType_Manufacturer: string = 'nsu=' + NS + ';i=15129'
    static readonly SoftwareType_Model: string = 'nsu=' + NS + ';i=15131'
    static readonly SoftwareType_SoftwareRevision: string = 'nsu=' + NS + ';i=15133'
    static readonly BlockType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly BlockType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly BlockType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly BlockType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly BlockType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly BlockType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly BlockType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly BlockType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly BlockType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly BlockType_RevisionCounter: string = 'nsu=' + NS + ';i=6009'
    static readonly BlockType_ActualMode: string = 'nsu=' + NS + ';i=6010'
    static readonly BlockType_PermittedMode: string = 'nsu=' + NS + ';i=6011'
    static readonly BlockType_NormalMode: string = 'nsu=' + NS + ';i=6012'
    static readonly BlockType_TargetMode: string = 'nsu=' + NS + ';i=6013'
    static readonly LifetimeVariableType_StartValue: string = 'nsu=' + NS + ';i=469'
    static readonly LifetimeVariableType_LimitValue: string = 'nsu=' + NS + ';i=470'
    static readonly LifetimeVariableType_Indication: string = 'nsu=' + NS + ';i=471'
    static readonly LifetimeVariableType_WarningValues: string = 'nsu=' + NS + ';i=472'
    static readonly FunctionalGroupType_GroupIdentifier_Placeholder_UIElement: string = 'nsu=' + NS + ';i=6242'
    static readonly FunctionalGroupType_UIElement: string = 'nsu=' + NS + ';i=6243'
    static readonly DeviceHealthEnumeration_EnumStrings: string = 'nsu=' + NS + ';i=6450'
    static readonly IOperationCounterType_PowerOnDuration: string = 'nsu=' + NS + ';i=481'
    static readonly IOperationCounterType_OperationDuration: string = 'nsu=' + NS + ';i=482'
    static readonly IOperationCounterType_OperationCycleCounter: string = 'nsu=' + NS + ';i=483'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly NetworkType_CPIdentifier_Placeholder_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly NetworkType_Lock_Locked: string = 'nsu=' + NS + ';i=6497'
    static readonly NetworkType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6296'
    static readonly NetworkType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6297'
    static readonly NetworkType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6298'
    static readonly NetworkType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6300'
    static readonly NetworkType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6301'
    static readonly NetworkType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6303'
    static readonly NetworkType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6305'
    static readonly NetworkType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6307'
    static readonly ConnectionPointType_Lock_Locked: string = 'nsu=' + NS + ';i=6468'
    static readonly ConnectionPointType_Lock_LockingClient: string = 'nsu=' + NS + ';i=6163'
    static readonly ConnectionPointType_Lock_LockingUser: string = 'nsu=' + NS + ';i=6164'
    static readonly ConnectionPointType_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6165'
    static readonly ConnectionPointType_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6167'
    static readonly ConnectionPointType_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6168'
    static readonly ConnectionPointType_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6170'
    static readonly ConnectionPointType_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6172'
    static readonly ConnectionPointType_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6174'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_Locked: string = 'nsu=' + NS + ';i=6497'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_LockingClient: string = 'nsu=' + NS + ';i=6296'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_LockingUser: string = 'nsu=' + NS + ';i=6297'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RemainingLockTime: string = 'nsu=' + NS + ';i=6298'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6300'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6301'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6303'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6305'
    static readonly ConnectionPointType_NetworkIdentifier_Placeholder_Lock_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6307'
    static readonly TransferServicesType_TransferToDevice_OutputArguments: string = 'nsu=' + NS + ';i=6528'
    static readonly TransferServicesType_TransferFromDevice_OutputArguments: string = 'nsu=' + NS + ';i=6530'
    static readonly TransferServicesType_FetchTransferResultData_InputArguments: string = 'nsu=' + NS + ';i=6532'
    static readonly TransferServicesType_FetchTransferResultData_OutputArguments: string = 'nsu=' + NS + ';i=6533'
    static readonly LockingServicesType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=15890'
    static readonly LockingServicesType_Locked: string = 'nsu=' + NS + ';i=6534'
    static readonly LockingServicesType_LockingClient: string = 'nsu=' + NS + ';i=6390'
    static readonly LockingServicesType_LockingUser: string = 'nsu=' + NS + ';i=6391'
    static readonly LockingServicesType_RemainingLockTime: string = 'nsu=' + NS + ';i=6392'
    static readonly LockingServicesType_InitLock_InputArguments: string = 'nsu=' + NS + ';i=6394'
    static readonly LockingServicesType_InitLock_OutputArguments: string = 'nsu=' + NS + ';i=6395'
    static readonly LockingServicesType_RenewLock_OutputArguments: string = 'nsu=' + NS + ';i=6397'
    static readonly LockingServicesType_ExitLock_OutputArguments: string = 'nsu=' + NS + ';i=6399'
    static readonly LockingServicesType_BreakLock_OutputArguments: string = 'nsu=' + NS + ';i=6401'
    static readonly SoftwareUpdateType_PrepareForUpdate_CurrentState: string = 'nsu=' + NS + ';i=5'
    static readonly SoftwareUpdateType_PrepareForUpdate_CurrentState_Id: string = 'nsu=' + NS + ';i=6'
    static readonly SoftwareUpdateType_Installation_CurrentState: string = 'nsu=' + NS + ';i=41'
    static readonly SoftwareUpdateType_Installation_CurrentState_Id: string = 'nsu=' + NS + ';i=42'
    static readonly SoftwareUpdateType_Installation_InstallSoftwarePackage_InputArguments: string = 'nsu=' + NS + ';i=266'
    static readonly SoftwareUpdateType_Installation_InstallFiles_InputArguments: string = 'nsu=' + NS + ';i=269'
    static readonly SoftwareUpdateType_PowerCycle_CurrentState: string = 'nsu=' + NS + ';i=77'
    static readonly SoftwareUpdateType_PowerCycle_CurrentState_Id: string = 'nsu=' + NS + ';i=78'
    static readonly SoftwareUpdateType_Confirmation_CurrentState: string = 'nsu=' + NS + ';i=99'
    static readonly SoftwareUpdateType_Confirmation_CurrentState_Id: string = 'nsu=' + NS + ';i=100'
    static readonly SoftwareUpdateType_Confirmation_ConfirmationTimeout: string = 'nsu=' + NS + ';i=113'
    static readonly SoftwareUpdateType_Parameters_ClientProcessingTimeout: string = 'nsu=' + NS + ';i=123'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=125'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=126'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForWrite_InputArguments: string = 'nsu=' + NS + ';i=128'
    static readonly SoftwareUpdateType_Parameters_GenerateFileForWrite_OutputArguments: string = 'nsu=' + NS + ';i=129'
    static readonly SoftwareUpdateType_Parameters_CloseAndCommit_InputArguments: string = 'nsu=' + NS + ';i=131'
    static readonly SoftwareUpdateType_Parameters_CloseAndCommit_OutputArguments: string = 'nsu=' + NS + ';i=132'
    static readonly SoftwareUpdateType_UpdateStatus: string = 'nsu=' + NS + ';i=133'
    static readonly SoftwareUpdateType_VendorErrorCode: string = 'nsu=' + NS + ';i=402'
    static readonly SoftwareUpdateType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=134'
    static readonly SoftwareLoadingType_UpdateKey: string = 'nsu=' + NS + ';i=136'
    static readonly PackageLoadingType_CurrentVersion_Manufacturer: string = 'nsu=' + NS + ';i=345'
    static readonly PackageLoadingType_CurrentVersion_ManufacturerUri: string = 'nsu=' + NS + ';i=346'
    static readonly PackageLoadingType_CurrentVersion_SoftwareRevision: string = 'nsu=' + NS + ';i=347'
    static readonly PackageLoadingType_FileTransfer_ClientProcessingTimeout: string = 'nsu=' + NS + ';i=141'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=143'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=144'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: string = 'nsu=' + NS + ';i=146'
    static readonly PackageLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: string = 'nsu=' + NS + ';i=147'
    static readonly PackageLoadingType_FileTransfer_CloseAndCommit_InputArguments: string = 'nsu=' + NS + ';i=149'
    static readonly PackageLoadingType_FileTransfer_CloseAndCommit_OutputArguments: string = 'nsu=' + NS + ';i=150'
    static readonly PackageLoadingType_ErrorMessage: string = 'nsu=' + NS + ';i=151'
    static readonly PackageLoadingType_WriteBlockSize: string = 'nsu=' + NS + ';i=152'
    static readonly DirectLoadingType_CurrentVersion_Manufacturer: string = 'nsu=' + NS + ';i=345'
    static readonly DirectLoadingType_CurrentVersion_ManufacturerUri: string = 'nsu=' + NS + ';i=346'
    static readonly DirectLoadingType_CurrentVersion_SoftwareRevision: string = 'nsu=' + NS + ';i=347'
    static readonly DirectLoadingType_FileTransfer_ClientProcessingTimeout: string = 'nsu=' + NS + ';i=141'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=143'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=144'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: string = 'nsu=' + NS + ';i=146'
    static readonly DirectLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: string = 'nsu=' + NS + ';i=147'
    static readonly DirectLoadingType_FileTransfer_CloseAndCommit_InputArguments: string = 'nsu=' + NS + ';i=149'
    static readonly DirectLoadingType_FileTransfer_CloseAndCommit_OutputArguments: string = 'nsu=' + NS + ';i=150'
    static readonly DirectLoadingType_UpdateBehavior: string = 'nsu=' + NS + ';i=169'
    static readonly DirectLoadingType_WriteTimeout: string = 'nsu=' + NS + ';i=170'
    static readonly CachedLoadingType_CurrentVersion_Manufacturer: string = 'nsu=' + NS + ';i=345'
    static readonly CachedLoadingType_CurrentVersion_ManufacturerUri: string = 'nsu=' + NS + ';i=346'
    static readonly CachedLoadingType_CurrentVersion_SoftwareRevision: string = 'nsu=' + NS + ';i=347'
    static readonly CachedLoadingType_FileTransfer_ClientProcessingTimeout: string = 'nsu=' + NS + ';i=141'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=143'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=144'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: string = 'nsu=' + NS + ';i=146'
    static readonly CachedLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: string = 'nsu=' + NS + ';i=147'
    static readonly CachedLoadingType_FileTransfer_CloseAndCommit_InputArguments: string = 'nsu=' + NS + ';i=149'
    static readonly CachedLoadingType_FileTransfer_CloseAndCommit_OutputArguments: string = 'nsu=' + NS + ';i=150'
    static readonly CachedLoadingType_PendingVersion_Manufacturer: string = 'nsu=' + NS + ';i=366'
    static readonly CachedLoadingType_PendingVersion_ManufacturerUri: string = 'nsu=' + NS + ';i=367'
    static readonly CachedLoadingType_PendingVersion_SoftwareRevision: string = 'nsu=' + NS + ';i=368'
    static readonly CachedLoadingType_FallbackVersion_Manufacturer: string = 'nsu=' + NS + ';i=373'
    static readonly CachedLoadingType_FallbackVersion_ManufacturerUri: string = 'nsu=' + NS + ';i=374'
    static readonly CachedLoadingType_FallbackVersion_SoftwareRevision: string = 'nsu=' + NS + ';i=375'
    static readonly CachedLoadingType_GetUpdateBehavior_InputArguments: string = 'nsu=' + NS + ';i=190'
    static readonly CachedLoadingType_GetUpdateBehavior_OutputArguments: string = 'nsu=' + NS + ';i=191'
    static readonly FileSystemLoadingType_FileSystem_CreateDirectory_InputArguments: string = 'nsu=' + NS + ';i=196'
    static readonly FileSystemLoadingType_FileSystem_CreateDirectory_OutputArguments: string = 'nsu=' + NS + ';i=197'
    static readonly FileSystemLoadingType_FileSystem_CreateFile_InputArguments: string = 'nsu=' + NS + ';i=199'
    static readonly FileSystemLoadingType_FileSystem_CreateFile_OutputArguments: string = 'nsu=' + NS + ';i=200'
    static readonly FileSystemLoadingType_FileSystem_DeleteFileSystemObject_InputArguments: string = 'nsu=' + NS + ';i=202'
    static readonly FileSystemLoadingType_FileSystem_MoveOrCopy_InputArguments: string = 'nsu=' + NS + ';i=204'
    static readonly FileSystemLoadingType_FileSystem_MoveOrCopy_OutputArguments: string = 'nsu=' + NS + ';i=205'
    static readonly FileSystemLoadingType_GetUpdateBehavior_InputArguments: string = 'nsu=' + NS + ';i=207'
    static readonly FileSystemLoadingType_GetUpdateBehavior_OutputArguments: string = 'nsu=' + NS + ';i=208'
    static readonly FileSystemLoadingType_ValidateFiles_InputArguments: string = 'nsu=' + NS + ';i=210'
    static readonly FileSystemLoadingType_ValidateFiles_OutputArguments: string = 'nsu=' + NS + ';i=211'
    static readonly SoftwareVersionType_Manufacturer: string = 'nsu=' + NS + ';i=380'
    static readonly SoftwareVersionType_ManufacturerUri: string = 'nsu=' + NS + ';i=381'
    static readonly SoftwareVersionType_SoftwareRevision: string = 'nsu=' + NS + ';i=382'
    static readonly SoftwareVersionType_PatchIdentifiers: string = 'nsu=' + NS + ';i=383'
    static readonly SoftwareVersionType_ReleaseDate: string = 'nsu=' + NS + ';i=384'
    static readonly SoftwareVersionType_ChangeLogReference: string = 'nsu=' + NS + ';i=385'
    static readonly SoftwareVersionType_Hash: string = 'nsu=' + NS + ';i=386'
    static readonly PrepareForUpdateStateMachineType_PercentComplete: string = 'nsu=' + NS + ';i=227'
    static readonly PrepareForUpdateStateMachineType_Idle_StateNumber: string = 'nsu=' + NS + ';i=232'
    static readonly PrepareForUpdateStateMachineType_Preparing_StateNumber: string = 'nsu=' + NS + ';i=234'
    static readonly PrepareForUpdateStateMachineType_PreparedForUpdate_StateNumber: string = 'nsu=' + NS + ';i=236'
    static readonly PrepareForUpdateStateMachineType_Resuming_StateNumber: string = 'nsu=' + NS + ';i=238'
    static readonly PrepareForUpdateStateMachineType_IdleToPreparing_TransitionNumber: string = 'nsu=' + NS + ';i=240'
    static readonly PrepareForUpdateStateMachineType_PreparingToIdle_TransitionNumber: string = 'nsu=' + NS + ';i=242'
    static readonly PrepareForUpdateStateMachineType_PreparingToPreparedForUpdate_TransitionNumber: string = 'nsu=' + NS + ';i=244'
    static readonly PrepareForUpdateStateMachineType_PreparedForUpdateToResuming_TransitionNumber: string = 'nsu=' + NS + ';i=246'
    static readonly PrepareForUpdateStateMachineType_ResumingToIdle_TransitionNumber: string = 'nsu=' + NS + ';i=248'
    static readonly InstallationStateMachineType_PercentComplete: string = 'nsu=' + NS + ';i=263'
    static readonly InstallationStateMachineType_InstallationDelay: string = 'nsu=' + NS + ';i=264'
    static readonly InstallationStateMachineType_InstallSoftwarePackage_InputArguments: string = 'nsu=' + NS + ';i=266'
    static readonly InstallationStateMachineType_InstallFiles_InputArguments: string = 'nsu=' + NS + ';i=269'
    static readonly InstallationStateMachineType_Idle_StateNumber: string = 'nsu=' + NS + ';i=272'
    static readonly InstallationStateMachineType_Installing_StateNumber: string = 'nsu=' + NS + ';i=274'
    static readonly InstallationStateMachineType_Error_StateNumber: string = 'nsu=' + NS + ';i=276'
    static readonly InstallationStateMachineType_IdleToInstalling_TransitionNumber: string = 'nsu=' + NS + ';i=387'
    static readonly InstallationStateMachineType_InstallingToIdle_TransitionNumber: string = 'nsu=' + NS + ';i=280'
    static readonly InstallationStateMachineType_InstallingToError_TransitionNumber: string = 'nsu=' + NS + ';i=282'
    static readonly InstallationStateMachineType_ErrorToIdle_TransitionNumber: string = 'nsu=' + NS + ';i=284'
    static readonly PowerCycleStateMachineType_NotWaitingForPowerCycle_StateNumber: string = 'nsu=' + NS + ';i=300'
    static readonly PowerCycleStateMachineType_WaitingForPowerCycle_StateNumber: string = 'nsu=' + NS + ';i=302'
    static readonly PowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle_TransitionNumber: string = 'nsu=' + NS + ';i=304'
    static readonly PowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle_TransitionNumber: string = 'nsu=' + NS + ';i=306'
    static readonly ConfirmationStateMachineType_ConfirmationTimeout: string = 'nsu=' + NS + ';i=322'
    static readonly ConfirmationStateMachineType_NotWaitingForConfirm_StateNumber: string = 'nsu=' + NS + ';i=324'
    static readonly ConfirmationStateMachineType_WaitingForConfirm_StateNumber: string = 'nsu=' + NS + ';i=326'
    static readonly ConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm_TransitionNumber: string = 'nsu=' + NS + ';i=328'
    static readonly ConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm_TransitionNumber: string = 'nsu=' + NS + ';i=330'
    static readonly SoftwareVersionFileType_EnumStrings: string = 'nsu=' + NS + ';i=332'
    static readonly UpdateBehavior_OptionSetValues: string = 'nsu=' + NS + ';i=388'
}

export class VariableTypeIds {
    static readonly LifetimeVariableType: string = 'nsu=' + NS + ';i=468'
    static readonly UIElementType: string = 'nsu=' + NS + ';i=6246'
}
