from enum import Enum

class Namespaces(Enum):
     Uri = "http://opcfoundation.org/UA/Machinery/"

class BrowseNames(Enum):
    Component_Placeholder = "<Component>"
    Components = "Components"
    Consumption = "Consumption"
    Description = "Description"
    EquipmentLife = "EquipmentLife"
    Executing = "Executing"
    FromExecutingToExecuting = "FromExecutingToExecuting"
    FromExecutingToNotAvailable = "FromExecutingToNotAvailable"
    FromExecutingToNotExecuting = "FromExecutingToNotExecuting"
    FromExecutingToOutOfService = "FromExecutingToOutOfService"
    FromMaintenanceToMaintenance = "FromMaintenanceToMaintenance"
    FromMaintenanceToNone = "FromMaintenanceToNone"
    FromMaintenanceToProcessing = "FromMaintenanceToProcessing"
    FromMaintenanceToSetup = "FromMaintenanceToSetup"
    FromNoneToMaintenance = "FromNoneToMaintenance"
    FromNoneToNone = "FromNoneToNone"
    FromNoneToProcessing = "FromNoneToProcessing"
    FromNoneToSetup = "FromNoneToSetup"
    FromNotAvailableToExecuting = "FromNotAvailableToExecuting"
    FromNotAvailableToNotAvailable = "FromNotAvailableToNotAvailable"
    FromNotAvailableToNotExecuting = "FromNotAvailableToNotExecuting"
    FromNotAvailableToOutOfService = "FromNotAvailableToOutOfService"
    FromNotExecutingToExecuting = "FromNotExecutingToExecuting"
    FromNotExecutingToNotAvailable = "FromNotExecutingToNotAvailable"
    FromNotExecutingToNotExecuting = "FromNotExecutingToNotExecuting"
    FromNotExecutingToOutOfService = "FromNotExecutingToOutOfService"
    FromOutOfServiceToExecuting = "FromOutOfServiceToExecuting"
    FromOutOfServiceToNotAvailable = "FromOutOfServiceToNotAvailable"
    FromOutOfServiceToNotExecuting = "FromOutOfServiceToNotExecuting"
    FromOutOfServiceToOutOfService = "FromOutOfServiceToOutOfService"
    FromProcessingToMaintenance = "FromProcessingToMaintenance"
    FromProcessingToNone = "FromProcessingToNone"
    FromProcessingToProcessing = "FromProcessingToProcessing"
    FromProcessingToSetup = "FromProcessingToSetup"
    FromSetupToMaintenance = "FromSetupToMaintenance"
    FromSetupToNone = "FromSetupToNone"
    FromSetupToProcessing = "FromSetupToProcessing"
    FromSetupToSetup = "FromSetupToSetup"
    Health = "Health"
    Identification = "Identification"
    IMachineryEquipmentType = "IMachineryEquipmentType"
    IMachineryItemVendorNameplateType = "IMachineryItemVendorNameplateType"
    IMachineTagNameplateType = "IMachineTagNameplateType"
    IMachineVendorNameplateType = "IMachineVendorNameplateType"
    InitialOperationDate = "InitialOperationDate"
    LifetimeCounters = "LifetimeCounters"
    LifetimeVariable_Placeholder = "<LifetimeVariable>"
    Location = "Location"
    MachineComponentsType = "MachineComponentsType"
    MachineIdentificationType = "MachineIdentificationType"
    MachineryComponentIdentificationType = "MachineryComponentIdentificationType"
    MachineryEquipment = "MachineryEquipment"
    MachineryEquipment_Placeholder = "<MachineryEquipment>"
    MachineryEquipmentFolderType = "MachineryEquipmentFolderType"
    MachineryEquipmentTypeId = "MachineryEquipmentTypeId"
    MachineryItemIdentificationType = "MachineryItemIdentificationType"
    MachineryItemState = "MachineryItemState"
    MachineryItemState_StateMachineType = "MachineryItemState_StateMachineType"
    MachineryLifetimeCounterType = "MachineryLifetimeCounterType"
    MachineryOperationCounterType = "MachineryOperationCounterType"
    MachineryOperationMode = "MachineryOperationMode"
    MachineryOperationModeStateMachineType = "MachineryOperationModeStateMachineType"
    Machines = "Machines"
    Maintenance = "Maintenance"
    Monitoring = "Monitoring"
    MonitoringType = "MonitoringType"
    MonthOfConstruction = "MonthOfConstruction"
    None = "None"
    NotAvailable = "NotAvailable"
    NotExecuting = "NotExecuting"
    Notifications = "Notifications"
    NotificationsType = "NotificationsType"
    OperationCounters = "OperationCounters"
    OperationMode = "OperationMode"
    OutOfService = "OutOfService"
    Process = "Process"
    Processing = "Processing"
    Setup = "Setup"
    Stacklight = "Stacklight"
    Status = "Status"
    YearOfConstruction = "YearOfConstruction"

class ObjectIds(Enum):
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder = "nsu=http://opcfoundation.org/UA/Machinery/;i=5052"
    MonitoringType_Consumption = "nsu=http://opcfoundation.org/UA/Machinery/;i=5047"
    MonitoringType_Health = "nsu=http://opcfoundation.org/UA/Machinery/;i=5045"
    MonitoringType_Health_DeviceHealthAlarms = "nsu=http://opcfoundation.org/UA/Machinery/;i=5051"
    MonitoringType_Process = "nsu=http://opcfoundation.org/UA/Machinery/;i=5046"
    MonitoringType_Status = "nsu=http://opcfoundation.org/UA/Machinery/;i=5044"
    MonitoringType_Status_MachineryItemState = "nsu=http://opcfoundation.org/UA/Machinery/;i=5048"
    MonitoringType_Status_OperationMode = "nsu=http://opcfoundation.org/UA/Machinery/;i=5049"
    MonitoringType_Status_Stacklight = "nsu=http://opcfoundation.org/UA/Machinery/;i=5050"
    MachineComponentsType_Component_Placeholder = "nsu=http://opcfoundation.org/UA/Machinery/;i=5002"
    MachineComponentsType_Component_Placeholder_Identification = "nsu=http://opcfoundation.org/UA/Machinery/;i=5003"
    MachineryItemState_StateMachineType_Executing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5006"
    MachineryItemState_StateMachineType_FromExecutingToExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5023"
    MachineryItemState_StateMachineType_FromExecutingToNotAvailable = "nsu=http://opcfoundation.org/UA/Machinery/;i=5020"
    MachineryItemState_StateMachineType_FromExecutingToNotExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5022"
    MachineryItemState_StateMachineType_FromExecutingToOutOfService = "nsu=http://opcfoundation.org/UA/Machinery/;i=5021"
    MachineryItemState_StateMachineType_FromNotAvailableToExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5010"
    MachineryItemState_StateMachineType_FromNotAvailableToNotAvailable = "nsu=http://opcfoundation.org/UA/Machinery/;i=5011"
    MachineryItemState_StateMachineType_FromNotAvailableToNotExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5009"
    MachineryItemState_StateMachineType_FromNotAvailableToOutOfService = "nsu=http://opcfoundation.org/UA/Machinery/;i=5008"
    MachineryItemState_StateMachineType_FromNotExecutingToExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5018"
    MachineryItemState_StateMachineType_FromNotExecutingToNotAvailable = "nsu=http://opcfoundation.org/UA/Machinery/;i=5016"
    MachineryItemState_StateMachineType_FromNotExecutingToNotExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5019"
    MachineryItemState_StateMachineType_FromNotExecutingToOutOfService = "nsu=http://opcfoundation.org/UA/Machinery/;i=5017"
    MachineryItemState_StateMachineType_FromOutOfServiceToExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5014"
    MachineryItemState_StateMachineType_FromOutOfServiceToNotAvailable = "nsu=http://opcfoundation.org/UA/Machinery/;i=5012"
    MachineryItemState_StateMachineType_FromOutOfServiceToNotExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5013"
    MachineryItemState_StateMachineType_FromOutOfServiceToOutOfService = "nsu=http://opcfoundation.org/UA/Machinery/;i=5015"
    MachineryItemState_StateMachineType_NotAvailable = "nsu=http://opcfoundation.org/UA/Machinery/;i=5005"
    MachineryItemState_StateMachineType_NotExecuting = "nsu=http://opcfoundation.org/UA/Machinery/;i=5007"
    MachineryItemState_StateMachineType_OutOfService = "nsu=http://opcfoundation.org/UA/Machinery/;i=5004"
    MachineryOperationModeStateMachineType_FromMaintenanceToMaintenance = "nsu=http://opcfoundation.org/UA/Machinery/;i=5035"
    MachineryOperationModeStateMachineType_FromMaintenanceToNone = "nsu=http://opcfoundation.org/UA/Machinery/;i=5032"
    MachineryOperationModeStateMachineType_FromMaintenanceToProcessing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5034"
    MachineryOperationModeStateMachineType_FromMaintenanceToSetup = "nsu=http://opcfoundation.org/UA/Machinery/;i=5033"
    MachineryOperationModeStateMachineType_FromNoneToMaintenance = "nsu=http://opcfoundation.org/UA/Machinery/;i=5028"
    MachineryOperationModeStateMachineType_FromNoneToNone = "nsu=http://opcfoundation.org/UA/Machinery/;i=5031"
    MachineryOperationModeStateMachineType_FromNoneToProcessing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5030"
    MachineryOperationModeStateMachineType_FromNoneToSetup = "nsu=http://opcfoundation.org/UA/Machinery/;i=5029"
    MachineryOperationModeStateMachineType_FromProcessingToMaintenance = "nsu=http://opcfoundation.org/UA/Machinery/;i=5041"
    MachineryOperationModeStateMachineType_FromProcessingToNone = "nsu=http://opcfoundation.org/UA/Machinery/;i=5040"
    MachineryOperationModeStateMachineType_FromProcessingToProcessing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5043"
    MachineryOperationModeStateMachineType_FromProcessingToSetup = "nsu=http://opcfoundation.org/UA/Machinery/;i=5042"
    MachineryOperationModeStateMachineType_FromSetupToMaintenance = "nsu=http://opcfoundation.org/UA/Machinery/;i=5037"
    MachineryOperationModeStateMachineType_FromSetupToNone = "nsu=http://opcfoundation.org/UA/Machinery/;i=5036"
    MachineryOperationModeStateMachineType_FromSetupToProcessing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5038"
    MachineryOperationModeStateMachineType_FromSetupToSetup = "nsu=http://opcfoundation.org/UA/Machinery/;i=5039"
    MachineryOperationModeStateMachineType_Maintenance = "nsu=http://opcfoundation.org/UA/Machinery/;i=5025"
    MachineryOperationModeStateMachineType_None = "nsu=http://opcfoundation.org/UA/Machinery/;i=5024"
    MachineryOperationModeStateMachineType_Processing = "nsu=http://opcfoundation.org/UA/Machinery/;i=5026"
    MachineryOperationModeStateMachineType_Setup = "nsu=http://opcfoundation.org/UA/Machinery/;i=5027"
    Machines = "nsu=http://opcfoundation.org/UA/Machinery/;i=1001"

def get_ObjectIds_name(value: str) -> str:
    try:
        return ObjectIds(value).name
    except ValueError:
        return None


class ObjectTypeIds(Enum):
    IMachineTagNameplateType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1011"
    IMachineryEquipmentType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1007"
    IMachineryItemVendorNameplateType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1003"
    IMachineVendorNameplateType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1010"
    MachineryItemIdentificationType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1004"
    MachineIdentificationType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1012"
    MachineryComponentIdentificationType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1005"
    MachineryOperationCounterType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1009"
    MachineryEquipmentFolderType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1013"
    MachineryLifetimeCounterType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1015"
    MonitoringType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1014"
    NotificationsType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1017"
    MachineComponentsType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1006"
    MachineryItemState_StateMachineType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1002"
    MachineryOperationModeStateMachineType = "nsu=http://opcfoundation.org/UA/Machinery/;i=1008"

def get_ObjectTypeIds_name(value: str) -> str:
    try:
        return ObjectTypeIds(value).name
    except ValueError:
        return None


class VariableIds(Enum):
    IMachineTagNameplateType_Location = "nsu=http://opcfoundation.org/UA/Machinery/;i=6028"
    IMachineryEquipmentType_Description = "nsu=http://opcfoundation.org/UA/Machinery/;i=6107"
    IMachineryEquipmentType_EquipmentLife = "nsu=http://opcfoundation.org/UA/Machinery/;i=6109"
    IMachineryEquipmentType_EquipmentLife_EngineeringUnits = "nsu=http://opcfoundation.org/UA/Machinery/;i=6112"
    IMachineryEquipmentType_EquipmentLife_StartValue = "nsu=http://opcfoundation.org/UA/Machinery/;i=6111"
    IMachineryEquipmentType_EquipmentLife_LimitValue = "nsu=http://opcfoundation.org/UA/Machinery/;i=6110"
    IMachineryEquipmentType_MachineryEquipmentTypeId = "nsu=http://opcfoundation.org/UA/Machinery/;i=6108"
    IMachineryItemVendorNameplateType_Manufacturer = "nsu=http://opcfoundation.org/UA/Machinery/;i=6022"
    IMachineryItemVendorNameplateType_SerialNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6024"
    IMachineryItemVendorNameplateType_InitialOperationDate = "nsu=http://opcfoundation.org/UA/Machinery/;i=6027"
    IMachineryItemVendorNameplateType_MonthOfConstruction = "nsu=http://opcfoundation.org/UA/Machinery/;i=6026"
    IMachineryItemVendorNameplateType_YearOfConstruction = "nsu=http://opcfoundation.org/UA/Machinery/;i=6025"
    IMachineVendorNameplateType_ProductInstanceUri = "nsu=http://opcfoundation.org/UA/Machinery/;i=6023"
    MachineryItemIdentificationType_AssetId = "nsu=http://opcfoundation.org/UA/Machinery/;i=6013"
    MachineryItemIdentificationType_ComponentName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6014"
    MachineryItemIdentificationType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6088"
    MachineryItemIdentificationType_DeviceClass = "nsu=http://opcfoundation.org/UA/Machinery/;i=6012"
    MachineryItemIdentificationType_HardwareRevision = "nsu=http://opcfoundation.org/UA/Machinery/;i=6010"
    MachineryItemIdentificationType_InitialOperationDate = "nsu=http://opcfoundation.org/UA/Machinery/;i=6006"
    MachineryItemIdentificationType_Manufacturer = "nsu=http://opcfoundation.org/UA/Machinery/;i=6002"
    MachineryItemIdentificationType_ManufacturerUri = "nsu=http://opcfoundation.org/UA/Machinery/;i=6007"
    MachineryItemIdentificationType_Model = "nsu=http://opcfoundation.org/UA/Machinery/;i=6008"
    MachineryItemIdentificationType_MonthOfConstruction = "nsu=http://opcfoundation.org/UA/Machinery/;i=6005"
    MachineryItemIdentificationType_ProductCode = "nsu=http://opcfoundation.org/UA/Machinery/;i=6009"
    MachineryItemIdentificationType_ProductInstanceUri = "nsu=http://opcfoundation.org/UA/Machinery/;i=6001"
    MachineryItemIdentificationType_SerialNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6003"
    MachineryItemIdentificationType_SoftwareRevision = "nsu=http://opcfoundation.org/UA/Machinery/;i=6011"
    MachineryItemIdentificationType_YearOfConstruction = "nsu=http://opcfoundation.org/UA/Machinery/;i=6004"
    MachineIdentificationType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6030"
    MachineIdentificationType_ProductInstanceUri = "nsu=http://opcfoundation.org/UA/Machinery/;i=6015"
    MachineIdentificationType_Location = "nsu=http://opcfoundation.org/UA/Machinery/;i=6029"
    MachineryComponentIdentificationType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6016"
    MachineryComponentIdentificationType_DeviceRevision = "nsu=http://opcfoundation.org/UA/Machinery/;i=6017"
    MachineryOperationCounterType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6082"
    MachineryOperationCounterType_OperationCycleCounter = "nsu=http://opcfoundation.org/UA/Machinery/;i=6081"
    MachineryOperationCounterType_OperationDuration = "nsu=http://opcfoundation.org/UA/Machinery/;i=6080"
    MachineryOperationCounterType_PowerOnDuration = "nsu=http://opcfoundation.org/UA/Machinery/;i=6079"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_AssetId = "nsu=http://opcfoundation.org/UA/Machinery/;i=6096"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_ComponentName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6097"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Description = "nsu=http://opcfoundation.org/UA/Machinery/;i=6098"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_DeviceClass = "nsu=http://opcfoundation.org/UA/Machinery/;i=6099"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Location = "nsu=http://opcfoundation.org/UA/Machinery/;i=6100"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_MachineryEquipmentTypeId = "nsu=http://opcfoundation.org/UA/Machinery/;i=6101"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_ManufacturerUri = "nsu=http://opcfoundation.org/UA/Machinery/;i=6102"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Model = "nsu=http://opcfoundation.org/UA/Machinery/;i=6103"
    MachineryEquipmentFolderType_MachineryEquipment_Placeholder_SerialNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6104"
    MachineryEquipmentFolderType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6105"
    MachineryLifetimeCounterType_LifetimeVariable_Placeholder = "nsu=http://opcfoundation.org/UA/Machinery/;i=6083"
    MachineryLifetimeCounterType_LifetimeVariable_Placeholder_EngineeringUnits = "nsu=http://opcfoundation.org/UA/Machinery/;i=6086"
    MachineryLifetimeCounterType_LifetimeVariable_Placeholder_StartValue = "nsu=http://opcfoundation.org/UA/Machinery/;i=6085"
    MachineryLifetimeCounterType_LifetimeVariable_Placeholder_LimitValue = "nsu=http://opcfoundation.org/UA/Machinery/;i=6084"
    MachineryLifetimeCounterType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6087"
    MonitoringType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6089"
    MonitoringType_Health_DeviceHealth = "nsu=http://opcfoundation.org/UA/Machinery/;i=6095"
    MonitoringType_Status_MachineryItemState_CurrentState = "nsu=http://opcfoundation.org/UA/Machinery/;i=6090"
    MonitoringType_Status_MachineryItemState_CurrentState_Id = "nsu=http://opcfoundation.org/UA/Machinery/;i=6091"
    MonitoringType_Status_OperationMode_CurrentState = "nsu=http://opcfoundation.org/UA/Machinery/;i=6092"
    MonitoringType_Status_OperationMode_CurrentState_Id = "nsu=http://opcfoundation.org/UA/Machinery/;i=6093"
    MonitoringType_Status_Stacklight_StackLevel_DisplayMode = "nsu=http://opcfoundation.org/UA/Machinery/;i=6034"
    MonitoringType_Status_Stacklight_StackLevel_LevelPercent = "nsu=http://opcfoundation.org/UA/Machinery/;i=6035"
    MonitoringType_Status_Stacklight_StackLevel_LevelPercent_EURange = "nsu=http://opcfoundation.org/UA/Machinery/;i=6036"
    MonitoringType_Status_Stacklight_StacklightMode = "nsu=http://opcfoundation.org/UA/Machinery/;i=6094"
    NotificationsType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6106"
    MachineComponentsType_Component_Placeholder_Identification_Manufacturer = "nsu=http://opcfoundation.org/UA/Machinery/;i=6019"
    MachineComponentsType_Component_Placeholder_Identification_SerialNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6020"
    MachineComponentsType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6018"
    MachineryItemState_StateMachineType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6021"
    MachineryItemState_StateMachineType_Executing_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6040"
    MachineryItemState_StateMachineType_FromExecutingToExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6057"
    MachineryItemState_StateMachineType_FromExecutingToNotAvailable_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6054"
    MachineryItemState_StateMachineType_FromExecutingToNotExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6056"
    MachineryItemState_StateMachineType_FromExecutingToOutOfService_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6055"
    MachineryItemState_StateMachineType_FromNotAvailableToExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6044"
    MachineryItemState_StateMachineType_FromNotAvailableToNotAvailable_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6045"
    MachineryItemState_StateMachineType_FromNotAvailableToNotExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6043"
    MachineryItemState_StateMachineType_FromNotAvailableToOutOfService_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6042"
    MachineryItemState_StateMachineType_FromNotExecutingToExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6052"
    MachineryItemState_StateMachineType_FromNotExecutingToNotAvailable_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6050"
    MachineryItemState_StateMachineType_FromNotExecutingToNotExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6053"
    MachineryItemState_StateMachineType_FromNotExecutingToOutOfService_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6051"
    MachineryItemState_StateMachineType_FromOutOfServiceToExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6048"
    MachineryItemState_StateMachineType_FromOutOfServiceToNotAvailable_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6046"
    MachineryItemState_StateMachineType_FromOutOfServiceToNotExecuting_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6047"
    MachineryItemState_StateMachineType_FromOutOfServiceToOutOfService_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6049"
    MachineryItemState_StateMachineType_NotAvailable_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6039"
    MachineryItemState_StateMachineType_NotExecuting_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6041"
    MachineryItemState_StateMachineType_OutOfService_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6038"
    MachineryOperationModeStateMachineType_DefaultInstanceBrowseName = "nsu=http://opcfoundation.org/UA/Machinery/;i=6058"
    MachineryOperationModeStateMachineType_FromMaintenanceToMaintenance_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6070"
    MachineryOperationModeStateMachineType_FromMaintenanceToNone_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6067"
    MachineryOperationModeStateMachineType_FromMaintenanceToProcessing_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6069"
    MachineryOperationModeStateMachineType_FromMaintenanceToSetup_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6068"
    MachineryOperationModeStateMachineType_FromNoneToMaintenance_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6063"
    MachineryOperationModeStateMachineType_FromNoneToNone_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6066"
    MachineryOperationModeStateMachineType_FromNoneToProcessing_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6065"
    MachineryOperationModeStateMachineType_FromNoneToSetup_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6064"
    MachineryOperationModeStateMachineType_FromProcessingToMaintenance_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6076"
    MachineryOperationModeStateMachineType_FromProcessingToNone_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6075"
    MachineryOperationModeStateMachineType_FromProcessingToProcessing_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6078"
    MachineryOperationModeStateMachineType_FromProcessingToSetup_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6077"
    MachineryOperationModeStateMachineType_FromSetupToMaintenance_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6072"
    MachineryOperationModeStateMachineType_FromSetupToNone_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6071"
    MachineryOperationModeStateMachineType_FromSetupToProcessing_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6073"
    MachineryOperationModeStateMachineType_FromSetupToSetup_TransitionNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6074"
    MachineryOperationModeStateMachineType_Maintenance_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6060"
    MachineryOperationModeStateMachineType_None_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6059"
    MachineryOperationModeStateMachineType_Processing_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6061"
    MachineryOperationModeStateMachineType_Setup_StateNumber = "nsu=http://opcfoundation.org/UA/Machinery/;i=6062"

def get_VariableIds_name(value: str) -> str:
    try:
        return VariableIds(value).name
    except ValueError:
        return None

