export const NS = 'http://opcfoundation.org/UA/IJT/Base/';

export const BrowseNames = Object.freeze({
   AbortJoiningProcess: 'AbortJoiningProcess',
   AcceptedEntityConditionClassType: 'AcceptedEntityConditionClassType',
   Accessories: 'Accessories',
   Accessory_Placeholder: '<Accessory>',
   AddedEntityConditionClassType: 'AddedEntityConditionClassType',
   AssemblyType: 'AssemblyType',
   AssetConnectedConditionClassType: 'AssetConnectedConditionClassType',
   AssetDisabledConditionClassType: 'AssetDisabledConditionClassType',
   AssetDisconnectedConditionClassType: 'AssetDisconnectedConditionClassType',
   AssetEnabledConditionClassType: 'AssetEnabledConditionClassType',
   AssetLocationConditionClassType: 'AssetLocationConditionClassType',
   AssetManagement: 'AssetManagement',
   Assets: 'Assets',
   AssociatedEntities: 'AssociatedEntities',
   Batteries: 'Batteries',
   Battery_Placeholder: '<Battery>',
   Cable_Placeholder: '<Cable>',
   Cables: 'Cables',
   Calibration: 'Calibration',
   CalibrationDataType: 'CalibrationDataType',
   CalibrationPlace: 'CalibrationPlace',
   CalibrationValue: 'CalibrationValue',
   CertificateConditionClassType: 'CertificateConditionClassType',
   CertificateUri: 'CertificateUri',
   Classification: 'Classification',
   ConfigurationChangeConditionClassType: 'ConfigurationChangeConditionClassType',
   Connected: 'Connected',
   Controller_Placeholder: '<Controller>',
   Controllers: 'Controllers',
   DataValidationFailureConditionClassType: 'DataValidationFailureConditionClassType',
   DecrementJoiningProcessCounter: 'DecrementJoiningProcessCounter',
   DeleteJoiningProcess: 'DeleteJoiningProcess',
   DeleteJoint: 'DeleteJoint',
   DeleteJointComponent: 'DeleteJointComponent',
   DeleteJointDesign: 'DeleteJointDesign',
   Description: 'Description',
   DeselectJoiningProcess: 'DeselectJoiningProcess',
   DesignValueDataType: 'DesignValueDataType',
   DisconnectAsset: 'DisconnectAsset',
   EnableAsset: 'EnableAsset',
   Enabled: 'Enabled',
   EngineeringUnits: 'EngineeringUnits',
   EntityDataType: 'EntityDataType',
   EntityExpiryWarningConditionClassType: 'EntityExpiryWarningConditionClassType',
   ErrorCode: 'ErrorCode',
   ErrorConditionClassType: 'ErrorConditionClassType',
   ErrorInformationDataType: 'ErrorInformationDataType',
   ErrorMessage: 'ErrorMessage',
   ErrorTimestamp: 'ErrorTimestamp',
   EventCode: 'EventCode',
   EventText: 'EventText',
   ExecuteOperation: 'ExecuteOperation',
   ExpiredEntityConditionClassType: 'ExpiredEntityConditionClassType',
   ExtendedMetaData: 'ExtendedMetaData',
   Feeder_Placeholder: '<Feeder>',
   Feeders: 'Feeders',
   GetErrorInformation: 'GetErrorInformation',
   GetFeedbackFileList: 'GetFeedbackFileList',
   GetIdentifiers: 'GetIdentifiers',
   GetIOSignals: 'GetIOSignals',
   GetJoiningProcess: 'GetJoiningProcess',
   GetJoiningProcessList: 'GetJoiningProcessList',
   GetJoiningProcessRevisionList: 'GetJoiningProcessRevisionList',
   GetJoint: 'GetJoint',
   GetJointComponent: 'GetJointComponent',
   GetJointComponentList: 'GetJointComponentList',
   GetJointDesign: 'GetJointDesign',
   GetJointDesignList: 'GetJointDesignList',
   GetJointList: 'GetJointList',
   GetJointRevisionList: 'GetJointRevisionList',
   GetSelectedJoiningProgram: 'GetSelectedJoiningProgram',
   HardwareConditionClassType: 'HardwareConditionClassType',
   Health: 'Health',
   IAccessoryType: 'IAccessoryType',
   IBatteryType: 'IBatteryType',
   ICableType: 'ICableType',
   IControllerType: 'IControllerType',
   Identification: 'Identification',
   IFeederType: 'IFeederType',
   IJoiningAdditionalInformationType: 'IJoiningAdditionalInformationType',
   IJoiningSystemAssetType: 'IJoiningSystemAssetType',
   IMemoryDeviceType: 'IMemoryDeviceType',
   IncompatibleEntityConditionClassType: 'IncompatibleEntityConditionClassType',
   IncrementJoiningProcessCounter: 'IncrementJoiningProcessCounter',
   InputValidationFailureConditionClassType: 'InputValidationFailureConditionClassType',
   IntegratorName: 'IntegratorName',
   InterventionType: 'InterventionType',
   InvalidEntityConditionClassType: 'InvalidEntityConditionClassType',
   IOSignals: 'IOSignals',
   IPowerSupplyType: 'IPowerSupplyType',
   ISensorType: 'ISensorType',
   IServoType: 'IServoType',
   IsGeneratedOffline: 'IsGeneratedOffline',
   ISoftwareType: 'ISoftwareType',
   ISubComponentType: 'ISubComponentType',
   IToolType: 'IToolType',
   IVirtualStationType: 'IVirtualStationType',
   JoiningDataVariableType: 'JoiningDataVariableType',
   JoiningProcessDataType: 'JoiningProcessDataType',
   JoiningProcessIdentificationDataType: 'JoiningProcessIdentificationDataType',
   JoiningProcessManagement: 'JoiningProcessManagement',
   JoiningProcessManagementType: 'JoiningProcessManagementType',
   JoiningProcessMetaDataType: 'JoiningProcessMetaDataType',
   JoiningResultDataType: 'JoiningResultDataType',
   JoiningResultMetaDataType: 'JoiningResultMetaDataType',
   JoiningSystemAssetMethodSetType: 'JoiningSystemAssetMethodSetType',
   JoiningSystemConditionType: 'JoiningSystemConditionType',
   JoiningSystemEventContent: 'JoiningSystemEventContent',
   JoiningSystemEventContentType: 'JoiningSystemEventContentType',
   JoiningSystemEventType: 'JoiningSystemEventType',
   JoiningSystemIdentificationType: 'JoiningSystemIdentificationType',
   JoiningSystemResultManagementType: 'JoiningSystemResultManagementType',
   JoiningSystemResultReadyEventType: 'JoiningSystemResultReadyEventType',
   JoiningSystemResultType: 'JoiningSystemResultType',
   JoiningSystemType: 'JoiningSystemType',
   JoiningSystemUserLoggedInConditionClassType: 'JoiningSystemUserLoggedInConditionClassType',
   JoiningSystemUserLoggedOutConditionClassType: 'JoiningSystemUserLoggedOutConditionClassType',
   JoiningTechnology: 'JoiningTechnology',
   JoiningTraceDataType: 'JoiningTraceDataType',
   JointComponentDataType: 'JointComponentDataType',
   JointDataType: 'JointDataType',
   JointDesignDataType: 'JointDesignDataType',
   JointManagement: 'JointManagement',
   JointManagementType: 'JointManagementType',
   KeyValueDataType: 'KeyValueDataType',
   LastCalibration: 'LastCalibration',
   LastService: 'LastService',
   LicenseConditionClassType: 'LicenseConditionClassType',
   LocationInZoneConditionClassType: 'LocationInZoneConditionClassType',
   LocationOutOfZoneConditionClassType: 'LocationOutOfZoneConditionClassType',
   MemoryDevice_Placeholder: '<MemoryDevice>',
   MemoryDevices: 'MemoryDevices',
   MethodSet: 'MethodSet',
   MissingEntityConditionClassType: 'MissingEntityConditionClassType',
   Name: 'Name',
   NextCalibration: 'NextCalibration',
   NextService: 'NextService',
   NotAvailableEntityConditionClassType: 'NotAvailableEntityConditionClassType',
   NotSupportedEntityConditionClassType: 'NotSupportedEntityConditionClassType',
   NumberOfServices: 'NumberOfServices',
   OperationMode: 'OperationMode',
   Parameters: 'Parameters',
   PhysicalQuantity: 'PhysicalQuantity',
   PowerSupplies: 'PowerSupplies',
   PowerSupply_Placeholder: '<PowerSupply>',
   RebootAsset: 'RebootAsset',
   ReceivedEntityConditionClassType: 'ReceivedEntityConditionClassType',
   RejectedEntityConditionClassType: 'RejectedEntityConditionClassType',
   RemainingCycles: 'RemainingCycles',
   RemovedEntityConditionClassType: 'RemovedEntityConditionClassType',
   ReportedValueDataType: 'ReportedValueDataType',
   ReportedValues: 'ReportedValues',
   RequestedResultEventType: 'RequestedResultEventType',
   RequestedResultVariable_Placeholder: '<RequestedResultVariable>',
   RequestResults: 'RequestResults',
   RequestUnacknowledgedResults: 'RequestUnacknowledgedResults',
   ResetIdentifiers: 'ResetIdentifiers',
   ResetJoiningProcess: 'ResetJoiningProcess',
   ResultCounterDataType: 'ResultCounterDataType',
   ResultCounters: 'ResultCounters',
   ResultValueDataType: 'ResultValueDataType',
   ResultVariable_Placeholder: '<ResultVariable>',
   SelectedEntityConditionClassType: 'SelectedEntityConditionClassType',
   SelectedProcessConditionClassType: 'SelectedProcessConditionClassType',
   SelectJoiningProcess: 'SelectJoiningProcess',
   SelectJoint: 'SelectJoint',
   SendFeedback: 'SendFeedback',
   SendIdentifiers: 'SendIdentifiers',
   SendJoiningProcess: 'SendJoiningProcess',
   SendJoint: 'SendJoint',
   SendJointComponent: 'SendJointComponent',
   SendJointDesign: 'SendJointDesign',
   SendTextIdentifiers: 'SendTextIdentifiers',
   Sensor_Placeholder: '<Sensor>',
   Sensors: 'Sensors',
   SensorScale: 'SensorScale',
   SequenceNumber: 'SequenceNumber',
   Service: 'Service',
   ServiceCycleCount: 'ServiceCycleCount',
   ServiceCycleSpan: 'ServiceCycleSpan',
   ServiceOperationCycles: 'ServiceOperationCycles',
   ServicePlace: 'ServicePlace',
   ServiceReminderCycles: 'ServiceReminderCycles',
   ServiceReminderDays: 'ServiceReminderDays',
   Servo_Placeholder: '<Servo>',
   Servos: 'Servos',
   SetCalibration: 'SetCalibration',
   SetIOSignals: 'SetIOSignals',
   SetJoiningProcessCounter: 'SetJoiningProcessCounter',
   SetJoiningProcessMapping: 'SetJoiningProcessMapping',
   SetJoiningProcessSize: 'SetJoiningProcessSize',
   SetOfflineTimer: 'SetOfflineTimer',
   SetTime: 'SetTime',
   SignalDataType: 'SignalDataType',
   Software_Placeholder: '<Software>',
   SoftwareComponents: 'SoftwareComponents',
   SoftwareConditionClassType: 'SoftwareConditionClassType',
   StartedEntityConditionClassType: 'StartedEntityConditionClassType',
   StartJoiningProcess: 'StartJoiningProcess',
   StartSelectedJoining: 'StartSelectedJoining',
   StepResultDataType: 'StepResultDataType',
   StepTraceDataType: 'StepTraceDataType',
   StoppedEntityConditionClassType: 'StoppedEntityConditionClassType',
   SubComponent_Placeholder: '<SubComponent>',
   SubComponents: 'SubComponents',
   SupplierCode: 'SupplierCode',
   SystemId: 'SystemId',
   Temperature: 'Temperature',
   ThresholdViolationConditionClassType: 'ThresholdViolationConditionClassType',
   ThresholdViolationResolvedConditionClassType: 'ThresholdViolationResolvedConditionClassType',
   Tool_Placeholder: '<Tool>',
   Tools: 'Tools',
   TraceContentDataType: 'TraceContentDataType',
   TraceDataType: 'TraceDataType',
   UnacknowledgedResultsConditionClassType: 'UnacknowledgedResultsConditionClassType',
   UpdatedEntityConditionClassType: 'UpdatedEntityConditionClassType',
   VirtualStation_Placeholder: '<VirtualStation>',
   VirtualStations: 'VirtualStations',
});

export const DataTypeIds = Object.freeze({
   CalibrationDataType: 'nsu=' + NS + ';i=3003',
   DesignValueDataType: 'nsu=' + NS + ';i=3015',
   EntityDataType: 'nsu=' + NS + ';i=3010',
   ErrorInformationDataType: 'nsu=' + NS + ';i=3006',
   JoiningProcessDataType: 'nsu=' + NS + ';i=3016',
   JoiningProcessIdentificationDataType: 'nsu=' + NS + ';i=3029',
   JoiningProcessMetaDataType: 'nsu=' + NS + ';i=3024',
   JoiningResultDataType: 'nsu=' + NS + ';i=3005',
   JointComponentDataType: 'nsu=' + NS + ';i=3021',
   JointDataType: 'nsu=' + NS + ';i=3028',
   JointDesignDataType: 'nsu=' + NS + ';i=3025',
   KeyValueDataType: 'nsu=' + NS + ';i=3008',
   ReportedValueDataType: 'nsu=' + NS + ';i=3022',
   ResultCounterDataType: 'nsu=' + NS + ';i=3004',
   JoiningResultMetaDataType: 'nsu=' + NS + ';i=3020',
   ResultValueDataType: 'nsu=' + NS + ';i=3007',
   SignalDataType: 'nsu=' + NS + ';i=3019',
   StepResultDataType: 'nsu=' + NS + ';i=3009',
   StepTraceDataType: 'nsu=' + NS + ';i=3013',
   TraceContentDataType: 'nsu=' + NS + ';i=3014',
   TraceDataType: 'nsu=' + NS + ';i=3011',
   JoiningTraceDataType: 'nsu=' + NS + ';i=3012',
});

export const MethodIds = Object.freeze({
   JoiningProcessManagementType_AbortJoiningProcess: 'nsu=' + NS + ';i=7053',
   JoiningProcessManagementType_DecrementJoiningProcessCounter: 'nsu=' + NS + ';i=7049',
   JoiningProcessManagementType_DeleteJoiningProcess: 'nsu=' + NS + ';i=7054',
   JoiningProcessManagementType_DeselectJoiningProcess: 'nsu=' + NS + ';i=7047',
   JoiningProcessManagementType_GetJoiningProcess: 'nsu=' + NS + ';i=7093',
   JoiningProcessManagementType_GetJoiningProcessList: 'nsu=' + NS + ';i=7043',
   JoiningProcessManagementType_GetJoiningProcessRevisionList: 'nsu=' + NS + ';i=7044',
   JoiningProcessManagementType_GetSelectedJoiningProgram: 'nsu=' + NS + ';i=7091',
   JoiningProcessManagementType_IncrementJoiningProcessCounter: 'nsu=' + NS + ';i=7048',
   JoiningProcessManagementType_ResetJoiningProcess: 'nsu=' + NS + ';i=7052',
   JoiningProcessManagementType_SelectJoiningProcess: 'nsu=' + NS + ';i=7046',
   JoiningProcessManagementType_SendJoiningProcess: 'nsu=' + NS + ';i=7042',
   JoiningProcessManagementType_SetJoiningProcessCounter: 'nsu=' + NS + ';i=7050',
   JoiningProcessManagementType_SetJoiningProcessMapping: 'nsu=' + NS + ';i=7045',
   JoiningProcessManagementType_SetJoiningProcessSize: 'nsu=' + NS + ';i=7051',
   JoiningProcessManagementType_StartJoiningProcess: 'nsu=' + NS + ';i=7056',
   JoiningProcessManagementType_StartSelectedJoining: 'nsu=' + NS + ';i=7073',
   JoiningSystemAssetMethodSetType_DisconnectAsset: 'nsu=' + NS + ';i=7007',
   JoiningSystemAssetMethodSetType_EnableAsset: 'nsu=' + NS + ';i=7006',
   JoiningSystemAssetMethodSetType_ExecuteOperation: 'nsu=' + NS + ';i=7018',
   JoiningSystemAssetMethodSetType_GetErrorInformation: 'nsu=' + NS + ';i=7019',
   JoiningSystemAssetMethodSetType_GetFeedbackFileList: 'nsu=' + NS + ';i=7011',
   JoiningSystemAssetMethodSetType_GetIdentifiers: 'nsu=' + NS + ';i=7014',
   JoiningSystemAssetMethodSetType_GetIOSignals: 'nsu=' + NS + ';i=7013',
   JoiningSystemAssetMethodSetType_RebootAsset: 'nsu=' + NS + ';i=7008',
   JoiningSystemAssetMethodSetType_ResetIdentifiers: 'nsu=' + NS + ';i=7017',
   JoiningSystemAssetMethodSetType_SendFeedback: 'nsu=' + NS + ';i=7010',
   JoiningSystemAssetMethodSetType_SendIdentifiers: 'nsu=' + NS + ';i=7015',
   JoiningSystemAssetMethodSetType_SendTextIdentifiers: 'nsu=' + NS + ';i=7016',
   JoiningSystemAssetMethodSetType_SetCalibration: 'nsu=' + NS + ';i=7005',
   JoiningSystemAssetMethodSetType_SetIOSignals: 'nsu=' + NS + ';i=7012',
   JoiningSystemAssetMethodSetType_SetOfflineTimer: 'nsu=' + NS + ';i=7009',
   JoiningSystemAssetMethodSetType_SetTime: 'nsu=' + NS + ';i=7072',
   JoiningSystemType_AssetManagement_MethodSet_DisconnectAsset: 'nsu=' + NS + ';i=7075',
   JoiningSystemType_AssetManagement_MethodSet_EnableAsset: 'nsu=' + NS + ';i=7076',
   JoiningSystemType_AssetManagement_MethodSet_ExecuteOperation: 'nsu=' + NS + ';i=7077',
   JoiningSystemType_AssetManagement_MethodSet_GetErrorInformation: 'nsu=' + NS + ';i=7078',
   JoiningSystemType_AssetManagement_MethodSet_GetFeedbackFileList: 'nsu=' + NS + ';i=7079',
   JoiningSystemType_AssetManagement_MethodSet_GetIdentifiers: 'nsu=' + NS + ';i=7081',
   JoiningSystemType_AssetManagement_MethodSet_GetIOSignals: 'nsu=' + NS + ';i=7080',
   JoiningSystemType_AssetManagement_MethodSet_RebootAsset: 'nsu=' + NS + ';i=7082',
   JoiningSystemType_AssetManagement_MethodSet_ResetIdentifiers: 'nsu=' + NS + ';i=7083',
   JoiningSystemType_AssetManagement_MethodSet_SendFeedback: 'nsu=' + NS + ';i=7084',
   JoiningSystemType_AssetManagement_MethodSet_SendIdentifiers: 'nsu=' + NS + ';i=7085',
   JoiningSystemType_AssetManagement_MethodSet_SendTextIdentifiers: 'nsu=' + NS + ';i=7086',
   JoiningSystemType_AssetManagement_MethodSet_SetCalibration: 'nsu=' + NS + ';i=7087',
   JoiningSystemType_AssetManagement_MethodSet_SetIOSignals: 'nsu=' + NS + ';i=7088',
   JoiningSystemType_AssetManagement_MethodSet_SetOfflineTimer: 'nsu=' + NS + ';i=7089',
   JoiningSystemType_AssetManagement_MethodSet_SetTime: 'nsu=' + NS + ';i=7090',
   JoiningSystemType_JoiningProcessManagement_AbortJoiningProcess: 'nsu=' + NS + ';i=7057',
   JoiningSystemType_JoiningProcessManagement_DecrementJoiningProcessCounter: 'nsu=' + NS + ';i=7058',
   JoiningSystemType_JoiningProcessManagement_DeselectJoiningProcess: 'nsu=' + NS + ';i=7059',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessList: 'nsu=' + NS + ';i=7060',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessRevisionList: 'nsu=' + NS + ';i=7061',
   JoiningSystemType_JoiningProcessManagement_IncrementJoiningProcessCounter: 'nsu=' + NS + ';i=7062',
   JoiningSystemType_JoiningProcessManagement_ResetJoiningProcess: 'nsu=' + NS + ';i=7063',
   JoiningSystemType_JoiningProcessManagement_SelectJoiningProcess: 'nsu=' + NS + ';i=7065',
   JoiningSystemType_JoiningProcessManagement_SendJoiningProcess: 'nsu=' + NS + ';i=7066',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessCounter: 'nsu=' + NS + ';i=7067',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessMapping: 'nsu=' + NS + ';i=7068',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessSize: 'nsu=' + NS + ';i=7069',
   JoiningSystemType_JoiningProcessManagement_StartJoiningProcess: 'nsu=' + NS + ';i=7070',
   JoiningSystemType_JointManagement_GetJoint: 'nsu=' + NS + ';i=7031',
   JoiningSystemType_JointManagement_GetJointComponent: 'nsu=' + NS + ';i=7032',
   JoiningSystemType_JointManagement_GetJointComponentList: 'nsu=' + NS + ';i=7033',
   JoiningSystemType_JointManagement_GetJointDesign: 'nsu=' + NS + ';i=7034',
   JoiningSystemType_JointManagement_GetJointDesignList: 'nsu=' + NS + ';i=7035',
   JoiningSystemType_JointManagement_GetJointList: 'nsu=' + NS + ';i=7036',
   JoiningSystemType_JointManagement_GetJointRevisionList: 'nsu=' + NS + ';i=7037',
   JoiningSystemType_JointManagement_SelectJoint: 'nsu=' + NS + ';i=7038',
   JoiningSystemType_JointManagement_SendJoint: 'nsu=' + NS + ';i=7039',
   JoiningSystemType_JointManagement_SendJointComponent: 'nsu=' + NS + ';i=7040',
   JoiningSystemType_JointManagement_SendJointDesign: 'nsu=' + NS + ';i=7041',
   JoiningSystemType_ResultManagement_GetLatestResult: 'nsu=' + NS + ';i=7001',
   JoiningSystemType_ResultManagement_GetResultById: 'nsu=' + NS + ';i=7002',
   JoiningSystemType_ResultManagement_GetResultIdListFiltered: 'nsu=' + NS + ';i=7003',
   JoiningSystemType_ResultManagement_ReleaseResultHandle: 'nsu=' + NS + ';i=7004',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=7002',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=7004',
   JoiningSystemType_ResultManagement_ResultTransfer_CloseAndCommit: 'nsu=' + NS + ';i=7003',
   JointManagementType_DeleteJoint: 'nsu=' + NS + ';i=7055',
   JointManagementType_DeleteJointComponent: 'nsu=' + NS + ';i=7071',
   JointManagementType_DeleteJointDesign: 'nsu=' + NS + ';i=7064',
   JointManagementType_GetJoint: 'nsu=' + NS + ';i=7028',
   JointManagementType_GetJointComponent: 'nsu=' + NS + ';i=7030',
   JointManagementType_GetJointComponentList: 'nsu=' + NS + ';i=7026',
   JointManagementType_GetJointDesign: 'nsu=' + NS + ';i=7029',
   JointManagementType_GetJointDesignList: 'nsu=' + NS + ';i=7025',
   JointManagementType_GetJointList: 'nsu=' + NS + ';i=7024',
   JointManagementType_GetJointRevisionList: 'nsu=' + NS + ';i=7027',
   JointManagementType_SelectJoint: 'nsu=' + NS + ';i=7023',
   JointManagementType_SendJoint: 'nsu=' + NS + ';i=7020',
   JointManagementType_SendJointComponent: 'nsu=' + NS + ';i=7022',
   JointManagementType_SendJointDesign: 'nsu=' + NS + ';i=7021',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=7002',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=7004',
   JoiningSystemResultManagementType_ResultTransfer_CloseAndCommit: 'nsu=' + NS + ';i=7003',
   JoiningSystemResultManagementType_RequestResults: 'nsu=' + NS + ';i=7074',
   JoiningSystemResultManagementType_RequestUnacknowledgedResults: 'nsu=' + NS + ';i=7092',
});

export const ObjectIds = Object.freeze({
   IJoiningSystemAssetType_Health: 'nsu=' + NS + ';i=5045',
   IJoiningSystemAssetType_Health_DeviceHealthAlarms: 'nsu=' + NS + ';i=5114',
   IJoiningSystemAssetType_Identification: 'nsu=' + NS + ';i=5052',
   IJoiningSystemAssetType_LifetimeCounters: 'nsu=' + NS + ';i=5147',
   IJoiningSystemAssetType_MachineryBuildingBlocks: 'nsu=' + NS + ';i=5080',
   IJoiningSystemAssetType_OperationCounters: 'nsu=' + NS + ';i=5002',
   IJoiningSystemAssetType_Maintenance: 'nsu=' + NS + ';i=5027',
   IJoiningSystemAssetType_Maintenance_Calibration: 'nsu=' + NS + ';i=5003',
   IJoiningSystemAssetType_Maintenance_Service: 'nsu=' + NS + ';i=5020',
   IJoiningSystemAssetType_Monitoring: 'nsu=' + NS + ';i=5162',
   IJoiningSystemAssetType_Monitoring_Consumption: 'nsu=' + NS + ';i=5164',
   IJoiningSystemAssetType_Monitoring_Health: 'nsu=' + NS + ';i=5165',
   IJoiningSystemAssetType_Monitoring_Health_DeviceHealthAlarms: 'nsu=' + NS + ';i=5168',
   IJoiningSystemAssetType_Monitoring_Process: 'nsu=' + NS + ';i=5166',
   IJoiningSystemAssetType_Monitoring_Status: 'nsu=' + NS + ';i=5167',
   IJoiningSystemAssetType_Notifications: 'nsu=' + NS + ';i=5163',
   IJoiningSystemAssetType_Parameters: 'nsu=' + NS + ';i=5015',
   IAccessoryType_Parameters: 'nsu=' + NS + ';i=5024',
   IBatteryType_Parameters: 'nsu=' + NS + ';i=5009',
   ICableType_Parameters: 'nsu=' + NS + ';i=5010',
   IControllerType_Parameters: 'nsu=' + NS + ';i=5006',
   IFeederType_Parameters: 'nsu=' + NS + ';i=5011',
   IMemoryDeviceType_Parameters: 'nsu=' + NS + ';i=5013',
   IPowerSupplyType_Parameters: 'nsu=' + NS + ';i=5012',
   ISensorType_Parameters: 'nsu=' + NS + ';i=5014',
   IServoType_Parameters: 'nsu=' + NS + ';i=5007',
   ISubComponentType_Parameters: 'nsu=' + NS + ';i=5019',
   IToolType_Parameters: 'nsu=' + NS + ';i=5008',
   JoiningSystemType_AssetManagement: 'nsu=' + NS + ';i=5004',
   JoiningSystemType_AssetManagement_Assets: 'nsu=' + NS + ';i=5016',
   JoiningSystemType_AssetManagement_Assets_Accessories: 'nsu=' + NS + ';i=5032',
   JoiningSystemType_AssetManagement_Assets_Batteries: 'nsu=' + NS + ';i=5029',
   JoiningSystemType_AssetManagement_Assets_Cables: 'nsu=' + NS + ';i=5028',
   JoiningSystemType_AssetManagement_Assets_Controllers: 'nsu=' + NS + ';i=5018',
   JoiningSystemType_AssetManagement_Assets_Feeders: 'nsu=' + NS + ';i=5031',
   JoiningSystemType_AssetManagement_Assets_MemoryDevices: 'nsu=' + NS + ';i=5023',
   JoiningSystemType_AssetManagement_Assets_PowerSupplies: 'nsu=' + NS + ';i=5030',
   JoiningSystemType_AssetManagement_Assets_Sensors: 'nsu=' + NS + ';i=5025',
   JoiningSystemType_AssetManagement_Assets_Servos: 'nsu=' + NS + ';i=5022',
   JoiningSystemType_AssetManagement_Assets_SoftwareComponents: 'nsu=' + NS + ';i=5001',
   JoiningSystemType_AssetManagement_Assets_SubComponents: 'nsu=' + NS + ';i=5033',
   JoiningSystemType_AssetManagement_Assets_Tools: 'nsu=' + NS + ';i=5021',
   JoiningSystemType_AssetManagement_Assets_VirtualStations: 'nsu=' + NS + ';i=5087',
   JoiningSystemType_AssetManagement_MethodSet: 'nsu=' + NS + ';i=5124',
   JoiningSystemType_Identification: 'nsu=' + NS + ';i=5026',
   JoiningSystemType_JoiningProcessManagement: 'nsu=' + NS + ';i=5113',
   JoiningSystemType_JointManagement: 'nsu=' + NS + ';i=5100',
   JoiningSystemType_MachineryBuildingBlocks: 'nsu=' + NS + ';i=5074',
   JoiningSystemType_ResultManagement: 'nsu=' + NS + ';i=5005',
   JoiningSystemType_ResultManagement_Results: 'nsu=' + NS + ';i=5078',
   JoiningSystemResultManagementType_Results: 'nsu=' + NS + ';i=5098',
   CalibrationDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5017',
   JoiningResultMetaDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5046',
   JoiningResultMetaDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5047',
   CalibrationDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5048',
   JoiningResultDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5049',
   JoiningResultDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5050',
   DesignValueDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5051',
   ErrorInformationDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5053',
   ErrorInformationDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5054',
   EntityDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5055',
   ResultValueDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5056',
   ResultValueDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5057',
   ErrorInformationDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5058',
   StepResultDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5059',
   StepResultDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5060',
   JoiningProcessDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5061',
   TraceDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5062',
   TraceDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5063',
   JoiningProcessIdentificationDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5064',
   JoiningTraceDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5065',
   JoiningTraceDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5066',
   JoiningProcessMetaDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5067',
   StepTraceDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5068',
   StepTraceDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5069',
   JoiningResultDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5070',
   TraceContentDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5071',
   TraceContentDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5072',
   JointComponentDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5073',
   CalibrationDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5075',
   JointDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5076',
   EntityDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5079',
   SignalDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5081',
   DesignValueDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5082',
   DesignValueDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5083',
   EntityDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5084',
   JointDesignDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5085',
   KeyValueDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5086',
   ResultCounterDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5089',
   ResultCounterDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5090',
   ReportedValueDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5091',
   ReportedValueDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5095',
   ReportedValueDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5096',
   ResultCounterDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5097',
   JoiningResultMetaDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5099',
   ResultValueDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5103',
   JointComponentDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5104',
   JointComponentDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5105',
   SignalDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5106',
   JointDesignDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5107',
   JointDesignDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5108',
   StepResultDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5109',
   JointDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5110',
   JointDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5111',
   StepTraceDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5112',
   JoiningProcessDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5115',
   JoiningProcessDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5116',
   TraceContentDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5117',
   JoiningProcessMetaDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5118',
   JoiningProcessMetaDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5119',
   TraceDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5120',
   JoiningProcessIdentificationDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5121',
   JoiningProcessIdentificationDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5122',
   JoiningTraceDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5123',
   SignalDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5125',
   KeyValueDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5148',
   KeyValueDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5149',
});

export const ObjectTypeIds = Object.freeze({
   AcceptedEntityConditionClassType: 'nsu=' + NS + ';i=1090',
   AddedEntityConditionClassType: 'nsu=' + NS + ';i=1096',
   AssetConnectedConditionClassType: 'nsu=' + NS + ';i=1018',
   AssetDisabledConditionClassType: 'nsu=' + NS + ';i=1027',
   AssetDisconnectedConditionClassType: 'nsu=' + NS + ';i=1021',
   AssetEnabledConditionClassType: 'nsu=' + NS + ';i=1024',
   AssetLocationConditionClassType: 'nsu=' + NS + ';i=1048',
   CertificateConditionClassType: 'nsu=' + NS + ';i=1072',
   ConfigurationChangeConditionClassType: 'nsu=' + NS + ';i=1030',
   DataValidationFailureConditionClassType: 'nsu=' + NS + ';i=1057',
   EntityExpiryWarningConditionClassType: 'nsu=' + NS + ';i=1034',
   ErrorConditionClassType: 'nsu=' + NS + ';i=1063',
   ExpiredEntityConditionClassType: 'nsu=' + NS + ';i=1081',
   HardwareConditionClassType: 'nsu=' + NS + ';i=1069',
   IncompatibleEntityConditionClassType: 'nsu=' + NS + ';i=1087',
   InputValidationFailureConditionClassType: 'nsu=' + NS + ';i=1060',
   InvalidEntityConditionClassType: 'nsu=' + NS + ';i=1084',
   JoiningSystemUserLoggedInConditionClassType: 'nsu=' + NS + ';i=1039',
   JoiningSystemUserLoggedOutConditionClassType: 'nsu=' + NS + ';i=1042',
   LicenseConditionClassType: 'nsu=' + NS + ';i=1075',
   LocationInZoneConditionClassType: 'nsu=' + NS + ';i=1051',
   LocationOutOfZoneConditionClassType: 'nsu=' + NS + ';i=1054',
   MissingEntityConditionClassType: 'nsu=' + NS + ';i=1078',
   NotAvailableEntityConditionClassType: 'nsu=' + NS + ';i=1047',
   NotSupportedEntityConditionClassType: 'nsu=' + NS + ';i=1052',
   ReceivedEntityConditionClassType: 'nsu=' + NS + ';i=1105',
   RejectedEntityConditionClassType: 'nsu=' + NS + ';i=1093',
   RemovedEntityConditionClassType: 'nsu=' + NS + ';i=1102',
   SelectedEntityConditionClassType: 'nsu=' + NS + ';i=1032',
   SelectedProcessConditionClassType: 'nsu=' + NS + ';i=1037',
   SoftwareConditionClassType: 'nsu=' + NS + ';i=1066',
   StartedEntityConditionClassType: 'nsu=' + NS + ';i=1038',
   StoppedEntityConditionClassType: 'nsu=' + NS + ';i=1044',
   ThresholdViolationConditionClassType: 'nsu=' + NS + ';i=1033',
   ThresholdViolationResolvedConditionClassType: 'nsu=' + NS + ';i=1036',
   UnacknowledgedResultsConditionClassType: 'nsu=' + NS + ';i=1041',
   UpdatedEntityConditionClassType: 'nsu=' + NS + ';i=1099',
   JoiningSystemConditionType: 'nsu=' + NS + ';i=1020',
   JoiningSystemEventType: 'nsu=' + NS + ';i=1006',
   JoiningSystemResultReadyEventType: 'nsu=' + NS + ';i=1007',
   RequestedResultEventType: 'nsu=' + NS + ';i=1035',
   IJoiningAdditionalInformationType: 'nsu=' + NS + ';i=1017',
   IJoiningSystemAssetType: 'nsu=' + NS + ';i=1002',
   IAccessoryType: 'nsu=' + NS + ';i=1015',
   IBatteryType: 'nsu=' + NS + ';i=1010',
   ICableType: 'nsu=' + NS + ';i=1014',
   IControllerType: 'nsu=' + NS + ';i=1003',
   IFeederType: 'nsu=' + NS + ';i=1012',
   IMemoryDeviceType: 'nsu=' + NS + ';i=1013',
   IPowerSupplyType: 'nsu=' + NS + ';i=1009',
   ISensorType: 'nsu=' + NS + ';i=1011',
   IServoType: 'nsu=' + NS + ';i=1008',
   ISoftwareType: 'nsu=' + NS + ';i=1019',
   ISubComponentType: 'nsu=' + NS + ';i=1016',
   IToolType: 'nsu=' + NS + ';i=1004',
   IVirtualStationType: 'nsu=' + NS + ';i=1031',
   JoiningSystemIdentificationType: 'nsu=' + NS + ';i=1029',
   JoiningProcessManagementType: 'nsu=' + NS + ';i=1025',
   JoiningSystemAssetMethodSetType: 'nsu=' + NS + ';i=1026',
   JoiningSystemType: 'nsu=' + NS + ';i=1005',
   JointManagementType: 'nsu=' + NS + ';i=1023',
   JoiningSystemResultManagementType: 'nsu=' + NS + ';i=1022',
});

export const VariableIds = Object.freeze({
   JoiningDataVariableType_EngineeringUnits: 'nsu=' + NS + ';i=6042',
   JoiningDataVariableType_PhysicalQuantity: 'nsu=' + NS + ';i=6084',
   JoiningDataVariableType_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   JoiningSystemEventContentType_AssociatedEntities: 'nsu=' + NS + ';i=6026',
   JoiningSystemEventContentType_EventCode: 'nsu=' + NS + ';i=6030',
   JoiningSystemEventContentType_EventText: 'nsu=' + NS + ';i=6029',
   JoiningSystemEventContentType_JoiningTechnology: 'nsu=' + NS + ';i=6025',
   JoiningSystemEventContentType_ReportedValues: 'nsu=' + NS + ';i=6279',
   JoiningSystemResultType_ResultMetaData: 'nsu=' + NS + ';i=6003',
   JoiningSystemResultType_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6160',
   JoiningSystemResultType_ResultMetaData_AssemblyType: 'nsu=' + NS + ';i=6139',
   JoiningSystemResultType_ResultMetaData_AssociatedEntities: 'nsu=' + NS + ';i=6137',
   JoiningSystemResultType_ResultMetaData_Classification: 'nsu=' + NS + ';i=6124',
   JoiningSystemResultType_ResultMetaData_Description: 'nsu=' + NS + ';i=6101',
   JoiningSystemResultType_ResultMetaData_ExtendedMetaData: 'nsu=' + NS + ';i=6173',
   JoiningSystemResultType_ResultMetaData_InterventionType: 'nsu=' + NS + ';i=6135',
   JoiningSystemResultType_ResultMetaData_IsGeneratedOffline: 'nsu=' + NS + ';i=6136',
   JoiningSystemResultType_ResultMetaData_JoiningTechnology: 'nsu=' + NS + ';i=6098',
   JoiningSystemResultType_ResultMetaData_Name: 'nsu=' + NS + ';i=6100',
   JoiningSystemResultType_ResultMetaData_OperationMode: 'nsu=' + NS + ';i=6010',
   JoiningSystemResultType_ResultMetaData_ResultCounters: 'nsu=' + NS + ';i=6138',
   JoiningSystemResultType_ResultMetaData_SequenceNumber: 'nsu=' + NS + ';i=6099',
   JoiningSystemConditionType_JoiningSystemEventContent: 'nsu=' + NS + ';i=6177',
   JoiningSystemConditionType_JoiningSystemEventContent_AssociatedEntities: 'nsu=' + NS + ';i=6281',
   JoiningSystemConditionType_JoiningSystemEventContent_EventCode: 'nsu=' + NS + ';i=6282',
   JoiningSystemConditionType_JoiningSystemEventContent_EventText: 'nsu=' + NS + ';i=6283',
   JoiningSystemConditionType_JoiningSystemEventContent_JoiningTechnology: 'nsu=' + NS + ';i=6284',
   JoiningSystemConditionType_JoiningSystemEventContent_ReportedValues: 'nsu=' + NS + ';i=6285',
   JoiningSystemEventType_JoiningSystemEventContent: 'nsu=' + NS + ';i=6039',
   JoiningSystemEventType_JoiningSystemEventContent_AssociatedEntities: 'nsu=' + NS + ';i=6275',
   JoiningSystemEventType_JoiningSystemEventContent_EventCode: 'nsu=' + NS + ';i=6276',
   JoiningSystemEventType_JoiningSystemEventContent_EventText: 'nsu=' + NS + ';i=6277',
   JoiningSystemEventType_JoiningSystemEventContent_JoiningTechnology: 'nsu=' + NS + ';i=6278',
   JoiningSystemEventType_JoiningSystemEventContent_ReportedValues: 'nsu=' + NS + ';i=6280',
   JoiningSystemResultReadyEventType_Result: 'nsu=' + NS + ';i=6001',
   JoiningSystemResultReadyEventType_Result_ResultContent: 'nsu=' + NS + ';i=6210',
   JoiningSystemResultReadyEventType_Result_ResultMetaData: 'nsu=' + NS + ';i=6002',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6207',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_AssemblyType: 'nsu=' + NS + ';i=6004',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_AssociatedEntities: 'nsu=' + NS + ';i=6007',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_Classification: 'nsu=' + NS + ';i=6009',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_Description: 'nsu=' + NS + ';i=6011',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_InterventionType: 'nsu=' + NS + ';i=6023',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_IsGeneratedOffline: 'nsu=' + NS + ';i=6032',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_JoiningTechnology: 'nsu=' + NS + ';i=6048',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_Name: 'nsu=' + NS + ';i=6052',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_ResultCounters: 'nsu=' + NS + ';i=6071',
   JoiningSystemResultReadyEventType_Result_ResultMetaData_SequenceNumber: 'nsu=' + NS + ';i=6152',
   RequestedResultEventType_Result_ResultMetaData: 'nsu=' + NS + ';i=6002',
   RequestedResultEventType_Result_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6207',
   IJoiningAdditionalInformationType_Description: 'nsu=' + NS + ';i=6175',
   IJoiningAdditionalInformationType_JoiningTechnology: 'nsu=' + NS + ';i=6176',
   IJoiningAdditionalInformationType_SupplierCode: 'nsu=' + NS + ';i=6452',
   IJoiningSystemAssetType_Health_DeviceHealth: 'nsu=' + NS + ';i=6005',
   IJoiningSystemAssetType_Health_ErrorCode: 'nsu=' + NS + ';i=6083',
   IJoiningSystemAssetType_Health_ErrorMessage: 'nsu=' + NS + ';i=6077',
   IJoiningSystemAssetType_Health_ErrorTimestamp: 'nsu=' + NS + ';i=6082',
   IJoiningSystemAssetType_Health_Temperature: 'nsu=' + NS + ';i=6090',
   IJoiningSystemAssetType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IJoiningSystemAssetType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IJoiningSystemAssetType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IJoiningSystemAssetType_Identification_Description: 'nsu=' + NS + ';i=6006',
   IJoiningSystemAssetType_Identification_JoiningTechnology: 'nsu=' + NS + ';i=6016',
   IJoiningSystemAssetType_Identification_SupplierCode: 'nsu=' + NS + ';i=6018',
   IJoiningSystemAssetType_LifetimeCounters_LifetimeVariable_Placeholder: 'nsu=' + NS + ';i=6164',
   IJoiningSystemAssetType_LifetimeCounters_LifetimeVariable_Placeholder_EngineeringUnits: 'nsu=' + NS + ';i=6165',
   IJoiningSystemAssetType_LifetimeCounters_LifetimeVariable_Placeholder_StartValue: 'nsu=' + NS + ';i=6167',
   IJoiningSystemAssetType_LifetimeCounters_LifetimeVariable_Placeholder_LimitValue: 'nsu=' + NS + ';i=6166',
   IJoiningSystemAssetType_OperationCounters_OperationCycleCounter: 'nsu=' + NS + ';i=6017',
   IJoiningSystemAssetType_OperationCounters_OperationDuration: 'nsu=' + NS + ';i=6108',
   IJoiningSystemAssetType_OperationCounters_PowerOnDuration: 'nsu=' + NS + ';i=6120',
   IJoiningSystemAssetType_Maintenance_Calibration_CalibrationPlace: 'nsu=' + NS + ';i=6037',
   IJoiningSystemAssetType_Maintenance_Calibration_CalibrationValue: 'nsu=' + NS + ';i=6028',
   IJoiningSystemAssetType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IJoiningSystemAssetType_Maintenance_Calibration_CertificateUri: 'nsu=' + NS + ';i=6038',
   IJoiningSystemAssetType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IJoiningSystemAssetType_Maintenance_Calibration_NextCalibration: 'nsu=' + NS + ';i=6020',
   IJoiningSystemAssetType_Maintenance_Calibration_SensorScale: 'nsu=' + NS + ';i=6036',
   IJoiningSystemAssetType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IJoiningSystemAssetType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IJoiningSystemAssetType_Maintenance_Service_NextService: 'nsu=' + NS + ';i=6089',
   IJoiningSystemAssetType_Maintenance_Service_NumberOfServices: 'nsu=' + NS + ';i=6094',
   IJoiningSystemAssetType_Maintenance_Service_RemainingCycles: 'nsu=' + NS + ';i=6110',
   IJoiningSystemAssetType_Maintenance_Service_ServiceCycleCount: 'nsu=' + NS + ';i=6093',
   IJoiningSystemAssetType_Maintenance_Service_ServiceCycleSpan: 'nsu=' + NS + ';i=6092',
   IJoiningSystemAssetType_Maintenance_Service_ServiceOperationCycles: 'nsu=' + NS + ';i=6050',
   IJoiningSystemAssetType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IJoiningSystemAssetType_Maintenance_Service_ServiceReminderCycles: 'nsu=' + NS + ';i=6049',
   IJoiningSystemAssetType_Maintenance_Service_ServiceReminderDays: 'nsu=' + NS + ';i=6109',
   IJoiningSystemAssetType_Monitoring_Health_DeviceHealth: 'nsu=' + NS + ';i=6465',
   IJoiningSystemAssetType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IJoiningSystemAssetType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IJoiningSystemAssetType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IJoiningSystemAssetType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IJoiningSystemAssetType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IJoiningSystemAssetType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IJoiningSystemAssetType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IJoiningSystemAssetType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IJoiningSystemAssetType_Monitoring_Health_ErrorCode: 'nsu=' + NS + ';i=6466',
   IJoiningSystemAssetType_Monitoring_Health_ErrorMessage: 'nsu=' + NS + ';i=6467',
   IJoiningSystemAssetType_Monitoring_Health_ErrorTimestamp: 'nsu=' + NS + ';i=6468',
   IJoiningSystemAssetType_Monitoring_Health_Temperature: 'nsu=' + NS + ';i=6469',
   IJoiningSystemAssetType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IJoiningSystemAssetType_Parameters_Connected: 'nsu=' + NS + ';i=6091',
   IJoiningSystemAssetType_Parameters_Enabled: 'nsu=' + NS + ';i=6008',
   IJoiningSystemAssetType_Parameters_IOSignals: 'nsu=' + NS + ';i=6044',
   IAccessoryType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IAccessoryType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IAccessoryType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IAccessoryType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IAccessoryType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IAccessoryType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IAccessoryType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IAccessoryType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IAccessoryType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IAccessoryType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IAccessoryType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IAccessoryType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IAccessoryType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IAccessoryType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IAccessoryType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IAccessoryType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IAccessoryType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IAccessoryType_Parameters_Type: 'nsu=' + NS + ';i=6117',
   IBatteryType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IBatteryType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IBatteryType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IBatteryType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IBatteryType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IBatteryType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IBatteryType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IBatteryType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IBatteryType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IBatteryType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IBatteryType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IBatteryType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IBatteryType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IBatteryType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IBatteryType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IBatteryType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IBatteryType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IBatteryType_Parameters_Capacity: 'nsu=' + NS + ';i=6121',
   IBatteryType_Parameters_Capacity_EngineeringUnits: 'nsu=' + NS + ';i=6012',
   IBatteryType_Parameters_Capacity_PhysicalQuantity: 'nsu=' + NS + ';i=6013',
   IBatteryType_Parameters_Capacity_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6014',
   IBatteryType_Parameters_ChargeCycleCount: 'nsu=' + NS + ';i=6122',
   IBatteryType_Parameters_NominalVoltage: 'nsu=' + NS + ';i=6119',
   IBatteryType_Parameters_NominalVoltage_EngineeringUnits: 'nsu=' + NS + ';i=6015',
   IBatteryType_Parameters_NominalVoltage_PhysicalQuantity: 'nsu=' + NS + ';i=6021',
   IBatteryType_Parameters_NominalVoltage_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6022',
   IBatteryType_Parameters_StateOfCharge: 'nsu=' + NS + ';i=6123',
   IBatteryType_Parameters_StateOfHealth: 'nsu=' + NS + ';i=6125',
   IBatteryType_Parameters_Type: 'nsu=' + NS + ';i=6126',
   ICableType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ICableType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   ICableType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   ICableType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ICableType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   ICableType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ICableType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   ICableType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   ICableType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   ICableType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   ICableType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   ICableType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   ICableType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   ICableType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   ICableType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   ICableType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   ICableType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ICableType_Parameters_CableLength: 'nsu=' + NS + ';i=6132',
   ICableType_Parameters_CableLength_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ICableType_Parameters_Type: 'nsu=' + NS + ';i=6130',
   ICableType_Parameters_Type_EnumStrings: 'nsu=' + NS + ';i=6131',
   IControllerType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IControllerType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IControllerType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IControllerType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IControllerType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IControllerType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IControllerType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IControllerType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IControllerType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IControllerType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IControllerType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IControllerType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IControllerType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IControllerType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IControllerType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IControllerType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IControllerType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IControllerType_Parameters_Type: 'nsu=' + NS + ';i=6128',
   IControllerType_Parameters_Type_EnumStrings: 'nsu=' + NS + ';i=6129',
   IFeederType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IFeederType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IFeederType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IFeederType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IFeederType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IFeederType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IFeederType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IFeederType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IFeederType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IFeederType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IFeederType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IFeederType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IFeederType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IFeederType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IFeederType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IFeederType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IFeederType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IFeederType_Parameters_FeedingSpeed: 'nsu=' + NS + ';i=6149',
   IFeederType_Parameters_FeedingSpeed_EngineeringUnits: 'nsu=' + NS + ';i=6033',
   IFeederType_Parameters_FeedingSpeed_PhysicalQuantity: 'nsu=' + NS + ';i=6035',
   IFeederType_Parameters_FeedingSpeed_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6045',
   IFeederType_Parameters_FillLevel: 'nsu=' + NS + ';i=6148',
   IFeederType_Parameters_Material: 'nsu=' + NS + ';i=6145',
   IFeederType_Parameters_Type: 'nsu=' + NS + ';i=6146',
   IFeederType_Parameters_Type_EnumStrings: 'nsu=' + NS + ';i=6147',
   IMemoryDeviceType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IMemoryDeviceType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IMemoryDeviceType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IMemoryDeviceType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IMemoryDeviceType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IMemoryDeviceType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IMemoryDeviceType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IMemoryDeviceType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IMemoryDeviceType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IMemoryDeviceType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IMemoryDeviceType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IMemoryDeviceType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IMemoryDeviceType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IMemoryDeviceType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IMemoryDeviceType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IMemoryDeviceType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IMemoryDeviceType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IMemoryDeviceType_Parameters_StorageCapacity: 'nsu=' + NS + ';i=6154',
   IMemoryDeviceType_Parameters_Type: 'nsu=' + NS + ';i=6150',
   IMemoryDeviceType_Parameters_UsedSpace: 'nsu=' + NS + ';i=6155',
   IPowerSupplyType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IPowerSupplyType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IPowerSupplyType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IPowerSupplyType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IPowerSupplyType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IPowerSupplyType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IPowerSupplyType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IPowerSupplyType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IPowerSupplyType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IPowerSupplyType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IPowerSupplyType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IPowerSupplyType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IPowerSupplyType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IPowerSupplyType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IPowerSupplyType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IPowerSupplyType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IPowerSupplyType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IPowerSupplyType_Parameters_ActualPower: 'nsu=' + NS + ';i=6158',
   IPowerSupplyType_Parameters_ActualPower_EngineeringUnits: 'nsu=' + NS + ';i=6054',
   IPowerSupplyType_Parameters_ActualPower_PhysicalQuantity: 'nsu=' + NS + ';i=6060',
   IPowerSupplyType_Parameters_ActualPower_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6065',
   IPowerSupplyType_Parameters_InputSpecification: 'nsu=' + NS + ';i=6156',
   IPowerSupplyType_Parameters_NominalPower: 'nsu=' + NS + ';i=6157',
   IPowerSupplyType_Parameters_NominalPower_EngineeringUnits: 'nsu=' + NS + ';i=6066',
   IPowerSupplyType_Parameters_NominalPower_PhysicalQuantity: 'nsu=' + NS + ';i=6073',
   IPowerSupplyType_Parameters_NominalPower_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6074',
   IPowerSupplyType_Parameters_OutputSpecification: 'nsu=' + NS + ';i=6249',
   ISensorType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISensorType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   ISensorType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   ISensorType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISensorType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   ISensorType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISensorType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   ISensorType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   ISensorType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   ISensorType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   ISensorType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   ISensorType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   ISensorType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   ISensorType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   ISensorType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   ISensorType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   ISensorType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISensorType_Parameters_MeasuredValue: 'nsu=' + NS + ';i=6231',
   ISensorType_Parameters_OverloadCount: 'nsu=' + NS + ';i=6171',
   ISensorType_Parameters_Type: 'nsu=' + NS + ';i=6169',
   ISensorType_Parameters_Type_EnumStrings: 'nsu=' + NS + ';i=6170',
   IServoType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IServoType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IServoType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IServoType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IServoType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IServoType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IServoType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IServoType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IServoType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IServoType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IServoType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IServoType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IServoType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IServoType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IServoType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IServoType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IServoType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IServoType_Parameters_NodeNumber: 'nsu=' + NS + ';i=6118',
   ISoftwareType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISoftwareType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   ISoftwareType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   ISoftwareType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISoftwareType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   ISoftwareType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISoftwareType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   ISoftwareType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   ISoftwareType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   ISoftwareType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   ISoftwareType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   ISoftwareType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   ISoftwareType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   ISoftwareType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   ISoftwareType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   ISoftwareType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   ISoftwareType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISubComponentType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISubComponentType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   ISubComponentType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   ISubComponentType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISubComponentType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   ISubComponentType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISubComponentType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   ISubComponentType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   ISubComponentType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   ISubComponentType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   ISubComponentType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   ISubComponentType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   ISubComponentType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   ISubComponentType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   ISubComponentType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   ISubComponentType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   ISubComponentType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   ISubComponentType_Parameters_Type: 'nsu=' + NS + ';i=6185',
   IToolType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IToolType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IToolType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IToolType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IToolType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IToolType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IToolType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IToolType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IToolType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IToolType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IToolType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IToolType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IToolType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IToolType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IToolType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IToolType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IToolType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IToolType_Parameters_Type: 'nsu=' + NS + ';i=6133',
   IToolType_Parameters_Type_EnumStrings: 'nsu=' + NS + ';i=6134',
   IVirtualStationType_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IVirtualStationType_Identification_Manufacturer: 'nsu=' + NS + ';i=6142',
   IVirtualStationType_Identification_SerialNumber: 'nsu=' + NS + ';i=6143',
   IVirtualStationType_Maintenance_Calibration_CalibrationValue_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IVirtualStationType_Maintenance_Calibration_LastCalibration: 'nsu=' + NS + ';i=6019',
   IVirtualStationType_Maintenance_Calibration_SensorScale_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   IVirtualStationType_Maintenance_Service_LastService: 'nsu=' + NS + ';i=6075',
   IVirtualStationType_Maintenance_Service_ServicePlace: 'nsu=' + NS + ';i=6076',
   IVirtualStationType_Monitoring_Status_MachineryItemState_CurrentState: 'nsu=' + NS + ';i=6090',
   IVirtualStationType_Monitoring_Status_MachineryItemState_CurrentState_Id: 'nsu=' + NS + ';i=6091',
   IVirtualStationType_Monitoring_Status_OperationMode_CurrentState: 'nsu=' + NS + ';i=6092',
   IVirtualStationType_Monitoring_Status_OperationMode_CurrentState_Id: 'nsu=' + NS + ';i=6093',
   IVirtualStationType_Monitoring_Status_Stacklight_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   IVirtualStationType_Monitoring_Status_Stacklight_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   IVirtualStationType_Monitoring_Status_Stacklight_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   IVirtualStationType_Monitoring_Status_Stacklight_StacklightMode: 'nsu=' + NS + ';i=6094',
   IVirtualStationType_Monitoring_Health_Temperature_PhysicalQuantity_EnumStrings: 'nsu=' + NS + ';i=6294',
   JoiningSystemIdentificationType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6234',
   JoiningSystemIdentificationType_Description: 'nsu=' + NS + ';i=6242',
   JoiningSystemIdentificationType_IntegratorName: 'nsu=' + NS + ';i=6241',
   JoiningSystemIdentificationType_JoiningTechnology: 'nsu=' + NS + ';i=6244',
   JoiningSystemIdentificationType_Location: 'nsu=' + NS + ';i=6458',
   JoiningSystemIdentificationType_Manufacturer: 'nsu=' + NS + ';i=6245',
   JoiningSystemIdentificationType_ManufacturerUri: 'nsu=' + NS + ';i=6246',
   JoiningSystemIdentificationType_Model: 'nsu=' + NS + ';i=6247',
   JoiningSystemIdentificationType_Name: 'nsu=' + NS + ';i=6240',
   JoiningSystemIdentificationType_ProductInstanceUri: 'nsu=' + NS + ';i=6236',
   JoiningSystemIdentificationType_SystemId: 'nsu=' + NS + ';i=6248',
   JoiningProcessManagementType_AbortJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6368',
   JoiningProcessManagementType_AbortJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6369',
   JoiningProcessManagementType_DecrementJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6360',
   JoiningProcessManagementType_DecrementJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6361',
   JoiningProcessManagementType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6338',
   JoiningProcessManagementType_DeleteJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6127',
   JoiningProcessManagementType_DeleteJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6140',
   JoiningProcessManagementType_DeselectJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6356',
   JoiningProcessManagementType_DeselectJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6357',
   JoiningProcessManagementType_GetJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6448',
   JoiningProcessManagementType_GetJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6449',
   JoiningProcessManagementType_GetJoiningProcessList_InputArguments: 'nsu=' + NS + ';i=6348',
   JoiningProcessManagementType_GetJoiningProcessList_OutputArguments: 'nsu=' + NS + ';i=6349',
   JoiningProcessManagementType_GetJoiningProcessRevisionList_InputArguments: 'nsu=' + NS + ';i=6350',
   JoiningProcessManagementType_GetJoiningProcessRevisionList_OutputArguments: 'nsu=' + NS + ';i=6351',
   JoiningProcessManagementType_GetSelectedJoiningProgram_InputArguments: 'nsu=' + NS + ';i=6461',
   JoiningProcessManagementType_GetSelectedJoiningProgram_OutputArguments: 'nsu=' + NS + ';i=6462',
   JoiningProcessManagementType_IncrementJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6358',
   JoiningProcessManagementType_IncrementJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6359',
   JoiningProcessManagementType_ResetJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6366',
   JoiningProcessManagementType_ResetJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6367',
   JoiningProcessManagementType_SelectJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6354',
   JoiningProcessManagementType_SelectJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6355',
   JoiningProcessManagementType_SendJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6340',
   JoiningProcessManagementType_SendJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6347',
   JoiningProcessManagementType_SetJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6362',
   JoiningProcessManagementType_SetJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6363',
   JoiningProcessManagementType_SetJoiningProcessMapping_InputArguments: 'nsu=' + NS + ';i=6352',
   JoiningProcessManagementType_SetJoiningProcessMapping_OutputArguments: 'nsu=' + NS + ';i=6353',
   JoiningProcessManagementType_SetJoiningProcessSize_InputArguments: 'nsu=' + NS + ';i=6364',
   JoiningProcessManagementType_SetJoiningProcessSize_OutputArguments: 'nsu=' + NS + ';i=6365',
   JoiningProcessManagementType_StartJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6374',
   JoiningProcessManagementType_StartJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6375',
   JoiningProcessManagementType_StartSelectedJoining_InputArguments: 'nsu=' + NS + ';i=6408',
   JoiningProcessManagementType_StartSelectedJoining_OutputArguments: 'nsu=' + NS + ';i=6409',
   JoiningSystemAssetMethodSetType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6295',
   JoiningSystemAssetMethodSetType_DisconnectAsset_InputArguments: 'nsu=' + NS + ';i=6047',
   JoiningSystemAssetMethodSetType_DisconnectAsset_OutputArguments: 'nsu=' + NS + ';i=6051',
   JoiningSystemAssetMethodSetType_EnableAsset_InputArguments: 'nsu=' + NS + ';i=6043',
   JoiningSystemAssetMethodSetType_EnableAsset_OutputArguments: 'nsu=' + NS + ';i=6046',
   JoiningSystemAssetMethodSetType_ExecuteOperation_InputArguments: 'nsu=' + NS + ';i=6086',
   JoiningSystemAssetMethodSetType_ExecuteOperation_OutputArguments: 'nsu=' + NS + ';i=6087',
   JoiningSystemAssetMethodSetType_GetErrorInformation_InputArguments: 'nsu=' + NS + ';i=6088',
   JoiningSystemAssetMethodSetType_GetErrorInformation_OutputArguments: 'nsu=' + NS + ';i=6102',
   JoiningSystemAssetMethodSetType_GetFeedbackFileList_InputArguments: 'nsu=' + NS + ';i=6061',
   JoiningSystemAssetMethodSetType_GetFeedbackFileList_OutputArguments: 'nsu=' + NS + ';i=6062',
   JoiningSystemAssetMethodSetType_GetIdentifiers_InputArguments: 'nsu=' + NS + ';i=6069',
   JoiningSystemAssetMethodSetType_GetIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6070',
   JoiningSystemAssetMethodSetType_GetIOSignals_InputArguments: 'nsu=' + NS + ';i=6067',
   JoiningSystemAssetMethodSetType_GetIOSignals_OutputArguments: 'nsu=' + NS + ';i=6068',
   JoiningSystemAssetMethodSetType_RebootAsset_InputArguments: 'nsu=' + NS + ';i=6053',
   JoiningSystemAssetMethodSetType_RebootAsset_OutputArguments: 'nsu=' + NS + ';i=6055',
   JoiningSystemAssetMethodSetType_ResetIdentifiers_InputArguments: 'nsu=' + NS + ';i=6081',
   JoiningSystemAssetMethodSetType_ResetIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6085',
   JoiningSystemAssetMethodSetType_SendFeedback_InputArguments: 'nsu=' + NS + ';i=6058',
   JoiningSystemAssetMethodSetType_SendFeedback_OutputArguments: 'nsu=' + NS + ';i=6059',
   JoiningSystemAssetMethodSetType_SendIdentifiers_InputArguments: 'nsu=' + NS + ';i=6072',
   JoiningSystemAssetMethodSetType_SendIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6078',
   JoiningSystemAssetMethodSetType_SendTextIdentifiers_InputArguments: 'nsu=' + NS + ';i=6079',
   JoiningSystemAssetMethodSetType_SendTextIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6080',
   JoiningSystemAssetMethodSetType_SetCalibration_InputArguments: 'nsu=' + NS + ';i=6040',
   JoiningSystemAssetMethodSetType_SetCalibration_OutputArguments: 'nsu=' + NS + ';i=6041',
   JoiningSystemAssetMethodSetType_SetIOSignals_InputArguments: 'nsu=' + NS + ';i=6063',
   JoiningSystemAssetMethodSetType_SetIOSignals_OutputArguments: 'nsu=' + NS + ';i=6064',
   JoiningSystemAssetMethodSetType_SetOfflineTimer_InputArguments: 'nsu=' + NS + ';i=6056',
   JoiningSystemAssetMethodSetType_SetOfflineTimer_OutputArguments: 'nsu=' + NS + ';i=6057',
   JoiningSystemAssetMethodSetType_SetTime_InputArguments: 'nsu=' + NS + ';i=6406',
   JoiningSystemAssetMethodSetType_SetTime_OutputArguments: 'nsu=' + NS + ';i=6407',
   JoiningSystemType_AssetManagement_MethodSet_DisconnectAsset_InputArguments: 'nsu=' + NS + ';i=6412',
   JoiningSystemType_AssetManagement_MethodSet_DisconnectAsset_OutputArguments: 'nsu=' + NS + ';i=6413',
   JoiningSystemType_AssetManagement_MethodSet_EnableAsset_InputArguments: 'nsu=' + NS + ';i=6414',
   JoiningSystemType_AssetManagement_MethodSet_EnableAsset_OutputArguments: 'nsu=' + NS + ';i=6415',
   JoiningSystemType_AssetManagement_MethodSet_ExecuteOperation_InputArguments: 'nsu=' + NS + ';i=6416',
   JoiningSystemType_AssetManagement_MethodSet_ExecuteOperation_OutputArguments: 'nsu=' + NS + ';i=6417',
   JoiningSystemType_AssetManagement_MethodSet_GetErrorInformation_InputArguments: 'nsu=' + NS + ';i=6418',
   JoiningSystemType_AssetManagement_MethodSet_GetErrorInformation_OutputArguments: 'nsu=' + NS + ';i=6419',
   JoiningSystemType_AssetManagement_MethodSet_GetFeedbackFileList_InputArguments: 'nsu=' + NS + ';i=6420',
   JoiningSystemType_AssetManagement_MethodSet_GetFeedbackFileList_OutputArguments: 'nsu=' + NS + ';i=6421',
   JoiningSystemType_AssetManagement_MethodSet_GetIdentifiers_InputArguments: 'nsu=' + NS + ';i=6424',
   JoiningSystemType_AssetManagement_MethodSet_GetIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6425',
   JoiningSystemType_AssetManagement_MethodSet_GetIOSignals_InputArguments: 'nsu=' + NS + ';i=6422',
   JoiningSystemType_AssetManagement_MethodSet_GetIOSignals_OutputArguments: 'nsu=' + NS + ';i=6423',
   JoiningSystemType_AssetManagement_MethodSet_RebootAsset_InputArguments: 'nsu=' + NS + ';i=6426',
   JoiningSystemType_AssetManagement_MethodSet_RebootAsset_OutputArguments: 'nsu=' + NS + ';i=6427',
   JoiningSystemType_AssetManagement_MethodSet_ResetIdentifiers_InputArguments: 'nsu=' + NS + ';i=6428',
   JoiningSystemType_AssetManagement_MethodSet_ResetIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6429',
   JoiningSystemType_AssetManagement_MethodSet_SendFeedback_InputArguments: 'nsu=' + NS + ';i=6430',
   JoiningSystemType_AssetManagement_MethodSet_SendFeedback_OutputArguments: 'nsu=' + NS + ';i=6431',
   JoiningSystemType_AssetManagement_MethodSet_SendIdentifiers_InputArguments: 'nsu=' + NS + ';i=6432',
   JoiningSystemType_AssetManagement_MethodSet_SendIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6433',
   JoiningSystemType_AssetManagement_MethodSet_SendTextIdentifiers_InputArguments: 'nsu=' + NS + ';i=6434',
   JoiningSystemType_AssetManagement_MethodSet_SendTextIdentifiers_OutputArguments: 'nsu=' + NS + ';i=6435',
   JoiningSystemType_AssetManagement_MethodSet_SetCalibration_InputArguments: 'nsu=' + NS + ';i=6436',
   JoiningSystemType_AssetManagement_MethodSet_SetCalibration_OutputArguments: 'nsu=' + NS + ';i=6437',
   JoiningSystemType_AssetManagement_MethodSet_SetIOSignals_InputArguments: 'nsu=' + NS + ';i=6438',
   JoiningSystemType_AssetManagement_MethodSet_SetIOSignals_OutputArguments: 'nsu=' + NS + ';i=6439',
   JoiningSystemType_AssetManagement_MethodSet_SetOfflineTimer_InputArguments: 'nsu=' + NS + ';i=6440',
   JoiningSystemType_AssetManagement_MethodSet_SetOfflineTimer_OutputArguments: 'nsu=' + NS + ';i=6441',
   JoiningSystemType_AssetManagement_MethodSet_SetTime_InputArguments: 'nsu=' + NS + ';i=6442',
   JoiningSystemType_AssetManagement_MethodSet_SetTime_OutputArguments: 'nsu=' + NS + ';i=6443',
   JoiningSystemType_Identification_Description: 'nsu=' + NS + ';i=6194',
   JoiningSystemType_Identification_IntegratorName: 'nsu=' + NS + ';i=6195',
   JoiningSystemType_Identification_JoiningTechnology: 'nsu=' + NS + ';i=6196',
   JoiningSystemType_Identification_Location: 'nsu=' + NS + ';i=6197',
   JoiningSystemType_Identification_Manufacturer: 'nsu=' + NS + ';i=6223',
   JoiningSystemType_Identification_ManufacturerUri: 'nsu=' + NS + ';i=6224',
   JoiningSystemType_Identification_Model: 'nsu=' + NS + ';i=6237',
   JoiningSystemType_Identification_Name: 'nsu=' + NS + ';i=6193',
   JoiningSystemType_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=6238',
   JoiningSystemType_Identification_SystemId: 'nsu=' + NS + ';i=6239',
   JoiningSystemType_JoiningProcessManagement_AbortJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6376',
   JoiningSystemType_JoiningProcessManagement_AbortJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6377',
   JoiningSystemType_JoiningProcessManagement_DecrementJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6378',
   JoiningSystemType_JoiningProcessManagement_DecrementJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6379',
   JoiningSystemType_JoiningProcessManagement_DeleteJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6127',
   JoiningSystemType_JoiningProcessManagement_DeleteJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6140',
   JoiningSystemType_JoiningProcessManagement_DeselectJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6380',
   JoiningSystemType_JoiningProcessManagement_DeselectJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6381',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6448',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6449',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessList_InputArguments: 'nsu=' + NS + ';i=6382',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessList_OutputArguments: 'nsu=' + NS + ';i=6383',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessRevisionList_InputArguments: 'nsu=' + NS + ';i=6384',
   JoiningSystemType_JoiningProcessManagement_GetJoiningProcessRevisionList_OutputArguments: 'nsu=' + NS + ';i=6385',
   JoiningSystemType_JoiningProcessManagement_GetSelectedJoiningProgram_InputArguments: 'nsu=' + NS + ';i=6461',
   JoiningSystemType_JoiningProcessManagement_GetSelectedJoiningProgram_OutputArguments: 'nsu=' + NS + ';i=6462',
   JoiningSystemType_JoiningProcessManagement_IncrementJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6386',
   JoiningSystemType_JoiningProcessManagement_IncrementJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6387',
   JoiningSystemType_JoiningProcessManagement_ResetJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6388',
   JoiningSystemType_JoiningProcessManagement_ResetJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6389',
   JoiningSystemType_JoiningProcessManagement_SelectJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6392',
   JoiningSystemType_JoiningProcessManagement_SelectJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6393',
   JoiningSystemType_JoiningProcessManagement_SendJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6394',
   JoiningSystemType_JoiningProcessManagement_SendJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6395',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessCounter_InputArguments: 'nsu=' + NS + ';i=6396',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessCounter_OutputArguments: 'nsu=' + NS + ';i=6397',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessMapping_InputArguments: 'nsu=' + NS + ';i=6398',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessMapping_OutputArguments: 'nsu=' + NS + ';i=6399',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessSize_InputArguments: 'nsu=' + NS + ';i=6400',
   JoiningSystemType_JoiningProcessManagement_SetJoiningProcessSize_OutputArguments: 'nsu=' + NS + ';i=6401',
   JoiningSystemType_JoiningProcessManagement_StartJoiningProcess_InputArguments: 'nsu=' + NS + ';i=6402',
   JoiningSystemType_JoiningProcessManagement_StartJoiningProcess_OutputArguments: 'nsu=' + NS + ';i=6403',
   JoiningSystemType_JoiningProcessManagement_StartSelectedJoining_InputArguments: 'nsu=' + NS + ';i=6408',
   JoiningSystemType_JoiningProcessManagement_StartSelectedJoining_OutputArguments: 'nsu=' + NS + ';i=6409',
   JoiningSystemType_JointManagement_DeleteJoint_InputArguments: 'nsu=' + NS + ';i=6141',
   JoiningSystemType_JointManagement_DeleteJoint_OutputArguments: 'nsu=' + NS + ';i=6151',
   JoiningSystemType_JointManagement_DeleteJointComponent_InputArguments: 'nsu=' + NS + ';i=6162',
   JoiningSystemType_JointManagement_DeleteJointComponent_OutputArguments: 'nsu=' + NS + ';i=6163',
   JoiningSystemType_JointManagement_DeleteJointDesign_InputArguments: 'nsu=' + NS + ';i=6153',
   JoiningSystemType_JointManagement_DeleteJointDesign_OutputArguments: 'nsu=' + NS + ';i=6161',
   JoiningSystemType_JointManagement_GetJoint_InputArguments: 'nsu=' + NS + ';i=6316',
   JoiningSystemType_JointManagement_GetJoint_OutputArguments: 'nsu=' + NS + ';i=6317',
   JoiningSystemType_JointManagement_GetJointComponent_InputArguments: 'nsu=' + NS + ';i=6318',
   JoiningSystemType_JointManagement_GetJointComponent_OutputArguments: 'nsu=' + NS + ';i=6319',
   JoiningSystemType_JointManagement_GetJointComponentList_InputArguments: 'nsu=' + NS + ';i=6320',
   JoiningSystemType_JointManagement_GetJointComponentList_OutputArguments: 'nsu=' + NS + ';i=6321',
   JoiningSystemType_JointManagement_GetJointDesign_InputArguments: 'nsu=' + NS + ';i=6322',
   JoiningSystemType_JointManagement_GetJointDesign_OutputArguments: 'nsu=' + NS + ';i=6323',
   JoiningSystemType_JointManagement_GetJointDesignList_InputArguments: 'nsu=' + NS + ';i=6324',
   JoiningSystemType_JointManagement_GetJointDesignList_OutputArguments: 'nsu=' + NS + ';i=6325',
   JoiningSystemType_JointManagement_GetJointList_InputArguments: 'nsu=' + NS + ';i=6326',
   JoiningSystemType_JointManagement_GetJointList_OutputArguments: 'nsu=' + NS + ';i=6327',
   JoiningSystemType_JointManagement_GetJointRevisionList_InputArguments: 'nsu=' + NS + ';i=6328',
   JoiningSystemType_JointManagement_GetJointRevisionList_OutputArguments: 'nsu=' + NS + ';i=6329',
   JoiningSystemType_JointManagement_SelectJoint_InputArguments: 'nsu=' + NS + ';i=6330',
   JoiningSystemType_JointManagement_SelectJoint_OutputArguments: 'nsu=' + NS + ';i=6331',
   JoiningSystemType_JointManagement_SendJoint_InputArguments: 'nsu=' + NS + ';i=6332',
   JoiningSystemType_JointManagement_SendJoint_OutputArguments: 'nsu=' + NS + ';i=6333',
   JoiningSystemType_JointManagement_SendJointComponent_InputArguments: 'nsu=' + NS + ';i=6334',
   JoiningSystemType_JointManagement_SendJointComponent_OutputArguments: 'nsu=' + NS + ';i=6335',
   JoiningSystemType_JointManagement_SendJointDesign_InputArguments: 'nsu=' + NS + ';i=6336',
   JoiningSystemType_JointManagement_SendJointDesign_OutputArguments: 'nsu=' + NS + ';i=6337',
   JoiningSystemType_ResultManagement_AcknowledgeResults_InputArguments: 'nsu=' + NS + ';i=6089',
   JoiningSystemType_ResultManagement_AcknowledgeResults_OutputArguments: 'nsu=' + NS + ';i=6090',
   JoiningSystemType_ResultManagement_GetLatestResult_InputArguments: 'nsu=' + NS + ';i=6106',
   JoiningSystemType_ResultManagement_GetLatestResult_OutputArguments: 'nsu=' + NS + ';i=6107',
   JoiningSystemType_ResultManagement_GetResultById_InputArguments: 'nsu=' + NS + ';i=6095',
   JoiningSystemType_ResultManagement_GetResultById_OutputArguments: 'nsu=' + NS + ';i=6096',
   JoiningSystemType_ResultManagement_GetResultIdListFiltered_InputArguments: 'nsu=' + NS + ';i=6097',
   JoiningSystemType_ResultManagement_GetResultIdListFiltered_OutputArguments: 'nsu=' + NS + ';i=6103',
   JoiningSystemType_ResultManagement_ReleaseResultHandle_InputArguments: 'nsu=' + NS + ';i=6104',
   JoiningSystemType_ResultManagement_ReleaseResultHandle_OutputArguments: 'nsu=' + NS + ';i=6105',
   JoiningSystemType_ResultManagement_ResultTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=6040',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=6038',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=6039',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=6043',
   JoiningSystemType_ResultManagement_ResultTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=6044',
   JoiningSystemType_ResultManagement_ResultTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=6041',
   JoiningSystemType_ResultManagement_ResultTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=6042',
   JoiningSystemType_ResultManagement_RequestResults_InputArguments: 'nsu=' + NS + ';i=6459',
   JoiningSystemType_ResultManagement_RequestResults_OutputArguments: 'nsu=' + NS + ';i=6460',
   JoiningSystemType_ResultManagement_RequestUnacknowledgedResults_InputArguments: 'nsu=' + NS + ';i=6470',
   JoiningSystemType_ResultManagement_RequestUnacknowledgedResults_OutputArguments: 'nsu=' + NS + ';i=6471',
   JointManagementType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6339',
   JointManagementType_DeleteJoint_InputArguments: 'nsu=' + NS + ';i=6141',
   JointManagementType_DeleteJoint_OutputArguments: 'nsu=' + NS + ';i=6151',
   JointManagementType_DeleteJointComponent_InputArguments: 'nsu=' + NS + ';i=6162',
   JointManagementType_DeleteJointComponent_OutputArguments: 'nsu=' + NS + ';i=6163',
   JointManagementType_DeleteJointDesign_InputArguments: 'nsu=' + NS + ';i=6153',
   JointManagementType_DeleteJointDesign_OutputArguments: 'nsu=' + NS + ';i=6161',
   JointManagementType_GetJoint_InputArguments: 'nsu=' + NS + ';i=6310',
   JointManagementType_GetJoint_OutputArguments: 'nsu=' + NS + ';i=6311',
   JointManagementType_GetJointComponent_InputArguments: 'nsu=' + NS + ';i=6314',
   JointManagementType_GetJointComponent_OutputArguments: 'nsu=' + NS + ';i=6315',
   JointManagementType_GetJointComponentList_InputArguments: 'nsu=' + NS + ';i=6306',
   JointManagementType_GetJointComponentList_OutputArguments: 'nsu=' + NS + ';i=6307',
   JointManagementType_GetJointDesign_InputArguments: 'nsu=' + NS + ';i=6312',
   JointManagementType_GetJointDesign_OutputArguments: 'nsu=' + NS + ';i=6313',
   JointManagementType_GetJointDesignList_InputArguments: 'nsu=' + NS + ';i=6304',
   JointManagementType_GetJointDesignList_OutputArguments: 'nsu=' + NS + ';i=6305',
   JointManagementType_GetJointList_InputArguments: 'nsu=' + NS + ';i=6235',
   JointManagementType_GetJointList_OutputArguments: 'nsu=' + NS + ';i=6303',
   JointManagementType_GetJointRevisionList_InputArguments: 'nsu=' + NS + ';i=6308',
   JointManagementType_GetJointRevisionList_OutputArguments: 'nsu=' + NS + ';i=6309',
   JointManagementType_SelectJoint_InputArguments: 'nsu=' + NS + ';i=6229',
   JointManagementType_SelectJoint_OutputArguments: 'nsu=' + NS + ';i=6230',
   JointManagementType_SendJoint_InputArguments: 'nsu=' + NS + ';i=6183',
   JointManagementType_SendJoint_OutputArguments: 'nsu=' + NS + ';i=6184',
   JointManagementType_SendJointComponent_InputArguments: 'nsu=' + NS + ';i=6192',
   JointManagementType_SendJointComponent_OutputArguments: 'nsu=' + NS + ';i=6228',
   JointManagementType_SendJointDesign_InputArguments: 'nsu=' + NS + ';i=6186',
   JointManagementType_SendJointDesign_OutputArguments: 'nsu=' + NS + ';i=6191',
   JoiningSystemResultManagementType_AcknowledgeResults_InputArguments: 'nsu=' + NS + ';i=6089',
   JoiningSystemResultManagementType_AcknowledgeResults_OutputArguments: 'nsu=' + NS + ';i=6090',
   JoiningSystemResultManagementType_GetLatestResult_InputArguments: 'nsu=' + NS + ';i=6054',
   JoiningSystemResultManagementType_GetLatestResult_OutputArguments: 'nsu=' + NS + ';i=6055',
   JoiningSystemResultManagementType_GetResultById_InputArguments: 'nsu=' + NS + ';i=6048',
   JoiningSystemResultManagementType_GetResultById_OutputArguments: 'nsu=' + NS + ';i=6049',
   JoiningSystemResultManagementType_GetResultIdListFiltered_InputArguments: 'nsu=' + NS + ';i=6050',
   JoiningSystemResultManagementType_GetResultIdListFiltered_OutputArguments: 'nsu=' + NS + ';i=6051',
   JoiningSystemResultManagementType_ReleaseResultHandle_InputArguments: 'nsu=' + NS + ';i=6052',
   JoiningSystemResultManagementType_ReleaseResultHandle_OutputArguments: 'nsu=' + NS + ';i=6053',
   JoiningSystemResultManagementType_ResultTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=6040',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=6038',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=6039',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=6043',
   JoiningSystemResultManagementType_ResultTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=6044',
   JoiningSystemResultManagementType_ResultTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=6041',
   JoiningSystemResultManagementType_ResultTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=6042',
   JoiningSystemResultManagementType_RequestResults_InputArguments: 'nsu=' + NS + ';i=6459',
   JoiningSystemResultManagementType_RequestResults_OutputArguments: 'nsu=' + NS + ';i=6460',
   JoiningSystemResultManagementType_RequestUnacknowledgedResults_InputArguments: 'nsu=' + NS + ';i=6470',
   JoiningSystemResultManagementType_RequestUnacknowledgedResults_OutputArguments: 'nsu=' + NS + ';i=6471',
   JoiningSystemResultManagementType_Results_RequestedResultVariable_Placeholder: 'nsu=' + NS + ';i=6159',
   JoiningSystemResultManagementType_Results_RequestedResultVariable_Placeholder_ResultMetaData: 'nsu=' + NS + ';i=6472',
   JoiningSystemResultManagementType_Results_RequestedResultVariable_Placeholder_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6473',
   JoiningSystemResultManagementType_Results_ResultVariable_Placeholder: 'nsu=' + NS + ';i=6225',
   JoiningSystemResultManagementType_Results_ResultVariable_Placeholder_ResultContent: 'nsu=' + NS + ';i=6211',
   JoiningSystemResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData: 'nsu=' + NS + ';i=6226',
   JoiningSystemResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6208',
});

export const VariableTypeIds = Object.freeze({
   JoiningDataVariableType: 'nsu=' + NS + ';i=2011',
   JoiningSystemEventContentType: 'nsu=' + NS + ';i=2008',
   JoiningSystemResultType: 'nsu=' + NS + ';i=2014',
});
