export const NS = 'http://opcfoundation.org/UA/DI/';

export const BrowseNames = Object.freeze({
   Abort: 'Abort',
   ActualMode: 'ActualMode',
   AssetId: 'AssetId',
   BaseLifetimeIndicationType: 'BaseLifetimeIndicationType',
   BlockType: 'BlockType',
   BreakLock: 'BreakLock',
   CachedLoadingType: 'CachedLoadingType',
   ChangeLogReference: 'ChangeLogReference',
   CheckFunctionAlarmType: 'CheckFunctionAlarmType',
   ComponentName: 'ComponentName',
   ComponentType: 'ComponentType',
   ConfigurableObjectType: 'ConfigurableObjectType',
   Confirm: 'Confirm',
   Confirmation: 'Confirmation',
   ConfirmationStateMachineType: 'ConfirmationStateMachineType',
   ConfirmationTimeout: 'ConfirmationTimeout',
   ConnectionPointType: 'ConnectionPointType',
   ConnectsTo: 'ConnectsTo',
   ConnectsToParent: 'ConnectsToParent',
   CPIdentifier_Placeholder: '<CPIdentifier>',
   CurrentVersion: 'CurrentVersion',
   DeviceClass: 'DeviceClass',
   DeviceFeatures: 'DeviceFeatures',
   DeviceHealth: 'DeviceHealth',
   DeviceHealthAlarms: 'DeviceHealthAlarms',
   DeviceHealthDiagnosticAlarmType: 'DeviceHealthDiagnosticAlarmType',
   DeviceHealthEnumeration: 'DeviceHealthEnumeration',
   DeviceManual: 'DeviceManual',
   DeviceRevision: 'DeviceRevision',
   DeviceSet: 'DeviceSet',
   DeviceTopology: 'DeviceTopology',
   DeviceType: 'DeviceType',
   DeviceTypeImage: 'DeviceTypeImage',
   DiameterIndicationType: 'DiameterIndicationType',
   DirectLoadingType: 'DirectLoadingType',
   Documentation: 'Documentation',
   DocumentationFiles: 'DocumentationFiles',
   DocumentFileId_Placeholder: '<DocumentFileId>',
   DocumentIdentifier_Placeholder: '<DocumentIdentifier>',
   Error: 'Error',
   ErrorMessage: 'ErrorMessage',
   ErrorToIdle: 'ErrorToIdle',
   ExitLock: 'ExitLock',
   FailureAlarmType: 'FailureAlarmType',
   FallbackVersion: 'FallbackVersion',
   FetchResultDataType: 'FetchResultDataType',
   FetchTransferResultData: 'FetchTransferResultData',
   FileSystemLoadingType: 'FileSystemLoadingType',
   FileTransfer: 'FileTransfer',
   FunctionalGroupType: 'FunctionalGroupType',
   GetUpdateBehavior: 'GetUpdateBehavior',
   GroupIdentifier_Placeholder: '<GroupIdentifier>',
   HardwareRevision: 'HardwareRevision',
   Hash: 'Hash',
   Identification: 'Identification',
   IDeviceHealthType: 'IDeviceHealthType',
   Idle: 'Idle',
   IdleToInstalling: 'IdleToInstalling',
   IdleToPreparing: 'IdleToPreparing',
   ImageIdentifier_Placeholder: '<ImageIdentifier>',
   ImageSet: 'ImageSet',
   Indication: 'Indication',
   InitLock: 'InitLock',
   Installation: 'Installation',
   InstallationDelay: 'InstallationDelay',
   InstallationStateMachineType: 'InstallationStateMachineType',
   InstallFiles: 'InstallFiles',
   Installing: 'Installing',
   InstallingToError: 'InstallingToError',
   InstallingToIdle: 'InstallingToIdle',
   InstallSoftwarePackage: 'InstallSoftwarePackage',
   IOperationCounterType: 'IOperationCounterType',
   IsOnline: 'IsOnline',
   ISupportInfoType: 'ISupportInfoType',
   ITagNameplateType: 'ITagNameplateType',
   IVendorNameplateType: 'IVendorNameplateType',
   LengthIndicationType: 'LengthIndicationType',
   LifetimeVariableType: 'LifetimeVariableType',
   LimitValue: 'LimitValue',
   Loading: 'Loading',
   Lock: 'Lock',
   Locked: 'Locked',
   LockingClient: 'LockingClient',
   LockingServicesType: 'LockingServicesType',
   LockingUser: 'LockingUser',
   MaintenanceRequiredAlarmType: 'MaintenanceRequiredAlarmType',
   Manufacturer: 'Manufacturer',
   ManufacturerUri: 'ManufacturerUri',
   MethodSet: 'MethodSet',
   Model: 'Model',
   NetworkAddress: 'NetworkAddress',
   NetworkIdentifier_Placeholder: '<NetworkIdentifier>',
   NetworkSet: 'NetworkSet',
   NetworkType: 'NetworkType',
   NormalMode: 'NormalMode',
   NotWaitingForConfirm: 'NotWaitingForConfirm',
   NotWaitingForConfirmToWaitingForConfirm: 'NotWaitingForConfirmToWaitingForConfirm',
   NotWaitingForPowerCycle: 'NotWaitingForPowerCycle',
   NotWaitingForPowerCycleToWaitingForPowerCycle: 'NotWaitingForPowerCycleToWaitingForPowerCycle',
   NumberOfPartsIndicationType: 'NumberOfPartsIndicationType',
   NumberOfUsagesIndicationType: 'NumberOfUsagesIndicationType',
   ObjectIdentifier_Placeholder: '<ObjectIdentifier>',
   OffSpecAlarmType: 'OffSpecAlarmType',
   OnlineAccess: 'OnlineAccess',
   OperationCycleCounter: 'OperationCycleCounter',
   OperationDuration: 'OperationDuration',
   PackageLoadingType: 'PackageLoadingType',
   ParameterIdentifier_Placeholder: '<ParameterIdentifier>',
   ParameterResultDataType: 'ParameterResultDataType',
   Parameters: 'Parameters',
   ParameterSet: 'ParameterSet',
   PatchIdentifiers: 'PatchIdentifiers',
   PendingVersion: 'PendingVersion',
   PercentComplete: 'PercentComplete',
   PermittedMode: 'PermittedMode',
   PowerCycle: 'PowerCycle',
   PowerCycleStateMachineType: 'PowerCycleStateMachineType',
   PowerOnDuration: 'PowerOnDuration',
   Prepare: 'Prepare',
   PreparedForUpdate: 'PreparedForUpdate',
   PreparedForUpdateToResuming: 'PreparedForUpdateToResuming',
   PrepareForUpdate: 'PrepareForUpdate',
   PrepareForUpdateStateMachineType: 'PrepareForUpdateStateMachineType',
   Preparing: 'Preparing',
   PreparingToIdle: 'PreparingToIdle',
   PreparingToPreparedForUpdate: 'PreparingToPreparedForUpdate',
   ProductCode: 'ProductCode',
   ProductInstanceUri: 'ProductInstanceUri',
   ProfileIdentifier_Placeholder: '<ProfileIdentifier>',
   ProtocolSupport: 'ProtocolSupport',
   ProtocolSupportIdentifier_Placeholder: '<ProtocolSupportIdentifier>',
   ProtocolType: 'ProtocolType',
   ReleaseDate: 'ReleaseDate',
   RemainingLockTime: 'RemainingLockTime',
   RenewLock: 'RenewLock',
   Resume: 'Resume',
   Resuming: 'Resuming',
   ResumingToIdle: 'ResumingToIdle',
   RevisionCounter: 'RevisionCounter',
   SerialNumber: 'SerialNumber',
   SoftwareLoadingType: 'SoftwareLoadingType',
   SoftwareReleaseDate: 'SoftwareReleaseDate',
   SoftwareRevision: 'SoftwareRevision',
   SoftwareType: 'SoftwareType',
   SoftwareUpdate: 'SoftwareUpdate',
   SoftwareUpdateType: 'SoftwareUpdateType',
   SoftwareVersionFileType: 'SoftwareVersionFileType',
   SoftwareVersionType: 'SoftwareVersionType',
   StartValue: 'StartValue',
   SubstanceVolumeIndicationType: 'SubstanceVolumeIndicationType',
   SupportedTypes: 'SupportedTypes',
   TargetMode: 'TargetMode',
   TimeIndicationType: 'TimeIndicationType',
   TopologyElementType: 'TopologyElementType',
   TransferFromDevice: 'TransferFromDevice',
   TransferResultDataDataType: 'TransferResultDataDataType',
   TransferResultErrorDataType: 'TransferResultErrorDataType',
   TransferServicesType: 'TransferServicesType',
   TransferToDevice: 'TransferToDevice',
   UIElement: 'UIElement',
   UIElementType: 'UIElementType',
   UpdateBehavior: 'UpdateBehavior',
   UpdateKey: 'UpdateKey',
   UpdateStatus: 'UpdateStatus',
   ValidateFiles: 'ValidateFiles',
   VendorErrorCode: 'VendorErrorCode',
   WaitingForConfirm: 'WaitingForConfirm',
   WaitingForConfirmToNotWaitingForConfirm: 'WaitingForConfirmToNotWaitingForConfirm',
   WaitingForPowerCycle: 'WaitingForPowerCycle',
   WaitingForPowerCycleToNotWaitingForPowerCycle: 'WaitingForPowerCycleToNotWaitingForPowerCycle',
   WarningValues: 'WarningValues',
   WriteBlockSize: 'WriteBlockSize',
   WriteTimeout: 'WriteTimeout',
});

export const DataTypeIds = Object.freeze({
   DeviceHealthEnumeration: 'nsu=' + NS + ';i=6244',
   FetchResultDataType: 'nsu=' + NS + ';i=6522',
   TransferResultErrorDataType: 'nsu=' + NS + ';i=15888',
   TransferResultDataDataType: 'nsu=' + NS + ';i=15889',
   ParameterResultDataType: 'nsu=' + NS + ';i=6525',
   SoftwareVersionFileType: 'nsu=' + NS + ';i=331',
   UpdateBehavior: 'nsu=' + NS + ';i=333',
});

export const MethodIds = Object.freeze({
   TopologyElementType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   TopologyElementType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   TopologyElementType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   TopologyElementType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open: 'nsu=' + NS + ';i=36',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Close: 'nsu=' + NS + ';i=39',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read: 'nsu=' + NS + ';i=63',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Write: 'nsu=' + NS + ';i=66',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition: 'nsu=' + NS + ';i=68',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_SetPosition: 'nsu=' + NS + ';i=71',
   ComponentType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   ComponentType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   ComponentType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   ComponentType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   DeviceType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   DeviceType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   DeviceType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   DeviceType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   DeviceType_CPIdentifier_Placeholder_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   DeviceType_CPIdentifier_Placeholder_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   DeviceType_CPIdentifier_Placeholder_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   DeviceType_CPIdentifier_Placeholder_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   SoftwareType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   SoftwareType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   SoftwareType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   SoftwareType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   BlockType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   BlockType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   BlockType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   BlockType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   NetworkType_CPIdentifier_Placeholder_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   NetworkType_CPIdentifier_Placeholder_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   NetworkType_CPIdentifier_Placeholder_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   NetworkType_CPIdentifier_Placeholder_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   NetworkType_Lock_InitLock: 'nsu=' + NS + ';i=6299',
   NetworkType_Lock_RenewLock: 'nsu=' + NS + ';i=6302',
   NetworkType_Lock_ExitLock: 'nsu=' + NS + ';i=6304',
   NetworkType_Lock_BreakLock: 'nsu=' + NS + ';i=6306',
   ConnectionPointType_Lock_InitLock: 'nsu=' + NS + ';i=6166',
   ConnectionPointType_Lock_RenewLock: 'nsu=' + NS + ';i=6169',
   ConnectionPointType_Lock_ExitLock: 'nsu=' + NS + ';i=6171',
   ConnectionPointType_Lock_BreakLock: 'nsu=' + NS + ';i=6173',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock: 'nsu=' + NS + ';i=6299',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RenewLock: 'nsu=' + NS + ';i=6302',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_ExitLock: 'nsu=' + NS + ';i=6304',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_BreakLock: 'nsu=' + NS + ';i=6306',
   TransferServicesType_TransferToDevice: 'nsu=' + NS + ';i=6527',
   TransferServicesType_TransferFromDevice: 'nsu=' + NS + ';i=6529',
   TransferServicesType_FetchTransferResultData: 'nsu=' + NS + ';i=6531',
   LockingServicesType_InitLock: 'nsu=' + NS + ';i=6393',
   LockingServicesType_RenewLock: 'nsu=' + NS + ';i=6396',
   LockingServicesType_ExitLock: 'nsu=' + NS + ';i=6398',
   LockingServicesType_BreakLock: 'nsu=' + NS + ';i=6400',
   SoftwareUpdateType_PrepareForUpdate_Prepare: 'nsu=' + NS + ';i=19',
   SoftwareUpdateType_PrepareForUpdate_Abort: 'nsu=' + NS + ';i=20',
   SoftwareUpdateType_Installation_Resume: 'nsu=' + NS + ';i=61',
   SoftwareUpdateType_Confirmation_Confirm: 'nsu=' + NS + ';i=112',
   SoftwareUpdateType_Parameters_GenerateFileForRead: 'nsu=' + NS + ';i=124',
   SoftwareUpdateType_Parameters_GenerateFileForWrite: 'nsu=' + NS + ';i=127',
   SoftwareUpdateType_Parameters_CloseAndCommit: 'nsu=' + NS + ';i=130',
   PackageLoadingType_FileTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=142',
   PackageLoadingType_FileTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=145',
   PackageLoadingType_FileTransfer_CloseAndCommit: 'nsu=' + NS + ';i=148',
   DirectLoadingType_FileTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=142',
   DirectLoadingType_FileTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=145',
   DirectLoadingType_FileTransfer_CloseAndCommit: 'nsu=' + NS + ';i=148',
   CachedLoadingType_FileTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=142',
   CachedLoadingType_FileTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=145',
   CachedLoadingType_FileTransfer_CloseAndCommit: 'nsu=' + NS + ';i=148',
   CachedLoadingType_GetUpdateBehavior: 'nsu=' + NS + ';i=189',
   FileSystemLoadingType_FileSystem_CreateDirectory: 'nsu=' + NS + ';i=195',
   FileSystemLoadingType_FileSystem_CreateFile: 'nsu=' + NS + ';i=198',
   FileSystemLoadingType_FileSystem_DeleteFileSystemObject: 'nsu=' + NS + ';i=201',
   FileSystemLoadingType_FileSystem_MoveOrCopy: 'nsu=' + NS + ';i=203',
   FileSystemLoadingType_GetUpdateBehavior: 'nsu=' + NS + ';i=206',
   FileSystemLoadingType_ValidateFiles: 'nsu=' + NS + ';i=209',
   PrepareForUpdateStateMachineType_Prepare: 'nsu=' + NS + ';i=228',
   PrepareForUpdateStateMachineType_Abort: 'nsu=' + NS + ';i=229',
   PrepareForUpdateStateMachineType_Resume: 'nsu=' + NS + ';i=230',
   InstallationStateMachineType_InstallSoftwarePackage: 'nsu=' + NS + ';i=265',
   InstallationStateMachineType_InstallFiles: 'nsu=' + NS + ';i=268',
   InstallationStateMachineType_Resume: 'nsu=' + NS + ';i=270',
   ConfirmationStateMachineType_Confirm: 'nsu=' + NS + ';i=321',
});

export const ObjectIds = Object.freeze({
   DeviceSet: 'nsu=' + NS + ';i=5001',
   DeviceFeatures: 'nsu=' + NS + ';i=15034',
   NetworkSet: 'nsu=' + NS + ';i=6078',
   DeviceTopology: 'nsu=' + NS + ';i=6094',
   TopologyElementType_ParameterSet: 'nsu=' + NS + ';i=5002',
   TopologyElementType_MethodSet: 'nsu=' + NS + ';i=5003',
   TopologyElementType_GroupIdentifier_Placeholder: 'nsu=' + NS + ';i=6567',
   TopologyElementType_Identification: 'nsu=' + NS + ';i=6014',
   TopologyElementType_Lock: 'nsu=' + NS + ';i=6161',
   IDeviceHealthType_DeviceHealthAlarms: 'nsu=' + NS + ';i=15053',
   ISupportInfoType_DeviceTypeImage: 'nsu=' + NS + ';i=15055',
   ISupportInfoType_Documentation: 'nsu=' + NS + ';i=15057',
   ISupportInfoType_DocumentationFiles: 'nsu=' + NS + ';i=27',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder: 'nsu=' + NS + ';i=28',
   ISupportInfoType_ProtocolSupport: 'nsu=' + NS + ';i=15059',
   ISupportInfoType_ImageSet: 'nsu=' + NS + ';i=15061',
   DeviceType_CPIdentifier_Placeholder: 'nsu=' + NS + ';i=6571',
   DeviceType_CPIdentifier_Placeholder_NetworkAddress: 'nsu=' + NS + ';i=6592',
   DeviceType_DeviceHealthAlarms: 'nsu=' + NS + ';i=15105',
   DeviceType_DeviceTypeImage: 'nsu=' + NS + ';i=6209',
   DeviceType_Documentation: 'nsu=' + NS + ';i=6211',
   DeviceType_ProtocolSupport: 'nsu=' + NS + ';i=6213',
   DeviceType_ImageSet: 'nsu=' + NS + ';i=6215',
   ConfigurableObjectType_SupportedTypes: 'nsu=' + NS + ';i=5004',
   ConfigurableObjectType_ObjectIdentifier_Placeholder: 'nsu=' + NS + ';i=6026',
   FunctionalGroupType_GroupIdentifier_Placeholder: 'nsu=' + NS + ';i=6027',
   NetworkType_ProfileIdentifier_Placeholder: 'nsu=' + NS + ';i=6596',
   NetworkType_CPIdentifier_Placeholder: 'nsu=' + NS + ';i=6248',
   NetworkType_CPIdentifier_Placeholder_NetworkAddress: 'nsu=' + NS + ';i=6292',
   NetworkType_Lock: 'nsu=' + NS + ';i=6294',
   ConnectionPointType_NetworkAddress: 'nsu=' + NS + ';i=6354',
   ConnectionPointType_ProfileIdentifier_Placeholder: 'nsu=' + NS + ';i=6499',
   ConnectionPointType_NetworkIdentifier_Placeholder: 'nsu=' + NS + ';i=6599',
   SoftwareUpdateType_Loading: 'nsu=' + NS + ';i=2',
   SoftwareUpdateType_PrepareForUpdate: 'nsu=' + NS + ';i=4',
   SoftwareUpdateType_Installation: 'nsu=' + NS + ';i=40',
   SoftwareUpdateType_PowerCycle: 'nsu=' + NS + ';i=76',
   SoftwareUpdateType_Confirmation: 'nsu=' + NS + ';i=98',
   SoftwareUpdateType_Parameters: 'nsu=' + NS + ';i=122',
   PackageLoadingType_CurrentVersion: 'nsu=' + NS + ';i=139',
   PackageLoadingType_FileTransfer: 'nsu=' + NS + ';i=140',
   CachedLoadingType_PendingVersion: 'nsu=' + NS + ';i=187',
   CachedLoadingType_FallbackVersion: 'nsu=' + NS + ';i=188',
   FileSystemLoadingType_FileSystem: 'nsu=' + NS + ';i=194',
   PrepareForUpdateStateMachineType_Idle: 'nsu=' + NS + ';i=231',
   PrepareForUpdateStateMachineType_Preparing: 'nsu=' + NS + ';i=233',
   PrepareForUpdateStateMachineType_PreparedForUpdate: 'nsu=' + NS + ';i=235',
   PrepareForUpdateStateMachineType_Resuming: 'nsu=' + NS + ';i=237',
   PrepareForUpdateStateMachineType_IdleToPreparing: 'nsu=' + NS + ';i=239',
   PrepareForUpdateStateMachineType_PreparingToIdle: 'nsu=' + NS + ';i=241',
   PrepareForUpdateStateMachineType_PreparingToPreparedForUpdate: 'nsu=' + NS + ';i=243',
   PrepareForUpdateStateMachineType_PreparedForUpdateToResuming: 'nsu=' + NS + ';i=245',
   PrepareForUpdateStateMachineType_ResumingToIdle: 'nsu=' + NS + ';i=247',
   InstallationStateMachineType_Idle: 'nsu=' + NS + ';i=271',
   InstallationStateMachineType_Installing: 'nsu=' + NS + ';i=273',
   InstallationStateMachineType_Error: 'nsu=' + NS + ';i=275',
   InstallationStateMachineType_IdleToInstalling: 'nsu=' + NS + ';i=277',
   InstallationStateMachineType_InstallingToIdle: 'nsu=' + NS + ';i=279',
   InstallationStateMachineType_InstallingToError: 'nsu=' + NS + ';i=281',
   InstallationStateMachineType_ErrorToIdle: 'nsu=' + NS + ';i=283',
   PowerCycleStateMachineType_NotWaitingForPowerCycle: 'nsu=' + NS + ';i=299',
   PowerCycleStateMachineType_WaitingForPowerCycle: 'nsu=' + NS + ';i=301',
   PowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle: 'nsu=' + NS + ';i=303',
   PowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle: 'nsu=' + NS + ';i=305',
   ConfirmationStateMachineType_NotWaitingForConfirm: 'nsu=' + NS + ';i=323',
   ConfirmationStateMachineType_WaitingForConfirm: 'nsu=' + NS + ';i=325',
   ConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm: 'nsu=' + NS + ';i=327',
   ConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm: 'nsu=' + NS + ';i=329',
   FetchResultDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=6551',
   TransferResultErrorDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=15891',
   TransferResultDataDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=15892',
   ParameterResultDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=6554',
   FetchResultDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=6535',
   TransferResultErrorDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=15900',
   TransferResultDataDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=15901',
   ParameterResultDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=6538',
   FetchResultDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=15909',
   TransferResultErrorDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=15910',
   TransferResultDataDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=15911',
   ParameterResultDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=15912',
});

export const ObjectTypeIds = Object.freeze({
   TopologyElementType: 'nsu=' + NS + ';i=1001',
   IVendorNameplateType: 'nsu=' + NS + ';i=15035',
   ITagNameplateType: 'nsu=' + NS + ';i=15048',
   IDeviceHealthType: 'nsu=' + NS + ';i=15051',
   ISupportInfoType: 'nsu=' + NS + ';i=15054',
   ComponentType: 'nsu=' + NS + ';i=15063',
   DeviceType: 'nsu=' + NS + ';i=1002',
   SoftwareType: 'nsu=' + NS + ';i=15106',
   BlockType: 'nsu=' + NS + ';i=1003',
   DeviceHealthDiagnosticAlarmType: 'nsu=' + NS + ';i=15143',
   FailureAlarmType: 'nsu=' + NS + ';i=15292',
   CheckFunctionAlarmType: 'nsu=' + NS + ';i=15441',
   OffSpecAlarmType: 'nsu=' + NS + ';i=15590',
   MaintenanceRequiredAlarmType: 'nsu=' + NS + ';i=15739',
   ConfigurableObjectType: 'nsu=' + NS + ';i=1004',
   BaseLifetimeIndicationType: 'nsu=' + NS + ';i=473',
   TimeIndicationType: 'nsu=' + NS + ';i=474',
   NumberOfPartsIndicationType: 'nsu=' + NS + ';i=475',
   NumberOfUsagesIndicationType: 'nsu=' + NS + ';i=476',
   LengthIndicationType: 'nsu=' + NS + ';i=477',
   DiameterIndicationType: 'nsu=' + NS + ';i=478',
   SubstanceVolumeIndicationType: 'nsu=' + NS + ';i=479',
   FunctionalGroupType: 'nsu=' + NS + ';i=1005',
   ProtocolType: 'nsu=' + NS + ';i=1006',
   IOperationCounterType: 'nsu=' + NS + ';i=480',
   NetworkType: 'nsu=' + NS + ';i=6247',
   ConnectionPointType: 'nsu=' + NS + ';i=6308',
   TransferServicesType: 'nsu=' + NS + ';i=6526',
   LockingServicesType: 'nsu=' + NS + ';i=6388',
   SoftwareUpdateType: 'nsu=' + NS + ';i=1',
   SoftwareLoadingType: 'nsu=' + NS + ';i=135',
   PackageLoadingType: 'nsu=' + NS + ';i=137',
   DirectLoadingType: 'nsu=' + NS + ';i=153',
   CachedLoadingType: 'nsu=' + NS + ';i=171',
   FileSystemLoadingType: 'nsu=' + NS + ';i=192',
   SoftwareVersionType: 'nsu=' + NS + ';i=212',
   PrepareForUpdateStateMachineType: 'nsu=' + NS + ';i=213',
   InstallationStateMachineType: 'nsu=' + NS + ';i=249',
   PowerCycleStateMachineType: 'nsu=' + NS + ';i=285',
   ConfirmationStateMachineType: 'nsu=' + NS + ';i=307',
});

export const ReferenceTypeIds = Object.freeze({
   ConnectsTo: 'nsu=' + NS + ';i=6030',
   ConnectsToParent: 'nsu=' + NS + ';i=6467',
   IsOnline: 'nsu=' + NS + ';i=6031',
});

export const VariableIds = Object.freeze({
   TopologyElementType_ParameterSet_ParameterIdentifier_Placeholder: 'nsu=' + NS + ';i=6017',
   TopologyElementType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   TopologyElementType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   TopologyElementType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   TopologyElementType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   TopologyElementType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   TopologyElementType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   TopologyElementType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   TopologyElementType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   TopologyElementType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   IVendorNameplateType_Manufacturer: 'nsu=' + NS + ';i=15036',
   IVendorNameplateType_ManufacturerUri: 'nsu=' + NS + ';i=15037',
   IVendorNameplateType_Model: 'nsu=' + NS + ';i=15038',
   IVendorNameplateType_HardwareRevision: 'nsu=' + NS + ';i=15039',
   IVendorNameplateType_SoftwareRevision: 'nsu=' + NS + ';i=15040',
   IVendorNameplateType_DeviceRevision: 'nsu=' + NS + ';i=15041',
   IVendorNameplateType_ProductCode: 'nsu=' + NS + ';i=15042',
   IVendorNameplateType_DeviceManual: 'nsu=' + NS + ';i=15043',
   IVendorNameplateType_DeviceClass: 'nsu=' + NS + ';i=15044',
   IVendorNameplateType_SerialNumber: 'nsu=' + NS + ';i=15045',
   IVendorNameplateType_ProductInstanceUri: 'nsu=' + NS + ';i=15046',
   IVendorNameplateType_RevisionCounter: 'nsu=' + NS + ';i=15047',
   IVendorNameplateType_SoftwareReleaseDate: 'nsu=' + NS + ';i=23',
   IVendorNameplateType_PatchIdentifiers: 'nsu=' + NS + ';i=24',
   ITagNameplateType_AssetId: 'nsu=' + NS + ';i=15049',
   ITagNameplateType_ComponentName: 'nsu=' + NS + ';i=15050',
   IDeviceHealthType_DeviceHealth: 'nsu=' + NS + ';i=15052',
   ISupportInfoType_DeviceTypeImage_ImageIdentifier_Placeholder: 'nsu=' + NS + ';i=15056',
   ISupportInfoType_Documentation_DocumentIdentifier_Placeholder: 'nsu=' + NS + ';i=15058',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Size: 'nsu=' + NS + ';i=29',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Writable: 'nsu=' + NS + ';i=30',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_UserWritable: 'nsu=' + NS + ';i=31',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_OpenCount: 'nsu=' + NS + ';i=32',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open_InputArguments: 'nsu=' + NS + ';i=37',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Open_OutputArguments: 'nsu=' + NS + ';i=38',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Close_InputArguments: 'nsu=' + NS + ';i=62',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read_InputArguments: 'nsu=' + NS + ';i=64',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Read_OutputArguments: 'nsu=' + NS + ';i=65',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_Write_InputArguments: 'nsu=' + NS + ';i=67',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition_InputArguments: 'nsu=' + NS + ';i=69',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_GetPosition_OutputArguments: 'nsu=' + NS + ';i=70',
   ISupportInfoType_DocumentationFiles_DocumentFileId_Placeholder_SetPosition_InputArguments: 'nsu=' + NS + ';i=72',
   ISupportInfoType_ProtocolSupport_ProtocolSupportIdentifier_Placeholder: 'nsu=' + NS + ';i=15060',
   ISupportInfoType_ImageSet_ImageIdentifier_Placeholder: 'nsu=' + NS + ';i=15062',
   ComponentType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   ComponentType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   ComponentType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   ComponentType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   ComponentType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   ComponentType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   ComponentType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   ComponentType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   ComponentType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   ComponentType_Manufacturer: 'nsu=' + NS + ';i=15086',
   ComponentType_ManufacturerUri: 'nsu=' + NS + ';i=15087',
   ComponentType_Model: 'nsu=' + NS + ';i=15088',
   ComponentType_HardwareRevision: 'nsu=' + NS + ';i=15089',
   ComponentType_SoftwareRevision: 'nsu=' + NS + ';i=15090',
   ComponentType_DeviceRevision: 'nsu=' + NS + ';i=15091',
   ComponentType_ProductCode: 'nsu=' + NS + ';i=15092',
   ComponentType_DeviceManual: 'nsu=' + NS + ';i=15093',
   ComponentType_DeviceClass: 'nsu=' + NS + ';i=15094',
   ComponentType_SerialNumber: 'nsu=' + NS + ';i=15095',
   ComponentType_ProductInstanceUri: 'nsu=' + NS + ';i=15096',
   ComponentType_RevisionCounter: 'nsu=' + NS + ';i=15097',
   ComponentType_AssetId: 'nsu=' + NS + ';i=15098',
   ComponentType_ComponentName: 'nsu=' + NS + ';i=15099',
   DeviceType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   DeviceType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   DeviceType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   DeviceType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   DeviceType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   DeviceType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   DeviceType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   DeviceType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   DeviceType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   DeviceType_Manufacturer: 'nsu=' + NS + ';i=6003',
   DeviceType_ManufacturerUri: 'nsu=' + NS + ';i=15100',
   DeviceType_Model: 'nsu=' + NS + ';i=6004',
   DeviceType_HardwareRevision: 'nsu=' + NS + ';i=6008',
   DeviceType_SoftwareRevision: 'nsu=' + NS + ';i=6007',
   DeviceType_DeviceRevision: 'nsu=' + NS + ';i=6006',
   DeviceType_ProductCode: 'nsu=' + NS + ';i=15101',
   DeviceType_DeviceManual: 'nsu=' + NS + ';i=6005',
   DeviceType_DeviceClass: 'nsu=' + NS + ';i=6470',
   DeviceType_SerialNumber: 'nsu=' + NS + ';i=6001',
   DeviceType_ProductInstanceUri: 'nsu=' + NS + ';i=15102',
   DeviceType_RevisionCounter: 'nsu=' + NS + ';i=6002',
   DeviceType_CPIdentifier_Placeholder_Lock_Locked: 'nsu=' + NS + ';i=6468',
   DeviceType_CPIdentifier_Placeholder_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   DeviceType_CPIdentifier_Placeholder_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   DeviceType_CPIdentifier_Placeholder_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   DeviceType_CPIdentifier_Placeholder_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   DeviceType_CPIdentifier_Placeholder_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   DeviceType_CPIdentifier_Placeholder_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   DeviceType_CPIdentifier_Placeholder_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   DeviceType_CPIdentifier_Placeholder_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   DeviceType_DeviceHealth: 'nsu=' + NS + ';i=6208',
   DeviceType_DeviceTypeImage_ImageIdentifier_Placeholder: 'nsu=' + NS + ';i=6210',
   DeviceType_Documentation_DocumentIdentifier_Placeholder: 'nsu=' + NS + ';i=6212',
   DeviceType_ProtocolSupport_ProtocolSupportIdentifier_Placeholder: 'nsu=' + NS + ';i=6214',
   DeviceType_ImageSet_ImageIdentifier_Placeholder: 'nsu=' + NS + ';i=6216',
   SoftwareType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   SoftwareType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   SoftwareType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   SoftwareType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   SoftwareType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   SoftwareType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   SoftwareType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   SoftwareType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   SoftwareType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   SoftwareType_Manufacturer: 'nsu=' + NS + ';i=15129',
   SoftwareType_Model: 'nsu=' + NS + ';i=15131',
   SoftwareType_SoftwareRevision: 'nsu=' + NS + ';i=15133',
   BlockType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   BlockType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   BlockType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   BlockType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   BlockType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   BlockType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   BlockType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   BlockType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   BlockType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   BlockType_RevisionCounter: 'nsu=' + NS + ';i=6009',
   BlockType_ActualMode: 'nsu=' + NS + ';i=6010',
   BlockType_PermittedMode: 'nsu=' + NS + ';i=6011',
   BlockType_NormalMode: 'nsu=' + NS + ';i=6012',
   BlockType_TargetMode: 'nsu=' + NS + ';i=6013',
   LifetimeVariableType_StartValue: 'nsu=' + NS + ';i=469',
   LifetimeVariableType_LimitValue: 'nsu=' + NS + ';i=470',
   LifetimeVariableType_Indication: 'nsu=' + NS + ';i=471',
   LifetimeVariableType_WarningValues: 'nsu=' + NS + ';i=472',
   FunctionalGroupType_GroupIdentifier_Placeholder_UIElement: 'nsu=' + NS + ';i=6242',
   FunctionalGroupType_UIElement: 'nsu=' + NS + ';i=6243',
   DeviceHealthEnumeration_EnumStrings: 'nsu=' + NS + ';i=6450',
   IOperationCounterType_PowerOnDuration: 'nsu=' + NS + ';i=481',
   IOperationCounterType_OperationDuration: 'nsu=' + NS + ';i=482',
   IOperationCounterType_OperationCycleCounter: 'nsu=' + NS + ';i=483',
   NetworkType_CPIdentifier_Placeholder_Lock_Locked: 'nsu=' + NS + ';i=6468',
   NetworkType_CPIdentifier_Placeholder_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   NetworkType_CPIdentifier_Placeholder_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   NetworkType_CPIdentifier_Placeholder_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   NetworkType_CPIdentifier_Placeholder_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   NetworkType_CPIdentifier_Placeholder_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   NetworkType_CPIdentifier_Placeholder_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   NetworkType_CPIdentifier_Placeholder_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   NetworkType_CPIdentifier_Placeholder_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   NetworkType_Lock_Locked: 'nsu=' + NS + ';i=6497',
   NetworkType_Lock_LockingClient: 'nsu=' + NS + ';i=6296',
   NetworkType_Lock_LockingUser: 'nsu=' + NS + ';i=6297',
   NetworkType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6298',
   NetworkType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6300',
   NetworkType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6301',
   NetworkType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6303',
   NetworkType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6305',
   NetworkType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6307',
   ConnectionPointType_Lock_Locked: 'nsu=' + NS + ';i=6468',
   ConnectionPointType_Lock_LockingClient: 'nsu=' + NS + ';i=6163',
   ConnectionPointType_Lock_LockingUser: 'nsu=' + NS + ';i=6164',
   ConnectionPointType_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6165',
   ConnectionPointType_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6167',
   ConnectionPointType_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6168',
   ConnectionPointType_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6170',
   ConnectionPointType_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6172',
   ConnectionPointType_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6174',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_Locked: 'nsu=' + NS + ';i=6497',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_LockingClient: 'nsu=' + NS + ';i=6296',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_LockingUser: 'nsu=' + NS + ';i=6297',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RemainingLockTime: 'nsu=' + NS + ';i=6298',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock_InputArguments: 'nsu=' + NS + ';i=6300',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_InitLock_OutputArguments: 'nsu=' + NS + ';i=6301',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6303',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6305',
   ConnectionPointType_NetworkIdentifier_Placeholder_Lock_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6307',
   TransferServicesType_TransferToDevice_OutputArguments: 'nsu=' + NS + ';i=6528',
   TransferServicesType_TransferFromDevice_OutputArguments: 'nsu=' + NS + ';i=6530',
   TransferServicesType_FetchTransferResultData_InputArguments: 'nsu=' + NS + ';i=6532',
   TransferServicesType_FetchTransferResultData_OutputArguments: 'nsu=' + NS + ';i=6533',
   LockingServicesType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=15890',
   LockingServicesType_Locked: 'nsu=' + NS + ';i=6534',
   LockingServicesType_LockingClient: 'nsu=' + NS + ';i=6390',
   LockingServicesType_LockingUser: 'nsu=' + NS + ';i=6391',
   LockingServicesType_RemainingLockTime: 'nsu=' + NS + ';i=6392',
   LockingServicesType_InitLock_InputArguments: 'nsu=' + NS + ';i=6394',
   LockingServicesType_InitLock_OutputArguments: 'nsu=' + NS + ';i=6395',
   LockingServicesType_RenewLock_OutputArguments: 'nsu=' + NS + ';i=6397',
   LockingServicesType_ExitLock_OutputArguments: 'nsu=' + NS + ';i=6399',
   LockingServicesType_BreakLock_OutputArguments: 'nsu=' + NS + ';i=6401',
   SoftwareUpdateType_PrepareForUpdate_CurrentState: 'nsu=' + NS + ';i=5',
   SoftwareUpdateType_PrepareForUpdate_CurrentState_Id: 'nsu=' + NS + ';i=6',
   SoftwareUpdateType_Installation_CurrentState: 'nsu=' + NS + ';i=41',
   SoftwareUpdateType_Installation_CurrentState_Id: 'nsu=' + NS + ';i=42',
   SoftwareUpdateType_Installation_InstallSoftwarePackage_InputArguments: 'nsu=' + NS + ';i=266',
   SoftwareUpdateType_Installation_InstallFiles_InputArguments: 'nsu=' + NS + ';i=269',
   SoftwareUpdateType_PowerCycle_CurrentState: 'nsu=' + NS + ';i=77',
   SoftwareUpdateType_PowerCycle_CurrentState_Id: 'nsu=' + NS + ';i=78',
   SoftwareUpdateType_Confirmation_CurrentState: 'nsu=' + NS + ';i=99',
   SoftwareUpdateType_Confirmation_CurrentState_Id: 'nsu=' + NS + ';i=100',
   SoftwareUpdateType_Confirmation_ConfirmationTimeout: 'nsu=' + NS + ';i=113',
   SoftwareUpdateType_Parameters_ClientProcessingTimeout: 'nsu=' + NS + ';i=123',
   SoftwareUpdateType_Parameters_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=125',
   SoftwareUpdateType_Parameters_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=126',
   SoftwareUpdateType_Parameters_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=128',
   SoftwareUpdateType_Parameters_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=129',
   SoftwareUpdateType_Parameters_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=131',
   SoftwareUpdateType_Parameters_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=132',
   SoftwareUpdateType_UpdateStatus: 'nsu=' + NS + ';i=133',
   SoftwareUpdateType_VendorErrorCode: 'nsu=' + NS + ';i=402',
   SoftwareUpdateType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=134',
   SoftwareLoadingType_UpdateKey: 'nsu=' + NS + ';i=136',
   PackageLoadingType_CurrentVersion_Manufacturer: 'nsu=' + NS + ';i=345',
   PackageLoadingType_CurrentVersion_ManufacturerUri: 'nsu=' + NS + ';i=346',
   PackageLoadingType_CurrentVersion_SoftwareRevision: 'nsu=' + NS + ';i=347',
   PackageLoadingType_FileTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=141',
   PackageLoadingType_FileTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=143',
   PackageLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=144',
   PackageLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=146',
   PackageLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=147',
   PackageLoadingType_FileTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=149',
   PackageLoadingType_FileTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=150',
   PackageLoadingType_ErrorMessage: 'nsu=' + NS + ';i=151',
   PackageLoadingType_WriteBlockSize: 'nsu=' + NS + ';i=152',
   DirectLoadingType_CurrentVersion_Manufacturer: 'nsu=' + NS + ';i=345',
   DirectLoadingType_CurrentVersion_ManufacturerUri: 'nsu=' + NS + ';i=346',
   DirectLoadingType_CurrentVersion_SoftwareRevision: 'nsu=' + NS + ';i=347',
   DirectLoadingType_FileTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=141',
   DirectLoadingType_FileTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=143',
   DirectLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=144',
   DirectLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=146',
   DirectLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=147',
   DirectLoadingType_FileTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=149',
   DirectLoadingType_FileTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=150',
   DirectLoadingType_UpdateBehavior: 'nsu=' + NS + ';i=169',
   DirectLoadingType_WriteTimeout: 'nsu=' + NS + ';i=170',
   CachedLoadingType_CurrentVersion_Manufacturer: 'nsu=' + NS + ';i=345',
   CachedLoadingType_CurrentVersion_ManufacturerUri: 'nsu=' + NS + ';i=346',
   CachedLoadingType_CurrentVersion_SoftwareRevision: 'nsu=' + NS + ';i=347',
   CachedLoadingType_FileTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=141',
   CachedLoadingType_FileTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=143',
   CachedLoadingType_FileTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=144',
   CachedLoadingType_FileTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=146',
   CachedLoadingType_FileTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=147',
   CachedLoadingType_FileTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=149',
   CachedLoadingType_FileTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=150',
   CachedLoadingType_PendingVersion_Manufacturer: 'nsu=' + NS + ';i=366',
   CachedLoadingType_PendingVersion_ManufacturerUri: 'nsu=' + NS + ';i=367',
   CachedLoadingType_PendingVersion_SoftwareRevision: 'nsu=' + NS + ';i=368',
   CachedLoadingType_FallbackVersion_Manufacturer: 'nsu=' + NS + ';i=373',
   CachedLoadingType_FallbackVersion_ManufacturerUri: 'nsu=' + NS + ';i=374',
   CachedLoadingType_FallbackVersion_SoftwareRevision: 'nsu=' + NS + ';i=375',
   CachedLoadingType_GetUpdateBehavior_InputArguments: 'nsu=' + NS + ';i=190',
   CachedLoadingType_GetUpdateBehavior_OutputArguments: 'nsu=' + NS + ';i=191',
   FileSystemLoadingType_FileSystem_CreateDirectory_InputArguments: 'nsu=' + NS + ';i=196',
   FileSystemLoadingType_FileSystem_CreateDirectory_OutputArguments: 'nsu=' + NS + ';i=197',
   FileSystemLoadingType_FileSystem_CreateFile_InputArguments: 'nsu=' + NS + ';i=199',
   FileSystemLoadingType_FileSystem_CreateFile_OutputArguments: 'nsu=' + NS + ';i=200',
   FileSystemLoadingType_FileSystem_DeleteFileSystemObject_InputArguments: 'nsu=' + NS + ';i=202',
   FileSystemLoadingType_FileSystem_MoveOrCopy_InputArguments: 'nsu=' + NS + ';i=204',
   FileSystemLoadingType_FileSystem_MoveOrCopy_OutputArguments: 'nsu=' + NS + ';i=205',
   FileSystemLoadingType_GetUpdateBehavior_InputArguments: 'nsu=' + NS + ';i=207',
   FileSystemLoadingType_GetUpdateBehavior_OutputArguments: 'nsu=' + NS + ';i=208',
   FileSystemLoadingType_ValidateFiles_InputArguments: 'nsu=' + NS + ';i=210',
   FileSystemLoadingType_ValidateFiles_OutputArguments: 'nsu=' + NS + ';i=211',
   SoftwareVersionType_Manufacturer: 'nsu=' + NS + ';i=380',
   SoftwareVersionType_ManufacturerUri: 'nsu=' + NS + ';i=381',
   SoftwareVersionType_SoftwareRevision: 'nsu=' + NS + ';i=382',
   SoftwareVersionType_PatchIdentifiers: 'nsu=' + NS + ';i=383',
   SoftwareVersionType_ReleaseDate: 'nsu=' + NS + ';i=384',
   SoftwareVersionType_ChangeLogReference: 'nsu=' + NS + ';i=385',
   SoftwareVersionType_Hash: 'nsu=' + NS + ';i=386',
   PrepareForUpdateStateMachineType_PercentComplete: 'nsu=' + NS + ';i=227',
   PrepareForUpdateStateMachineType_Idle_StateNumber: 'nsu=' + NS + ';i=232',
   PrepareForUpdateStateMachineType_Preparing_StateNumber: 'nsu=' + NS + ';i=234',
   PrepareForUpdateStateMachineType_PreparedForUpdate_StateNumber: 'nsu=' + NS + ';i=236',
   PrepareForUpdateStateMachineType_Resuming_StateNumber: 'nsu=' + NS + ';i=238',
   PrepareForUpdateStateMachineType_IdleToPreparing_TransitionNumber: 'nsu=' + NS + ';i=240',
   PrepareForUpdateStateMachineType_PreparingToIdle_TransitionNumber: 'nsu=' + NS + ';i=242',
   PrepareForUpdateStateMachineType_PreparingToPreparedForUpdate_TransitionNumber: 'nsu=' + NS + ';i=244',
   PrepareForUpdateStateMachineType_PreparedForUpdateToResuming_TransitionNumber: 'nsu=' + NS + ';i=246',
   PrepareForUpdateStateMachineType_ResumingToIdle_TransitionNumber: 'nsu=' + NS + ';i=248',
   InstallationStateMachineType_PercentComplete: 'nsu=' + NS + ';i=263',
   InstallationStateMachineType_InstallationDelay: 'nsu=' + NS + ';i=264',
   InstallationStateMachineType_InstallSoftwarePackage_InputArguments: 'nsu=' + NS + ';i=266',
   InstallationStateMachineType_InstallFiles_InputArguments: 'nsu=' + NS + ';i=269',
   InstallationStateMachineType_Idle_StateNumber: 'nsu=' + NS + ';i=272',
   InstallationStateMachineType_Installing_StateNumber: 'nsu=' + NS + ';i=274',
   InstallationStateMachineType_Error_StateNumber: 'nsu=' + NS + ';i=276',
   InstallationStateMachineType_IdleToInstalling_TransitionNumber: 'nsu=' + NS + ';i=387',
   InstallationStateMachineType_InstallingToIdle_TransitionNumber: 'nsu=' + NS + ';i=280',
   InstallationStateMachineType_InstallingToError_TransitionNumber: 'nsu=' + NS + ';i=282',
   InstallationStateMachineType_ErrorToIdle_TransitionNumber: 'nsu=' + NS + ';i=284',
   PowerCycleStateMachineType_NotWaitingForPowerCycle_StateNumber: 'nsu=' + NS + ';i=300',
   PowerCycleStateMachineType_WaitingForPowerCycle_StateNumber: 'nsu=' + NS + ';i=302',
   PowerCycleStateMachineType_NotWaitingForPowerCycleToWaitingForPowerCycle_TransitionNumber: 'nsu=' + NS + ';i=304',
   PowerCycleStateMachineType_WaitingForPowerCycleToNotWaitingForPowerCycle_TransitionNumber: 'nsu=' + NS + ';i=306',
   ConfirmationStateMachineType_ConfirmationTimeout: 'nsu=' + NS + ';i=322',
   ConfirmationStateMachineType_NotWaitingForConfirm_StateNumber: 'nsu=' + NS + ';i=324',
   ConfirmationStateMachineType_WaitingForConfirm_StateNumber: 'nsu=' + NS + ';i=326',
   ConfirmationStateMachineType_NotWaitingForConfirmToWaitingForConfirm_TransitionNumber: 'nsu=' + NS + ';i=328',
   ConfirmationStateMachineType_WaitingForConfirmToNotWaitingForConfirm_TransitionNumber: 'nsu=' + NS + ';i=330',
   SoftwareVersionFileType_EnumStrings: 'nsu=' + NS + ';i=332',
   UpdateBehavior_OptionSetValues: 'nsu=' + NS + ';i=388',
});

export const VariableTypeIds = Object.freeze({
   LifetimeVariableType: 'nsu=' + NS + ';i=468',
   UIElementType: 'nsu=' + NS + ';i=6246',
});
