export const NS = 'http://opcfoundation.org/UA/AMB/';

export class BrowseNames {
   static readonly AddLink: string = 'AddLink'
   static readonly Assets: string = 'Assets'
   static readonly AssetsByAssetId: string = 'AssetsByAssetId'
   static readonly AssetsByProductInstanceUri: string = 'AssetsByProductInstanceUri'
   static readonly BadConfigurationConditionClassType: string = 'BadConfigurationConditionClassType'
   static readonly CalibrationDueConditionClassType: string = 'CalibrationDueConditionClassType'
   static readonly ConfigurationChanged: string = 'ConfigurationChanged'
   static readonly ConnectionFailureConditionClassType: string = 'ConnectionFailureConditionClassType'
   static readonly Contains: string = 'Contains'
   static readonly DocumentationLinks: string = 'DocumentationLinks'
   static readonly DocumentationLinksType: string = 'DocumentationLinksType'
   static readonly EstimatedDowntime: string = 'EstimatedDowntime'
   static readonly Executing: string = 'Executing'
   static readonly ExternalCheckConditionClassType: string = 'ExternalCheckConditionClassType'
   static readonly Finished: string = 'Finished'
   static readonly FlashUpdateFailedConditionClassType: string = 'FlashUpdateFailedConditionClassType'
   static readonly FlashUpdateInProgressConditionClassType: string = 'FlashUpdateInProgressConditionClassType'
   static readonly FromExecutingToFinished: string = 'FromExecutingToFinished'
   static readonly FromFinishedToPlanned: string = 'FromFinishedToPlanned'
   static readonly FromPlannedToExecuting: string = 'FromPlannedToExecuting'
   static readonly HierarchicalContains: string = 'HierarchicalContains'
   static readonly HierarchicalLocations: string = 'HierarchicalLocations'
   static readonly IMaintenanceEventType: string = 'IMaintenanceEventType'
   static readonly ImprovementConditionClassType: string = 'ImprovementConditionClassType'
   static readonly InspectionConditionClassType: string = 'InspectionConditionClassType'
   static readonly IRootCauseIndicationType: string = 'IRootCauseIndicationType'
   static readonly Link_Placeholder: string = '<Link>'
   static readonly MaintenanceEventStateMachineType: string = 'MaintenanceEventStateMachineType'
   static readonly MaintenanceMethod: string = 'MaintenanceMethod'
   static readonly MaintenanceMethodEnum: string = 'MaintenanceMethodEnum'
   static readonly MaintenanceState: string = 'MaintenanceState'
   static readonly MaintenanceSupplier: string = 'MaintenanceSupplier'
   static readonly NameNodeIdDataType: string = 'NameNodeIdDataType'
   static readonly OperationalContains: string = 'OperationalContains'
   static readonly OperationalLocations: string = 'OperationalLocations'
   static readonly OutOfMemoryConditionClassType: string = 'OutOfMemoryConditionClassType'
   static readonly OutOfResourcesConditionClassType: string = 'OutOfResourcesConditionClassType'
   static readonly OverTemperatureConditionClassType: string = 'OverTemperatureConditionClassType'
   static readonly PartsOfAssetReplaced: string = 'PartsOfAssetReplaced'
   static readonly PartsOfAssetServiced: string = 'PartsOfAssetServiced'
   static readonly Planned: string = 'Planned'
   static readonly PlannedDate: string = 'PlannedDate'
   static readonly PotentialRootCauses: string = 'PotentialRootCauses'
   static readonly QualificationOfPersonnel: string = 'QualificationOfPersonnel'
   static readonly RemoveLink: string = 'RemoveLink'
   static readonly RepairConditionClassType: string = 'RepairConditionClassType'
   static readonly RootCauseDataType: string = 'RootCauseDataType'
   static readonly SelfTestFailureConditionClassType: string = 'SelfTestFailureConditionClassType'
   static readonly ServicingConditionClassType: string = 'ServicingConditionClassType'
}

export class DataTypeIds {
    static readonly MaintenanceMethodEnum: string = 'nsu=' + NS + ';i=3004'
    static readonly NameNodeIdDataType: string = 'nsu=' + NS + ';i=3003'
    static readonly RootCauseDataType: string = 'nsu=' + NS + ';i=3002'
}

export class MethodIds {
    static readonly DocumentationLinksType_AddLink: string = 'nsu=' + NS + ';i=7004'
    static readonly DocumentationLinksType_RemoveLink: string = 'nsu=' + NS + ';i=7005'
    static readonly Assets_FindAlias: string = 'nsu=' + NS + ';i=7001'
    static readonly AssetsByAssetId_FindAlias: string = 'nsu=' + NS + ';i=7003'
    static readonly AssetsByProductInstanceUri_FindAlias: string = 'nsu=' + NS + ';i=7002'
}

export class ObjectIds {
    static readonly IMaintenanceEventType_MaintenanceState: string = 'nsu=' + NS + ';i=5014'
    static readonly MaintenanceEventStateMachineType_Executing: string = 'nsu=' + NS + ';i=5007'
    static readonly MaintenanceEventStateMachineType_Finished: string = 'nsu=' + NS + ';i=5008'
    static readonly MaintenanceEventStateMachineType_FromExecutingToFinished: string = 'nsu=' + NS + ';i=5010'
    static readonly MaintenanceEventStateMachineType_FromFinishedToPlanned: string = 'nsu=' + NS + ';i=5011'
    static readonly MaintenanceEventStateMachineType_FromPlannedToExecuting: string = 'nsu=' + NS + ';i=5009'
    static readonly MaintenanceEventStateMachineType_Planned: string = 'nsu=' + NS + ';i=5006'
    static readonly Assets: string = 'nsu=' + NS + ';i=5002'
    static readonly AssetsByAssetId: string = 'nsu=' + NS + ';i=5004'
    static readonly AssetsByProductInstanceUri: string = 'nsu=' + NS + ';i=5003'
    static readonly HierarchicalLocations: string = 'nsu=' + NS + ';i=5021'
    static readonly OperationalLocations: string = 'nsu=' + NS + ';i=5022'
    static readonly RootCauseDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5001'
    static readonly RootCauseDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5005'
    static readonly NameNodeIdDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5012'
    static readonly NameNodeIdDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5013'
}

export class ObjectTypeIds {
    static readonly CalibrationDueConditionClassType: string = 'nsu=' + NS + ';i=1005'
    static readonly ExternalCheckConditionClassType: string = 'nsu=' + NS + ';i=1015'
    static readonly FlashUpdateInProgressConditionClassType: string = 'nsu=' + NS + ';i=1007'
    static readonly ImprovementConditionClassType: string = 'nsu=' + NS + ';i=1018'
    static readonly InspectionConditionClassType: string = 'nsu=' + NS + ';i=1014'
    static readonly RepairConditionClassType: string = 'nsu=' + NS + ';i=1017'
    static readonly ServicingConditionClassType: string = 'nsu=' + NS + ';i=1016'
    static readonly BadConfigurationConditionClassType: string = 'nsu=' + NS + ';i=1008'
    static readonly ConnectionFailureConditionClassType: string = 'nsu=' + NS + ';i=1003'
    static readonly FlashUpdateFailedConditionClassType: string = 'nsu=' + NS + ';i=1019'
    static readonly OutOfResourcesConditionClassType: string = 'nsu=' + NS + ';i=1009'
    static readonly OutOfMemoryConditionClassType: string = 'nsu=' + NS + ';i=1010'
    static readonly OverTemperatureConditionClassType: string = 'nsu=' + NS + ';i=1004'
    static readonly SelfTestFailureConditionClassType: string = 'nsu=' + NS + ';i=1006'
    static readonly IMaintenanceEventType: string = 'nsu=' + NS + ';i=1012'
    static readonly IRootCauseIndicationType: string = 'nsu=' + NS + ';i=1002'
    static readonly DocumentationLinksType: string = 'nsu=' + NS + ';i=1011'
    static readonly MaintenanceEventStateMachineType: string = 'nsu=' + NS + ';i=1013'
}

export class ReferenceTypeIds {
    static readonly Contains: string = 'nsu=' + NS + ';i=4002'
    static readonly HierarchicalContains: string = 'nsu=' + NS + ';i=4003'
    static readonly OperationalContains: string = 'nsu=' + NS + ';i=4004'
}

export class VariableIds {
    static readonly MaintenanceMethodEnum_EnumValues: string = 'nsu=' + NS + ';i=6029'
    static readonly IMaintenanceEventType_ConfigurationChanged: string = 'nsu=' + NS + ';i=6042'
    static readonly IMaintenanceEventType_EstimatedDowntime: string = 'nsu=' + NS + ';i=6036'
    static readonly IMaintenanceEventType_MaintenanceMethod: string = 'nsu=' + NS + ';i=6041'
    static readonly IMaintenanceEventType_MaintenanceState_CurrentState: string = 'nsu=' + NS + ';i=6033'
    static readonly IMaintenanceEventType_MaintenanceState_CurrentState_Id: string = 'nsu=' + NS + ';i=6034'
    static readonly IMaintenanceEventType_MaintenanceSupplier: string = 'nsu=' + NS + ';i=6037'
    static readonly IMaintenanceEventType_PartsOfAssetReplaced: string = 'nsu=' + NS + ';i=6039'
    static readonly IMaintenanceEventType_PartsOfAssetServiced: string = 'nsu=' + NS + ';i=6040'
    static readonly IMaintenanceEventType_PlannedDate: string = 'nsu=' + NS + ';i=6035'
    static readonly IMaintenanceEventType_QualificationOfPersonnel: string = 'nsu=' + NS + ';i=6038'
    static readonly IRootCauseIndicationType_PotentialRootCauses: string = 'nsu=' + NS + ';i=6015'
    static readonly DocumentationLinksType_Link_Placeholder: string = 'nsu=' + NS + ';i=6017'
    static readonly DocumentationLinksType_AddLink_InputArguments: string = 'nsu=' + NS + ';i=6018'
    static readonly DocumentationLinksType_AddLink_OutputArguments: string = 'nsu=' + NS + ';i=6019'
    static readonly DocumentationLinksType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6016'
    static readonly DocumentationLinksType_RemoveLink_InputArguments: string = 'nsu=' + NS + ';i=6020'
    static readonly MaintenanceEventStateMachineType_Executing_StateNumber: string = 'nsu=' + NS + ';i=6022'
    static readonly MaintenanceEventStateMachineType_Finished_StateNumber: string = 'nsu=' + NS + ';i=6023'
    static readonly MaintenanceEventStateMachineType_FromExecutingToFinished_TransitionNumber: string = 'nsu=' + NS + ';i=6025'
    static readonly MaintenanceEventStateMachineType_FromFinishedToPlanned_TransitionNumber: string = 'nsu=' + NS + ';i=6026'
    static readonly MaintenanceEventStateMachineType_FromPlannedToExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6024'
    static readonly MaintenanceEventStateMachineType_Planned_StateNumber: string = 'nsu=' + NS + ';i=6021'
    static readonly Assets_FindAlias_InputArguments: string = 'nsu=' + NS + ';i=6001'
    static readonly Assets_FindAlias_OutputArguments: string = 'nsu=' + NS + ';i=6002'
    static readonly AssetsByAssetId_FindAlias_InputArguments: string = 'nsu=' + NS + ';i=6006'
    static readonly AssetsByAssetId_FindAlias_OutputArguments: string = 'nsu=' + NS + ';i=6007'
    static readonly AssetsByProductInstanceUri_FindAlias_InputArguments: string = 'nsu=' + NS + ';i=6003'
    static readonly AssetsByProductInstanceUri_FindAlias_OutputArguments: string = 'nsu=' + NS + ';i=6004'
}
