export const NS = 'http://opcfoundation.org/UA/AMB/';

export const BrowseNames = Object.freeze({
   AddLink: 'AddLink',
   Assets: 'Assets',
   AssetsByAssetId: 'AssetsByAssetId',
   AssetsByProductInstanceUri: 'AssetsByProductInstanceUri',
   BadConfigurationConditionClassType: 'BadConfigurationConditionClassType',
   CalibrationDueConditionClassType: 'CalibrationDueConditionClassType',
   ConfigurationChanged: 'ConfigurationChanged',
   ConnectionFailureConditionClassType: 'ConnectionFailureConditionClassType',
   Contains: 'Contains',
   DocumentationLinks: 'DocumentationLinks',
   DocumentationLinksType: 'DocumentationLinksType',
   EstimatedDowntime: 'EstimatedDowntime',
   Executing: 'Executing',
   ExternalCheckConditionClassType: 'ExternalCheckConditionClassType',
   Finished: 'Finished',
   FlashUpdateFailedConditionClassType: 'FlashUpdateFailedConditionClassType',
   FlashUpdateInProgressConditionClassType: 'FlashUpdateInProgressConditionClassType',
   FromExecutingToFinished: 'FromExecutingToFinished',
   FromFinishedToPlanned: 'FromFinishedToPlanned',
   FromPlannedToExecuting: 'FromPlannedToExecuting',
   HierarchicalContains: 'HierarchicalContains',
   HierarchicalLocations: 'HierarchicalLocations',
   IMaintenanceEventType: 'IMaintenanceEventType',
   ImprovementConditionClassType: 'ImprovementConditionClassType',
   InspectionConditionClassType: 'InspectionConditionClassType',
   IRootCauseIndicationType: 'IRootCauseIndicationType',
   Link_Placeholder: '<Link>',
   MaintenanceEventStateMachineType: 'MaintenanceEventStateMachineType',
   MaintenanceMethod: 'MaintenanceMethod',
   MaintenanceMethodEnum: 'MaintenanceMethodEnum',
   MaintenanceState: 'MaintenanceState',
   MaintenanceSupplier: 'MaintenanceSupplier',
   NameNodeIdDataType: 'NameNodeIdDataType',
   OperationalContains: 'OperationalContains',
   OperationalLocations: 'OperationalLocations',
   OutOfMemoryConditionClassType: 'OutOfMemoryConditionClassType',
   OutOfResourcesConditionClassType: 'OutOfResourcesConditionClassType',
   OverTemperatureConditionClassType: 'OverTemperatureConditionClassType',
   PartsOfAssetReplaced: 'PartsOfAssetReplaced',
   PartsOfAssetServiced: 'PartsOfAssetServiced',
   Planned: 'Planned',
   PlannedDate: 'PlannedDate',
   PotentialRootCauses: 'PotentialRootCauses',
   QualificationOfPersonnel: 'QualificationOfPersonnel',
   RemoveLink: 'RemoveLink',
   RepairConditionClassType: 'RepairConditionClassType',
   RootCauseDataType: 'RootCauseDataType',
   SelfTestFailureConditionClassType: 'SelfTestFailureConditionClassType',
   ServicingConditionClassType: 'ServicingConditionClassType',
});

export const DataTypeIds = Object.freeze({
   MaintenanceMethodEnum: 'nsu=' + NS + ';i=3004',
   NameNodeIdDataType: 'nsu=' + NS + ';i=3003',
   RootCauseDataType: 'nsu=' + NS + ';i=3002',
});

export const MethodIds = Object.freeze({
   DocumentationLinksType_AddLink: 'nsu=' + NS + ';i=7004',
   DocumentationLinksType_RemoveLink: 'nsu=' + NS + ';i=7005',
   Assets_FindAlias: 'nsu=' + NS + ';i=7001',
   AssetsByAssetId_FindAlias: 'nsu=' + NS + ';i=7003',
   AssetsByProductInstanceUri_FindAlias: 'nsu=' + NS + ';i=7002',
});

export const ObjectIds = Object.freeze({
   IMaintenanceEventType_MaintenanceState: 'nsu=' + NS + ';i=5014',
   MaintenanceEventStateMachineType_Executing: 'nsu=' + NS + ';i=5007',
   MaintenanceEventStateMachineType_Finished: 'nsu=' + NS + ';i=5008',
   MaintenanceEventStateMachineType_FromExecutingToFinished: 'nsu=' + NS + ';i=5010',
   MaintenanceEventStateMachineType_FromFinishedToPlanned: 'nsu=' + NS + ';i=5011',
   MaintenanceEventStateMachineType_FromPlannedToExecuting: 'nsu=' + NS + ';i=5009',
   MaintenanceEventStateMachineType_Planned: 'nsu=' + NS + ';i=5006',
   Assets: 'nsu=' + NS + ';i=5002',
   AssetsByAssetId: 'nsu=' + NS + ';i=5004',
   AssetsByProductInstanceUri: 'nsu=' + NS + ';i=5003',
   HierarchicalLocations: 'nsu=' + NS + ';i=5021',
   OperationalLocations: 'nsu=' + NS + ';i=5022',
   RootCauseDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5001',
   RootCauseDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5005',
   NameNodeIdDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5012',
   NameNodeIdDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5013',
});

export const ObjectTypeIds = Object.freeze({
   CalibrationDueConditionClassType: 'nsu=' + NS + ';i=1005',
   ExternalCheckConditionClassType: 'nsu=' + NS + ';i=1015',
   FlashUpdateInProgressConditionClassType: 'nsu=' + NS + ';i=1007',
   ImprovementConditionClassType: 'nsu=' + NS + ';i=1018',
   InspectionConditionClassType: 'nsu=' + NS + ';i=1014',
   RepairConditionClassType: 'nsu=' + NS + ';i=1017',
   ServicingConditionClassType: 'nsu=' + NS + ';i=1016',
   BadConfigurationConditionClassType: 'nsu=' + NS + ';i=1008',
   ConnectionFailureConditionClassType: 'nsu=' + NS + ';i=1003',
   FlashUpdateFailedConditionClassType: 'nsu=' + NS + ';i=1019',
   OutOfResourcesConditionClassType: 'nsu=' + NS + ';i=1009',
   OutOfMemoryConditionClassType: 'nsu=' + NS + ';i=1010',
   OverTemperatureConditionClassType: 'nsu=' + NS + ';i=1004',
   SelfTestFailureConditionClassType: 'nsu=' + NS + ';i=1006',
   IMaintenanceEventType: 'nsu=' + NS + ';i=1012',
   IRootCauseIndicationType: 'nsu=' + NS + ';i=1002',
   DocumentationLinksType: 'nsu=' + NS + ';i=1011',
   MaintenanceEventStateMachineType: 'nsu=' + NS + ';i=1013',
});

export const ReferenceTypeIds = Object.freeze({
   Contains: 'nsu=' + NS + ';i=4002',
   HierarchicalContains: 'nsu=' + NS + ';i=4003',
   OperationalContains: 'nsu=' + NS + ';i=4004',
});

export const VariableIds = Object.freeze({
   MaintenanceMethodEnum_EnumValues: 'nsu=' + NS + ';i=6029',
   IMaintenanceEventType_ConfigurationChanged: 'nsu=' + NS + ';i=6042',
   IMaintenanceEventType_EstimatedDowntime: 'nsu=' + NS + ';i=6036',
   IMaintenanceEventType_MaintenanceMethod: 'nsu=' + NS + ';i=6041',
   IMaintenanceEventType_MaintenanceState_CurrentState: 'nsu=' + NS + ';i=6033',
   IMaintenanceEventType_MaintenanceState_CurrentState_Id: 'nsu=' + NS + ';i=6034',
   IMaintenanceEventType_MaintenanceSupplier: 'nsu=' + NS + ';i=6037',
   IMaintenanceEventType_PartsOfAssetReplaced: 'nsu=' + NS + ';i=6039',
   IMaintenanceEventType_PartsOfAssetServiced: 'nsu=' + NS + ';i=6040',
   IMaintenanceEventType_PlannedDate: 'nsu=' + NS + ';i=6035',
   IMaintenanceEventType_QualificationOfPersonnel: 'nsu=' + NS + ';i=6038',
   IRootCauseIndicationType_PotentialRootCauses: 'nsu=' + NS + ';i=6015',
   DocumentationLinksType_Link_Placeholder: 'nsu=' + NS + ';i=6017',
   DocumentationLinksType_AddLink_InputArguments: 'nsu=' + NS + ';i=6018',
   DocumentationLinksType_AddLink_OutputArguments: 'nsu=' + NS + ';i=6019',
   DocumentationLinksType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6016',
   DocumentationLinksType_RemoveLink_InputArguments: 'nsu=' + NS + ';i=6020',
   MaintenanceEventStateMachineType_Executing_StateNumber: 'nsu=' + NS + ';i=6022',
   MaintenanceEventStateMachineType_Finished_StateNumber: 'nsu=' + NS + ';i=6023',
   MaintenanceEventStateMachineType_FromExecutingToFinished_TransitionNumber: 'nsu=' + NS + ';i=6025',
   MaintenanceEventStateMachineType_FromFinishedToPlanned_TransitionNumber: 'nsu=' + NS + ';i=6026',
   MaintenanceEventStateMachineType_FromPlannedToExecuting_TransitionNumber: 'nsu=' + NS + ';i=6024',
   MaintenanceEventStateMachineType_Planned_StateNumber: 'nsu=' + NS + ';i=6021',
   Assets_FindAlias_InputArguments: 'nsu=' + NS + ';i=6001',
   Assets_FindAlias_OutputArguments: 'nsu=' + NS + ';i=6002',
   AssetsByAssetId_FindAlias_InputArguments: 'nsu=' + NS + ';i=6006',
   AssetsByAssetId_FindAlias_OutputArguments: 'nsu=' + NS + ';i=6007',
   AssetsByProductInstanceUri_FindAlias_InputArguments: 'nsu=' + NS + ';i=6003',
   AssetsByProductInstanceUri_FindAlias_OutputArguments: 'nsu=' + NS + ';i=6004',
});
