export const NS = 'http://opcfoundation.org/UA/IA/';

export class BrowseNames {
   static readonly AcousticSignals: string = 'AcousticSignals'
   static readonly AcousticSignalType: string = 'AcousticSignalType'
   static readonly AudioSample: string = 'AudioSample'
   static readonly BaseCalibrationTargetCategoryType: string = 'BaseCalibrationTargetCategoryType'
   static readonly BasicStacklightType: string = 'BasicStacklightType'
   static readonly CalibrationTargetCategory: string = 'CalibrationTargetCategory'
   static readonly CalibrationTargetFeatures: string = 'CalibrationTargetFeatures'
   static readonly CalibrationTargetType: string = 'CalibrationTargetType'
   static readonly CalibrationValue_Placeholder: string = '<CalibrationValue>'
   static readonly CalibrationValueType: string = 'CalibrationValueType'
   static readonly CapacityRange_Placeholder: string = '<CapacityRange>'
   static readonly CapacityRangeType: string = 'CapacityRangeType'
   static readonly CertificateUri: string = 'CertificateUri'
   static readonly ChannelColor: string = 'ChannelColor'
   static readonly ControlChannel_Placeholder: string = '<ControlChannel>'
   static readonly ControlChannelType: string = 'ControlChannelType'
   static readonly DisplayMode: string = 'DisplayMode'
   static readonly DynamicCalibrationTargetCategoryType: string = 'DynamicCalibrationTargetCategoryType'
   static readonly HasReferenceMeasurementInstrument: string = 'HasReferenceMeasurementInstrument'
   static readonly HasStatisticComponent: string = 'HasStatisticComponent'
   static readonly IAggregateStatisticsType: string = 'IAggregateStatisticsType'
   static readonly Intensity: string = 'Intensity'
   static readonly IRollingStatisticsType: string = 'IRollingStatisticsType'
   static readonly IsPartOfBase: string = 'IsPartOfBase'
   static readonly IStatisticsType: string = 'IStatisticsType'
   static readonly LastValidationDate: string = 'LastValidationDate'
   static readonly LevelDisplayMode: string = 'LevelDisplayMode'
   static readonly LevelPercent: string = 'LevelPercent'
   static readonly NextValidationDate: string = 'NextValidationDate'
   static readonly OneTimeCalibrationTargetCategoryType: string = 'OneTimeCalibrationTargetCategoryType'
   static readonly OperationalConditions: string = 'OperationalConditions'
   static readonly OperationMode: string = 'OperationMode'
   static readonly Quality: string = 'Quality'
   static readonly ResetCondition: string = 'ResetCondition'
   static readonly ResetStatistics: string = 'ResetStatistics'
   static readonly Resolution: string = 'Resolution'
   static readonly ReusableCalibrationTargetCategoryType: string = 'ReusableCalibrationTargetCategoryType'
   static readonly ReusableDeviceCalibrationTargetCategoryType: string = 'ReusableDeviceCalibrationTargetCategoryType'
   static readonly RGBWDataType: string = 'RGBWDataType'
   static readonly SignalColor: string = 'SignalColor'
   static readonly SignalMode: string = 'SignalMode'
   static readonly SignalModeLight: string = 'SignalModeLight'
   static readonly SignalOn: string = 'SignalOn'
   static readonly SignalRGBWValue: string = 'SignalRGBWValue'
   static readonly StackElementAcousticType: string = 'StackElementAcousticType'
   static readonly StackElementLightType: string = 'StackElementLightType'
   static readonly StackElementType: string = 'StackElementType'
   static readonly StackLevel: string = 'StackLevel'
   static readonly StackLevelType: string = 'StackLevelType'
   static readonly StacklightMode: string = 'StacklightMode'
   static readonly StacklightOperationMode: string = 'StacklightOperationMode'
   static readonly StacklightType: string = 'StacklightType'
   static readonly StackRunning: string = 'StackRunning'
   static readonly StackRunningType: string = 'StackRunningType'
   static readonly StartTime: string = 'StartTime'
   static readonly WindowDuration: string = 'WindowDuration'
   static readonly WindowNumberOfValues: string = 'WindowNumberOfValues'
}

export class DataTypeIds {
    static readonly LevelDisplayMode: string = 'nsu=' + NS + ';i=3003'
    static readonly SignalColor: string = 'nsu=' + NS + ';i=3004'
    static readonly SignalModeLight: string = 'nsu=' + NS + ';i=3005'
    static readonly StacklightOperationMode: string = 'nsu=' + NS + ';i=3002'
    static readonly RGBWDataType: string = 'nsu=' + NS + ';i=3007'
}

export class MethodIds {
    static readonly IStatisticsType_ResetStatistics: string = 'nsu=' + NS + ';i=7001'
}

export class ObjectIds {
    static readonly CalibrationTargetType_CalibrationTargetCategory: string = 'nsu=' + NS + ';i=5011'
    static readonly CalibrationTargetType_CalibrationTargetFeatures: string = 'nsu=' + NS + ';i=5013'
    static readonly CalibrationTargetType_Identification: string = 'nsu=' + NS + ';i=5010'
    static readonly CalibrationTargetType_OperationalConditions: string = 'nsu=' + NS + ';i=5012'
    static readonly BasicStacklightType_OrderedObject_Placeholder: string = 'nsu=' + NS + ';i=5006'
    static readonly BasicStacklightType_StackLevel: string = 'nsu=' + NS + ';i=5001'
    static readonly BasicStacklightType_StackRunning: string = 'nsu=' + NS + ';i=5005'
    static readonly StacklightType_DeviceHealthAlarms: string = 'nsu=' + NS + ';i=5007'
    static readonly StackElementAcousticType_AcousticSignals: string = 'nsu=' + NS + ';i=5003'
    static readonly StackElementAcousticType_AcousticSignals_OrderedObject: string = 'nsu=' + NS + ';i=5004'
    static readonly StackElementLightType_ControlChannel_Placeholder: string = 'nsu=' + NS + ';i=5002'
    static readonly RGBWDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5009'
    static readonly RGBWDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5014'
}

export class ObjectTypeIds {
    static readonly AcousticSignalType: string = 'nsu=' + NS + ';i=1009'
    static readonly BaseCalibrationTargetCategoryType: string = 'nsu=' + NS + ';i=1014'
    static readonly DynamicCalibrationTargetCategoryType: string = 'nsu=' + NS + ';i=1018'
    static readonly OneTimeCalibrationTargetCategoryType: string = 'nsu=' + NS + ';i=1017'
    static readonly ReusableCalibrationTargetCategoryType: string = 'nsu=' + NS + ';i=1015'
    static readonly ReusableDeviceCalibrationTargetCategoryType: string = 'nsu=' + NS + ';i=1016'
    static readonly IStatisticsType: string = 'nsu=' + NS + ';i=1011'
    static readonly IAggregateStatisticsType: string = 'nsu=' + NS + ';i=1012'
    static readonly IRollingStatisticsType: string = 'nsu=' + NS + ';i=1013'
    static readonly CalibrationTargetType: string = 'nsu=' + NS + ';i=1019'
    static readonly ControlChannelType: string = 'nsu=' + NS + ';i=1008'
    static readonly BasicStacklightType: string = 'nsu=' + NS + ';i=1002'
    static readonly StacklightType: string = 'nsu=' + NS + ';i=1010'
    static readonly StackElementType: string = 'nsu=' + NS + ';i=1005'
    static readonly StackElementAcousticType: string = 'nsu=' + NS + ';i=1007'
    static readonly StackElementLightType: string = 'nsu=' + NS + ';i=1006'
    static readonly StackLevelType: string = 'nsu=' + NS + ';i=1003'
    static readonly StackRunningType: string = 'nsu=' + NS + ';i=1004'
}

export class ReferenceTypeIds {
    static readonly HasStatisticComponent: string = 'nsu=' + NS + ';i=4002'
    static readonly HasReferenceMeasurementInstrument: string = 'nsu=' + NS + ';i=4003'
}

export class VariableIds {
    static readonly LevelDisplayMode_EnumValues: string = 'nsu=' + NS + ';i=6001'
    static readonly SignalColor_EnumValues: string = 'nsu=' + NS + ';i=6007'
    static readonly SignalModeLight_EnumValues: string = 'nsu=' + NS + ';i=6008'
    static readonly StacklightOperationMode_EnumValues: string = 'nsu=' + NS + ';i=6006'
    static readonly CalibrationValueType_EngineeringUnits: string = 'nsu=' + NS + ';i=6057'
    static readonly CapacityRangeType_EngineeringUnits: string = 'nsu=' + NS + ';i=6058'
    static readonly CapacityRangeType_Resolution: string = 'nsu=' + NS + ';i=6059'
    static readonly AcousticSignalType_AudioSample: string = 'nsu=' + NS + ';i=6029'
    static readonly AcousticSignalType_NumberInList: string = 'nsu=' + NS + ';i=6028'
    static readonly IStatisticsType_StartTime: string = 'nsu=' + NS + ';i=6046'
    static readonly IAggregateStatisticsType_ResetCondition: string = 'nsu=' + NS + ';i=6047'
    static readonly IRollingStatisticsType_WindowDuration: string = 'nsu=' + NS + ';i=6048'
    static readonly IRollingStatisticsType_WindowNumberOfValues: string = 'nsu=' + NS + ';i=6049'
    static readonly CalibrationTargetType_CalibrationTargetFeatures_CalibrationValue_Placeholder: string = 'nsu=' + NS + ';i=6064'
    static readonly CalibrationTargetType_CalibrationTargetFeatures_CalibrationValue_Placeholder_EngineeringUnits: string = 'nsu=' + NS + ';i=6065'
    static readonly CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder: string = 'nsu=' + NS + ';i=6066'
    static readonly CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder_EngineeringUnits: string = 'nsu=' + NS + ';i=6067'
    static readonly CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder_Resolution: string = 'nsu=' + NS + ';i=6068'
    static readonly CalibrationTargetType_CertificateUri: string = 'nsu=' + NS + ';i=6063'
    static readonly CalibrationTargetType_Identification_AssetId: string = 'nsu=' + NS + ';i=6080'
    static readonly CalibrationTargetType_Identification_ComponentName: string = 'nsu=' + NS + ';i=6081'
    static readonly CalibrationTargetType_Identification_DeviceClass: string = 'nsu=' + NS + ';i=6076'
    static readonly CalibrationTargetType_Identification_DeviceManual: string = 'nsu=' + NS + ';i=6082'
    static readonly CalibrationTargetType_Identification_DeviceRevision: string = 'nsu=' + NS + ';i=6075'
    static readonly CalibrationTargetType_Identification_HardwareRevision: string = 'nsu=' + NS + ';i=6073'
    static readonly CalibrationTargetType_Identification_Manufacturer: string = 'nsu=' + NS + ';i=6069'
    static readonly CalibrationTargetType_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=6070'
    static readonly CalibrationTargetType_Identification_Model: string = 'nsu=' + NS + ';i=6071'
    static readonly CalibrationTargetType_Identification_ProductCode: string = 'nsu=' + NS + ';i=6072'
    static readonly CalibrationTargetType_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=6078'
    static readonly CalibrationTargetType_Identification_RevisionCounter: string = 'nsu=' + NS + ';i=6079'
    static readonly CalibrationTargetType_Identification_SerialNumber: string = 'nsu=' + NS + ';i=6077'
    static readonly CalibrationTargetType_Identification_SoftwareRevision: string = 'nsu=' + NS + ';i=6074'
    static readonly CalibrationTargetType_LastValidationDate: string = 'nsu=' + NS + ';i=6060'
    static readonly CalibrationTargetType_NextValidationDate: string = 'nsu=' + NS + ';i=6061'
    static readonly CalibrationTargetType_Quality: string = 'nsu=' + NS + ';i=6062'
    static readonly ControlChannelType_ChannelColor: string = 'nsu=' + NS + ';i=6024'
    static readonly ControlChannelType_Intensity: string = 'nsu=' + NS + ';i=6026'
    static readonly ControlChannelType_Intensity_EURange: string = 'nsu=' + NS + ';i=6027'
    static readonly ControlChannelType_SignalMode: string = 'nsu=' + NS + ';i=6025'
    static readonly ControlChannelType_SignalOn: string = 'nsu=' + NS + ';i=6023'
    static readonly BasicStacklightType_OrderedObject_Placeholder_NumberInList: string = 'nsu=' + NS + ';i=6037'
    static readonly BasicStacklightType_StackLevel_DisplayMode: string = 'nsu=' + NS + ';i=6034'
    static readonly BasicStacklightType_StackLevel_LevelPercent: string = 'nsu=' + NS + ';i=6035'
    static readonly BasicStacklightType_StackLevel_LevelPercent_EURange: string = 'nsu=' + NS + ';i=6036'
    static readonly BasicStacklightType_StacklightMode: string = 'nsu=' + NS + ';i=6009'
    static readonly StacklightType_OrderedObject_Placeholder_NumberInList: string = 'nsu=' + NS + ';i=6037'
    static readonly StacklightType_StackLevel_DisplayMode: string = 'nsu=' + NS + ';i=6034'
    static readonly StacklightType_StackLevel_LevelPercent: string = 'nsu=' + NS + ';i=6035'
    static readonly StacklightType_StackLevel_LevelPercent_EURange: string = 'nsu=' + NS + ';i=6036'
    static readonly StacklightType_DeviceHealth: string = 'nsu=' + NS + ';i=6038'
    static readonly StackElementType_IsPartOfBase: string = 'nsu=' + NS + ';i=6014'
    static readonly StackElementType_NumberInList: string = 'nsu=' + NS + ';i=6015'
    static readonly StackElementType_SignalOn: string = 'nsu=' + NS + ';i=6013'
    static readonly StackElementAcousticType_AcousticSignals_OrderedObject_NumberInList: string = 'nsu=' + NS + ';i=6030'
    static readonly StackElementAcousticType_Intensity: string = 'nsu=' + NS + ';i=6021'
    static readonly StackElementAcousticType_Intensity_EURange: string = 'nsu=' + NS + ';i=6022'
    static readonly StackElementAcousticType_OperationMode: string = 'nsu=' + NS + ';i=6020'
    static readonly StackElementLightType_ControlChannel_Placeholder_ChannelColor: string = 'nsu=' + NS + ';i=6031'
    static readonly StackElementLightType_ControlChannel_Placeholder_Intensity_EURange: string = 'nsu=' + NS + ';i=6027'
    static readonly StackElementLightType_ControlChannel_Placeholder_SignalMode: string = 'nsu=' + NS + ';i=6032'
    static readonly StackElementLightType_ControlChannel_Placeholder_SignalOn: string = 'nsu=' + NS + ';i=6033'
    static readonly StackElementLightType_Intensity: string = 'nsu=' + NS + ';i=6018'
    static readonly StackElementLightType_Intensity_EURange: string = 'nsu=' + NS + ';i=6019'
    static readonly StackElementLightType_SignalColor: string = 'nsu=' + NS + ';i=6016'
    static readonly StackElementLightType_SignalMode: string = 'nsu=' + NS + ';i=6017'
    static readonly StackElementLightType_SignalRGBWValue: string = 'nsu=' + NS + ';i=6052'
    static readonly StackLevelType_DisplayMode: string = 'nsu=' + NS + ';i=6012'
    static readonly StackLevelType_LevelPercent: string = 'nsu=' + NS + ';i=6010'
    static readonly StackLevelType_LevelPercent_EURange: string = 'nsu=' + NS + ';i=6011'
}

export class VariableTypeIds {
    static readonly CalibrationValueType: string = 'nsu=' + NS + ';i=2002'
    static readonly CapacityRangeType: string = 'nsu=' + NS + ';i=2003'
}
