export const NS = 'http://opcfoundation.org/UA/Machinery/';

export class BrowseNames {
   static readonly Component_Placeholder: string = '<Component>'
   static readonly Components: string = 'Components'
   static readonly Consumption: string = 'Consumption'
   static readonly Description: string = 'Description'
   static readonly EquipmentLife: string = 'EquipmentLife'
   static readonly Executing: string = 'Executing'
   static readonly FromExecutingToExecuting: string = 'FromExecutingToExecuting'
   static readonly FromExecutingToNotAvailable: string = 'FromExecutingToNotAvailable'
   static readonly FromExecutingToNotExecuting: string = 'FromExecutingToNotExecuting'
   static readonly FromExecutingToOutOfService: string = 'FromExecutingToOutOfService'
   static readonly FromMaintenanceToMaintenance: string = 'FromMaintenanceToMaintenance'
   static readonly FromMaintenanceToNone: string = 'FromMaintenanceToNone'
   static readonly FromMaintenanceToProcessing: string = 'FromMaintenanceToProcessing'
   static readonly FromMaintenanceToSetup: string = 'FromMaintenanceToSetup'
   static readonly FromNoneToMaintenance: string = 'FromNoneToMaintenance'
   static readonly FromNoneToNone: string = 'FromNoneToNone'
   static readonly FromNoneToProcessing: string = 'FromNoneToProcessing'
   static readonly FromNoneToSetup: string = 'FromNoneToSetup'
   static readonly FromNotAvailableToExecuting: string = 'FromNotAvailableToExecuting'
   static readonly FromNotAvailableToNotAvailable: string = 'FromNotAvailableToNotAvailable'
   static readonly FromNotAvailableToNotExecuting: string = 'FromNotAvailableToNotExecuting'
   static readonly FromNotAvailableToOutOfService: string = 'FromNotAvailableToOutOfService'
   static readonly FromNotExecutingToExecuting: string = 'FromNotExecutingToExecuting'
   static readonly FromNotExecutingToNotAvailable: string = 'FromNotExecutingToNotAvailable'
   static readonly FromNotExecutingToNotExecuting: string = 'FromNotExecutingToNotExecuting'
   static readonly FromNotExecutingToOutOfService: string = 'FromNotExecutingToOutOfService'
   static readonly FromOutOfServiceToExecuting: string = 'FromOutOfServiceToExecuting'
   static readonly FromOutOfServiceToNotAvailable: string = 'FromOutOfServiceToNotAvailable'
   static readonly FromOutOfServiceToNotExecuting: string = 'FromOutOfServiceToNotExecuting'
   static readonly FromOutOfServiceToOutOfService: string = 'FromOutOfServiceToOutOfService'
   static readonly FromProcessingToMaintenance: string = 'FromProcessingToMaintenance'
   static readonly FromProcessingToNone: string = 'FromProcessingToNone'
   static readonly FromProcessingToProcessing: string = 'FromProcessingToProcessing'
   static readonly FromProcessingToSetup: string = 'FromProcessingToSetup'
   static readonly FromSetupToMaintenance: string = 'FromSetupToMaintenance'
   static readonly FromSetupToNone: string = 'FromSetupToNone'
   static readonly FromSetupToProcessing: string = 'FromSetupToProcessing'
   static readonly FromSetupToSetup: string = 'FromSetupToSetup'
   static readonly Health: string = 'Health'
   static readonly Identification: string = 'Identification'
   static readonly IMachineryEquipmentType: string = 'IMachineryEquipmentType'
   static readonly IMachineryItemVendorNameplateType: string = 'IMachineryItemVendorNameplateType'
   static readonly IMachineTagNameplateType: string = 'IMachineTagNameplateType'
   static readonly IMachineVendorNameplateType: string = 'IMachineVendorNameplateType'
   static readonly InitialOperationDate: string = 'InitialOperationDate'
   static readonly LifetimeCounters: string = 'LifetimeCounters'
   static readonly LifetimeVariable_Placeholder: string = '<LifetimeVariable>'
   static readonly Location: string = 'Location'
   static readonly MachineComponentsType: string = 'MachineComponentsType'
   static readonly MachineIdentificationType: string = 'MachineIdentificationType'
   static readonly MachineryComponentIdentificationType: string = 'MachineryComponentIdentificationType'
   static readonly MachineryEquipment: string = 'MachineryEquipment'
   static readonly MachineryEquipment_Placeholder: string = '<MachineryEquipment>'
   static readonly MachineryEquipmentFolderType: string = 'MachineryEquipmentFolderType'
   static readonly MachineryEquipmentTypeId: string = 'MachineryEquipmentTypeId'
   static readonly MachineryItemIdentificationType: string = 'MachineryItemIdentificationType'
   static readonly MachineryItemState: string = 'MachineryItemState'
   static readonly MachineryItemState_StateMachineType: string = 'MachineryItemState_StateMachineType'
   static readonly MachineryLifetimeCounterType: string = 'MachineryLifetimeCounterType'
   static readonly MachineryOperationCounterType: string = 'MachineryOperationCounterType'
   static readonly MachineryOperationMode: string = 'MachineryOperationMode'
   static readonly MachineryOperationModeStateMachineType: string = 'MachineryOperationModeStateMachineType'
   static readonly Machines: string = 'Machines'
   static readonly Maintenance: string = 'Maintenance'
   static readonly Monitoring: string = 'Monitoring'
   static readonly MonitoringType: string = 'MonitoringType'
   static readonly MonthOfConstruction: string = 'MonthOfConstruction'
   static readonly None: string = 'None'
   static readonly NotAvailable: string = 'NotAvailable'
   static readonly NotExecuting: string = 'NotExecuting'
   static readonly Notifications: string = 'Notifications'
   static readonly NotificationsType: string = 'NotificationsType'
   static readonly OperationCounters: string = 'OperationCounters'
   static readonly OperationMode: string = 'OperationMode'
   static readonly OutOfService: string = 'OutOfService'
   static readonly Process: string = 'Process'
   static readonly Processing: string = 'Processing'
   static readonly Setup: string = 'Setup'
   static readonly Stacklight: string = 'Stacklight'
   static readonly Status: string = 'Status'
   static readonly YearOfConstruction: string = 'YearOfConstruction'
}

export class ObjectIds {
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder: string = 'nsu=' + NS + ';i=5052'
    static readonly MonitoringType_Consumption: string = 'nsu=' + NS + ';i=5047'
    static readonly MonitoringType_Health: string = 'nsu=' + NS + ';i=5045'
    static readonly MonitoringType_Health_DeviceHealthAlarms: string = 'nsu=' + NS + ';i=5051'
    static readonly MonitoringType_Process: string = 'nsu=' + NS + ';i=5046'
    static readonly MonitoringType_Status: string = 'nsu=' + NS + ';i=5044'
    static readonly MonitoringType_Status_MachineryItemState: string = 'nsu=' + NS + ';i=5048'
    static readonly MonitoringType_Status_OperationMode: string = 'nsu=' + NS + ';i=5049'
    static readonly MonitoringType_Status_Stacklight: string = 'nsu=' + NS + ';i=5050'
    static readonly MachineComponentsType_Component_Placeholder: string = 'nsu=' + NS + ';i=5002'
    static readonly MachineComponentsType_Component_Placeholder_Identification: string = 'nsu=' + NS + ';i=5003'
    static readonly MachineryItemState_StateMachineType_Executing: string = 'nsu=' + NS + ';i=5006'
    static readonly MachineryItemState_StateMachineType_FromExecutingToExecuting: string = 'nsu=' + NS + ';i=5023'
    static readonly MachineryItemState_StateMachineType_FromExecutingToNotAvailable: string = 'nsu=' + NS + ';i=5020'
    static readonly MachineryItemState_StateMachineType_FromExecutingToNotExecuting: string = 'nsu=' + NS + ';i=5022'
    static readonly MachineryItemState_StateMachineType_FromExecutingToOutOfService: string = 'nsu=' + NS + ';i=5021'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToExecuting: string = 'nsu=' + NS + ';i=5010'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToNotAvailable: string = 'nsu=' + NS + ';i=5011'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToNotExecuting: string = 'nsu=' + NS + ';i=5009'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToOutOfService: string = 'nsu=' + NS + ';i=5008'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToExecuting: string = 'nsu=' + NS + ';i=5018'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToNotAvailable: string = 'nsu=' + NS + ';i=5016'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToNotExecuting: string = 'nsu=' + NS + ';i=5019'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToOutOfService: string = 'nsu=' + NS + ';i=5017'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToExecuting: string = 'nsu=' + NS + ';i=5014'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToNotAvailable: string = 'nsu=' + NS + ';i=5012'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToNotExecuting: string = 'nsu=' + NS + ';i=5013'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToOutOfService: string = 'nsu=' + NS + ';i=5015'
    static readonly MachineryItemState_StateMachineType_NotAvailable: string = 'nsu=' + NS + ';i=5005'
    static readonly MachineryItemState_StateMachineType_NotExecuting: string = 'nsu=' + NS + ';i=5007'
    static readonly MachineryItemState_StateMachineType_OutOfService: string = 'nsu=' + NS + ';i=5004'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToMaintenance: string = 'nsu=' + NS + ';i=5035'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToNone: string = 'nsu=' + NS + ';i=5032'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToProcessing: string = 'nsu=' + NS + ';i=5034'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToSetup: string = 'nsu=' + NS + ';i=5033'
    static readonly MachineryOperationModeStateMachineType_FromNoneToMaintenance: string = 'nsu=' + NS + ';i=5028'
    static readonly MachineryOperationModeStateMachineType_FromNoneToNone: string = 'nsu=' + NS + ';i=5031'
    static readonly MachineryOperationModeStateMachineType_FromNoneToProcessing: string = 'nsu=' + NS + ';i=5030'
    static readonly MachineryOperationModeStateMachineType_FromNoneToSetup: string = 'nsu=' + NS + ';i=5029'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToMaintenance: string = 'nsu=' + NS + ';i=5041'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToNone: string = 'nsu=' + NS + ';i=5040'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToProcessing: string = 'nsu=' + NS + ';i=5043'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToSetup: string = 'nsu=' + NS + ';i=5042'
    static readonly MachineryOperationModeStateMachineType_FromSetupToMaintenance: string = 'nsu=' + NS + ';i=5037'
    static readonly MachineryOperationModeStateMachineType_FromSetupToNone: string = 'nsu=' + NS + ';i=5036'
    static readonly MachineryOperationModeStateMachineType_FromSetupToProcessing: string = 'nsu=' + NS + ';i=5038'
    static readonly MachineryOperationModeStateMachineType_FromSetupToSetup: string = 'nsu=' + NS + ';i=5039'
    static readonly MachineryOperationModeStateMachineType_Maintenance: string = 'nsu=' + NS + ';i=5025'
    static readonly MachineryOperationModeStateMachineType_None: string = 'nsu=' + NS + ';i=5024'
    static readonly MachineryOperationModeStateMachineType_Processing: string = 'nsu=' + NS + ';i=5026'
    static readonly MachineryOperationModeStateMachineType_Setup: string = 'nsu=' + NS + ';i=5027'
    static readonly Machines: string = 'nsu=' + NS + ';i=1001'
}

export class ObjectTypeIds {
    static readonly IMachineTagNameplateType: string = 'nsu=' + NS + ';i=1011'
    static readonly IMachineryEquipmentType: string = 'nsu=' + NS + ';i=1007'
    static readonly IMachineryItemVendorNameplateType: string = 'nsu=' + NS + ';i=1003'
    static readonly IMachineVendorNameplateType: string = 'nsu=' + NS + ';i=1010'
    static readonly MachineryItemIdentificationType: string = 'nsu=' + NS + ';i=1004'
    static readonly MachineIdentificationType: string = 'nsu=' + NS + ';i=1012'
    static readonly MachineryComponentIdentificationType: string = 'nsu=' + NS + ';i=1005'
    static readonly MachineryOperationCounterType: string = 'nsu=' + NS + ';i=1009'
    static readonly MachineryEquipmentFolderType: string = 'nsu=' + NS + ';i=1013'
    static readonly MachineryLifetimeCounterType: string = 'nsu=' + NS + ';i=1015'
    static readonly MonitoringType: string = 'nsu=' + NS + ';i=1014'
    static readonly NotificationsType: string = 'nsu=' + NS + ';i=1017'
    static readonly MachineComponentsType: string = 'nsu=' + NS + ';i=1006'
    static readonly MachineryItemState_StateMachineType: string = 'nsu=' + NS + ';i=1002'
    static readonly MachineryOperationModeStateMachineType: string = 'nsu=' + NS + ';i=1008'
}

export class VariableIds {
    static readonly IMachineTagNameplateType_Location: string = 'nsu=' + NS + ';i=6028'
    static readonly IMachineryEquipmentType_Description: string = 'nsu=' + NS + ';i=6107'
    static readonly IMachineryEquipmentType_EquipmentLife: string = 'nsu=' + NS + ';i=6109'
    static readonly IMachineryEquipmentType_EquipmentLife_EngineeringUnits: string = 'nsu=' + NS + ';i=6112'
    static readonly IMachineryEquipmentType_EquipmentLife_StartValue: string = 'nsu=' + NS + ';i=6111'
    static readonly IMachineryEquipmentType_EquipmentLife_LimitValue: string = 'nsu=' + NS + ';i=6110'
    static readonly IMachineryEquipmentType_MachineryEquipmentTypeId: string = 'nsu=' + NS + ';i=6108'
    static readonly IMachineryItemVendorNameplateType_Manufacturer: string = 'nsu=' + NS + ';i=6022'
    static readonly IMachineryItemVendorNameplateType_SerialNumber: string = 'nsu=' + NS + ';i=6024'
    static readonly IMachineryItemVendorNameplateType_InitialOperationDate: string = 'nsu=' + NS + ';i=6027'
    static readonly IMachineryItemVendorNameplateType_MonthOfConstruction: string = 'nsu=' + NS + ';i=6026'
    static readonly IMachineryItemVendorNameplateType_YearOfConstruction: string = 'nsu=' + NS + ';i=6025'
    static readonly IMachineVendorNameplateType_ProductInstanceUri: string = 'nsu=' + NS + ';i=6023'
    static readonly MachineryItemIdentificationType_AssetId: string = 'nsu=' + NS + ';i=6013'
    static readonly MachineryItemIdentificationType_ComponentName: string = 'nsu=' + NS + ';i=6014'
    static readonly MachineryItemIdentificationType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6088'
    static readonly MachineryItemIdentificationType_DeviceClass: string = 'nsu=' + NS + ';i=6012'
    static readonly MachineryItemIdentificationType_HardwareRevision: string = 'nsu=' + NS + ';i=6010'
    static readonly MachineryItemIdentificationType_InitialOperationDate: string = 'nsu=' + NS + ';i=6006'
    static readonly MachineryItemIdentificationType_Manufacturer: string = 'nsu=' + NS + ';i=6002'
    static readonly MachineryItemIdentificationType_ManufacturerUri: string = 'nsu=' + NS + ';i=6007'
    static readonly MachineryItemIdentificationType_Model: string = 'nsu=' + NS + ';i=6008'
    static readonly MachineryItemIdentificationType_MonthOfConstruction: string = 'nsu=' + NS + ';i=6005'
    static readonly MachineryItemIdentificationType_ProductCode: string = 'nsu=' + NS + ';i=6009'
    static readonly MachineryItemIdentificationType_ProductInstanceUri: string = 'nsu=' + NS + ';i=6001'
    static readonly MachineryItemIdentificationType_SerialNumber: string = 'nsu=' + NS + ';i=6003'
    static readonly MachineryItemIdentificationType_SoftwareRevision: string = 'nsu=' + NS + ';i=6011'
    static readonly MachineryItemIdentificationType_YearOfConstruction: string = 'nsu=' + NS + ';i=6004'
    static readonly MachineIdentificationType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6030'
    static readonly MachineIdentificationType_ProductInstanceUri: string = 'nsu=' + NS + ';i=6015'
    static readonly MachineIdentificationType_Location: string = 'nsu=' + NS + ';i=6029'
    static readonly MachineryComponentIdentificationType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6016'
    static readonly MachineryComponentIdentificationType_DeviceRevision: string = 'nsu=' + NS + ';i=6017'
    static readonly MachineryOperationCounterType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6082'
    static readonly MachineryOperationCounterType_OperationCycleCounter: string = 'nsu=' + NS + ';i=6081'
    static readonly MachineryOperationCounterType_OperationDuration: string = 'nsu=' + NS + ';i=6080'
    static readonly MachineryOperationCounterType_PowerOnDuration: string = 'nsu=' + NS + ';i=6079'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_AssetId: string = 'nsu=' + NS + ';i=6096'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_ComponentName: string = 'nsu=' + NS + ';i=6097'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Description: string = 'nsu=' + NS + ';i=6098'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_DeviceClass: string = 'nsu=' + NS + ';i=6099'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Location: string = 'nsu=' + NS + ';i=6100'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_MachineryEquipmentTypeId: string = 'nsu=' + NS + ';i=6101'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_ManufacturerUri: string = 'nsu=' + NS + ';i=6102'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_Model: string = 'nsu=' + NS + ';i=6103'
    static readonly MachineryEquipmentFolderType_MachineryEquipment_Placeholder_SerialNumber: string = 'nsu=' + NS + ';i=6104'
    static readonly MachineryEquipmentFolderType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6105'
    static readonly MachineryLifetimeCounterType_LifetimeVariable_Placeholder: string = 'nsu=' + NS + ';i=6083'
    static readonly MachineryLifetimeCounterType_LifetimeVariable_Placeholder_EngineeringUnits: string = 'nsu=' + NS + ';i=6086'
    static readonly MachineryLifetimeCounterType_LifetimeVariable_Placeholder_StartValue: string = 'nsu=' + NS + ';i=6085'
    static readonly MachineryLifetimeCounterType_LifetimeVariable_Placeholder_LimitValue: string = 'nsu=' + NS + ';i=6084'
    static readonly MachineryLifetimeCounterType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6087'
    static readonly MonitoringType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6089'
    static readonly MonitoringType_Health_DeviceHealth: string = 'nsu=' + NS + ';i=6095'
    static readonly MonitoringType_Status_MachineryItemState_CurrentState: string = 'nsu=' + NS + ';i=6090'
    static readonly MonitoringType_Status_MachineryItemState_CurrentState_Id: string = 'nsu=' + NS + ';i=6091'
    static readonly MonitoringType_Status_OperationMode_CurrentState: string = 'nsu=' + NS + ';i=6092'
    static readonly MonitoringType_Status_OperationMode_CurrentState_Id: string = 'nsu=' + NS + ';i=6093'
    static readonly MonitoringType_Status_Stacklight_StackLevel_DisplayMode: string = 'nsu=' + NS + ';i=6034'
    static readonly MonitoringType_Status_Stacklight_StackLevel_LevelPercent: string = 'nsu=' + NS + ';i=6035'
    static readonly MonitoringType_Status_Stacklight_StackLevel_LevelPercent_EURange: string = 'nsu=' + NS + ';i=6036'
    static readonly MonitoringType_Status_Stacklight_StacklightMode: string = 'nsu=' + NS + ';i=6094'
    static readonly NotificationsType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6106'
    static readonly MachineComponentsType_Component_Placeholder_Identification_Manufacturer: string = 'nsu=' + NS + ';i=6019'
    static readonly MachineComponentsType_Component_Placeholder_Identification_SerialNumber: string = 'nsu=' + NS + ';i=6020'
    static readonly MachineComponentsType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6018'
    static readonly MachineryItemState_StateMachineType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6021'
    static readonly MachineryItemState_StateMachineType_Executing_StateNumber: string = 'nsu=' + NS + ';i=6040'
    static readonly MachineryItemState_StateMachineType_FromExecutingToExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6057'
    static readonly MachineryItemState_StateMachineType_FromExecutingToNotAvailable_TransitionNumber: string = 'nsu=' + NS + ';i=6054'
    static readonly MachineryItemState_StateMachineType_FromExecutingToNotExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6056'
    static readonly MachineryItemState_StateMachineType_FromExecutingToOutOfService_TransitionNumber: string = 'nsu=' + NS + ';i=6055'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6044'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToNotAvailable_TransitionNumber: string = 'nsu=' + NS + ';i=6045'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToNotExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6043'
    static readonly MachineryItemState_StateMachineType_FromNotAvailableToOutOfService_TransitionNumber: string = 'nsu=' + NS + ';i=6042'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6052'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToNotAvailable_TransitionNumber: string = 'nsu=' + NS + ';i=6050'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToNotExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6053'
    static readonly MachineryItemState_StateMachineType_FromNotExecutingToOutOfService_TransitionNumber: string = 'nsu=' + NS + ';i=6051'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6048'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToNotAvailable_TransitionNumber: string = 'nsu=' + NS + ';i=6046'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToNotExecuting_TransitionNumber: string = 'nsu=' + NS + ';i=6047'
    static readonly MachineryItemState_StateMachineType_FromOutOfServiceToOutOfService_TransitionNumber: string = 'nsu=' + NS + ';i=6049'
    static readonly MachineryItemState_StateMachineType_NotAvailable_StateNumber: string = 'nsu=' + NS + ';i=6039'
    static readonly MachineryItemState_StateMachineType_NotExecuting_StateNumber: string = 'nsu=' + NS + ';i=6041'
    static readonly MachineryItemState_StateMachineType_OutOfService_StateNumber: string = 'nsu=' + NS + ';i=6038'
    static readonly MachineryOperationModeStateMachineType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6058'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToMaintenance_TransitionNumber: string = 'nsu=' + NS + ';i=6070'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToNone_TransitionNumber: string = 'nsu=' + NS + ';i=6067'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToProcessing_TransitionNumber: string = 'nsu=' + NS + ';i=6069'
    static readonly MachineryOperationModeStateMachineType_FromMaintenanceToSetup_TransitionNumber: string = 'nsu=' + NS + ';i=6068'
    static readonly MachineryOperationModeStateMachineType_FromNoneToMaintenance_TransitionNumber: string = 'nsu=' + NS + ';i=6063'
    static readonly MachineryOperationModeStateMachineType_FromNoneToNone_TransitionNumber: string = 'nsu=' + NS + ';i=6066'
    static readonly MachineryOperationModeStateMachineType_FromNoneToProcessing_TransitionNumber: string = 'nsu=' + NS + ';i=6065'
    static readonly MachineryOperationModeStateMachineType_FromNoneToSetup_TransitionNumber: string = 'nsu=' + NS + ';i=6064'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToMaintenance_TransitionNumber: string = 'nsu=' + NS + ';i=6076'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToNone_TransitionNumber: string = 'nsu=' + NS + ';i=6075'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToProcessing_TransitionNumber: string = 'nsu=' + NS + ';i=6078'
    static readonly MachineryOperationModeStateMachineType_FromProcessingToSetup_TransitionNumber: string = 'nsu=' + NS + ';i=6077'
    static readonly MachineryOperationModeStateMachineType_FromSetupToMaintenance_TransitionNumber: string = 'nsu=' + NS + ';i=6072'
    static readonly MachineryOperationModeStateMachineType_FromSetupToNone_TransitionNumber: string = 'nsu=' + NS + ';i=6071'
    static readonly MachineryOperationModeStateMachineType_FromSetupToProcessing_TransitionNumber: string = 'nsu=' + NS + ';i=6073'
    static readonly MachineryOperationModeStateMachineType_FromSetupToSetup_TransitionNumber: string = 'nsu=' + NS + ';i=6074'
    static readonly MachineryOperationModeStateMachineType_Maintenance_StateNumber: string = 'nsu=' + NS + ';i=6060'
    static readonly MachineryOperationModeStateMachineType_None_StateNumber: string = 'nsu=' + NS + ';i=6059'
    static readonly MachineryOperationModeStateMachineType_Processing_StateNumber: string = 'nsu=' + NS + ';i=6061'
    static readonly MachineryOperationModeStateMachineType_Setup_StateNumber: string = 'nsu=' + NS + ';i=6062'
}
