export const NS = 'http://opcfoundation.org/UA/Machinery/Result/';

export const BrowseNames = Object.freeze({
   AcknowledgeResults: 'AcknowledgeResults',
   BaseResultTransferOptionsDataType: 'BaseResultTransferOptionsDataType',
   CreationTime: 'CreationTime',
   ExternalConfigurationId: 'ExternalConfigurationId',
   ExternalRecipeId: 'ExternalRecipeId',
   FileFormat: 'FileFormat',
   GetLatestResult: 'GetLatestResult',
   GetResultById: 'GetResultById',
   GetResultIdListFiltered: 'GetResultIdListFiltered',
   HasTransferableDataOnFile: 'HasTransferableDataOnFile',
   InternalConfigurationId: 'InternalConfigurationId',
   InternalRecipeId: 'InternalRecipeId',
   IsPartial: 'IsPartial',
   IsSimulated: 'IsSimulated',
   JobId: 'JobId',
   PartId: 'PartId',
   ProcessingTimes: 'ProcessingTimes',
   ProcessingTimesDataType: 'ProcessingTimesDataType',
   ProductId: 'ProductId',
   ReducedResultContent: 'ReducedResultContent',
   ReleaseResultHandle: 'ReleaseResultHandle',
   Result: 'Result',
   ResultContent: 'ResultContent',
   ResultDataType: 'ResultDataType',
   ResultEvaluation: 'ResultEvaluation',
   ResultEvaluationCode: 'ResultEvaluationCode',
   ResultEvaluationDetails: 'ResultEvaluationDetails',
   ResultEvaluationEnum: 'ResultEvaluationEnum',
   ResultId: 'ResultId',
   ResultManagement: 'ResultManagement',
   ResultManagementType: 'ResultManagementType',
   ResultMetaData: 'ResultMetaData',
   ResultMetaDataType: 'ResultMetaDataType',
   ResultReadyEventType: 'ResultReadyEventType',
   Results: 'Results',
   ResultState: 'ResultState',
   ResultTransfer: 'ResultTransfer',
   ResultTransferOptionsDataType: 'ResultTransferOptionsDataType',
   ResultTransferType: 'ResultTransferType',
   ResultType: 'ResultType',
   ResultUri: 'ResultUri',
   ResultVariable_Placeholder: '<ResultVariable>',
   StepId: 'StepId',
});

export const DataTypeIds = Object.freeze({
   ResultEvaluationEnum: 'nsu=' + NS + ';i=3002',
   BaseResultTransferOptionsDataType: 'nsu=' + NS + ';i=3005',
   ResultTransferOptionsDataType: 'nsu=' + NS + ';i=3004',
   ProcessingTimesDataType: 'nsu=' + NS + ';i=3006',
   ResultDataType: 'nsu=' + NS + ';i=3008',
   ResultMetaDataType: 'nsu=' + NS + ';i=3007',
});

export const MethodIds = Object.freeze({
   ResultManagementType_AcknowledgeResults: 'nsu=' + NS + ';i=7009',
   ResultManagementType_GetLatestResult: 'nsu=' + NS + ';i=7008',
   ResultManagementType_GetResultById: 'nsu=' + NS + ';i=7005',
   ResultManagementType_GetResultIdListFiltered: 'nsu=' + NS + ';i=7006',
   ResultManagementType_ReleaseResultHandle: 'nsu=' + NS + ';i=7007',
   ResultManagementType_ResultTransfer_GenerateFileForRead: 'nsu=' + NS + ';i=7002',
   ResultManagementType_ResultTransfer_GenerateFileForWrite: 'nsu=' + NS + ';i=7004',
   ResultManagementType_ResultTransfer_CloseAndCommit: 'nsu=' + NS + ';i=7003',
   ResultTransferType_GenerateFileForRead: 'nsu=' + NS + ';i=7001',
});

export const ObjectIds = Object.freeze({
   ResultManagementType_Results: 'nsu=' + NS + ';i=5011',
   ResultManagementType_ResultTransfer: 'nsu=' + NS + ';i=5010',
   ResultTransferOptionsDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5001',
   ResultTransferOptionsDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5002',
   ProcessingTimesDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5003',
   ProcessingTimesDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5004',
   ResultMetaDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5005',
   ResultMetaDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5006',
   ResultDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5008',
   ResultDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5009',
   ResultTransferOptionsDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5012',
   ProcessingTimesDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5013',
   ResultDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5014',
   ResultMetaDataType_Encoding_DefaultJson: 'nsu=' + NS + ';i=5015',
});

export const ObjectTypeIds = Object.freeze({
   ResultReadyEventType: 'nsu=' + NS + ';i=1002',
   ResultManagementType: 'nsu=' + NS + ';i=1004',
   ResultTransferType: 'nsu=' + NS + ';i=1003',
});

export const VariableIds = Object.freeze({
   ResultEvaluationEnum_EnumValues: 'nsu=' + NS + ';i=6001',
   ResultType_ReducedResultContent: 'nsu=' + NS + ';i=6011',
   ResultType_ResultContent: 'nsu=' + NS + ';i=6010',
   ResultType_ResultMetaData: 'nsu=' + NS + ';i=6009',
   ResultType_ResultMetaData_CreationTime: 'nsu=' + NS + ';i=6025',
   ResultType_ResultMetaData_ExternalConfigurationId: 'nsu=' + NS + ';i=6022',
   ResultType_ResultMetaData_ExternalRecipeId: 'nsu=' + NS + ';i=6019',
   ResultType_ResultMetaData_FileFormat: 'nsu=' + NS + ';i=6031',
   ResultType_ResultMetaData_HasTransferableDataOnFile: 'nsu=' + NS + ';i=6013',
   ResultType_ResultMetaData_InternalConfigurationId: 'nsu=' + NS + ';i=6023',
   ResultType_ResultMetaData_InternalRecipeId: 'nsu=' + NS + ';i=6020',
   ResultType_ResultMetaData_IsPartial: 'nsu=' + NS + ';i=6014',
   ResultType_ResultMetaData_IsSimulated: 'nsu=' + NS + ';i=6015',
   ResultType_ResultMetaData_JobId: 'nsu=' + NS + ';i=6024',
   ResultType_ResultMetaData_PartId: 'nsu=' + NS + ';i=6018',
   ResultType_ResultMetaData_ProcessingTimes: 'nsu=' + NS + ';i=6026',
   ResultType_ResultMetaData_ProductId: 'nsu=' + NS + ';i=6021',
   ResultType_ResultMetaData_ResultEvaluation: 'nsu=' + NS + ';i=6028',
   ResultType_ResultMetaData_ResultEvaluationCode: 'nsu=' + NS + ';i=6030',
   ResultType_ResultMetaData_ResultEvaluationDetails: 'nsu=' + NS + ';i=6029',
   ResultType_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6012',
   ResultType_ResultMetaData_ResultState: 'nsu=' + NS + ';i=6016',
   ResultType_ResultMetaData_ResultUri: 'nsu=' + NS + ';i=6027',
   ResultType_ResultMetaData_StepId: 'nsu=' + NS + ';i=6017',
   ResultReadyEventType_Result: 'nsu=' + NS + ';i=6032',
   ResultReadyEventType_Result_ResultMetaData: 'nsu=' + NS + ';i=6033',
   ResultReadyEventType_Result_ResultMetaData_CreationTime: 'nsu=' + NS + ';i=6056',
   ResultReadyEventType_Result_ResultMetaData_ExternalConfigurationId: 'nsu=' + NS + ';i=6057',
   ResultReadyEventType_Result_ResultMetaData_ExternalRecipeId: 'nsu=' + NS + ';i=6058',
   ResultReadyEventType_Result_ResultMetaData_FileFormat: 'nsu=' + NS + ';i=6059',
   ResultReadyEventType_Result_ResultMetaData_HasTransferableDataOnFile: 'nsu=' + NS + ';i=6060',
   ResultReadyEventType_Result_ResultMetaData_InternalConfigurationId: 'nsu=' + NS + ';i=6061',
   ResultReadyEventType_Result_ResultMetaData_InternalRecipeId: 'nsu=' + NS + ';i=6062',
   ResultReadyEventType_Result_ResultMetaData_IsPartial: 'nsu=' + NS + ';i=6063',
   ResultReadyEventType_Result_ResultMetaData_IsSimulated: 'nsu=' + NS + ';i=6064',
   ResultReadyEventType_Result_ResultMetaData_JobId: 'nsu=' + NS + ';i=6065',
   ResultReadyEventType_Result_ResultMetaData_PartId: 'nsu=' + NS + ';i=6066',
   ResultReadyEventType_Result_ResultMetaData_ProcessingTimes: 'nsu=' + NS + ';i=6067',
   ResultReadyEventType_Result_ResultMetaData_ProductId: 'nsu=' + NS + ';i=6068',
   ResultReadyEventType_Result_ResultMetaData_ResultEvaluation: 'nsu=' + NS + ';i=6069',
   ResultReadyEventType_Result_ResultMetaData_ResultEvaluationCode: 'nsu=' + NS + ';i=6070',
   ResultReadyEventType_Result_ResultMetaData_ResultEvaluationDetails: 'nsu=' + NS + ';i=6071',
   ResultReadyEventType_Result_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6034',
   ResultReadyEventType_Result_ResultMetaData_ResultState: 'nsu=' + NS + ';i=6072',
   ResultReadyEventType_Result_ResultMetaData_ResultUri: 'nsu=' + NS + ';i=6073',
   ResultReadyEventType_Result_ResultMetaData_StepId: 'nsu=' + NS + ';i=6074',
   ResultManagementType_AcknowledgeResults_InputArguments: 'nsu=' + NS + ';i=6089',
   ResultManagementType_AcknowledgeResults_OutputArguments: 'nsu=' + NS + ';i=6090',
   ResultManagementType_DefaultInstanceBrowseName: 'nsu=' + NS + ';i=6037',
   ResultManagementType_GetLatestResult_InputArguments: 'nsu=' + NS + ';i=6054',
   ResultManagementType_GetLatestResult_OutputArguments: 'nsu=' + NS + ';i=6055',
   ResultManagementType_GetResultById_InputArguments: 'nsu=' + NS + ';i=6048',
   ResultManagementType_GetResultById_OutputArguments: 'nsu=' + NS + ';i=6049',
   ResultManagementType_GetResultIdListFiltered_InputArguments: 'nsu=' + NS + ';i=6050',
   ResultManagementType_GetResultIdListFiltered_OutputArguments: 'nsu=' + NS + ';i=6051',
   ResultManagementType_ReleaseResultHandle_InputArguments: 'nsu=' + NS + ';i=6052',
   ResultManagementType_ReleaseResultHandle_OutputArguments: 'nsu=' + NS + ';i=6053',
   ResultManagementType_Results_ResultVariable_Placeholder: 'nsu=' + NS + ';i=6045',
   ResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData: 'nsu=' + NS + ';i=6046',
   ResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData_ResultId: 'nsu=' + NS + ';i=6047',
   ResultManagementType_ResultTransfer_ClientProcessingTimeout: 'nsu=' + NS + ';i=6040',
   ResultManagementType_ResultTransfer_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=6038',
   ResultManagementType_ResultTransfer_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=6039',
   ResultManagementType_ResultTransfer_GenerateFileForWrite_InputArguments: 'nsu=' + NS + ';i=6043',
   ResultManagementType_ResultTransfer_GenerateFileForWrite_OutputArguments: 'nsu=' + NS + ';i=6044',
   ResultManagementType_ResultTransfer_CloseAndCommit_InputArguments: 'nsu=' + NS + ';i=6041',
   ResultManagementType_ResultTransfer_CloseAndCommit_OutputArguments: 'nsu=' + NS + ';i=6042',
   ResultTransferType_GenerateFileForRead_InputArguments: 'nsu=' + NS + ';i=6035',
   ResultTransferType_GenerateFileForRead_OutputArguments: 'nsu=' + NS + ';i=6036',
});

export const VariableTypeIds = Object.freeze({
   ResultType: 'nsu=' + NS + ';i=2001',
});
