export const NS = 'http://opcfoundation.org/UA/Machinery/Result/';

export class BrowseNames {
   static readonly AcknowledgeResults: string = 'AcknowledgeResults'
   static readonly BaseResultTransferOptionsDataType: string = 'BaseResultTransferOptionsDataType'
   static readonly CreationTime: string = 'CreationTime'
   static readonly ExternalConfigurationId: string = 'ExternalConfigurationId'
   static readonly ExternalRecipeId: string = 'ExternalRecipeId'
   static readonly FileFormat: string = 'FileFormat'
   static readonly GetLatestResult: string = 'GetLatestResult'
   static readonly GetResultById: string = 'GetResultById'
   static readonly GetResultIdListFiltered: string = 'GetResultIdListFiltered'
   static readonly HasTransferableDataOnFile: string = 'HasTransferableDataOnFile'
   static readonly InternalConfigurationId: string = 'InternalConfigurationId'
   static readonly InternalRecipeId: string = 'InternalRecipeId'
   static readonly IsPartial: string = 'IsPartial'
   static readonly IsSimulated: string = 'IsSimulated'
   static readonly JobId: string = 'JobId'
   static readonly PartId: string = 'PartId'
   static readonly ProcessingTimes: string = 'ProcessingTimes'
   static readonly ProcessingTimesDataType: string = 'ProcessingTimesDataType'
   static readonly ProductId: string = 'ProductId'
   static readonly ReducedResultContent: string = 'ReducedResultContent'
   static readonly ReleaseResultHandle: string = 'ReleaseResultHandle'
   static readonly Result: string = 'Result'
   static readonly ResultContent: string = 'ResultContent'
   static readonly ResultDataType: string = 'ResultDataType'
   static readonly ResultEvaluation: string = 'ResultEvaluation'
   static readonly ResultEvaluationCode: string = 'ResultEvaluationCode'
   static readonly ResultEvaluationDetails: string = 'ResultEvaluationDetails'
   static readonly ResultEvaluationEnum: string = 'ResultEvaluationEnum'
   static readonly ResultId: string = 'ResultId'
   static readonly ResultManagement: string = 'ResultManagement'
   static readonly ResultManagementType: string = 'ResultManagementType'
   static readonly ResultMetaData: string = 'ResultMetaData'
   static readonly ResultMetaDataType: string = 'ResultMetaDataType'
   static readonly ResultReadyEventType: string = 'ResultReadyEventType'
   static readonly Results: string = 'Results'
   static readonly ResultState: string = 'ResultState'
   static readonly ResultTransfer: string = 'ResultTransfer'
   static readonly ResultTransferOptionsDataType: string = 'ResultTransferOptionsDataType'
   static readonly ResultTransferType: string = 'ResultTransferType'
   static readonly ResultType: string = 'ResultType'
   static readonly ResultUri: string = 'ResultUri'
   static readonly ResultVariable_Placeholder: string = '<ResultVariable>'
   static readonly StepId: string = 'StepId'
}

export class DataTypeIds {
    static readonly ResultEvaluationEnum: string = 'nsu=' + NS + ';i=3002'
    static readonly BaseResultTransferOptionsDataType: string = 'nsu=' + NS + ';i=3005'
    static readonly ResultTransferOptionsDataType: string = 'nsu=' + NS + ';i=3004'
    static readonly ProcessingTimesDataType: string = 'nsu=' + NS + ';i=3006'
    static readonly ResultDataType: string = 'nsu=' + NS + ';i=3008'
    static readonly ResultMetaDataType: string = 'nsu=' + NS + ';i=3007'
}

export class MethodIds {
    static readonly ResultManagementType_AcknowledgeResults: string = 'nsu=' + NS + ';i=7009'
    static readonly ResultManagementType_GetLatestResult: string = 'nsu=' + NS + ';i=7008'
    static readonly ResultManagementType_GetResultById: string = 'nsu=' + NS + ';i=7005'
    static readonly ResultManagementType_GetResultIdListFiltered: string = 'nsu=' + NS + ';i=7006'
    static readonly ResultManagementType_ReleaseResultHandle: string = 'nsu=' + NS + ';i=7007'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForRead: string = 'nsu=' + NS + ';i=7002'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForWrite: string = 'nsu=' + NS + ';i=7004'
    static readonly ResultManagementType_ResultTransfer_CloseAndCommit: string = 'nsu=' + NS + ';i=7003'
    static readonly ResultTransferType_GenerateFileForRead: string = 'nsu=' + NS + ';i=7001'
}

export class ObjectIds {
    static readonly ResultManagementType_Results: string = 'nsu=' + NS + ';i=5011'
    static readonly ResultManagementType_ResultTransfer: string = 'nsu=' + NS + ';i=5010'
    static readonly ResultTransferOptionsDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5001'
    static readonly ResultTransferOptionsDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5002'
    static readonly ProcessingTimesDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5003'
    static readonly ProcessingTimesDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5004'
    static readonly ResultMetaDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5005'
    static readonly ResultMetaDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5006'
    static readonly ResultDataType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=5008'
    static readonly ResultDataType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=5009'
    static readonly ResultTransferOptionsDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=5012'
    static readonly ProcessingTimesDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=5013'
    static readonly ResultDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=5014'
    static readonly ResultMetaDataType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=5015'
}

export class ObjectTypeIds {
    static readonly ResultReadyEventType: string = 'nsu=' + NS + ';i=1002'
    static readonly ResultManagementType: string = 'nsu=' + NS + ';i=1004'
    static readonly ResultTransferType: string = 'nsu=' + NS + ';i=1003'
}

export class VariableIds {
    static readonly ResultEvaluationEnum_EnumValues: string = 'nsu=' + NS + ';i=6001'
    static readonly ResultType_ReducedResultContent: string = 'nsu=' + NS + ';i=6011'
    static readonly ResultType_ResultContent: string = 'nsu=' + NS + ';i=6010'
    static readonly ResultType_ResultMetaData: string = 'nsu=' + NS + ';i=6009'
    static readonly ResultType_ResultMetaData_CreationTime: string = 'nsu=' + NS + ';i=6025'
    static readonly ResultType_ResultMetaData_ExternalConfigurationId: string = 'nsu=' + NS + ';i=6022'
    static readonly ResultType_ResultMetaData_ExternalRecipeId: string = 'nsu=' + NS + ';i=6019'
    static readonly ResultType_ResultMetaData_FileFormat: string = 'nsu=' + NS + ';i=6031'
    static readonly ResultType_ResultMetaData_HasTransferableDataOnFile: string = 'nsu=' + NS + ';i=6013'
    static readonly ResultType_ResultMetaData_InternalConfigurationId: string = 'nsu=' + NS + ';i=6023'
    static readonly ResultType_ResultMetaData_InternalRecipeId: string = 'nsu=' + NS + ';i=6020'
    static readonly ResultType_ResultMetaData_IsPartial: string = 'nsu=' + NS + ';i=6014'
    static readonly ResultType_ResultMetaData_IsSimulated: string = 'nsu=' + NS + ';i=6015'
    static readonly ResultType_ResultMetaData_JobId: string = 'nsu=' + NS + ';i=6024'
    static readonly ResultType_ResultMetaData_PartId: string = 'nsu=' + NS + ';i=6018'
    static readonly ResultType_ResultMetaData_ProcessingTimes: string = 'nsu=' + NS + ';i=6026'
    static readonly ResultType_ResultMetaData_ProductId: string = 'nsu=' + NS + ';i=6021'
    static readonly ResultType_ResultMetaData_ResultEvaluation: string = 'nsu=' + NS + ';i=6028'
    static readonly ResultType_ResultMetaData_ResultEvaluationCode: string = 'nsu=' + NS + ';i=6030'
    static readonly ResultType_ResultMetaData_ResultEvaluationDetails: string = 'nsu=' + NS + ';i=6029'
    static readonly ResultType_ResultMetaData_ResultId: string = 'nsu=' + NS + ';i=6012'
    static readonly ResultType_ResultMetaData_ResultState: string = 'nsu=' + NS + ';i=6016'
    static readonly ResultType_ResultMetaData_ResultUri: string = 'nsu=' + NS + ';i=6027'
    static readonly ResultType_ResultMetaData_StepId: string = 'nsu=' + NS + ';i=6017'
    static readonly ResultReadyEventType_Result: string = 'nsu=' + NS + ';i=6032'
    static readonly ResultReadyEventType_Result_ResultMetaData: string = 'nsu=' + NS + ';i=6033'
    static readonly ResultReadyEventType_Result_ResultMetaData_CreationTime: string = 'nsu=' + NS + ';i=6056'
    static readonly ResultReadyEventType_Result_ResultMetaData_ExternalConfigurationId: string = 'nsu=' + NS + ';i=6057'
    static readonly ResultReadyEventType_Result_ResultMetaData_ExternalRecipeId: string = 'nsu=' + NS + ';i=6058'
    static readonly ResultReadyEventType_Result_ResultMetaData_FileFormat: string = 'nsu=' + NS + ';i=6059'
    static readonly ResultReadyEventType_Result_ResultMetaData_HasTransferableDataOnFile: string = 'nsu=' + NS + ';i=6060'
    static readonly ResultReadyEventType_Result_ResultMetaData_InternalConfigurationId: string = 'nsu=' + NS + ';i=6061'
    static readonly ResultReadyEventType_Result_ResultMetaData_InternalRecipeId: string = 'nsu=' + NS + ';i=6062'
    static readonly ResultReadyEventType_Result_ResultMetaData_IsPartial: string = 'nsu=' + NS + ';i=6063'
    static readonly ResultReadyEventType_Result_ResultMetaData_IsSimulated: string = 'nsu=' + NS + ';i=6064'
    static readonly ResultReadyEventType_Result_ResultMetaData_JobId: string = 'nsu=' + NS + ';i=6065'
    static readonly ResultReadyEventType_Result_ResultMetaData_PartId: string = 'nsu=' + NS + ';i=6066'
    static readonly ResultReadyEventType_Result_ResultMetaData_ProcessingTimes: string = 'nsu=' + NS + ';i=6067'
    static readonly ResultReadyEventType_Result_ResultMetaData_ProductId: string = 'nsu=' + NS + ';i=6068'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultEvaluation: string = 'nsu=' + NS + ';i=6069'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultEvaluationCode: string = 'nsu=' + NS + ';i=6070'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultEvaluationDetails: string = 'nsu=' + NS + ';i=6071'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultId: string = 'nsu=' + NS + ';i=6034'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultState: string = 'nsu=' + NS + ';i=6072'
    static readonly ResultReadyEventType_Result_ResultMetaData_ResultUri: string = 'nsu=' + NS + ';i=6073'
    static readonly ResultReadyEventType_Result_ResultMetaData_StepId: string = 'nsu=' + NS + ';i=6074'
    static readonly ResultManagementType_AcknowledgeResults_InputArguments: string = 'nsu=' + NS + ';i=6089'
    static readonly ResultManagementType_AcknowledgeResults_OutputArguments: string = 'nsu=' + NS + ';i=6090'
    static readonly ResultManagementType_DefaultInstanceBrowseName: string = 'nsu=' + NS + ';i=6037'
    static readonly ResultManagementType_GetLatestResult_InputArguments: string = 'nsu=' + NS + ';i=6054'
    static readonly ResultManagementType_GetLatestResult_OutputArguments: string = 'nsu=' + NS + ';i=6055'
    static readonly ResultManagementType_GetResultById_InputArguments: string = 'nsu=' + NS + ';i=6048'
    static readonly ResultManagementType_GetResultById_OutputArguments: string = 'nsu=' + NS + ';i=6049'
    static readonly ResultManagementType_GetResultIdListFiltered_InputArguments: string = 'nsu=' + NS + ';i=6050'
    static readonly ResultManagementType_GetResultIdListFiltered_OutputArguments: string = 'nsu=' + NS + ';i=6051'
    static readonly ResultManagementType_ReleaseResultHandle_InputArguments: string = 'nsu=' + NS + ';i=6052'
    static readonly ResultManagementType_ReleaseResultHandle_OutputArguments: string = 'nsu=' + NS + ';i=6053'
    static readonly ResultManagementType_Results_ResultVariable_Placeholder: string = 'nsu=' + NS + ';i=6045'
    static readonly ResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData: string = 'nsu=' + NS + ';i=6046'
    static readonly ResultManagementType_Results_ResultVariable_Placeholder_ResultMetaData_ResultId: string = 'nsu=' + NS + ';i=6047'
    static readonly ResultManagementType_ResultTransfer_ClientProcessingTimeout: string = 'nsu=' + NS + ';i=6040'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=6038'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=6039'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForWrite_InputArguments: string = 'nsu=' + NS + ';i=6043'
    static readonly ResultManagementType_ResultTransfer_GenerateFileForWrite_OutputArguments: string = 'nsu=' + NS + ';i=6044'
    static readonly ResultManagementType_ResultTransfer_CloseAndCommit_InputArguments: string = 'nsu=' + NS + ';i=6041'
    static readonly ResultManagementType_ResultTransfer_CloseAndCommit_OutputArguments: string = 'nsu=' + NS + ';i=6042'
    static readonly ResultTransferType_GenerateFileForRead_InputArguments: string = 'nsu=' + NS + ';i=6035'
    static readonly ResultTransferType_GenerateFileForRead_OutputArguments: string = 'nsu=' + NS + ';i=6036'
}

export class VariableTypeIds {
    static readonly ResultType: string = 'nsu=' + NS + ';i=2001'
}
