// <auto-generated />
// Compatibility extension for Roslyn source-generated NodeStates in SDK 2.0

#nullable enable

namespace MachineryResult
{
    public partial class ResultMetaDataType
    {
        public static explicit operator global::Opc.Ua.ExtensionObject(ResultMetaDataType? value)
        {
            if (value is null)
            {
                return default;
            }
            return new global::Opc.Ua.ExtensionObject(value);
        }

        public static implicit operator ResultMetaDataType?(global::Opc.Ua.ExtensionObject value)
        {
            if (value.TryGetValue(out ResultMetaDataType? result))
                return result;
            return null;
        }
    }
}
