/* ========================================================================
 * Copyright (c) 2005-2024 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Text;
using System.IO;
using Opc.Ua;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CA1515 // Consider making public types internal
#pragma warning disable CA1707 // Identifiers should not contain underscores
#pragma warning disable CA1028 // Enum Storage should be Int32

namespace UAModel.MachineryResult
{
    #region _ClassName_ Declarations
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Opc.Ua.ModelCompiler", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public static partial class PredefinedNodes
    {
        #region PredefinedNodes Declarations
        // <summary/>
        public static NodeStateCollection Load(ISystemContext context)
        {
            byte[] initializationBuffer = Convert.FromBase64String(
               "AQAAAC0AAABodHRwOi8vb3BjZm91bmRhdGlvbi5vcmcvVUEvTWFjaGluZXJ5L1Jlc3VsdC//////FgAA" +
               "ACRgAFBAAAAAAQAUAAAAUmVzdWx0RXZhbHVhdGlvbkVudW0BAboLAwAAAAArAAAASW5kaWNhdGVzIHdo" +
               "ZXRoZXIgYSByZXN1bHQgd2FzIGluIHRvbGVyYW5jZQAdAHsBTgEAAAQAAAAAAAAAAAAAAAIJAAAAVW5k" +
               "ZWZpbmVkAkYAAABUaGUgZXZhbHVhdGlvbiBvZiB0aGUgcmVzdWx0IGlzIHVua25vd24sIGZvciBleGFt" +
               "cGxlIGJlY2F1c2UgaXQgZmFpbGVkCQAAAFVuZGVmaW5lZAEAAAAAAAAAAgIAAABPSwIaAAAAVGhlIHJl" +
               "c3VsdCBpcyBpbiB0b2xlcmFuY2UCAAAAT0sCAAAAAAAAAAIFAAAATm90T0sCHgAAAFRoZSByZXN1bHQg" +
               "aXMgb3V0IG9mIHRvbGVyYW5jZQUAAABOb3RPSwMAAAAAAAAAAgwAAABOb3REZWNpZGFibGUCPAAAAFRo" +
               "ZSBkZWNpc2lvbiBpcyBub3QgcG9zc2libGUgZHVlIHRvIG1lYXN1cmVtZW50IHVuY2VydGFpbnR5LgwA" +
               "AABOb3REZWNpZGFibGX/////AQAAABdgqQoCAAAAAAAKAAAARW51bVZhbHVlcwEBcRcALgBEcRcAAJYE" +
               "AAAAAQA7IAFhAAAAAAAAAAAAAAACCQAAAFVuZGVmaW5lZAJGAAAAVGhlIGV2YWx1YXRpb24gb2YgdGhl" +
               "IHJlc3VsdCBpcyB1bmtub3duLCBmb3IgZXhhbXBsZSBiZWNhdXNlIGl0IGZhaWxlZAEAOyABLgAAAAEA" +
               "AAAAAAAAAgIAAABPSwIaAAAAVGhlIHJlc3VsdCBpcyBpbiB0b2xlcmFuY2UBADsgATUAAAACAAAAAAAA" +
               "AAIFAAAATm90T0sCHgAAAFRoZSByZXN1bHQgaXMgb3V0IG9mIHRvbGVyYW5jZQEAOyABWgAAAAMAAAAA" +
               "AAAAAgwAAABOb3REZWNpZGFibGUCPAAAAFRoZSBkZWNpc2lvbiBpcyBub3QgcG9zc2libGUgZHVlIHRv" +
               "IG1lYXN1cmVtZW50IHVuY2VydGFpbnR5LgEAqh0BAAAAAQAAAAQAAAABAf////8AAAAAJGgAUEAAAAAB" +
               "ACEAAABCYXNlUmVzdWx0VHJhbnNmZXJPcHRpb25zRGF0YVR5cGUBAb0LAwAAAABDAAAAQWJzdHJhY3Qg" +
               "dHlwZSBjb250YWluaW5nIGluZm9ybWF0aW9uIHdoaWNoIGZpbGUgc2hvdWxkIGJlIHByb3ZpZGVkLgAW" +
               "AQB6AWMAAAAAAAAWAAAAAAEAAAAIAAAAUmVzdWx0SWQCNQAAAFRoZSBJZCBvZiB0aGUgcmVzdWx0IHRv" +
               "IGJlIHRyYW5zZmVycmVkIHRvIHRoZSBDbGllbnRzAQCufP////8AAAAAAAAAAAD/////AAAAACRgAFBA" +
               "AAAAAQAdAAAAUmVzdWx0VHJhbnNmZXJPcHRpb25zRGF0YVR5cGUBAbwLAwAAAAAzAAAAQ29udGFpbnMg" +
               "aW5mb3JtYXRpb24gd2hpY2ggZmlsZSBzaG91bGQgYmUgcHJvdmlkZWQuAQG9CwB6AWUAAAAAAAEBvQsA" +
               "AAAAAQAAAAgAAABSZXN1bHRJZAI1AAAAVGhlIElkIG9mIHRoZSByZXN1bHQgdG8gYmUgdHJhbnNmZXJy" +
               "ZWQgdG8gdGhlIENsaWVudHMBAK58/////wAAAAAAAAAAAAMAAAAAJgABAYkTACYAAQGUEwAmAAEBihMA" +
               "AAAAJGAAUEAAAAABABcAAABQcm9jZXNzaW5nVGltZXNEYXRhVHlwZQEBvgsDAAAAAE0AAABDb250YWlu" +
               "cyBtZWFzdXJlZCB0aW1lcyB0aGF0IHdlcmUgZ2VuZXJhdGVkIGR1cmluZyB0aGUgZXhlY3V0aW9uIG9m" +
               "IGEgcmVjaXBlLgAWAHoBlAEAAAAAABYBAAAABAAAAAkAAABTdGFydFRpbWUCQgAAAENvbnRhaW5zIHRo" +
               "ZSB0aW1lIHdoZW4gdGhlIHN5c3RlbSBzdGFydGVkIGV4ZWN1dGlvbiBvZiB0aGUgcmVjaXBlLgEAJgH/" +
               "////AAAAAAAAAAAABwAAAEVuZFRpbWUCWAAAAENvbnRhaW5zIHRoZSB0aW1lIHdoZW4gdGhlIHN5c3Rl" +
               "bSBmaW5pc2hlZCAob3Igc3RvcHBlZC9hYm9ydGVkKSBleGVjdXRpb24gb2YgdGhlIHJlY2lwZS4BACYB" +
               "/////wAAAAAAAAAAABMAAABBY3F1aXNpdGlvbkR1cmF0aW9uAigAAABUaW1lIHNwZW50IGJ5IHRoZSBz" +
               "eXN0ZW0gYWNxdWlyaW5nIGRhdGEuAQAiAf////8AAAAAAAAAAAESAAAAUHJvY2Vzc2luZ0R1cmF0aW9u" +
               "AikAAABUaW1lIHNwZW50IGJ5IHRoZSBzeXN0ZW0gcHJvY2Vzc2luZyBkYXRhLgEAIgH/////AAAAAAAA" +
               "AAABAwAAAAAmAAEBixMAJgABAZUTACYAAQGMEwAAAAAkYABQQAAAAAEADgAAAFJlc3VsdERhdGFUeXBl" +
               "AQHACwMAAAAAQwAAAENvbnRhaW5zIGZpZWxkcyB0aGF0IHdlcmUgY3JlYXRlZCBkdXJpbmcgdGhlIGV4" +
               "ZWN1dGlvbiBvZiBhIHJlY2lwZS4AFgB6AecAAAAAAAAWAwAAAAIAAAAOAAAAUmVzdWx0TWV0YURhdGEC" +
               "MAAAAENvbnRhaW5zIG1ldGEgZGF0YSBkZXNjcmliaW5nIHRoZSByZXN1bHRDb250ZW50LgEBvwv/////" +
               "AAAAAAAAAAABDQAAAFJlc3VsdENvbnRlbnQCWgAAAEFic3RyYWN0IGRhdGEgdHlwZSB0byBiZSBzdWJ0" +
               "eXBlZCBmcm9tIHRvIGhvbGQgcmVzdWx0IGRhdGEgY3JlYXRlZCBieSB0aGUgc2VsZWN0ZWQgcmVjaXBl" +
               "LgAYAQAAAAEAAAAAAAAAAAAAAAADAAAAACYAAQGQEwAmAAEBlhMAJgABAZETAAAAACRgAFBAAAAAAQAS" +
               "AAAAUmVzdWx0TWV0YURhdGFUeXBlAQG/CwMAAAAALQAAAE1ldGEgZGF0YSBvZiBhIHJlc3VsdCwgZGVz" +
               "Y3JpYmluZyB0aGUgcmVzdWx0LgAWAHoB5xIAAAAAABYBAAAAFAAAAAgAAABSZXN1bHRJZAIiAQAAU3lz" +
               "dGVtLXdpZGUgdW5pcXVlIGlkZW50aWZpZXIsIHdoaWNoIGlzIGFzc2lnbmVkIGJ5IHRoZSBzeXN0ZW0u" +
               "IFRoaXMgSUQgY2FuIGJlIHVzZWQgZm9yIGZldGNoaW5nIGV4YWN0bHkgdGhpcyByZXN1bHQgdXNpbmcg" +
               "dGhlIG1ldGhvZCBHZXRSZXN1bHRCeUlkIGFuZCBpdCBpcyBpZGVudGljYWwgdG8gdGhlIFJlc3VsdElk" +
               "IG9mIHRoZSBSZXN1bHRSZWFkeUV2ZW50VHlwZS4KSWYgdGhlIHN5c3RlbSBkb2VzIG5vdCBtYW5hZ2Ug" +
               "cmVzdWx0SWRzLCBpdCBzaG91bGQgYWx3YXlzIGJlIHNldCB0byDigJxOQeKAnS4BAK58/////wAAAAAA" +
               "AAAAABkAAABIYXNUcmFuc2ZlcmFibGVEYXRhT25GaWxlApUAAABJbmRpY2F0ZXMgdGhhdCBhZGRpdGlv" +
               "bmFsIGRhdGEgZm9yIHRoaXMgcmVzdWx0IGNhbiBiZSByZXRyaWV2ZWQgYnkgdGVtcG9yYXJ5IGZpbGUg" +
               "dHJhbnNmZXIuCklmIG5vdCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0aGF0IG5vIGZpbGUgaXMgYXZh" +
               "aWxhYmxlLgAB/////wAAAAAAAAAAAQkAAABJc1BhcnRpYWwCuQAAAEluZGljYXRlcyB3aGV0aGVyIHRo" +
               "ZSByZXN1bHQgaXMgdGhlIHBhcnRpYWwgcmVzdWx0IG9mIGEgdG90YWwgcmVzdWx0LiBXaGVuIG5vdCBh" +
               "bGwgc2FtcGxlcyBhcmUgZmluaXNoZWQgeWV0IHRoZSByZXN1bHQgaXMgJ3BhcnRpYWwnLgpJZiBub3Qg" +
               "cHJvdmlkZWQsIGl0IGlzIGFzc3VtZWQgdG8gYmUgYSB0b3RhbCByZXN1bHQuAAH/////AAAAAAAAAAAB" +
               "CwAAAElzU2ltdWxhdGVkAuYAAABJbmRpY2F0ZXMgd2hldGhlciB0aGUgcmVzdWx0IHdhcyBjcmVhdGVk" +
               "IGluIHNpbXVsYXRpb24gbW9kZS4KU2ltdWxhdGlvbiBtb2RlIGltcGxpZXMgdGhhdCB0aGUgcmVzdWx0" +
               "IGlzIG9ubHkgZ2VuZXJhdGVkIGZvciB0ZXN0aW5nIHB1cnBvc2VzIGFuZCBub3QgYmFzZWQgb24gcmVh" +
               "bCBwcm9kdWN0aW9uIGRhdGEuCklmIG5vdCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0byBub3QgYmUg" +
               "c2ltdWxhdGVkLgAB/////wAAAAAAAAAAAQsAAABSZXN1bHRTdGF0ZQLuAQAAUmVzdWx0U3RhdGUgcHJv" +
               "dmlkZXMgaW5mb3JtYXRpb24gYWJvdXQgdGhlIGN1cnJlbnQgc3RhdGUgb2YgdGhlIHByb2Nlc3Mgb3Ig" +
               "bWVhc3VyZW1lbnQgY3JlYXRpbmcgYSByZXN1bHQuCkFwcGxpY2F0aW9ucyBtYXkgdXNlIG5lZ2F0aXZl" +
               "IHZhbHVlcyBmb3IgYXBwbGljYXRpb24tc3BlY2lmaWMgc3RhdGVzLiBBbGwgb3RoZXIgdmFsdWVzIHNo" +
               "YWxsIG9ubHkgYmUgdXNlZCBhcyBkZWZpbmVkIGluIHRoZSBmb2xsb3dpbmc6CjAg4oCTIFVuZGVmaW5l" +
               "ZCBpbml0aWFsIHZhbHVlCjEg4oCTIENvbXBsZXRlZDogUHJvY2Vzc2luZyB3YXMgY2FycmllZCBvdXQg" +
               "Y29tcGxldGVseQoyIOKAkyBQcm9jZXNzaW5nOiBQcm9jZXNzaW5nIGhhcyBub3QgYmVlbiBmaW5pc2hl" +
               "ZCB5ZXQKMyDigJMgQWJvcnRlZDogUHJvY2Vzc2luZyB3YXMgc3RvcHBlZCBhdCBzb21lIHBvaW50IGJl" +
               "Zm9yZSBjb21wbGV0aW9uCjQg4oCTIEZhaWxlZDogUHJvY2Vzc2luZyBmYWlsZWQgaW4gc29tZSB3YXkA" +
               "Bv////8AAAAAAAAAAAEGAAAAU3RlcElkAm4BAABJZGVudGlmaWVzIHRoZSBzdGVwIHdoaWNoIHByb2R1" +
               "Y2VkIHRoZSByZXN1bHQuCkFsdGhvdWdoIHRoZSBzeXN0ZW0td2lkZSB1bmlxdWUgSm9iSWQgd291bGQg" +
               "YmUgc3VmZmljaWVudCB0byBpZGVudGlmeSB0aGUgam9iIHdoaWNoIHRoZSByZXN1bHQgYmVsb25ncyB0" +
               "bywgdGhpcyBtYWtlcyBmb3IgZWFzaWVyIGZpbHRlcmluZyB3aXRob3V0IGtlZXBpbmcgdHJhY2sgb2Yg" +
               "Sm9iSWRzLgpUaGlzIHNwZWNpZmljYXRpb24gZG9lcyBub3QgZGVmaW5lIGhvdyB0aGUgc3RlcElkIGlz" +
               "IHRyYW5zbWl0dGVkIHRvIHRoZSBzeXN0ZW0uIFR5cGljYWxseSwgaXQgaXMgcHJvdmlkZWQgYnkgdGhl" +
               "IGNsaWVudCB3aGVuIHN0YXJ0aW5nIGFuIGV4ZWN1dGlvbi4BAK58/////wAAAAAAAAAAAQYAAABQYXJ0" +
               "SWQCagEAAElkZW50aWZpZXMgdGhlIHBhcnQgdXNlZCB0byBwcm9kdWNlIHRoZSByZXN1bHQuCkFsdGhv" +
               "dWdoIHRoZSBzeXN0ZW0td2lkZSB1bmlxdWUgSm9iSWQgd291bGQgYmUgc3VmZmljaWVudCB0byBpZGVu" +
               "dGlmeSB0aGUgam9iIHdoaWNoIHRoZSByZXN1bHQgYmVsb25ncyB0bywgdGhpcyBtYWtlcyBmb3IgZWFz" +
               "aWVyIGZpbHRlcmluZyB3aXRob3V0IGtlZXBpbmcgdHJhY2sgb2YgSm9iSWRzLgpUaGlzIHNwZWNpZmlj" +
               "YXRpb24gZG9lcyBub3QgZGVmaW5lIGhvdyB0aGUgcGFydElkIGlzIHRyYW5zbWl0dGVkIHRvIHRoZSBz" +
               "eXN0ZW0uIFR5cGljYWxseSwgaXQgaXMgcHJvdmlkZWQgYnkgdGhlIGNsaWVudCB3aGVuIHN0YXJ0aW5n" +
               "IHRoZSBqb2IuAQCufP////8AAAAAAAAAAAEQAAAARXh0ZXJuYWxSZWNpcGVJZALtAAAARXh0ZXJuYWwg" +
               "SUQgb2YgdGhlIHJlY2lwZSBpbiB1c2Ugd2hpY2ggcHJvZHVjZWQgdGhlIHJlc3VsdC4gVGhlIEV4dGVy" +
               "bmFsIElEIGlzIG1hbmFnZWQgYnkgdGhlIGVudmlyb25tZW50LgpUaGlzIHNwZWNpZmljYXRpb24gZG9l" +
               "cyBub3QgZGVmaW5lIGhvdyB0aGUgZXh0ZXJuYWxSZWNpcGVJZCBpcyB0cmFuc21pdHRlZCB0byB0aGUg" +
               "c3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3ZpZGVkIGJ5IHRoZSBjbGllbnQuAQCufP////8AAAAA" +
               "AAAAAAEQAAAASW50ZXJuYWxSZWNpcGVJZAJ7AAAASW50ZXJuYWwgSUQgb2YgdGhlIHJlY2lwZSBpbiB1" +
               "c2Ugd2hpY2ggcHJvZHVjZWQgdGhlIHJlc3VsdC4gVGhpcyBJRCBpcyBzeXN0ZW0td2lkZSB1bmlxdWUg" +
               "YW5kIGl0IGlzIGFzc2lnbmVkIGJ5IHRoZSBzeXN0ZW0uAQCufP////8AAAAAAAAAAAEJAAAAUHJvZHVj" +
               "dElkArUAAABJZGVudGlmaWVzIHRoZSBwcm9kdWN0IHVzZWQgdG8gcHJvZHVjZSB0aGUgcmVzdWx0LgpU" +
               "aGlzIHNwZWNpZmljYXRpb24gZG9lcyBub3QgZGVmaW5lIGhvdyB0aGUgZXh0ZXJuYWxSZWNpcGVJZCBp" +
               "cyB0cmFuc21pdHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3ZpZGVkIGJ5IHRo" +
               "ZSBjbGllbnQuAQCufP////8AAAAAAAAAAAEXAAAARXh0ZXJuYWxDb25maWd1cmF0aW9uSWQC8gAAAEV4" +
               "dGVybmFsIElEIG9mIHRoZSBDb25maWd1cmF0aW9uIGluIHVzZSB3aGlsZSB0aGUgcmVzdWx0IHdhcyBw" +
               "cm9kdWNlZC4KSXQgaXMgbWFuYWdlZCBieSB0aGUgRW52aXJvbm1lbnQuClRoaXMgc3BlY2lmaWNhdGlv" +
               "biBkb2VzIG5vdCBkZWZpbmUgaG93IHRoZSBleHRlcm5hbENvbmZpZ3VyYXRpb25JZCBpcyB0cmFuc21p" +
               "dHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3ZpZGVkIGJ5IHRoZSBjbGllbnQu" +
               "AQCufP////8AAAAAAAAAAAEXAAAASW50ZXJuYWxDb25maWd1cmF0aW9uSWQChgAAAEludGVybmFsIElE" +
               "IG9mIHRoZSBDb25maWd1cmF0aW9uIGluIHVzZSB3aGlsZSB0aGUgcmVzdWx0IHdhcyBwcm9kdWNlZC4g" +
               "VGhpcyBJRCBpcyBzeXN0ZW0td2lkZSB1bmlxdWUgYW5kIGl0IGlzIGFzc2lnbmVkIGJ5IHRoZSBzeXN0" +
               "ZW0uAQCufP////8AAAAAAAAAAAEFAAAASm9iSWQCbQAAAElkZW50aWZpZXMgdGhlIGpvYiB3aGljaCBw" +
               "cm9kdWNlZCB0aGUgcmVzdWx0LgpUaGlzIElEIGlzIHN5c3RlbS13aWRlIHVuaXF1ZSBhbmQgaXQgaXMg" +
               "YXNzaWduZWQgYnkgdGhlIHN5c3RlbS4BAK58/////wAAAAAAAAAAAQwAAABDcmVhdGlvblRpbWUCwAAA" +
               "AENyZWF0aW9uVGltZSBpbmRpY2F0ZXMgdGhlIHRpbWUgd2hlbiB0aGUgcmVzdWx0IHdhcyBjcmVhdGVk" +
               "LiBDcmVhdGlvbiB0aW1lIG9uIHRoZSBtZWFzdXJlbWVudCBzeXN0ZW0gKG5vdCB0aGUgcmVjZWl2ZSB0" +
               "aW1lIG9mIHRoZSBzZXJ2ZXIpLgpJdCBpcyByZWNvbW1lbmRlZCB0byBhbHdheXMgcHJvdmlkZSB0aGUg" +
               "Y3JlYXRpb25UaW1lLgEAJgH/////AAAAAAAAAAABDwAAAFByb2Nlc3NpbmdUaW1lcwJPAAAAQ29sbGVj" +
               "dGlvbiBvZiBkaWZmZXJlbnQgcHJvY2Vzc2luZyB0aW1lcyB0aGF0IHdlcmUgbmVlZGVkIHRvIGNyZWF0" +
               "ZSB0aGUgcmVzdWx0LgEBvgv/////AAAAAAAAAAABCQAAAFJlc3VsdFVyaQJDAAAAUGF0aCB0byB0aGUg" +
               "YWN0dWFsIG1lYXN1cmVkIHJlc3VsdCwgbWFuYWdlZCBleHRlcm5hbCB0byB0aGUgc2VydmVyLgEAx1wB" +
               "AAAAAQAAAAAAAAAAAAAAARAAAABSZXN1bHRFdmFsdWF0aW9uAkMAAABUaGUgUmVzdWx0RXZhbHVhdGlv" +
               "biBpbmRpY2F0ZXMgd2hldGhlciB0aGUgcmVzdWx0IHdhcyBpbiB0b2xlcmFuY2UuAQG6C/////8AAAAA" +
               "AAAAAAEUAAAAUmVzdWx0RXZhbHVhdGlvbkNvZGUCQQAAAFZlbmRvci1zcGVjaWZpYyBjb2RlIGRlc2Ny" +
               "aWJpbmcgbW9yZSBkZXRhaWxzIG9uIHJlc3VsdEV2YWx1YXRpb24uAAj/////AAAAAAAAAAABFwAAAFJl" +
               "c3VsdEV2YWx1YXRpb25EZXRhaWxzApAAAABUaGUgb3B0aW9uYWwgRXZhbHVhdGlvbkRldGFpbHMgcHJv" +
               "dmlkZXMgaGlnaCBsZXZlbCBzdGF0dXMgaW5mb3JtYXRpb24gaW4gYSB1c2VyLWZyaWVuZGx5IHRleHQu" +
               "IFRoaXMgY2FuIGJlIGxlZnQgZW1wdHkgZm9yIHN1Y2Nlc3NmdWwgb3BlcmF0aW9ucy4AFf////8AAAAA" +
               "AAAAAAEKAAAARmlsZUZvcm1hdAJEAQAAVGhlIGZvcm1hdCBpbiB3aGljaCB0aGUgbWVhc3VyZW1lbnQg" +
               "cmVzdWx0cyBhcmUgYXZhaWxhYmxlIChlLmcuIFFEQVMsIENTViwg4oCmKSB1c2luZyB0aGUgUmVzdWx0" +
               "VHJhbnNmZXIgT2JqZWN0LiBJZiBtdWx0aXBsZSBmaWxlIGZvcm1hdHMgYXJlIHByb3ZpZGVkLCB0aGUg" +
               "R2VuZXJhdGVGaWxlRm9yUmVhZCBvZiBSZXN1bHRUcmFuc2ZlciBzaG91bGQgY29udGFpbiBjb3JyZXNw" +
               "b25kaW5nIHRyYW5zZmVyT3B0aW9ucywgdG8gc2VsZWN0IHRoZSBmaWxlIGZvcm1hdC4gVGhpcyBzcGVj" +
               "aWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSB0aG9zZSB0cmFuc2Zlck9wdGlvbnMuAAwBAAAAAQAAAAAA" +
               "AAAAAAAAAQMAAAAAJgABAY0TACYAAQGXEwAmAAEBjhMAAAAANGAoEBAAAAABAAoAAABSZXN1bHRUeXBl" +
               "AQHRBwMAAAAASQAAAEV4cG9zZXMgdGhlIGluZm9ybWF0aW9uIG9mIHRoZSBSZXN1bHREYXRhVHlwZSBp" +
               "biBpbmRpdmlkdWFsIHN1YnZhcmlhYmxlcy4APxYBAZETAtsBAAA8UmVzdWx0RGF0YVR5cGUgeG1sbnM9" +
               "Imh0dHA6Ly9vcGNmb3VuZGF0aW9uLm9yZy9VQS9NYWNoaW5lcnkvUmVzdWx0L1R5cGVzLnhzZCI+PFJl" +
               "c3VsdE1ldGFEYXRhPjxUeXBlSWQgeG1sbnM9Imh0dHA6Ly9vcGNmb3VuZGF0aW9uLm9yZy9VQS8yMDA4" +
               "LzAyL1R5cGVzLnhzZCI+PElkZW50aWZpZXI+bnM9MTtpPTUwMDY8L0lkZW50aWZpZXI+PC9UeXBlSWQ+" +
               "PEJvZHkgeG1sbnM9Imh0dHA6Ly9vcGNmb3VuZGF0aW9uLm9yZy9VQS8yMDA4LzAyL1R5cGVzLnhzZCI+" +
               "PFJlc3VsdE1ldGFEYXRhVHlwZSB4bWxucz0iaHR0cDovL29wY2ZvdW5kYXRpb24ub3JnL1VBL01hY2hp" +
               "bmVyeS9SZXN1bHQvVHlwZXMueHNkIj48RW5jb2RpbmdNYXNrPjA8L0VuY29kaW5nTWFzaz48UmVzdWx0" +
               "SWQ+PC9SZXN1bHRJZD48L1Jlc3VsdE1ldGFEYXRhVHlwZT48L0JvZHk+PC9SZXN1bHRNZXRhRGF0YT48" +
               "UmVzdWx0Q29udGVudCAvPjwvUmVzdWx0RGF0YVR5cGU+AQHAC///////////AwAAABdgiQsCAAAAAQAU" +
               "AAAAUmVkdWNlZFJlc3VsdENvbnRlbnQBAXsXAC8APwBQexcAAAAYAQAAAAEAAAAAAAAAAwP/////AAAA" +
               "ABdgiQsCAAAAAQANAAAAUmVzdWx0Q29udGVudAEBehcBAEheAD8AUHoXAAAAGAEAAAABAAAAAAAAAAEB" +
               "/////wAAAAAVYIkLAgAAAAEADgAAAFJlc3VsdE1ldGFEYXRhAQF5FwEASF4APwBOeRcAAAEBvwv/////" +
               "AQH/////FAAAADVgiQsCAAAAAQAMAAAAQ3JlYXRpb25UaW1lAQGJFwMAAAAAwAAAAENyZWF0aW9uVGlt" +
               "ZSBpbmRpY2F0ZXMgdGhlIHRpbWUgd2hlbiB0aGUgcmVzdWx0IHdhcyBjcmVhdGVkLiBDcmVhdGlvbiB0" +
               "aW1lIG9uIHRoZSBtZWFzdXJlbWVudCBzeXN0ZW0gKG5vdCB0aGUgcmVjZWl2ZSB0aW1lIG9mIHRoZSBz" +
               "ZXJ2ZXIpLgpJdCBpcyByZWNvbW1lbmRlZCB0byBhbHdheXMgcHJvdmlkZSB0aGUgY3JlYXRpb25UaW1l" +
               "LgEASF4APwBQiRcAAAEAJgH/////AwP/////AAAAABVgqQsCAAAAAQAXAAAARXh0ZXJuYWxDb25maWd1" +
               "cmF0aW9uSWQBAYYXAQBIXgA/AFCGFwAADPIAAABFeHRlcm5hbCBJRCBvZiB0aGUgQ29uZmlndXJhdGlv" +
               "biBpbiB1c2Ugd2hpbGUgdGhlIHJlc3VsdCB3YXMgcHJvZHVjZWQuCkl0IGlzIG1hbmFnZWQgYnkgdGhl" +
               "IEVudmlyb25tZW50LgpUaGlzIHNwZWNpZmljYXRpb24gZG9lcyBub3QgZGVmaW5lIGhvdyB0aGUgZXh0" +
               "ZXJuYWxDb25maWd1cmF0aW9uSWQgaXMgdHJhbnNtaXR0ZWQgdG8gdGhlIHN5c3RlbS4gVHlwaWNhbGx5" +
               "LCBpdCBpcyBwcm92aWRlZCBieSB0aGUgY2xpZW50LgEArnz/////AwP/////AAAAADVgiQsCAAAAAQAQ" +
               "AAAARXh0ZXJuYWxSZWNpcGVJZAEBgxcDAAAAAO0AAABFeHRlcm5hbCBJRCBvZiB0aGUgcmVjaXBlIGlu" +
               "IHVzZSB3aGljaCBwcm9kdWNlZCB0aGUgcmVzdWx0LiBUaGUgRXh0ZXJuYWwgSUQgaXMgbWFuYWdlZCBi" +
               "eSB0aGUgZW52aXJvbm1lbnQuClRoaXMgc3BlY2lmaWNhdGlvbiBkb2VzIG5vdCBkZWZpbmUgaG93IHRo" +
               "ZSBleHRlcm5hbFJlY2lwZUlkIGlzIHRyYW5zbWl0dGVkIHRvIHRoZSBzeXN0ZW0uIFR5cGljYWxseSwg" +
               "aXQgaXMgcHJvdmlkZWQgYnkgdGhlIGNsaWVudC4BAEheAD8AUIMXAAABAK58/////wMD/////wAAAAA3" +
               "YIkLAgAAAAEACgAAAEZpbGVGb3JtYXQBAY8XAwAAAABEAQAAVGhlIGZvcm1hdCBpbiB3aGljaCB0aGUg" +
               "bWVhc3VyZW1lbnQgcmVzdWx0cyBhcmUgYXZhaWxhYmxlIChlLmcuIFFEQVMsIENTViwg4oCmKSB1c2lu" +
               "ZyB0aGUgUmVzdWx0VHJhbnNmZXIgT2JqZWN0LiBJZiBtdWx0aXBsZSBmaWxlIGZvcm1hdHMgYXJlIHBy" +
               "b3ZpZGVkLCB0aGUgR2VuZXJhdGVGaWxlRm9yUmVhZCBvZiBSZXN1bHRUcmFuc2ZlciBzaG91bGQgY29u" +
               "dGFpbiBjb3JyZXNwb25kaW5nIHRyYW5zZmVyT3B0aW9ucywgdG8gc2VsZWN0IHRoZSBmaWxlIGZvcm1h" +
               "dC4gVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSB0aG9zZSB0cmFuc2Zlck9wdGlvbnMu" +
               "AQBIXgA/AFCPFwAAAAwBAAAAAQAAAAAAAAADA/////8AAAAANWCJCwIAAAABABkAAABIYXNUcmFuc2Zl" +
               "cmFibGVEYXRhT25GaWxlAQF9FwMAAAAAlQAAAEluZGljYXRlcyB0aGF0IGFkZGl0aW9uYWwgZGF0YSBm" +
               "b3IgdGhpcyByZXN1bHQgY2FuIGJlIHJldHJpZXZlZCBieSB0ZW1wb3JhcnkgZmlsZSB0cmFuc2Zlci4K" +
               "SWYgbm90IHByb3ZpZGVkLCBpdCBpcyBhc3N1bWVkIHRoYXQgbm8gZmlsZSBpcyBhdmFpbGFibGUuAQBI" +
               "XgA/AFB9FwAAAAH/////AwP/////AAAAADVgiQsCAAAAAQAXAAAASW50ZXJuYWxDb25maWd1cmF0aW9u" +
               "SWQBAYcXAwAAAACGAAAASW50ZXJuYWwgSUQgb2YgdGhlIENvbmZpZ3VyYXRpb24gaW4gdXNlIHdoaWxl" +
               "IHRoZSByZXN1bHQgd2FzIHByb2R1Y2VkLiBUaGlzIElEIGlzIHN5c3RlbS13aWRlIHVuaXF1ZSBhbmQg" +
               "aXQgaXMgYXNzaWduZWQgYnkgdGhlIHN5c3RlbS4BAEheAD8AUIcXAAABAK58/////wMD/////wAAAAA1" +
               "YIkLAgAAAAEAEAAAAEludGVybmFsUmVjaXBlSWQBAYQXAwAAAAB7AAAASW50ZXJuYWwgSUQgb2YgdGhl" +
               "IHJlY2lwZSBpbiB1c2Ugd2hpY2ggcHJvZHVjZWQgdGhlIHJlc3VsdC4gVGhpcyBJRCBpcyBzeXN0ZW0t" +
               "d2lkZSB1bmlxdWUgYW5kIGl0IGlzIGFzc2lnbmVkIGJ5IHRoZSBzeXN0ZW0uAQBIXgA/AFCEFwAAAQCu" +
               "fP////8DA/////8AAAAANWCJCwIAAAABAAkAAABJc1BhcnRpYWwBAX4XAwAAAAC5AAAASW5kaWNhdGVz" +
               "IHdoZXRoZXIgdGhlIHJlc3VsdCBpcyB0aGUgcGFydGlhbCByZXN1bHQgb2YgYSB0b3RhbCByZXN1bHQu" +
               "IFdoZW4gbm90IGFsbCBzYW1wbGVzIGFyZSBmaW5pc2hlZCB5ZXQgdGhlIHJlc3VsdCBpcyAncGFydGlh" +
               "bCcuCklmIG5vdCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0byBiZSBhIHRvdGFsIHJlc3VsdC4BAEhe" +
               "AD8AUH4XAAAAAf////8DA/////8AAAAANWCJCwIAAAABAAsAAABJc1NpbXVsYXRlZAEBfxcDAAAAAOYA" +
               "AABJbmRpY2F0ZXMgd2hldGhlciB0aGUgcmVzdWx0IHdhcyBjcmVhdGVkIGluIHNpbXVsYXRpb24gbW9k" +
               "ZS4KU2ltdWxhdGlvbiBtb2RlIGltcGxpZXMgdGhhdCB0aGUgcmVzdWx0IGlzIG9ubHkgZ2VuZXJhdGVk" +
               "IGZvciB0ZXN0aW5nIHB1cnBvc2VzIGFuZCBub3QgYmFzZWQgb24gcmVhbCBwcm9kdWN0aW9uIGRhdGEu" +
               "CklmIG5vdCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0byBub3QgYmUgc2ltdWxhdGVkLgEASF4APwBQ" +
               "fxcAAAAB/////wMD/////wAAAAA1YIkLAgAAAAEABQAAAEpvYklkAQGIFwMAAAAAbQAAAElkZW50aWZp" +
               "ZXMgdGhlIGpvYiB3aGljaCBwcm9kdWNlZCB0aGUgcmVzdWx0LgpUaGlzIElEIGlzIHN5c3RlbS13aWRl" +
               "IHVuaXF1ZSBhbmQgaXQgaXMgYXNzaWduZWQgYnkgdGhlIHN5c3RlbS4BAEheAD8AUIgXAAABAK58////" +
               "/wMD/////wAAAAA1YIkLAgAAAAEABgAAAFBhcnRJZAEBghcDAAAAAGoBAABJZGVudGlmaWVzIHRoZSBw" +
               "YXJ0IHVzZWQgdG8gcHJvZHVjZSB0aGUgcmVzdWx0LgpBbHRob3VnaCB0aGUgc3lzdGVtLXdpZGUgdW5p" +
               "cXVlIEpvYklkIHdvdWxkIGJlIHN1ZmZpY2llbnQgdG8gaWRlbnRpZnkgdGhlIGpvYiB3aGljaCB0aGUg" +
               "cmVzdWx0IGJlbG9uZ3MgdG8sIHRoaXMgbWFrZXMgZm9yIGVhc2llciBmaWx0ZXJpbmcgd2l0aG91dCBr" +
               "ZWVwaW5nIHRyYWNrIG9mIEpvYklkcy4KVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBo" +
               "b3cgdGhlIHBhcnRJZCBpcyB0cmFuc21pdHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlz" +
               "IHByb3ZpZGVkIGJ5IHRoZSBjbGllbnQgd2hlbiBzdGFydGluZyB0aGUgam9iLgEASF4APwBQghcAAAEA" +
               "rnz/////AwP/////AAAAADVgqQsCAAAAAQAPAAAAUHJvY2Vzc2luZ1RpbWVzAQGKFwMAAAAATwAAAENv" +
               "bGxlY3Rpb24gb2YgZGlmZmVyZW50IHByb2Nlc3NpbmcgdGltZXMgdGhhdCB3ZXJlIG5lZWRlZCB0byBj" +
               "cmVhdGUgdGhlIHJlc3VsdC4BAEheAD8AUIoXAAAWAQGMEwLiAAAAPFByb2Nlc3NpbmdUaW1lc0RhdGFU" +
               "eXBlIHhtbG5zPSJodHRwOi8vb3BjZm91bmRhdGlvbi5vcmcvVUEvTWFjaGluZXJ5L1Jlc3VsdC9UeXBl" +
               "cy54c2QiPjxFbmNvZGluZ01hc2s+MDwvRW5jb2RpbmdNYXNrPjxTdGFydFRpbWU+MTkwMC0wMS0wMVQw" +
               "MDowMDowMFo8L1N0YXJ0VGltZT48RW5kVGltZT4xOTAwLTAxLTAxVDAwOjAwOjAwWjwvRW5kVGltZT48" +
               "L1Byb2Nlc3NpbmdUaW1lc0RhdGFUeXBlPgEBvgv/////AwP/////AAAAABVgqQsCAAAAAQAJAAAAUHJv" +
               "ZHVjdElkAQGFFwEASF4APwBQhRcAAAy1AAAASWRlbnRpZmllcyB0aGUgcHJvZHVjdCB1c2VkIHRvIHBy" +
               "b2R1Y2UgdGhlIHJlc3VsdC4KVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBob3cgdGhl" +
               "IGV4dGVybmFsUmVjaXBlSWQgaXMgdHJhbnNtaXR0ZWQgdG8gdGhlIHN5c3RlbS4gVHlwaWNhbGx5LCBp" +
               "dCBpcyBwcm92aWRlZCBieSB0aGUgY2xpZW50LgEArnz/////AwP/////AAAAADVgiQsCAAAAAQAQAAAA" +
               "UmVzdWx0RXZhbHVhdGlvbgEBjBcDAAAAAEMAAABUaGUgUmVzdWx0RXZhbHVhdGlvbiBpbmRpY2F0ZXMg" +
               "d2hldGhlciB0aGUgcmVzdWx0IHdhcyBpbiB0b2xlcmFuY2UuAQBIXgA/AFCMFwAAAQG6C/////8DA///" +
               "//8AAAAANWCpCwIAAAABABQAAABSZXN1bHRFdmFsdWF0aW9uQ29kZQEBjhcDAAAAAEEAAABWZW5kb3It" +
               "c3BlY2lmaWMgY29kZSBkZXNjcmliaW5nIG1vcmUgZGV0YWlscyBvbiByZXN1bHRFdmFsdWF0aW9uLgEA" +
               "SF4APwBQjhcAAAgAAAAAAAAAAAAI/////wMD/////wAAAAA1YIkLAgAAAAEAFwAAAFJlc3VsdEV2YWx1" +
               "YXRpb25EZXRhaWxzAQGNFwMAAAAAkAAAAFRoZSBvcHRpb25hbCBFdmFsdWF0aW9uRGV0YWlscyBwcm92" +
               "aWRlcyBoaWdoIGxldmVsIHN0YXR1cyBpbmZvcm1hdGlvbiBpbiBhIHVzZXItZnJpZW5kbHkgdGV4dC4g" +
               "VGhpcyBjYW4gYmUgbGVmdCBlbXB0eSBmb3Igc3VjY2Vzc2Z1bCBvcGVyYXRpb25zLgEASF4APwBQjRcA" +
               "AAAV/////wMD/////wAAAAA1YIkLAgAAAAEACAAAAFJlc3VsdElkAQF8FwMAAAAAIgEAAFN5c3RlbS13" +
               "aWRlIHVuaXF1ZSBpZGVudGlmaWVyLCB3aGljaCBpcyBhc3NpZ25lZCBieSB0aGUgc3lzdGVtLiBUaGlz" +
               "IElEIGNhbiBiZSB1c2VkIGZvciBmZXRjaGluZyBleGFjdGx5IHRoaXMgcmVzdWx0IHVzaW5nIHRoZSBt" +
               "ZXRob2QgR2V0UmVzdWx0QnlJZCBhbmQgaXQgaXMgaWRlbnRpY2FsIHRvIHRoZSBSZXN1bHRJZCBvZiB0" +
               "aGUgUmVzdWx0UmVhZHlFdmVudFR5cGUuCklmIHRoZSBzeXN0ZW0gZG9lcyBub3QgbWFuYWdlIHJlc3Vs" +
               "dElkcywgaXQgc2hvdWxkIGFsd2F5cyBiZSBzZXQgdG8g4oCcTkHigJ0uAQBIXgA/AE58FwAAAQCufP//" +
               "//8DA/////8AAAAANWCJCwIAAAABAAsAAABSZXN1bHRTdGF0ZQEBgBcDAAAAAO8BAABSZXN1bHRTdGF0" +
               "ZSBwcm92aWRlcyBpbmZvcm1hdGlvbiBhYm91dCB0aGUgY3VycmVudCBzdGF0ZSBvZiB0aGUgcHJvY2Vz" +
               "cyBvciBtZWFzdXJlbWVudCBjcmVhdGluZyBhIHJlc3VsdC4KQXBwbGljYXRpb25zIG1heSB1c2UgbmVn" +
               "YXRpdmUgdmFsdWVzIGZvciBhcHBsaWNhdGlvbi1zcGVjaWZpYyBzdGF0ZXMuIEFsbCBvdGhlciB2YWx1" +
               "ZXMgc2hhbGwgb25seSBiZSB1c2VkIGFzIGRlZmluZWQgaW4gdGhlIGZvbGxvd2luZzoKMCDigJMgVW5k" +
               "ZWZpbmVkIGluaXRpYWwgdmFsdWUKMSDigJMgQ29tcGxldGVkOiBQcm9jZXNzaW5nIHdhcyBjYXJyaWVk" +
               "IG91dCBjb21wbGV0ZWx5CjIg4oCTIFByb2Nlc3Npbmc6IFByb2Nlc3NpbmcgaGFzIG5vdCBiZWVuIGZp" +
               "bmlzaGVkIHlldAozIOKAkyBBYm9ydGVkOiBQcm9jZXNzaW5nIHdhcyBzdG9wcGVkIGF0IHNvbWUgcG9p" +
               "bnQgYmVmb3JlIGNvbXBsZXRpb24KNCDigJMgRmFpbGVkOiBQcm9jZXNzaW5nIGZhaWxlZCBpbiBzb21l" +
               "IHdheS4BAEheAD8AUIAXAAAABv////8DA/////8AAAAAN2CJCwIAAAABAAkAAABSZXN1bHRVcmkBAYsX" +
               "AwAAAABDAAAAUGF0aCB0byB0aGUgYWN0dWFsIG1lYXN1cmVkIHJlc3VsdCwgbWFuYWdlZCBleHRlcm5h" +
               "bCB0byB0aGUgc2VydmVyLgEASF4APwBQixcAAAEAx1wBAAAAAQAAAAAAAAADA/////8AAAAANWCJCwIA" +
               "AAABAAYAAABTdGVwSWQBAYEXAwAAAABuAQAASWRlbnRpZmllcyB0aGUgc3RlcCB3aGljaCBwcm9kdWNl" +
               "ZCB0aGUgcmVzdWx0LgpBbHRob3VnaCB0aGUgc3lzdGVtLXdpZGUgdW5pcXVlIEpvYklkIHdvdWxkIGJl" +
               "IHN1ZmZpY2llbnQgdG8gaWRlbnRpZnkgdGhlIGpvYiB3aGljaCB0aGUgcmVzdWx0IGJlbG9uZ3MgdG8s" +
               "IHRoaXMgbWFrZXMgZm9yIGVhc2llciBmaWx0ZXJpbmcgd2l0aG91dCBrZWVwaW5nIHRyYWNrIG9mIEpv" +
               "Yklkcy4KVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBob3cgdGhlIHN0ZXBJZCBpcyB0" +
               "cmFuc21pdHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3ZpZGVkIGJ5IHRoZSBj" +
               "bGllbnQgd2hlbiBzdGFydGluZyBhbiBleGVjdXRpb24uAQBIXgA/AFCBFwAAAQCufP////8DA/////8A" +
               "AAAAJGgAEAgAAAABABQAAABSZXN1bHRSZWFkeUV2ZW50VHlwZQEB6gMDAAAAADUAAABQcm92aWRlcyBp" +
               "bmZvcm1hdGlvbiBvZiBhIGNvbXBsZXRlIG9yIHBhcnRpYWwgcmVzdWx0LgEA+QcBAQAAAAApAQEB7AMB" +
               "AAAAFWCpCwIAAAABAAYAAABSZXN1bHQBAZAXAC8BAdEHAE6QFwAAFgEBkRMC2wEAADxSZXN1bHREYXRh" +
               "VHlwZSB4bWxucz0iaHR0cDovL29wY2ZvdW5kYXRpb24ub3JnL1VBL01hY2hpbmVyeS9SZXN1bHQvVHlw" +
               "ZXMueHNkIj48UmVzdWx0TWV0YURhdGE+PFR5cGVJZCB4bWxucz0iaHR0cDovL29wY2ZvdW5kYXRpb24u" +
               "b3JnL1VBLzIwMDgvMDIvVHlwZXMueHNkIj48SWRlbnRpZmllcj5ucz0xO2k9NTAwNjwvSWRlbnRpZmll" +
               "cj48L1R5cGVJZD48Qm9keSB4bWxucz0iaHR0cDovL29wY2ZvdW5kYXRpb24ub3JnL1VBLzIwMDgvMDIv" +
               "VHlwZXMueHNkIj48UmVzdWx0TWV0YURhdGFUeXBlIHhtbG5zPSJodHRwOi8vb3BjZm91bmRhdGlvbi5v" +
               "cmcvVUEvTWFjaGluZXJ5L1Jlc3VsdC9UeXBlcy54c2QiPjxFbmNvZGluZ01hc2s+MDwvRW5jb2RpbmdN" +
               "YXNrPjxSZXN1bHRJZD48L1Jlc3VsdElkPjwvUmVzdWx0TWV0YURhdGFUeXBlPjwvQm9keT48L1Jlc3Vs" +
               "dE1ldGFEYXRhPjxSZXN1bHRDb250ZW50IC8+PC9SZXN1bHREYXRhVHlwZT4BAcAL/////wMD/////wEA" +
               "AAAVYIkLAgAAAAEADgAAAFJlc3VsdE1ldGFEYXRhAQGRFwEASF4APwBOkRcAAAEBvwv/////AQH/////" +
               "FAAAADVgiQsCAAAAAQAMAAAAQ3JlYXRpb25UaW1lAQGoFwMAAAAAwAAAAENyZWF0aW9uVGltZSBpbmRp" +
               "Y2F0ZXMgdGhlIHRpbWUgd2hlbiB0aGUgcmVzdWx0IHdhcyBjcmVhdGVkLiBDcmVhdGlvbiB0aW1lIG9u" +
               "IHRoZSBtZWFzdXJlbWVudCBzeXN0ZW0gKG5vdCB0aGUgcmVjZWl2ZSB0aW1lIG9mIHRoZSBzZXJ2ZXIp" +
               "LgpJdCBpcyByZWNvbW1lbmRlZCB0byBhbHdheXMgcHJvdmlkZSB0aGUgY3JlYXRpb25UaW1lLgEASF4A" +
               "PwBQqBcAAAEAJgH/////AwP/////AAAAABVgqQsCAAAAAQAXAAAARXh0ZXJuYWxDb25maWd1cmF0aW9u" +
               "SWQBAakXAQBIXgA/AFCpFwAADPIAAABFeHRlcm5hbCBJRCBvZiB0aGUgQ29uZmlndXJhdGlvbiBpbiB1" +
               "c2Ugd2hpbGUgdGhlIHJlc3VsdCB3YXMgcHJvZHVjZWQuCkl0IGlzIG1hbmFnZWQgYnkgdGhlIEVudmly" +
               "b25tZW50LgpUaGlzIHNwZWNpZmljYXRpb24gZG9lcyBub3QgZGVmaW5lIGhvdyB0aGUgZXh0ZXJuYWxD" +
               "b25maWd1cmF0aW9uSWQgaXMgdHJhbnNtaXR0ZWQgdG8gdGhlIHN5c3RlbS4gVHlwaWNhbGx5LCBpdCBp" +
               "cyBwcm92aWRlZCBieSB0aGUgY2xpZW50LgEArnz/////AwP/////AAAAADVgiQsCAAAAAQAQAAAARXh0" +
               "ZXJuYWxSZWNpcGVJZAEBqhcDAAAAAO0AAABFeHRlcm5hbCBJRCBvZiB0aGUgcmVjaXBlIGluIHVzZSB3" +
               "aGljaCBwcm9kdWNlZCB0aGUgcmVzdWx0LiBUaGUgRXh0ZXJuYWwgSUQgaXMgbWFuYWdlZCBieSB0aGUg" +
               "ZW52aXJvbm1lbnQuClRoaXMgc3BlY2lmaWNhdGlvbiBkb2VzIG5vdCBkZWZpbmUgaG93IHRoZSBleHRl" +
               "cm5hbFJlY2lwZUlkIGlzIHRyYW5zbWl0dGVkIHRvIHRoZSBzeXN0ZW0uIFR5cGljYWxseSwgaXQgaXMg" +
               "cHJvdmlkZWQgYnkgdGhlIGNsaWVudC4BAEheAD8AUKoXAAABAK58/////wMD/////wAAAAA3YIkLAgAA" +
               "AAEACgAAAEZpbGVGb3JtYXQBAasXAwAAAABEAQAAVGhlIGZvcm1hdCBpbiB3aGljaCB0aGUgbWVhc3Vy" +
               "ZW1lbnQgcmVzdWx0cyBhcmUgYXZhaWxhYmxlIChlLmcuIFFEQVMsIENTViwg4oCmKSB1c2luZyB0aGUg" +
               "UmVzdWx0VHJhbnNmZXIgT2JqZWN0LiBJZiBtdWx0aXBsZSBmaWxlIGZvcm1hdHMgYXJlIHByb3ZpZGVk" +
               "LCB0aGUgR2VuZXJhdGVGaWxlRm9yUmVhZCBvZiBSZXN1bHRUcmFuc2ZlciBzaG91bGQgY29udGFpbiBj" +
               "b3JyZXNwb25kaW5nIHRyYW5zZmVyT3B0aW9ucywgdG8gc2VsZWN0IHRoZSBmaWxlIGZvcm1hdC4gVGhp" +
               "cyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSB0aG9zZSB0cmFuc2Zlck9wdGlvbnMuAQBIXgA/" +
               "AFCrFwAAAAwBAAAAAQAAAAAAAAADA/////8AAAAANWCJCwIAAAABABkAAABIYXNUcmFuc2ZlcmFibGVE" +
               "YXRhT25GaWxlAQGsFwMAAAAAlQAAAEluZGljYXRlcyB0aGF0IGFkZGl0aW9uYWwgZGF0YSBmb3IgdGhp" +
               "cyByZXN1bHQgY2FuIGJlIHJldHJpZXZlZCBieSB0ZW1wb3JhcnkgZmlsZSB0cmFuc2Zlci4KSWYgbm90" +
               "IHByb3ZpZGVkLCBpdCBpcyBhc3N1bWVkIHRoYXQgbm8gZmlsZSBpcyBhdmFpbGFibGUuAQBIXgA/AFCs" +
               "FwAAAAH/////AwP/////AAAAADVgiQsCAAAAAQAXAAAASW50ZXJuYWxDb25maWd1cmF0aW9uSWQBAa0X" +
               "AwAAAACGAAAASW50ZXJuYWwgSUQgb2YgdGhlIENvbmZpZ3VyYXRpb24gaW4gdXNlIHdoaWxlIHRoZSBy" +
               "ZXN1bHQgd2FzIHByb2R1Y2VkLiBUaGlzIElEIGlzIHN5c3RlbS13aWRlIHVuaXF1ZSBhbmQgaXQgaXMg" +
               "YXNzaWduZWQgYnkgdGhlIHN5c3RlbS4BAEheAD8AUK0XAAABAK58/////wMD/////wAAAAA1YIkLAgAA" +
               "AAEAEAAAAEludGVybmFsUmVjaXBlSWQBAa4XAwAAAAB7AAAASW50ZXJuYWwgSUQgb2YgdGhlIHJlY2lw" +
               "ZSBpbiB1c2Ugd2hpY2ggcHJvZHVjZWQgdGhlIHJlc3VsdC4gVGhpcyBJRCBpcyBzeXN0ZW0td2lkZSB1" +
               "bmlxdWUgYW5kIGl0IGlzIGFzc2lnbmVkIGJ5IHRoZSBzeXN0ZW0uAQBIXgA/AFCuFwAAAQCufP////8D" +
               "A/////8AAAAANWCJCwIAAAABAAkAAABJc1BhcnRpYWwBAa8XAwAAAAC5AAAASW5kaWNhdGVzIHdoZXRo" +
               "ZXIgdGhlIHJlc3VsdCBpcyB0aGUgcGFydGlhbCByZXN1bHQgb2YgYSB0b3RhbCByZXN1bHQuIFdoZW4g" +
               "bm90IGFsbCBzYW1wbGVzIGFyZSBmaW5pc2hlZCB5ZXQgdGhlIHJlc3VsdCBpcyAncGFydGlhbCcuCklm" +
               "IG5vdCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0byBiZSBhIHRvdGFsIHJlc3VsdC4BAEheAD8AUK8X" +
               "AAAAAf////8DA/////8AAAAANWCJCwIAAAABAAsAAABJc1NpbXVsYXRlZAEBsBcDAAAAAOYAAABJbmRp" +
               "Y2F0ZXMgd2hldGhlciB0aGUgcmVzdWx0IHdhcyBjcmVhdGVkIGluIHNpbXVsYXRpb24gbW9kZS4KU2lt" +
               "dWxhdGlvbiBtb2RlIGltcGxpZXMgdGhhdCB0aGUgcmVzdWx0IGlzIG9ubHkgZ2VuZXJhdGVkIGZvciB0" +
               "ZXN0aW5nIHB1cnBvc2VzIGFuZCBub3QgYmFzZWQgb24gcmVhbCBwcm9kdWN0aW9uIGRhdGEuCklmIG5v" +
               "dCBwcm92aWRlZCwgaXQgaXMgYXNzdW1lZCB0byBub3QgYmUgc2ltdWxhdGVkLgEASF4APwBQsBcAAAAB" +
               "/////wMD/////wAAAAA1YIkLAgAAAAEABQAAAEpvYklkAQGxFwMAAAAAbQAAAElkZW50aWZpZXMgdGhl" +
               "IGpvYiB3aGljaCBwcm9kdWNlZCB0aGUgcmVzdWx0LgpUaGlzIElEIGlzIHN5c3RlbS13aWRlIHVuaXF1" +
               "ZSBhbmQgaXQgaXMgYXNzaWduZWQgYnkgdGhlIHN5c3RlbS4BAEheAD8AULEXAAABAK58/////wMD////" +
               "/wAAAAA1YIkLAgAAAAEABgAAAFBhcnRJZAEBshcDAAAAAGoBAABJZGVudGlmaWVzIHRoZSBwYXJ0IHVz" +
               "ZWQgdG8gcHJvZHVjZSB0aGUgcmVzdWx0LgpBbHRob3VnaCB0aGUgc3lzdGVtLXdpZGUgdW5pcXVlIEpv" +
               "YklkIHdvdWxkIGJlIHN1ZmZpY2llbnQgdG8gaWRlbnRpZnkgdGhlIGpvYiB3aGljaCB0aGUgcmVzdWx0" +
               "IGJlbG9uZ3MgdG8sIHRoaXMgbWFrZXMgZm9yIGVhc2llciBmaWx0ZXJpbmcgd2l0aG91dCBrZWVwaW5n" +
               "IHRyYWNrIG9mIEpvYklkcy4KVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBob3cgdGhl" +
               "IHBhcnRJZCBpcyB0cmFuc21pdHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3Zp" +
               "ZGVkIGJ5IHRoZSBjbGllbnQgd2hlbiBzdGFydGluZyB0aGUgam9iLgEASF4APwBQshcAAAEArnz/////" +
               "AwP/////AAAAADVgqQsCAAAAAQAPAAAAUHJvY2Vzc2luZ1RpbWVzAQGzFwMAAAAATwAAAENvbGxlY3Rp" +
               "b24gb2YgZGlmZmVyZW50IHByb2Nlc3NpbmcgdGltZXMgdGhhdCB3ZXJlIG5lZWRlZCB0byBjcmVhdGUg" +
               "dGhlIHJlc3VsdC4BAEheAD8AULMXAAAWAQGMEwLiAAAAPFByb2Nlc3NpbmdUaW1lc0RhdGFUeXBlIHht" +
               "bG5zPSJodHRwOi8vb3BjZm91bmRhdGlvbi5vcmcvVUEvTWFjaGluZXJ5L1Jlc3VsdC9UeXBlcy54c2Qi" +
               "PjxFbmNvZGluZ01hc2s+MDwvRW5jb2RpbmdNYXNrPjxTdGFydFRpbWU+MTkwMC0wMS0wMVQwMDowMDow" +
               "MFo8L1N0YXJ0VGltZT48RW5kVGltZT4xOTAwLTAxLTAxVDAwOjAwOjAwWjwvRW5kVGltZT48L1Byb2Nl" +
               "c3NpbmdUaW1lc0RhdGFUeXBlPgEBvgv/////AwP/////AAAAABVgqQsCAAAAAQAJAAAAUHJvZHVjdElk" +
               "AQG0FwEASF4APwBQtBcAAAy1AAAASWRlbnRpZmllcyB0aGUgcHJvZHVjdCB1c2VkIHRvIHByb2R1Y2Ug" +
               "dGhlIHJlc3VsdC4KVGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBob3cgdGhlIGV4dGVy" +
               "bmFsUmVjaXBlSWQgaXMgdHJhbnNtaXR0ZWQgdG8gdGhlIHN5c3RlbS4gVHlwaWNhbGx5LCBpdCBpcyBw" +
               "cm92aWRlZCBieSB0aGUgY2xpZW50LgEArnz/////AwP/////AAAAADVgiQsCAAAAAQAQAAAAUmVzdWx0" +
               "RXZhbHVhdGlvbgEBtRcDAAAAAEMAAABUaGUgUmVzdWx0RXZhbHVhdGlvbiBpbmRpY2F0ZXMgd2hldGhl" +
               "ciB0aGUgcmVzdWx0IHdhcyBpbiB0b2xlcmFuY2UuAQBIXgA/AFC1FwAAAQG6C/////8DA/////8AAAAA" +
               "NWCpCwIAAAABABQAAABSZXN1bHRFdmFsdWF0aW9uQ29kZQEBthcDAAAAAEEAAABWZW5kb3Itc3BlY2lm" +
               "aWMgY29kZSBkZXNjcmliaW5nIG1vcmUgZGV0YWlscyBvbiByZXN1bHRFdmFsdWF0aW9uLgEASF4APwBQ" +
               "thcAAAgAAAAAAAAAAAAI/////wMD/////wAAAAA1YIkLAgAAAAEAFwAAAFJlc3VsdEV2YWx1YXRpb25E" +
               "ZXRhaWxzAQG3FwMAAAAAkAAAAFRoZSBvcHRpb25hbCBFdmFsdWF0aW9uRGV0YWlscyBwcm92aWRlcyBo" +
               "aWdoIGxldmVsIHN0YXR1cyBpbmZvcm1hdGlvbiBpbiBhIHVzZXItZnJpZW5kbHkgdGV4dC4gVGhpcyBj" +
               "YW4gYmUgbGVmdCBlbXB0eSBmb3Igc3VjY2Vzc2Z1bCBvcGVyYXRpb25zLgEASF4APwBQtxcAAAAV////" +
               "/wMD/////wAAAAA1YIkLAgAAAAEACAAAAFJlc3VsdElkAQGSFwMAAAAAIgEAAFN5c3RlbS13aWRlIHVu" +
               "aXF1ZSBpZGVudGlmaWVyLCB3aGljaCBpcyBhc3NpZ25lZCBieSB0aGUgc3lzdGVtLiBUaGlzIElEIGNh" +
               "biBiZSB1c2VkIGZvciBmZXRjaGluZyBleGFjdGx5IHRoaXMgcmVzdWx0IHVzaW5nIHRoZSBtZXRob2Qg" +
               "R2V0UmVzdWx0QnlJZCBhbmQgaXQgaXMgaWRlbnRpY2FsIHRvIHRoZSBSZXN1bHRJZCBvZiB0aGUgUmVz" +
               "dWx0UmVhZHlFdmVudFR5cGUuCklmIHRoZSBzeXN0ZW0gZG9lcyBub3QgbWFuYWdlIHJlc3VsdElkcywg" +
               "aXQgc2hvdWxkIGFsd2F5cyBiZSBzZXQgdG8g4oCcTkHigJ0uAQBIXgA/AE6SFwAAAQCufP////8DA///" +
               "//8AAAAANWCJCwIAAAABAAsAAABSZXN1bHRTdGF0ZQEBuBcDAAAAAO8BAABSZXN1bHRTdGF0ZSBwcm92" +
               "aWRlcyBpbmZvcm1hdGlvbiBhYm91dCB0aGUgY3VycmVudCBzdGF0ZSBvZiB0aGUgcHJvY2VzcyBvciBt" +
               "ZWFzdXJlbWVudCBjcmVhdGluZyBhIHJlc3VsdC4KQXBwbGljYXRpb25zIG1heSB1c2UgbmVnYXRpdmUg" +
               "dmFsdWVzIGZvciBhcHBsaWNhdGlvbi1zcGVjaWZpYyBzdGF0ZXMuIEFsbCBvdGhlciB2YWx1ZXMgc2hh" +
               "bGwgb25seSBiZSB1c2VkIGFzIGRlZmluZWQgaW4gdGhlIGZvbGxvd2luZzoKMCDigJMgVW5kZWZpbmVk" +
               "IGluaXRpYWwgdmFsdWUKMSDigJMgQ29tcGxldGVkOiBQcm9jZXNzaW5nIHdhcyBjYXJyaWVkIG91dCBj" +
               "b21wbGV0ZWx5CjIg4oCTIFByb2Nlc3Npbmc6IFByb2Nlc3NpbmcgaGFzIG5vdCBiZWVuIGZpbmlzaGVk" +
               "IHlldAozIOKAkyBBYm9ydGVkOiBQcm9jZXNzaW5nIHdhcyBzdG9wcGVkIGF0IHNvbWUgcG9pbnQgYmVm" +
               "b3JlIGNvbXBsZXRpb24KNCDigJMgRmFpbGVkOiBQcm9jZXNzaW5nIGZhaWxlZCBpbiBzb21lIHdheS4B" +
               "AEheAD8AULgXAAAABv////8DA/////8AAAAAN2CJCwIAAAABAAkAAABSZXN1bHRVcmkBAbkXAwAAAABD" +
               "AAAAUGF0aCB0byB0aGUgYWN0dWFsIG1lYXN1cmVkIHJlc3VsdCwgbWFuYWdlZCBleHRlcm5hbCB0byB0" +
               "aGUgc2VydmVyLgEASF4APwBQuRcAAAEAx1wBAAAAAQAAAAAAAAADA/////8AAAAANWCJCwIAAAABAAYA" +
               "AABTdGVwSWQBAboXAwAAAABuAQAASWRlbnRpZmllcyB0aGUgc3RlcCB3aGljaCBwcm9kdWNlZCB0aGUg" +
               "cmVzdWx0LgpBbHRob3VnaCB0aGUgc3lzdGVtLXdpZGUgdW5pcXVlIEpvYklkIHdvdWxkIGJlIHN1ZmZp" +
               "Y2llbnQgdG8gaWRlbnRpZnkgdGhlIGpvYiB3aGljaCB0aGUgcmVzdWx0IGJlbG9uZ3MgdG8sIHRoaXMg" +
               "bWFrZXMgZm9yIGVhc2llciBmaWx0ZXJpbmcgd2l0aG91dCBrZWVwaW5nIHRyYWNrIG9mIEpvYklkcy4K" +
               "VGhpcyBzcGVjaWZpY2F0aW9uIGRvZXMgbm90IGRlZmluZSBob3cgdGhlIHN0ZXBJZCBpcyB0cmFuc21p" +
               "dHRlZCB0byB0aGUgc3lzdGVtLiBUeXBpY2FsbHksIGl0IGlzIHByb3ZpZGVkIGJ5IHRoZSBjbGllbnQg" +
               "d2hlbiBzdGFydGluZyBhbiBleGVjdXRpb24uAQBIXgA/AFC6FwAAAQCufP////8DA/////8AAAAAJGAA" +
               "EAgAAAABABQAAABSZXN1bHRNYW5hZ2VtZW50VHlwZQEB7AMDAAAAAEgAAABQcm92aWRlcyBtZWNoYW5p" +
               "c20gdG8gYWNjZXNzIHJlc3VsdHMgZ2VuZXJhdGVkIGJ5IHRoZSB1bmRlcmx5aW5nIHN5c3RlbS4AOgEA" +
               "AAAAKQABAeoDCAAAAARhggsEAAAAAQASAAAAQWNrbm93bGVkZ2VSZXN1bHRzAQFhGwAvAQFhGwBQYRsA" +
               "AAEB/////wIAAAAXYKkLAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQHJFwAuAEQATskXAACWAQAAAAEA" +
               "KgEBUAAAAAkAAABSZXN1bHRJZHMBAK58AQAAAAEAAAAAAAAAAi4AAABMaXN0IG9mIHJlc3VsdCBpZGVu" +
               "dGlmaWVycyB0byBiZSBhY2tub3dsZWRnZWQuAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAXYKkLAgAA" +
               "AAAADwAAAE91dHB1dEFyZ3VtZW50cwEByhcALgBEAE7KFwAAlgIAAAABACoBAXUBAAAQAAAARXJyb3JQ" +
               "ZXJSZXN1bHRJZAAGAQAAAAEAAAAAAAAAAk4BAABTaGFsbCBiZSBudWxsIG9yIGVtcHR5IGlmIGVycm9y" +
               "IGVxdWFscyAwLiBTaGFsbCBoYXZlIHRoZSBzYW1lIGxlbmd0aCBhcyByZXN1bHRJZHMgaWYgZXJyb3Ig" +
               "aXMgbm90IGVxdWFsIDAuIEluZGljYXRlcyBmb3IgZWFjaCByZXN1bHRJZCBpbiByZXN1bHRJZHMsIGlm" +
               "IHRoZSBhY2tub3dsZWRnZSB3YXMgc3VjY2Vzc2Z1bC4KUGVyIGVudHJ5OgowIOKAkyBPSwpWYWx1ZXMg" +
               "PiAwIGFyZSByZXNlcnZlZCBmb3IgZXJyb3JzIGRlZmluZWQgYnkgdGhpcyBhbmQgZnV0dXJlIHN0YW5k" +
               "YXJkcy4KVmFsdWVzIDwgMCBzaGFsbCBiZSB1c2VkIGZvciBhcHBsaWNhdGlvbi1zcGVjaWZpYyBlcnJv" +
               "cnMuAQAqAQEzAQAABQAAAEVycm9yAAb/////AAAAAAIbAQAAMCDigJMgT0sKVmFsdWVzID4gMCBhcmUg" +
               "cmVzZXJ2ZWQgZm9yIGVycm9ycyBkZWZpbmVkIGJ5IHRoaXMgYW5kIGZ1dHVyZSBzdGFuZGFyZHMuClZh" +
               "bHVlcyA8IDAgc2hhbGwgYmUgdXNlZCBmb3IgYXBwbGljYXRpb24tc3BlY2lmaWMgZXJyb3JzLgpTaGFs" +
               "bCBiZSBub3QgZXF1YWwgMCBpZiBhbnkgcmVzdWx0SWQgb2YgcmVzdWx0SWRzIHdhcyBub3Qgc3VjY2Vz" +
               "c2Z1bGx5IGFja25vd2xlZGdlZC4gU2hhbGwgYmUgMCBpZiBhbGwgcmVzdWx0SWRzIHdoZXJlIGFja25v" +
               "d2xlZGdlZCBzdWNjZXNzZnVsLgEAKAEBAAAAAQAAAAIAAAABAf////8AAAAANWCpCgIAAAAAABkAAABE" +
               "ZWZhdWx0SW5zdGFuY2VCcm93c2VOYW1lAQGVFwMAAAAAMQAAAFRoZSBkZWZhdWx0IEJyb3dzZU5hbWUg" +
               "Zm9yIGluc3RhbmNlcyBvZiB0aGUgdHlwZS4ALgBElRcAABQBABAAAABSZXN1bHRNYW5hZ2VtZW50ABT/" +
               "////AwP/////AAAAAARhggsEAAAAAQAPAAAAR2V0TGF0ZXN0UmVzdWx0AQFgGwAvAQFgGwBQYBsAAAEB" +
               "/////wIAAAAXYKkLAgAAAAAADgAAAElucHV0QXJndW1lbnRzAQGmFwAuAEQATqYXAACWAQAAAAEAKgEB" +
               "NgIAAAcAAABUaW1lb3V0AAb/////AAAAAAIcAgAAV2l0aCB0aGlzIGFyZ3VtZW50IHRoZSBjbGllbnQg" +
               "Y2FuIGdpdmUgYSBoaW50IHRvIHRoZSBzZXJ2ZXIgaG93IGxvbmcgaXQgd2lsbCBuZWVkIGFjY2VzcyB0" +
               "byB0aGUgcmVzdWx0IGRhdGEuCkEgdmFsdWUgPiAwIGluZGljYXRlcyBhbiBlc3RpbWF0ZWQgbWF4aW11" +
               "bSB0aW1lIGZvciBwcm9jZXNzaW5nIHRoZSBkYXRhIGluIG1pbGxpc2Vjb25kcy4gCkEgdmFsdWUgPSAw" +
               "IGluZGljYXRlcyB0aGF0IHRoZSBjbGllbnQgd2lsbCBub3QgbmVlZCBhbnl0aGluZyBiZXNpZGVzIHRo" +
               "ZSBkYXRhIHJldHVybmVkIGJ5IHRoZSBtZXRob2QgY2FsbC4KQSB2YWx1ZSA8IDAgaW5kaWNhdGVzIHRo" +
               "YXQgdGhlIGNsaWVudCBjYW5ub3QgZ2l2ZSBhbiBlc3RpbWF0ZS4KVGhlIGNsaWVudCBjYW5ub3QgcmVs" +
               "eSBvbiB0aGUgZGF0YSBiZWluZyBhdmFpbGFibGUgZHVyaW5nIHRoZSBpbmRpY2F0ZWQgdGltZSBwZXJp" +
               "b2QuIFRoZSBhcmd1bWVudCBpcyBtZXJlbHkgYSBoaW50IGFsbG93aW5nIHRoZSBzZXJ2ZXIgdG8gb3B0" +
               "aW1pemUgaXRzIHJlc291cmNlIG1hbmFnZW1lbnQuAQAoAQEAAAABAAAAAQAAAAEB/////wAAAAAXYKkL" +
               "AgAAAAAADwAAAE91dHB1dEFyZ3VtZW50cwEBpxcALgBEAE6nFwAAlgMAAAABACoBASMCAAAMAAAAUmVz" +
               "dWx0SGFuZGxlAQCtfP////8AAAAAAgICAABUaGUgc2VydmVyIHNoYWxsIHJldHVybiB0byBlYWNoIGNs" +
               "aWVudCByZXF1ZXN0aW5nIHJlc3VsdCBkYXRhIGEgc3lzdGVtLXdpZGUgdW5pcXVlIGhhbmRsZSBpZGVu" +
               "dGlmeWluZyB0aGUgcmVzdWx0IHNldCAvIGNsaWVudCBjb21iaW5hdGlvbi4gVGhpcyBoYW5kbGUgc2hv" +
               "dWxkIGJlIHVzZWQgYnkgdGhlIGNsaWVudCB0byBpbmRpY2F0ZSB0byB0aGUgc2VydmVyIHRoYXQgdGhl" +
               "IHJlc3VsdCBkYXRhIGlzIG5vIGxvbmdlciBuZWVkZWQsIGFsbG93aW5nIHRoZSBzZXJ2ZXIgdG8gb3B0" +
               "aW1pemUgaXRzIHJlc291cmNlIGhhbmRsaW5nLgpJZiB0aGUgaW5zdGFuY2Ugb2YgUmVzdWx0TWFuYWdl" +
               "bWVudFR5cGUgZG9lcyBub3Qgc3VwcG9ydCB0aGUgUmVsZWFzZVJlc3VsdEhhbmRsZSBNZXRob2QsIHRo" +
               "ZSByZXN1bHRIYW5kbGUgc2hvdWxkIGFsd2F5cyBiZSBzZXQgdG8gMC4KSWYgdGhlIGVycm9yIGlzIHNl" +
               "dCB0byBhIHZhbHVlIG90aGVyIHRoYW4gMCwgdGhlIHJlc3VsdEhhbmRsZSBtYXkgYmUgc2V0IHRvIDAu" +
               "AQAqAQE5AAAABgAAAFJlc3VsdAEBwAv/////AAAAAAIeAAAAVGhlIHJlc3VsdCBpbmNsdWRpbmcgbWV0" +
               "YWRhdGEuAQAqAQGjAAAABQAAAEVycm9yAAb/////AAAAAAKLAAAAMCDigJMgT0sKVmFsdWVzID4gMCBh" +
               "cmUgcmVzZXJ2ZWQgZm9yIGVycm9ycyBkZWZpbmVkIGJ5IHRoaXMgYW5kIGZ1dHVyZSBzdGFuZGFyZHMu" +
               "ClZhbHVlcyA8IDAgc2hhbGwgYmUgdXNlZCBmb3IgYXBwbGljYXRpb24tc3BlY2lmaWMgZXJyb3JzLgEA" +
               "KAEBAAAAAQAAAAMAAAABAf////8AAAAAJGGCCwQAAAABAA0AAABHZXRSZXN1bHRCeUlkAQFdGwMAAAAA" +
               "AgIAAFRoZSBzZXJ2ZXIgc2hhbGwgcmV0dXJuIHRvIGVhY2ggY2xpZW50IHJlcXVlc3RpbmcgcmVzdWx0" +
               "IGRhdGEgYSBzeXN0ZW0td2lkZSB1bmlxdWUgaGFuZGxlIGlkZW50aWZ5aW5nIHRoZSByZXN1bHQgc2V0" +
               "IC8gY2xpZW50IGNvbWJpbmF0aW9uLiBUaGlzIGhhbmRsZSBzaG91bGQgYmUgdXNlZCBieSB0aGUgY2xp" +
               "ZW50IHRvIGluZGljYXRlIHRvIHRoZSBzZXJ2ZXIgdGhhdCB0aGUgcmVzdWx0IGRhdGEgaXMgbm8gbG9u" +
               "Z2VyIG5lZWRlZCwgYWxsb3dpbmcgdGhlIHNlcnZlciB0byBvcHRpbWl6ZSBpdHMgcmVzb3VyY2UgaGFu" +
               "ZGxpbmcuCklmIHRoZSBpbnN0YW5jZSBvZiBSZXN1bHRNYW5hZ2VtZW50VHlwZSBkb2VzIG5vdCBzdXBw" +
               "b3J0IHRoZSBSZWxlYXNlUmVzdWx0SGFuZGxlIE1ldGhvZCwgdGhlIHJlc3VsdEhhbmRsZSBzaG91bGQg" +
               "YWx3YXlzIGJlIHNldCB0byAwLgpJZiB0aGUgZXJyb3IgaXMgc2V0IHRvIGEgdmFsdWUgb3RoZXIgdGhh" +
               "biAwLCB0aGUgcmVzdWx0SGFuZGxlIG1heSBiZSBzZXQgdG8gMC4ALwEBXRsAUF0bAAABAf////8CAAAA" +
               "F2CpCwIAAAAAAA4AAABJbnB1dEFyZ3VtZW50cwEBoBcALgBEAE6gFwAAlgIAAAABACoBAUoAAAAIAAAA" +
               "UmVzdWx0SWQBAK58/////wAAAAACLQAAAFN5c3RlbS13aWRlIHVuaXF1ZSBpZGVudGlmaWVyIGZvciB0" +
               "aGUgcmVzdWx0LgEAKgEBNgIAAAcAAABUaW1lb3V0AAb/////AAAAAAIcAgAAV2l0aCB0aGlzIGFyZ3Vt" +
               "ZW50IHRoZSBjbGllbnQgY2FuIGdpdmUgYSBoaW50IHRvIHRoZSBzZXJ2ZXIgaG93IGxvbmcgaXQgd2ls" +
               "bCBuZWVkIGFjY2VzcyB0byB0aGUgcmVzdWx0IGRhdGEuCkEgdmFsdWUgPiAwIGluZGljYXRlcyBhbiBl" +
               "c3RpbWF0ZWQgbWF4aW11bSB0aW1lIGZvciBwcm9jZXNzaW5nIHRoZSBkYXRhIGluIG1pbGxpc2Vjb25k" +
               "cy4gCkEgdmFsdWUgPSAwIGluZGljYXRlcyB0aGF0IHRoZSBjbGllbnQgd2lsbCBub3QgbmVlZCBhbnl0" +
               "aGluZyBiZXNpZGVzIHRoZSBkYXRhIHJldHVybmVkIGJ5IHRoZSBtZXRob2QgY2FsbC4KQSB2YWx1ZSA8" +
               "IDAgaW5kaWNhdGVzIHRoYXQgdGhlIGNsaWVudCBjYW5ub3QgZ2l2ZSBhbiBlc3RpbWF0ZS4KVGhlIGNs" +
               "aWVudCBjYW5ub3QgcmVseSBvbiB0aGUgZGF0YSBiZWluZyBhdmFpbGFibGUgZHVyaW5nIHRoZSBpbmRp" +
               "Y2F0ZWQgdGltZSBwZXJpb2QuIFRoZSBhcmd1bWVudCBpcyBtZXJlbHkgYSBoaW50IGFsbG93aW5nIHRo" +
               "ZSBzZXJ2ZXIgdG8gb3B0aW1pemUgaXRzIHJlc291cmNlIG1hbmFnZW1lbnQuAQAoAQEAAAABAAAAAgAA" +
               "AAEB/////wAAAAAXYKkLAgAAAAAADwAAAE91dHB1dEFyZ3VtZW50cwEBoRcALgBEAE6hFwAAlgMAAAAB" +
               "ACoBASMCAAAMAAAAUmVzdWx0SGFuZGxlAQCtfP////8AAAAAAgICAABUaGUgc2VydmVyIHNoYWxsIHJl" +
               "dHVybiB0byBlYWNoIGNsaWVudCByZXF1ZXN0aW5nIHJlc3VsdCBkYXRhIGEgc3lzdGVtLXdpZGUgdW5p" +
               "cXVlIGhhbmRsZSBpZGVudGlmeWluZyB0aGUgcmVzdWx0IHNldCAvIGNsaWVudCBjb21iaW5hdGlvbi4g" +
               "VGhpcyBoYW5kbGUgc2hvdWxkIGJlIHVzZWQgYnkgdGhlIGNsaWVudCB0byBpbmRpY2F0ZSB0byB0aGUg" +
               "c2VydmVyIHRoYXQgdGhlIHJlc3VsdCBkYXRhIGlzIG5vIGxvbmdlciBuZWVkZWQsIGFsbG93aW5nIHRo" +
               "ZSBzZXJ2ZXIgdG8gb3B0aW1pemUgaXRzIHJlc291cmNlIGhhbmRsaW5nLgpJZiB0aGUgaW5zdGFuY2Ug" +
               "b2YgUmVzdWx0TWFuYWdlbWVudFR5cGUgZG9lcyBub3Qgc3VwcG9ydCB0aGUgUmVsZWFzZVJlc3VsdEhh" +
               "bmRsZSBNZXRob2QsIHRoZSByZXN1bHRIYW5kbGUgc2hvdWxkIGFsd2F5cyBiZSBzZXQgdG8gMC4KSWYg" +
               "dGhlIGVycm9yIGlzIHNldCB0byBhIHZhbHVlIG90aGVyIHRoYW4gMCwgdGhlIHJlc3VsdEhhbmRsZSBt" +
               "YXkgYmUgc2V0IHRvIDAuAQAqAQF2AAAABgAAAFJlc3VsdAEBwAv/////AAAAAAJbAAAAVGhlIHJlc3Vs" +
               "dCBpbmNsdWRpbmcgbWV0YWRhdGEuIE1heSBiZSBzZXQgdG8gTnVsbCwgaWYgZXJyb3IgaXMgc2V0IHRv" +
               "IGEgdmFsdWUgb3RoZXIgdGhhbiAwLgEAKgEBowAAAAUAAABFcnJvcgAG/////wAAAAACiwAAADAg4oCT" +
               "IE9LClZhbHVlcyA+IDAgYXJlIHJlc2VydmVkIGZvciBlcnJvcnMgZGVmaW5lZCBieSB0aGlzIGFuZCBm" +
               "dXR1cmUgc3RhbmRhcmRzLgpWYWx1ZXMgPCAwIHNoYWxsIGJlIHVzZWQgZm9yIGFwcGxpY2F0aW9uLXNw" +
               "ZWNpZmljIGVycm9ycy4BACgBAQAAAAEAAAADAAAAAQH/////AAAAAARhggsEAAAAAQAXAAAAR2V0UmVz" +
               "dWx0SWRMaXN0RmlsdGVyZWQBAV4bAC8BAV4bAFBeGwAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5w" +
               "dXRBcmd1bWVudHMBAaIXAC4ARABOohcAAJYEAAAAAQAqAQEYAQAABgAAAEZpbHRlcgEASgL/////AAAA" +
               "AAL9AAAARmlsdGVyIHVzZWQgdG8gZmlsdGVyIGZvciBzcGVjaWZpYyByZXN1bHRzIGJhc2VkIG9uIHRo" +
               "ZSBtZXRhIGRhdGEgb2YgdGhlIHJlc3VsdHMuIFZhbGlkIEJyb3dzZVBhdGhzIHVzZWQgaW4gdGhlIGZp" +
               "bHRlciBjYW4gYmUgYnVpbHQgZnJvbSB0aGUgZmllbGRzIG9mIHRoZSBSZXN1bHRSZWFkeUV2ZW50VHlw" +
               "ZSwgdGhlIFJlc3VsdFR5cGUgVmFyaWFibGVUeXBlIG9yIHRoZSBSZXN1bHREYXRhVHlwZSBvciBjb3Jy" +
               "ZXNwb25kaW5nIHN1YnR5cGVzLgEAKgEBKwEAAAkAAABPcmRlcmVkQnkBABwCAQAAAAEAAAAAAAAAAgkB" +
               "AABBbiBhcnJheSBvZiBCcm93c2VQYXRocyAoYXMgYXJyYXkgb2YgUXVhbGlmaWVkTmFtZSkgaWRlbnRp" +
               "ZnlpbmcgdGhlIG9yZGVyaW5nIGNyaXRlcmlhIGZvciB0aGUgcmVzdWx0cy4gSWYgdGhlIGFycmF5IGlz" +
               "IG51bGwgb3IgZW1wdHksIG5vIG9yZGVyaW5nIGlzIGV4ZWN1dGVkLgpJZiBzZXZlcmFsIEJyb3dzZVBh" +
               "dGhzIGFyZSBwcm92aWRlZCwgdGhlIGZpcnN0IGVudHJ5IGluIHRoZSBhcnJheSBpcyB1c2VkIGFzIGZp" +
               "cnN0IG9yZGVyaW5nIGNyaXRlcmlhLCBldGMuAQAqAQGOAAAACgAAAE1heFJlc3VsdHMAB/////8AAAAA" +
               "AnEAAABEZWZpbmVzIGhvdyBtYW55IHJlc3VsdElkcyB0aGUgQ2xpZW50IHdhbnRzIHRvIHJlY2VpdmUg" +
               "YXQgbW9zdC4gSWYgbm8gbWF4aW11bSBzaG91bGQgYmUgcHJvdmlkZWQsIGl0IGlzIHNldCB0byAwLgEA" +
               "KgEBNgIAAAcAAABUaW1lb3V0AAb/////AAAAAAIcAgAAV2l0aCB0aGlzIGFyZ3VtZW50IHRoZSBjbGll" +
               "bnQgY2FuIGdpdmUgYSBoaW50IHRvIHRoZSBzZXJ2ZXIgaG93IGxvbmcgaXQgd2lsbCBuZWVkIGFjY2Vz" +
               "cyB0byB0aGUgcmVzdWx0IGRhdGEuCkEgdmFsdWUgPiAwIGluZGljYXRlcyBhbiBlc3RpbWF0ZWQgbWF4" +
               "aW11bSB0aW1lIGZvciBwcm9jZXNzaW5nIHRoZSBkYXRhIGluIG1pbGxpc2Vjb25kcy4gCkEgdmFsdWUg" +
               "PSAwIGluZGljYXRlcyB0aGF0IHRoZSBjbGllbnQgd2lsbCBub3QgbmVlZCBhbnl0aGluZyBiZXNpZGVz" +
               "IHRoZSBkYXRhIHJldHVybmVkIGJ5IHRoZSBtZXRob2QgY2FsbC4KQSB2YWx1ZSA8IDAgaW5kaWNhdGVz" +
               "IHRoYXQgdGhlIGNsaWVudCBjYW5ub3QgZ2l2ZSBhbiBlc3RpbWF0ZS4KVGhlIGNsaWVudCBjYW5ub3Qg" +
               "cmVseSBvbiB0aGUgZGF0YSBiZWluZyBhdmFpbGFibGUgZHVyaW5nIHRoZSBpbmRpY2F0ZWQgdGltZSBw" +
               "ZXJpb2QuIFRoZSBhcmd1bWVudCBpcyBtZXJlbHkgYSBoaW50IGFsbG93aW5nIHRoZSBzZXJ2ZXIgdG8g" +
               "b3B0aW1pemUgaXRzIHJlc291cmNlIG1hbmFnZW1lbnQuAQAoAQEAAAABAAAABAAAAAEB/////wAAAAAX" +
               "YKkLAgAAAAAADwAAAE91dHB1dEFyZ3VtZW50cwEBoxcALgBEAE6jFwAAlgMAAAABACoBAcMBAAAMAAAA" +
               "UmVzdWx0SGFuZGxlAQCtfP////8AAAAAAqIBAABUaGUgc2VydmVyIHNoYWxsIHJldHVybiB0byBlYWNo" +
               "IGNsaWVudCByZXF1ZXN0aW5nIHJlc3VsdCBkYXRhIGEgc3lzdGVtLXdpZGUgdW5pcXVlIGhhbmRsZSBp" +
               "ZGVudGlmeWluZyB0aGUgcmVzdWx0IHNldCAvIGNsaWVudCBjb21iaW5hdGlvbi4gVGhpcyBoYW5kbGUg" +
               "aGFzIHRvIGJlIHVzZWQgYnkgdGhlIGNsaWVudCB0byByZWxlYXNlIHRoZSByZXN1bHQgc2V0LgpJZiB0" +
               "aGUgaW5zdGFuY2Ugb2YgUmVzdWx0TWFuYWdlbWVudFR5cGUgZG9lcyBub3Qgc3VwcG9ydCB0aGUgUmVs" +
               "ZWFzZVJlc3VsdEhhbmRsZSBNZXRob2QsIHRoZSByZXN1bHRIYW5kbGUgc2hvdWxkIGFsd2F5cyBiZSBz" +
               "ZXQgdG8gMC4KSWYgdGhlIGVycm9yIGlzIHNldCB0byBhIHZhbHVlIG90aGVyIHRoYW4gMCwgdGhlIHJl" +
               "c3VsdEhhbmRsZSBtYXkgYmUgc2V0IHRvIDAuAQAqAQFWAAAADAAAAFJlc3VsdElkTGlzdAEArnwBAAAA" +
               "AQAAAAAAAAACMQAAAExpc3Qgb2YgcmVzdWx0SWRzIG9mIHJlc3VsdHMgbWF0Y2hpbmcgdGhlIEZpbHRl" +
               "ci4BACoBAaMAAAAFAAAARXJyb3IABv////8AAAAAAosAAAAwIOKAkyBPSwpWYWx1ZXMgPiAwIGFyZSBy" +
               "ZXNlcnZlZCBmb3IgZXJyb3JzIGRlZmluZWQgYnkgdGhpcyBhbmQgZnV0dXJlIHN0YW5kYXJkcy4KVmFs" +
               "dWVzIDwgMCBzaGFsbCBiZSB1c2VkIGZvciBhcHBsaWNhdGlvbi1zcGVjaWZpYyBlcnJvcnMuAQAoAQEA" +
               "AAABAAAAAwAAAAEB/////wAAAAAEYYILBAAAAAEAEwAAAFJlbGVhc2VSZXN1bHRIYW5kbGUBAV8bAC8B" +
               "AV8bAFBfGwAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAaQXAC4ARABOpBcA" +
               "AJYBAAAAAQAqAQGMAAAADAAAAFJlc3VsdEhhbmRsZQEArXz/////AAAAAAJrAAAASGFuZGxlIHJldHVy" +
               "bmVkIGJ5IEdldFJlc3VsdEJ5SWQgb3IgR2V0UmVzdWx0SWRMaXN0RmlsdGVyZWQsIGlkZW50aWZ5aW5n" +
               "IHRoZSByZXN1bHQgc2V0L2NsaWVudCBjb21iaW5hdGlvbi4BACgBAQAAAAEAAAABAAAAAQH/////AAAA" +
               "ABdgqQsCAAAAAAAPAAAAT3V0cHV0QXJndW1lbnRzAQGlFwAuAEQATqUXAACWAQAAAAEAKgEBowAAAAUA" +
               "AABFcnJvcgAG/////wAAAAACiwAAADAg4oCTIE9LClZhbHVlcyA+IDAgYXJlIHJlc2VydmVkIGZvciBl" +
               "cnJvcnMgZGVmaW5lZCBieSB0aGlzIGFuZCBmdXR1cmUgc3RhbmRhcmRzLgpWYWx1ZXMgPCAwIHNoYWxs" +
               "IGJlIHVzZWQgZm9yIGFwcGxpY2F0aW9uLXNwZWNpZmljIGVycm9ycy4BACgBAQAAAAEAAAABAAAAAQH/" +
               "////AAAAAARggAsBAAAAAQAHAAAAUmVzdWx0cwEBkxMALwA9AFCTEwAA/////wEAAAAVYOkLAgAAABoA" +
               "AABSZXN1bHRWYXJpYWJsZV9QbGFjZWhvbGRlcgEAEAAAADxSZXN1bHRWYXJpYWJsZT4BAZ0XAC8BAdEH" +
               "AQD0LJ0XAAAWAQGREwLbAQAAPFJlc3VsdERhdGFUeXBlIHhtbG5zPSJodHRwOi8vb3BjZm91bmRhdGlv" +
               "bi5vcmcvVUEvTWFjaGluZXJ5L1Jlc3VsdC9UeXBlcy54c2QiPjxSZXN1bHRNZXRhRGF0YT48VHlwZUlk" +
               "IHhtbG5zPSJodHRwOi8vb3BjZm91bmRhdGlvbi5vcmcvVUEvMjAwOC8wMi9UeXBlcy54c2QiPjxJZGVu" +
               "dGlmaWVyPm5zPTE7aT01MDA2PC9JZGVudGlmaWVyPjwvVHlwZUlkPjxCb2R5IHhtbG5zPSJodHRwOi8v" +
               "b3BjZm91bmRhdGlvbi5vcmcvVUEvMjAwOC8wMi9UeXBlcy54c2QiPjxSZXN1bHRNZXRhRGF0YVR5cGUg" +
               "eG1sbnM9Imh0dHA6Ly9vcGNmb3VuZGF0aW9uLm9yZy9VQS9NYWNoaW5lcnkvUmVzdWx0L1R5cGVzLnhz" +
               "ZCI+PEVuY29kaW5nTWFzaz4wPC9FbmNvZGluZ01hc2s+PFJlc3VsdElkPjwvUmVzdWx0SWQ+PC9SZXN1" +
               "bHRNZXRhRGF0YVR5cGU+PC9Cb2R5PjwvUmVzdWx0TWV0YURhdGE+PFJlc3VsdENvbnRlbnQgLz48L1Jl" +
               "c3VsdERhdGFUeXBlPgEBwAv/////AwP/////AQAAABVgiQsCAAAAAQAOAAAAUmVzdWx0TWV0YURhdGEB" +
               "AZ4XAQBIXgA/AE6eFwAAAQG/C/////8BAf////8BAAAANWCJCwIAAAABAAgAAABSZXN1bHRJZAEBnxcD" +
               "AAAAACIBAABTeXN0ZW0td2lkZSB1bmlxdWUgaWRlbnRpZmllciwgd2hpY2ggaXMgYXNzaWduZWQgYnkg" +
               "dGhlIHN5c3RlbS4gVGhpcyBJRCBjYW4gYmUgdXNlZCBmb3IgZmV0Y2hpbmcgZXhhY3RseSB0aGlzIHJl" +
               "c3VsdCB1c2luZyB0aGUgbWV0aG9kIEdldFJlc3VsdEJ5SWQgYW5kIGl0IGlzIGlkZW50aWNhbCB0byB0" +
               "aGUgUmVzdWx0SWQgb2YgdGhlIFJlc3VsdFJlYWR5RXZlbnRUeXBlLgpJZiB0aGUgc3lzdGVtIGRvZXMg" +
               "bm90IG1hbmFnZSByZXN1bHRJZHMsIGl0IHNob3VsZCBhbHdheXMgYmUgc2V0IHRvIOKAnE5B4oCdLgEA" +
               "SF4APwBOnxcAAAEArnz/////AwP/////AAAAAARggAsBAAAAAQAOAAAAUmVzdWx0VHJhbnNmZXIBAZIT" +
               "AC8BAesDAFCSEwAA/////wQAAAAVYIkLAgAAAAAAFwAAAENsaWVudFByb2Nlc3NpbmdUaW1lb3V0AQGY" +
               "FwAuAEQATpgXAAABACIB/////wEB/////wAAAAAEYYILBAAAAAAAEwAAAEdlbmVyYXRlRmlsZUZvclJl" +
               "YWQBAVobAC8BAII9AE5aGwAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAZYX" +
               "AC4ARABOlhcAAJYBAAAAAQAqAQF/AAAADwAAAEdlbmVyYXRlT3B0aW9ucwEBvQv/////AAAAAAJbAAAA" +
               "T3B0aW9ucyBob3cgdG8gZ2VuZXJhdGUgdGhlIGZpbGUsIGluY2x1ZGluZyB0aGUgcmVzdWx0SWQgb2Yg" +
               "dGhlIHJlc3VsdCB0aGUgZmlsZSBiZWxvbmdzIHRvLgEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAF2Cp" +
               "CwIAAAAAAA8AAABPdXRwdXRBcmd1bWVudHMBAZcXAC4ARABOlxcAAJYDAAAAAQAqAQE6AAAACgAAAEZp" +
               "bGVOb2RlSWQAEf////8AAAAAAh0AAABOb2RlSWQgb2YgdGhlIHRlbXBvcmFyeSBmaWxlLgEAKgEBlQAA" +
               "AAoAAABGaWxlSGFuZGxlAAf/////AAAAAAJ4AAAAVGhlIEZpbGVIYW5kbGUgb2YgdGhlIG9wZW5lZCBU" +
               "cmFuc2ZlckZpbGUuClRoZSBGaWxlSGFuZGxlIGNhbiBiZSB1c2VkIHRvIGFjY2VzcyB0aGUgVHJhbnNm" +
               "ZXJGaWxlIG1ldGhvZHMgUmVhZCBhbmQgQ2xvc2UuAQAqAQGVAQAAFgAAAENvbXBsZXRpb25TdGF0ZU1h" +
               "Y2hpbmUAEf////8AAAAAAmwBAABJZiB0aGUgY3JlYXRpb24gb2YgdGhlIGZpbGUgaXMgY29tcGxldGVk" +
               "IGFzeW5jaHJvbm91c2x5LCB0aGUgcGFyYW1ldGVyIHJldHVybnMgdGhlIE5vZGVJZCBvZiB0aGUgY29y" +
               "cmVzcG9uZGluZyBGaWxlVHJhbnNmZXJTdGF0ZU1hY2hpbmVUeXBlIE9iamVjdC4KSWYgdGhlIGNyZWF0" +
               "aW9uIG9mIHRoZSBmaWxlIGlzIGFscmVhZHkgY29tcGxldGVkLCB0aGUgcGFyYW1ldGVyIGlzIG51bGwu" +
               "CklmIGEgRmlsZVRyYW5zZmVyU3RhdGVNYWNoaW5lVHlwZSBvYmplY3QgTm9kZUlkIGlzIHJldHVybmVk" +
               "LCB0aGUgUmVhZCBNZXRob2Qgb2YgdGhlIGZpbGUgZmFpbHMgdW50aWwgdGhlIFRyYW5zZmVyU3RhdGUg" +
               "Y2hhbmdlZCB0byBSZWFkVHJhbnNmZXIuAQAoAQEAAAABAAAAAwAAAAEB/////wAAAAAEYYILBAAAAAAA" +
               "FAAAAEdlbmVyYXRlRmlsZUZvcldyaXRlAQFcGwAvAQCFPQBOXBsAAAEB/////wIAAAAXYKkLAgAAAAAA" +
               "DgAAAElucHV0QXJndW1lbnRzAQGbFwAuAEQATpsXAACWAQAAAAEAKgEBHgAAAA8AAABHZW5lcmF0ZU9w" +
               "dGlvbnMAGP////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABPdXRw" +
               "dXRBcmd1bWVudHMBAZwXAC4ARABOnBcAAJYCAAAAAQAqAQEZAAAACgAAAEZpbGVOb2RlSWQAEf////8A" +
               "AAAAAAEAKgEBGQAAAAoAAABGaWxlSGFuZGxlAAf/////AAAAAAABACgBAQAAAAEAAAACAAAAAQH/////" +
               "AAAAAARhggsEAAAAAAAOAAAAQ2xvc2VBbmRDb21taXQBAVsbAC8BAIc9AE5bGwAAAQH/////AgAAABdg" +
               "qQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAZkXAC4ARABOmRcAAJYBAAAAAQAqAQEZAAAACgAAAEZp" +
               "bGVIYW5kbGUAB/////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABP" +
               "dXRwdXRBcmd1bWVudHMBAZoXAC4ARABOmhcAAJYBAAAAAQAqAQElAAAAFgAAAENvbXBsZXRpb25TdGF0" +
               "ZU1hY2hpbmUAEf////8AAAAAAAEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAJGAAEAgAAAABABIAAABS" +
               "ZXN1bHRUcmFuc2ZlclR5cGUBAesDAwAAAAAgAAAAVHJhbnNmZXJzIHJlc3VsdCBkYXRhIGFzIGEgZmls" +
               "ZS4BAIA9/////wEAAAAEYYILBAAAAAAAEwAAAEdlbmVyYXRlRmlsZUZvclJlYWQBAVkbAC8BAII9AE5Z" +
               "GwAAAQH/////AgAAABdgqQsCAAAAAAAOAAAASW5wdXRBcmd1bWVudHMBAZMXAC4ARABOkxcAAJYBAAAA" +
               "AQAqAQF/AAAADwAAAEdlbmVyYXRlT3B0aW9ucwEBvQv/////AAAAAAJbAAAAT3B0aW9ucyBob3cgdG8g" +
               "Z2VuZXJhdGUgdGhlIGZpbGUsIGluY2x1ZGluZyB0aGUgcmVzdWx0SWQgb2YgdGhlIHJlc3VsdCB0aGUg" +
               "ZmlsZSBiZWxvbmdzIHRvLgEAKAEBAAAAAQAAAAEAAAABAf////8AAAAAF2CpCwIAAAAAAA8AAABPdXRw" +
               "dXRBcmd1bWVudHMBAZQXAC4ARABOlBcAAJYDAAAAAQAqAQE6AAAACgAAAEZpbGVOb2RlSWQAEf////8A" +
               "AAAAAh0AAABOb2RlSWQgb2YgdGhlIHRlbXBvcmFyeSBmaWxlLgEAKgEBlQAAAAoAAABGaWxlSGFuZGxl" +
               "AAf/////AAAAAAJ4AAAAVGhlIEZpbGVIYW5kbGUgb2YgdGhlIG9wZW5lZCBUcmFuc2ZlckZpbGUuClRo" +
               "ZSBGaWxlSGFuZGxlIGNhbiBiZSB1c2VkIHRvIGFjY2VzcyB0aGUgVHJhbnNmZXJGaWxlIG1ldGhvZHMg" +
               "UmVhZCBhbmQgQ2xvc2UuAQAqAQGVAQAAFgAAAENvbXBsZXRpb25TdGF0ZU1hY2hpbmUAEf////8AAAAA" +
               "AmwBAABJZiB0aGUgY3JlYXRpb24gb2YgdGhlIGZpbGUgaXMgY29tcGxldGVkIGFzeW5jaHJvbm91c2x5" +
               "LCB0aGUgcGFyYW1ldGVyIHJldHVybnMgdGhlIE5vZGVJZCBvZiB0aGUgY29ycmVzcG9uZGluZyBGaWxl" +
               "VHJhbnNmZXJTdGF0ZU1hY2hpbmVUeXBlIE9iamVjdC4KSWYgdGhlIGNyZWF0aW9uIG9mIHRoZSBmaWxl" +
               "IGlzIGFscmVhZHkgY29tcGxldGVkLCB0aGUgcGFyYW1ldGVyIGlzIG51bGwuCklmIGEgRmlsZVRyYW5z" +
               "ZmVyU3RhdGVNYWNoaW5lVHlwZSBvYmplY3QgTm9kZUlkIGlzIHJldHVybmVkLCB0aGUgUmVhZCBNZXRo" +
               "b2Qgb2YgdGhlIGZpbGUgZmFpbHMgdW50aWwgdGhlIFRyYW5zZmVyU3RhdGUgY2hhbmdlZCB0byBSZWFk" +
               "VHJhbnNmZXIuAQAoAQEAAAABAAAAAwAAAAEB/////wAAAAAEYMACAQAAAA0AAABEZWZhdWx0QmluYXJ5" +
               "AAAOAAAARGVmYXVsdCBCaW5hcnkBAYkTAEyJEwAAAgAAAAAmAQEBvAsAJwABAb8XAAAAAARgwAIBAAAA" +
               "CgAAAERlZmF1bHRYbWwAAAsAAABEZWZhdWx0IFhNTAEBihMATIoTAAACAAAAACYBAQG8CwAnAAEBwBcA" +
               "AAAABGDAAgEAAAANAAAARGVmYXVsdEJpbmFyeQAADgAAAERlZmF1bHQgQmluYXJ5AQGLEwBMixMAAAIA" +
               "AAAAJgEBAb4LACcAAQHBFwAAAAAEYMACAQAAAAoAAABEZWZhdWx0WG1sAAALAAAARGVmYXVsdCBYTUwB" +
               "AYwTAEyMEwAAAgAAAAAmAQEBvgsAJwABAcIXAAAAAARgwAIBAAAADQAAAERlZmF1bHRCaW5hcnkAAA4A" +
               "AABEZWZhdWx0IEJpbmFyeQEBjRMATI0TAAACAAAAACYBAQG/CwAnAAEBxRcAAAAABGDAAgEAAAAKAAAA" +
               "RGVmYXVsdFhtbAAACwAAAERlZmF1bHQgWE1MAQGOEwBMjhMAAAIAAAAAJgEBAb8LACcAAQHGFwAAAAAE" +
               "YMACAQAAAA0AAABEZWZhdWx0QmluYXJ5AAAOAAAARGVmYXVsdCBCaW5hcnkBAZATAEyQEwAAAgAAAAAm" +
               "AQEBwAsAJwABAcMXAAAAAARgwAIBAAAACgAAAERlZmF1bHRYbWwAAAsAAABEZWZhdWx0IFhNTAEBkRMA" +
               "TJETAAACAAAAACYBAQHACwAnAAEBxBcAAAAABGDAAgEAAAALAAAARGVmYXVsdEpzb24AAAwAAABEZWZh" +
               "dWx0IEpTT04BAZQTAEyUEwAAAQAAAAAmAQEBvAsAAAAABGDAAgEAAAALAAAARGVmYXVsdEpzb24AAAwA" +
               "AABEZWZhdWx0IEpTT04BAZUTAEyVEwAAAQAAAAAmAQEBvgsAAAAABGDAAgEAAAALAAAARGVmYXVsdEpz" +
               "b24AAAwAAABEZWZhdWx0IEpTT04BAZYTAEyWEwAAAQAAAAAmAQEBwAsAAAAABGDAAgEAAAALAAAARGVm" +
               "YXVsdEpzb24AAAwAAABEZWZhdWx0IEpTT04BAZcTAEyXEwAAAQAAAAAmAQEBvwsAAAAA"
            );
            using (MemoryStream stream = new MemoryStream(initializationBuffer))
            {
                NodeStateCollection predefinedNodes = new NodeStateCollection();
                predefinedNodes.LoadFromBinary(context, stream, true);
                return predefinedNodes;
            }
        }
        #endregion
    }
    #endregion
}