#!/usr/bin/env python3
"""Generate, check, audit and fix the per-client Python lock files.

Design (one rule set for every Python client):
  * constraints.txt (repo root, hand-edited) holds shared intent: the asyncua
    pin and security floors (>=). It applies to every install in the repo.
  * <client>/requirements.lock (generated, never hand-edited) pins the exact
    version of every package that client installs, for Windows and Linux.
    It is built from the client's requirements*.txt plus constraints.txt.
  * Each client's runner and setup script install with ``-c requirements.lock``
    and reinstall their own venv automatically when the lock changes.

Commands:
  python scripts/update_python_locks.py              # regenerate locks (keeps current versions)
  python scripts/update_python_locks.py --upgrade    # newest allowed version of every package
  python scripts/update_python_locks.py -P anyio     # upgrade one package (repeatable)
  python scripts/update_python_locks.py --check      # offline: fail if a lock is out of date
  python scripts/update_python_locks.py --audit      # pip-audit every lock (no install needed)
  python scripts/update_python_locks.py --fix        # audit, raise floors, regenerate locks

Exit codes: 0 = ok, 1 = stale lock / vulnerabilities / manual action, 2 = tool could not run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess  # nosec B404
import sys
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ROOT_CONSTRAINTS = REPO_ROOT / "constraints.txt"
PYTHON_VERSION_FILE = REPO_ROOT / ".python-version"
CLIENTS_DIR = REPO_ROOT / "OPC_UA_Clients" / "Release2"
LOCK_NAME = "requirements.lock"
INPUT_NAMES = ("requirements.txt", "requirements-dev.txt")
# Bump when the lock layout or uv options change so every lock is regenerated.
LOCK_FORMAT = "2"
HASH_PREFIX = "# input-hash: "
UV_VERSION_SPEC = "uv>=0.9"
UV_TOOL_DIR = REPO_ROOT / "tmp" / "uv-venv"
MANAGED_MARKER = "# Security floors for transitive packages flagged by pip-audit"
# pip is upgraded by every runner before installing; a floor would not help.
SKIP_PACKAGES = frozenset({"pip"})

_REQ_LINE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)\s*(?P<spec>[^#;]*?)\s*(?P<rest>[;#].*)?$"
)


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


# ---------------------------------------------------------------------------
# Lock targets and input hashing
# ---------------------------------------------------------------------------


def lock_projects(clients_dir: Path = CLIENTS_DIR) -> list[Path]:
    """Every Python client: a Release2 folder with a requirements.txt."""
    return sorted(
        p for p in clients_dir.iterdir() if p.is_dir() and (p / "requirements.txt").is_file()
    )


def lock_inputs(project: Path) -> list[Path]:
    return [project / name for name in INPUT_NAMES if (project / name).is_file()]


def _normalized(path: Path) -> bytes:
    return path.read_bytes().replace(b"\r\n", b"\n")


def python_version() -> str:
    return PYTHON_VERSION_FILE.read_text(encoding="utf-8").strip()


def input_hash(project: Path) -> str:
    """Hash of everything that determines the lock; line endings are ignored."""
    h = hashlib.sha256()
    h.update(f"format={LOCK_FORMAT}\npython={python_version()}\n".encode())
    for path in (ROOT_CONSTRAINTS, *lock_inputs(project)):
        h.update(path.name.encode() + b"\0" + _normalized(path) + b"\0")
    return h.hexdigest()


def stored_hash(lock: Path) -> str | None:
    if not lock.is_file():
        return None
    for line in lock.read_text(encoding="utf-8").splitlines():
        if line.startswith(HASH_PREFIX):
            return line[len(HASH_PREFIX) :].strip()
    return None


def stale_locks(projects: Iterable[Path]) -> list[Path]:
    return [p for p in projects if stored_hash(p / LOCK_NAME) != input_hash(p)]


def lock_header(project: Path) -> str:
    rel = project.relative_to(REPO_ROOT).as_posix()
    inputs = " + ".join(p.name for p in lock_inputs(project))
    return (
        "# GENERATED by scripts/update_python_locks.py - do not edit by hand.\n"
        f"# Exact versions for {rel} ({inputs} + repo-root constraints.txt).\n"
        "# Change versions in requirements*.txt or constraints.txt, then run:\n"
        "#   python scripts/update_python_locks.py          (add -P NAME to upgrade one package)\n"
        f"{HASH_PREFIX}{input_hash(project)}\n"
    )


# ---------------------------------------------------------------------------
# uv (resolver) - found on PATH or installed into the gitignored repo tmp/ dir
# ---------------------------------------------------------------------------


def _venv_bin(venv: Path, name: str) -> Path:
    sub, ext = ("Scripts", ".exe") if os.name == "nt" else ("bin", "")
    return venv / sub / f"{name}{ext}"


def ensure_uv() -> str:
    found = shutil.which("uv")
    if found:
        return found
    uv = _venv_bin(UV_TOOL_DIR, "uv")
    if not uv.is_file():
        print(f"[locks] Installing {UV_VERSION_SPEC} into {UV_TOOL_DIR.relative_to(REPO_ROOT)} ...")
        subprocess.check_call([sys.executable, "-m", "venv", str(UV_TOOL_DIR)])  # nosec B603  # noqa: S603 - fixed internal command
        subprocess.check_call(  # nosec B603  # noqa: S603 - fixed internal command
            [
                str(_venv_bin(UV_TOOL_DIR, "python")),
                "-m",
                "pip",
                "install",
                "--quiet",
                UV_VERSION_SPEC,
            ]
        )
    return str(uv)


def compile_lock(project: Path, uv: str, upgrade: bool, upgrade_packages: list[str]) -> None:
    lock = project / LOCK_NAME
    with tempfile.TemporaryDirectory(dir=REPO_ROOT / "tmp") as tmp:
        out = Path(tmp) / LOCK_NAME
        if lock.is_file():
            # Existing pins are preferences: versions only move when needed or requested.
            out.write_bytes(lock.read_bytes())
        cmd = [
            uv,
            "pip",
            "compile",
            "--quiet",
            "--universal",
            "--python-version",
            python_version(),
            "--no-header",
            "--no-annotate",
            "--constraint",
            str(ROOT_CONSTRAINTS),
            "--output-file",
            str(out),
            *(str(p) for p in lock_inputs(project)),
        ]
        if upgrade:
            cmd.append("--upgrade")
        for name in upgrade_packages:
            cmd += ["--upgrade-package", name]
        env = {
            **os.environ,
            "UV_CACHE_DIR": os.environ.get("UV_CACHE_DIR", str(REPO_ROOT / "tmp" / "uv-cache")),
        }
        subprocess.run(cmd, check=True, cwd=project, env=env)  # nosec B603  # noqa: S603 - fixed internal command
        body = out.read_text(encoding="utf-8").replace("\r\n", "\n")
    lock.write_bytes((lock_header(project) + body).encode("utf-8"))


# ---------------------------------------------------------------------------
# Audit and floor raising
# ---------------------------------------------------------------------------


@dataclass
class FloorPlan:
    floors: dict[str, str] = field(default_factory=dict)
    display: dict[str, str] = field(default_factory=dict)
    advisory_only: list[str] = field(default_factory=list)


def _version_key(raw: str) -> tuple:
    from packaging.version import InvalidVersion, Version

    try:
        return (1, Version(raw))
    except InvalidVersion:
        return (0, raw)


def plan_floors(reports: Iterable[dict]) -> FloorPlan:
    """Lowest version per package that fixes every fixable advisory."""
    plan = FloorPlan()
    for report in reports:
        for dep in report.get("dependencies", []):
            name = str(dep.get("name", ""))
            key = canonical(name)
            for vuln in dep.get("vulns") or []:
                fixes = sorted((str(f) for f in vuln.get("fix_versions") or []), key=_version_key)
                if not fixes:
                    plan.advisory_only.append(
                        f"{name} {dep.get('version', '?')} {vuln.get('id', '?')}"
                    )
                    continue
                if key in SKIP_PACKAGES:
                    continue
                newer = [
                    f for f in fixes if _version_key(f) > _version_key(str(dep.get("version", "")))
                ]
                needed = newer[0] if newer else fixes[0]
                if key not in plan.floors or _version_key(needed) > _version_key(plan.floors[key]):
                    plan.floors[key] = needed
                    plan.display[key] = name
    plan.advisory_only = sorted(set(plan.advisory_only))
    return plan


@dataclass
class ApplyResult:
    text: str
    changed: list[str] = field(default_factory=list)
    manual: list[str] = field(default_factory=list)


def apply_floors(text: str, plan: FloorPlan) -> ApplyResult:
    """Raise existing >= floors in place; add new ones to the managed block (sorted)."""
    nl = "\r\n" if "\r\n" in text else "\n"
    lines = text.splitlines()
    result = ApplyResult(text=text)
    seen: set[str] = set()
    for i, line in enumerate(lines):
        match = _REQ_LINE.match(line)
        if not match or line.lstrip().startswith("#"):
            continue
        key = canonical(match["name"])
        if key not in plan.floors:
            continue
        seen.add(key)
        floor = plan.floors[key]
        spec = match["spec"].replace(" ", "")
        if spec.startswith(">=") and "," not in spec:
            if _version_key(spec[2:]) < _version_key(floor):
                rest = f"  {match['rest']}" if match["rest"] else ""
                lines[i] = f"{match['name']}>={floor}{rest}"
                result.changed.append(f"{match['name']} {spec[2:]} -> {floor}")
            continue
        if spec.startswith("==") and _version_key(spec[2:]) >= _version_key(floor):
            continue
        result.manual.append(
            f"{match['name']}{spec} (needs >= {floor}; edit by hand and re-validate)"
        )

    missing = sorted(k for k in plan.floors if k not in seen)
    if missing:
        marker = next((i for i, ln in enumerate(lines) if ln.startswith(MANAGED_MARKER)), None)
        if marker is None:
            lines += ["", f"{MANAGED_MARKER} (fixable advisories)."]
            marker = len(lines) - 1
        start = marker + 1
        while start < len(lines) and lines[start].startswith("#"):
            start += 1
        end = start
        while end < len(lines) and lines[end].strip():
            end += 1
        block = lines[start:end]
        for key in missing:
            entry = f"{plan.display[key]}>={plan.floors[key]}"
            block.append(entry)
            result.changed.append(f"{entry} (new)")
        block.sort(key=lambda ln: canonical(re.split(r"[<>=!~;\s]", ln, maxsplit=1)[0]))
        lines[start:end] = block
    result.text = nl.join(lines) + nl
    return result


def run_audit(locks: list[Path]) -> dict | None:
    """pip-audit the exact pins of every lock (no install, no resolution). None = could not run."""
    cache = REPO_ROOT / "tmp" / "pip-audit-cache"
    cache.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=REPO_ROOT / "tmp") as tmp:
        report = Path(tmp) / "audit.json"
        cmd = [
            sys.executable,
            "-m",
            "pip_audit",
            "--progress-spinner",
            "off",
            "--cache-dir",
            str(cache),
        ]
        cmd += ["--no-deps", "--disable-pip", "--format", "json", "--output", str(report)]
        for lock in locks:
            cmd += ["--requirement", str(lock)]
        proc = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)  # nosec B603  # noqa: S603 - fixed internal command
        if not report.is_file():
            sys.stderr.write(proc.stdout + proc.stderr)
            return None
        return json.loads(report.read_text(encoding="utf-8"))


def _summary(path: str | None, lines: list[str]) -> None:
    if path:
        with open(path, "a", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check", action="store_true", help="offline check that every lock is up to date"
    )
    mode.add_argument("--audit", action="store_true", help="pip-audit every lock")
    mode.add_argument(
        "--fix", action="store_true", help="audit, raise floors in constraints.txt, regenerate"
    )
    parser.add_argument(
        "--upgrade", action="store_true", help="upgrade every package to the newest allowed"
    )
    parser.add_argument("-P", "--upgrade-package", action="append", default=[], metavar="NAME")
    parser.add_argument(
        "--summary",
        metavar="FILE",
        default=os.environ.get("GITHUB_STEP_SUMMARY"),
        help="append a Markdown summary (default: $GITHUB_STEP_SUMMARY in GitHub Actions)",
    )
    return parser


def _cmd_check(projects: list[Path]) -> int:
    missing = [p for p in projects if not (p / LOCK_NAME).is_file()]
    stale = [p for p in stale_locks(projects) if p not in missing]
    for p in missing:
        print(f"[locks] MISSING {p.relative_to(REPO_ROOT).as_posix()}/{LOCK_NAME}")
    for p in stale:
        print(f"[locks] OUT OF DATE {p.relative_to(REPO_ROOT).as_posix()}/{LOCK_NAME}")
    if missing or stale:
        print("[locks] Fix: python scripts/update_python_locks.py")
        return 1
    print(f"[locks] {len(projects)} lock file(s) up to date")
    return 0


def _cmd_audit(projects: list[Path], fix: bool, summary: str | None) -> int:
    if (rc := _cmd_check(projects)) != 0:
        return rc
    report = run_audit([p / LOCK_NAME for p in projects])
    if report is None:
        print("[locks] pip-audit could not run (install it: pip install pip-audit)")
        return 2
    plan = plan_floors([report])
    for note in plan.advisory_only:
        print(f"[locks] advisory without a fixed release (allowed, review manually): {note}")
    if not plan.floors:
        print("[locks] pip-audit: no fixable vulnerabilities in any lock")
        _summary(summary, ["### Python locks", "", "No fixable vulnerabilities."])
        return 0
    wanted = ", ".join(f"{plan.display[k]}>={v}" for k, v in sorted(plan.floors.items()))
    print(f"[locks] fixable vulnerabilities: {wanted}")
    if not fix:
        print("[locks] Fix: python scripts/update_python_locks.py --fix")
        _summary(
            summary,
            [
                "### Python locks",
                "",
                f"Fixable vulnerabilities: `{wanted}`",
                "",
                "Run locally and commit:",
                "",
                "```",
                "python scripts/update_python_locks.py --fix",
                "```",
            ],
        )
        return 1
    result = apply_floors(ROOT_CONSTRAINTS.read_text(encoding="utf-8"), plan)
    for item in result.manual:
        print(f"[locks] MANUAL: {item}")
    if result.text != ROOT_CONSTRAINTS.read_text(encoding="utf-8"):
        ROOT_CONSTRAINTS.write_bytes(result.text.encode("utf-8"))
        print("[locks] constraints.txt: " + "; ".join(result.changed))
    uv = ensure_uv()
    for project in projects:
        compile_lock(project, uv, upgrade=False, upgrade_packages=sorted(plan.display.values()))
    print("[locks] Locks regenerated. Commit constraints.txt and the requirements.lock files.")
    return 1 if result.manual else 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    (REPO_ROOT / "tmp").mkdir(exist_ok=True)
    projects = lock_projects()
    if args.check:
        return _cmd_check(projects)
    if args.audit or args.fix:
        return _cmd_audit(projects, fix=args.fix, summary=args.summary)
    try:
        uv = ensure_uv()
        for project in projects:
            compile_lock(project, uv, args.upgrade, args.upgrade_package)
            print(f"[locks] wrote {project.relative_to(REPO_ROOT).as_posix()}/{LOCK_NAME}")
    except subprocess.CalledProcessError as exc:
        print(f"[locks] resolver failed: {exc}")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
