// <auto-generated />
// Compatibility shim for OPC Foundation .NET SDK 2.0 migration

#nullable enable

namespace Opc.Ua
{
    /// <summary>
    /// Compatibility interface for model-compiled types expecting IJsonEncodeable removed in OPC UA .NET Standard 2.0.0.
    /// </summary>
    public interface IJsonEncodeable
    {
        ExpandedNodeId JsonEncodingId { get; }
    }
}
