export const NS = 'http://opcfoundation.org/UA/IA/';

export const BrowseNames = Object.freeze({
   AcousticSignals: 'AcousticSignals',
   AcousticSignalType: 'AcousticSignalType',
   AudioSample: 'AudioSample',
   BaseCalibrationTargetCategoryType: 'BaseCalibrationTargetCategoryType',
   BasicStacklightType: 'BasicStacklightType',
   CalibrationTargetCategory: 'CalibrationTargetCategory',
   CalibrationTargetFeatures: 'CalibrationTargetFeatures',
   CalibrationTargetType: 'CalibrationTargetType',
   CalibrationValue_Placeholder: '<CalibrationValue>',
   CalibrationValueType: 'CalibrationValueType',
   CapacityRange_Placeholder: '<CapacityRange>',
   CapacityRangeType: 'CapacityRangeType',
   CertificateUri: 'CertificateUri',
   ChannelColor: 'ChannelColor',
   ControlChannel_Placeholder: '<ControlChannel>',
   ControlChannelType: 'ControlChannelType',
   DisplayMode: 'DisplayMode',
   DynamicCalibrationTargetCategoryType: 'DynamicCalibrationTargetCategoryType',
   HasReferenceMeasurementInstrument: 'HasReferenceMeasurementInstrument',
   HasStatisticComponent: 'HasStatisticComponent',
   IAggregateStatisticsType: 'IAggregateStatisticsType',
   Intensity: 'Intensity',
   IRollingStatisticsType: 'IRollingStatisticsType',
   IsPartOfBase: 'IsPartOfBase',
   IStatisticsType: 'IStatisticsType',
   LastValidationDate: 'LastValidationDate',
   LevelDisplayMode: 'LevelDisplayMode',
   LevelPercent: 'LevelPercent',
   NextValidationDate: 'NextValidationDate',
   OneTimeCalibrationTargetCategoryType: 'OneTimeCalibrationTargetCategoryType',
   OperationalConditions: 'OperationalConditions',
   OperationMode: 'OperationMode',
   Quality: 'Quality',
   ResetCondition: 'ResetCondition',
   ResetStatistics: 'ResetStatistics',
   Resolution: 'Resolution',
   ReusableCalibrationTargetCategoryType: 'ReusableCalibrationTargetCategoryType',
   ReusableDeviceCalibrationTargetCategoryType: 'ReusableDeviceCalibrationTargetCategoryType',
   RGBWDataType: 'RGBWDataType',
   SignalColor: 'SignalColor',
   SignalMode: 'SignalMode',
   SignalModeLight: 'SignalModeLight',
   SignalOn: 'SignalOn',
   SignalRGBWValue: 'SignalRGBWValue',
   StackElementAcousticType: 'StackElementAcousticType',
   StackElementLightType: 'StackElementLightType',
   StackElementType: 'StackElementType',
   StackLevel: 'StackLevel',
   StackLevelType: 'StackLevelType',
   StacklightMode: 'StacklightMode',
   StacklightOperationMode: 'StacklightOperationMode',
   StacklightType: 'StacklightType',
   StackRunning: 'StackRunning',
   StackRunningType: 'StackRunningType',
   StartTime: 'StartTime',
   WindowDuration: 'WindowDuration',
   WindowNumberOfValues: 'WindowNumberOfValues',
});

export const DataTypeIds = Object.freeze({
   LevelDisplayMode: 'nsu=' + NS + ';i=3003',
   SignalColor: 'nsu=' + NS + ';i=3004',
   SignalModeLight: 'nsu=' + NS + ';i=3005',
   StacklightOperationMode: 'nsu=' + NS + ';i=3002',
   RGBWDataType: 'nsu=' + NS + ';i=3007',
});

export const MethodIds = Object.freeze({
   IStatisticsType_ResetStatistics: 'nsu=' + NS + ';i=7001',
});

export const ObjectIds = Object.freeze({
   CalibrationTargetType_CalibrationTargetCategory: 'nsu=' + NS + ';i=5011',
   CalibrationTargetType_CalibrationTargetFeatures: 'nsu=' + NS + ';i=5013',
   CalibrationTargetType_Identification: 'nsu=' + NS + ';i=5010',
   CalibrationTargetType_OperationalConditions: 'nsu=' + NS + ';i=5012',
   BasicStacklightType_OrderedObject_Placeholder: 'nsu=' + NS + ';i=5006',
   BasicStacklightType_StackLevel: 'nsu=' + NS + ';i=5001',
   BasicStacklightType_StackRunning: 'nsu=' + NS + ';i=5005',
   StacklightType_DeviceHealthAlarms: 'nsu=' + NS + ';i=5007',
   StackElementAcousticType_AcousticSignals: 'nsu=' + NS + ';i=5003',
   StackElementAcousticType_AcousticSignals_OrderedObject: 'nsu=' + NS + ';i=5004',
   StackElementLightType_ControlChannel_Placeholder: 'nsu=' + NS + ';i=5002',
   RGBWDataType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=5009',
   RGBWDataType_Encoding_DefaultXml: 'nsu=' + NS + ';i=5014',
});

export const ObjectTypeIds = Object.freeze({
   AcousticSignalType: 'nsu=' + NS + ';i=1009',
   BaseCalibrationTargetCategoryType: 'nsu=' + NS + ';i=1014',
   DynamicCalibrationTargetCategoryType: 'nsu=' + NS + ';i=1018',
   OneTimeCalibrationTargetCategoryType: 'nsu=' + NS + ';i=1017',
   ReusableCalibrationTargetCategoryType: 'nsu=' + NS + ';i=1015',
   ReusableDeviceCalibrationTargetCategoryType: 'nsu=' + NS + ';i=1016',
   IStatisticsType: 'nsu=' + NS + ';i=1011',
   IAggregateStatisticsType: 'nsu=' + NS + ';i=1012',
   IRollingStatisticsType: 'nsu=' + NS + ';i=1013',
   CalibrationTargetType: 'nsu=' + NS + ';i=1019',
   ControlChannelType: 'nsu=' + NS + ';i=1008',
   BasicStacklightType: 'nsu=' + NS + ';i=1002',
   StacklightType: 'nsu=' + NS + ';i=1010',
   StackElementType: 'nsu=' + NS + ';i=1005',
   StackElementAcousticType: 'nsu=' + NS + ';i=1007',
   StackElementLightType: 'nsu=' + NS + ';i=1006',
   StackLevelType: 'nsu=' + NS + ';i=1003',
   StackRunningType: 'nsu=' + NS + ';i=1004',
});

export const ReferenceTypeIds = Object.freeze({
   HasStatisticComponent: 'nsu=' + NS + ';i=4002',
   HasReferenceMeasurementInstrument: 'nsu=' + NS + ';i=4003',
});

export const VariableIds = Object.freeze({
   LevelDisplayMode_EnumValues: 'nsu=' + NS + ';i=6001',
   SignalColor_EnumValues: 'nsu=' + NS + ';i=6007',
   SignalModeLight_EnumValues: 'nsu=' + NS + ';i=6008',
   StacklightOperationMode_EnumValues: 'nsu=' + NS + ';i=6006',
   CalibrationValueType_EngineeringUnits: 'nsu=' + NS + ';i=6057',
   CapacityRangeType_EngineeringUnits: 'nsu=' + NS + ';i=6058',
   CapacityRangeType_Resolution: 'nsu=' + NS + ';i=6059',
   AcousticSignalType_AudioSample: 'nsu=' + NS + ';i=6029',
   AcousticSignalType_NumberInList: 'nsu=' + NS + ';i=6028',
   IStatisticsType_StartTime: 'nsu=' + NS + ';i=6046',
   IAggregateStatisticsType_ResetCondition: 'nsu=' + NS + ';i=6047',
   IRollingStatisticsType_WindowDuration: 'nsu=' + NS + ';i=6048',
   IRollingStatisticsType_WindowNumberOfValues: 'nsu=' + NS + ';i=6049',
   CalibrationTargetType_CalibrationTargetFeatures_CalibrationValue_Placeholder: 'nsu=' + NS + ';i=6064',
   CalibrationTargetType_CalibrationTargetFeatures_CalibrationValue_Placeholder_EngineeringUnits: 'nsu=' + NS + ';i=6065',
   CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder: 'nsu=' + NS + ';i=6066',
   CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder_EngineeringUnits: 'nsu=' + NS + ';i=6067',
   CalibrationTargetType_CalibrationTargetFeatures_CapacityRange_Placeholder_Resolution: 'nsu=' + NS + ';i=6068',
   CalibrationTargetType_CertificateUri: 'nsu=' + NS + ';i=6063',
   CalibrationTargetType_Identification_AssetId: 'nsu=' + NS + ';i=6080',
   CalibrationTargetType_Identification_ComponentName: 'nsu=' + NS + ';i=6081',
   CalibrationTargetType_Identification_DeviceClass: 'nsu=' + NS + ';i=6076',
   CalibrationTargetType_Identification_DeviceManual: 'nsu=' + NS + ';i=6082',
   CalibrationTargetType_Identification_DeviceRevision: 'nsu=' + NS + ';i=6075',
   CalibrationTargetType_Identification_HardwareRevision: 'nsu=' + NS + ';i=6073',
   CalibrationTargetType_Identification_Manufacturer: 'nsu=' + NS + ';i=6069',
   CalibrationTargetType_Identification_ManufacturerUri: 'nsu=' + NS + ';i=6070',
   CalibrationTargetType_Identification_Model: 'nsu=' + NS + ';i=6071',
   CalibrationTargetType_Identification_ProductCode: 'nsu=' + NS + ';i=6072',
   CalibrationTargetType_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=6078',
   CalibrationTargetType_Identification_RevisionCounter: 'nsu=' + NS + ';i=6079',
   CalibrationTargetType_Identification_SerialNumber: 'nsu=' + NS + ';i=6077',
   CalibrationTargetType_Identification_SoftwareRevision: 'nsu=' + NS + ';i=6074',
   CalibrationTargetType_LastValidationDate: 'nsu=' + NS + ';i=6060',
   CalibrationTargetType_NextValidationDate: 'nsu=' + NS + ';i=6061',
   CalibrationTargetType_Quality: 'nsu=' + NS + ';i=6062',
   ControlChannelType_ChannelColor: 'nsu=' + NS + ';i=6024',
   ControlChannelType_Intensity: 'nsu=' + NS + ';i=6026',
   ControlChannelType_Intensity_EURange: 'nsu=' + NS + ';i=6027',
   ControlChannelType_SignalMode: 'nsu=' + NS + ';i=6025',
   ControlChannelType_SignalOn: 'nsu=' + NS + ';i=6023',
   BasicStacklightType_OrderedObject_Placeholder_NumberInList: 'nsu=' + NS + ';i=6037',
   BasicStacklightType_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   BasicStacklightType_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   BasicStacklightType_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   BasicStacklightType_StacklightMode: 'nsu=' + NS + ';i=6009',
   StacklightType_OrderedObject_Placeholder_NumberInList: 'nsu=' + NS + ';i=6037',
   StacklightType_StackLevel_DisplayMode: 'nsu=' + NS + ';i=6034',
   StacklightType_StackLevel_LevelPercent: 'nsu=' + NS + ';i=6035',
   StacklightType_StackLevel_LevelPercent_EURange: 'nsu=' + NS + ';i=6036',
   StacklightType_DeviceHealth: 'nsu=' + NS + ';i=6038',
   StackElementType_IsPartOfBase: 'nsu=' + NS + ';i=6014',
   StackElementType_NumberInList: 'nsu=' + NS + ';i=6015',
   StackElementType_SignalOn: 'nsu=' + NS + ';i=6013',
   StackElementAcousticType_AcousticSignals_OrderedObject_NumberInList: 'nsu=' + NS + ';i=6030',
   StackElementAcousticType_Intensity: 'nsu=' + NS + ';i=6021',
   StackElementAcousticType_Intensity_EURange: 'nsu=' + NS + ';i=6022',
   StackElementAcousticType_OperationMode: 'nsu=' + NS + ';i=6020',
   StackElementLightType_ControlChannel_Placeholder_ChannelColor: 'nsu=' + NS + ';i=6031',
   StackElementLightType_ControlChannel_Placeholder_Intensity_EURange: 'nsu=' + NS + ';i=6027',
   StackElementLightType_ControlChannel_Placeholder_SignalMode: 'nsu=' + NS + ';i=6032',
   StackElementLightType_ControlChannel_Placeholder_SignalOn: 'nsu=' + NS + ';i=6033',
   StackElementLightType_Intensity: 'nsu=' + NS + ';i=6018',
   StackElementLightType_Intensity_EURange: 'nsu=' + NS + ';i=6019',
   StackElementLightType_SignalColor: 'nsu=' + NS + ';i=6016',
   StackElementLightType_SignalMode: 'nsu=' + NS + ';i=6017',
   StackElementLightType_SignalRGBWValue: 'nsu=' + NS + ';i=6052',
   StackLevelType_DisplayMode: 'nsu=' + NS + ';i=6012',
   StackLevelType_LevelPercent: 'nsu=' + NS + ';i=6010',
   StackLevelType_LevelPercent_EURange: 'nsu=' + NS + ';i=6011',
});

export const VariableTypeIds = Object.freeze({
   CalibrationValueType: 'nsu=' + NS + ';i=2002',
   CapacityRangeType: 'nsu=' + NS + ';i=2003',
});
